export type ItemTrackerCategory =
  | 'Helm'
  | 'Torso'
  | 'Legs'
  | 'Gloves'
  | 'Amulet'
  | 'Ring'
  | 'Relic'
  | 'Archetype'
  | 'Trait'
  | 'Long Gun'
  | 'Hand Gun'
  | 'Melee'
  | 'Mod'
  | 'Mutator (Gun)'
  | 'Mutator (Melee)'
  | 'Prism'
  | 'Relic Fragment'
  | 'Concoction'
  | 'Consumable';
