import { Boss } from './types'

export const remnantBosses: Boss[] = [
  {
    name: 'Annihilation',
    category: 'world boss',
    imagePath: '/bosses/annihilation.jpg',
    location: 'Root Earth',
    dungeon: 'Blacked Citadel',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Annihilation'],
    id: 'g9FwDF',
  },
  {
    name: 'Corruptor',
    category: 'world boss',
    imagePath: '/bosses/corruptor.jpg',
    location: 'Yaesha',
    dungeon: 'The Great Bole',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Corruptor'],
    id: '6ABbmi',
  },
  {
    name: 'Faelin',
    category: 'world boss',
    imagePath: '/bosses/faelin.jpg',
    location: 'Losomn',
    dungeon: 'Beatific Gallery',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Faelin'],
    id: '8xK6gM',
  },
  {
    name: 'Faerin',
    category: 'world boss',
    imagePath: '/bosses/faerin.jpg',
    location: 'Losomn',
    dungeon: 'Malefic Gallery',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Faerin'],
    id: 'aJ8Tru',
  },
  {
    name: 'Labyrinth Sentinel',
    category: 'world boss',
    imagePath: '/bosses/labyrinth_sentinel.jpg',
    location: 'Labyrinth',
    dungeon: 'Labyrinth',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Labyrinth+Sentinel'],
    id: 'hZ7siN',
  },
  {
    name: 'Nightweaver',
    category: 'world boss',
    imagePath: '/bosses/nightweaver.jpg',
    location: 'Losomn',
    dungeon: 'The Tormented Asylum',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Nightweaver'],
    id: '9TzbrC',
  },
  {
    name: 'One True King',
    category: 'world boss',
    imagePath: '/bosses/one_true_king.jpg',
    location: 'Losomn',
    dungeon: 'Chamber of the Faithless',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/One+True+King'],
    id: 'Fjy5pF',
  },
  {
    name: 'Ravager',
    category: 'world boss',
    imagePath: '/bosses/ravager.jpg',
    location: 'Yaesha',
    dungeon: `Ravager's Lair`,
    wikiLinks: [`https://remnant2.wiki.fextralife.com/Corrupted+Ravager`],
    id: '4zrNaX',
  },
  {
    name: `Sha'Hala`,
    category: 'world boss',
    imagePath: '/bosses/shahala.jpg',
    location: 'Nerud',
    dungeon: `Sentinel's Keep`,
    wikiLinks: [
      `https://remnant2.wiki.fextralife.com/Sha'Hala+Spectral+Guardian+of+N'Erud`,
    ],
    id: '2ZmDKS',
  },
  {
    name: `Tal'Ratha`,
    category: 'world boss',
    imagePath: '/bosses/talratha.jpg',
    location: 'Nerud',
    dungeon: 'Forgotten Prison',
    wikiLinks: [`https://remnant2.wiki.fextralife.com/Tal+Ratha`],
    id: 'bFt8JS',
  },
  {
    name: `Tal'Ratha (Metaphysical)`,
    category: 'world boss',
    imagePath: '/bosses/talratha_metaphysical.jpg',
    location: 'Nerud',
    dungeon: 'Forgotten Prison',
    wikiLinks: [
      `https://remnant2.wiki.fextralife.com/Tal+Ratha+(Metaphysical)`,
    ],
    id: 'd5c8bN',
  },
  {
    name: 'Abomination',
    category: 'boss',
    imagePath: '/bosses/abomination.jpg',
    location: 'Nerud',
    dungeon: 'The Putrid Domain',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Abomination'],
    id: 'Ws384W',
  },
  {
    name: 'Astropath',
    category: 'boss',
    imagePath: '/bosses/astropath.jpg',
    location: 'Losomn',
    dungeon: `Astropath's Respite`,
    wikiLinks: [`https://remnant2.wiki.fextralife.com/The+Astropath`],
    id: '3GZ6k2',
  },
  {
    name: 'Befouled Altar',
    category: 'boss',
    imagePath: '/bosses/befouled_altar.jpg',
    location: 'Losomn',
    dungeon: 'The Forgotten Comune',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Befouled+Altar'],
    id: 'eN7hxx',
  },
  {
    name: 'Bruin, Blade of the King',
    category: 'boss',
    imagePath: '/bosses/bruin_blade_of_the_king.jpg',
    location: 'Losomn',
    dungeon: 'Glistering Cloister',
    wikiLinks: [
      'https://remnant2.wiki.fextralife.com/Bruin,+Blade+of+the+King',
    ],
    id: 'wEexW3',
  },
  {
    name: 'Bloat King',
    category: 'boss',
    imagePath: '/bosses/bloat_king.jpg',
    location: 'Losomn',
    dungeon: 'The Great Sewers',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Bloat+King'],
    id: '3efMrV',
  },
  {
    name: 'Cancer',
    category: 'boss',
    imagePath: '/bosses/cancer.jpg',
    location: 'Root Earth',
    dungeon: 'Ashen Wasteland',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Cancer'],
    id: 'jEFi2h',
  },
  {
    name: `Custodian's Eye`,
    category: 'boss',
    imagePath: '/bosses/custodians_eye.jpg',
    location: 'Nerud',
    dungeon: 'Spectrum Nexus',
    wikiLinks: [`https://remnant2.wiki.fextralife.com/The+Custodian's+Eye`],
    id: 'wb22RX',
  },
  {
    name: 'Gwendil The Unburnt',
    category: 'boss',
    imagePath: '/bosses/gwendil_the_unburnt.jpg',
    location: 'Losomn',
    dungeon: `Cotton's Kiln`,
    wikiLinks: [`https://remnant2.wiki.fextralife.com/Gwendil+The+Unburnt`],
    id: '7utUfw',
  },
  {
    name: 'Huntress',
    category: 'boss',
    imagePath: '/bosses/huntress.jpg',
    location: 'Losomn',
    dungeon: 'Brocwithe Quarter, Forsaken Quarter, Ironborough',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/The+Huntress'],
    id: 'm2vW25',
  },
  {
    name: 'Kaeula',
    category: 'boss',
    imagePath: '/bosses/kaeula.jpg',
    location: 'Yaesha',
    dungeon: `Kaeula's Rest`,
    wikiLinks: [`https://remnant2.wiki.fextralife.com/Kaeula's+Shadow`],
    id: 'E7LieX',
  },
  {
    name: 'Legion',
    category: 'boss',
    imagePath: '/bosses/legion.jpg',
    location: 'Yaesha',
    dungeon: 'The Twisted Chantry',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Legion'],
    id: 'dtB8ac',
  },
  {
    name: 'Magister Dullain',
    category: 'boss',
    imagePath: '/bosses/magister_dullain.jpg',
    location: 'Losomn',
    dungeon: 'Shattered Gallery',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Magister+Dullain'],
    id: 'BvjT2V',
  },
  {
    name: 'Mother Mind',
    category: 'boss',
    imagePath: '/bosses/mother_mind.jpg',
    location: 'Yaesha',
    dungeon: 'The Nameless Nest',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Mother+Mind'],
    id: 'HTbt5M',
  },
  {
    name: 'Primogenitor',
    category: 'boss',
    imagePath: '/bosses/primogenitor.jpg',
    location: 'Nerud',
    dungeon: 'The Hatchery',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Primogenitor'],
    id: 'JBn8ob',
  },
  {
    name: 'Red Prince',
    category: 'boss',
    imagePath: '/bosses/red_prince.jpg',
    location: 'Losomn',
    dungeon: 'Gilded Chambers',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/The+Red+Prince'],
    id: '35mW3e',
  },
  {
    name: 'Shrewd',
    category: 'boss',
    imagePath: '/bosses/shrewd.jpg',
    location: 'Yaesha',
    dungeon: 'The Expanding Glade',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Shrewd'],
    id: 'tfuw8P',
  },
  {
    name: 'Sunken Witch',
    category: 'boss',
    imagePath: '/bosses/sunken_witch.jpg',
    location: 'Losomn',
    dungeon: 'Sunken Haunt',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Sunken+Witch'],
    id: 'S8mXCm',
  },
  {
    name: 'The Council',
    category: 'boss',
    imagePath: '/bosses/the_council.jpg',
    location: 'Losomn',
    dungeon: 'Council Chamber',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/The+Council'],
    id: '73ZNjb',
  },
  {
    name: 'Venom',
    category: 'boss',
    imagePath: '/bosses/venom.jpg',
    location: 'Root Earth',
    dungeon: 'Corrupted Harbor',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Venom'],
    id: '5GEAx3',
  },
  {
    name: 'Atrophy',
    category: 'aberration',
    imagePath: '/bosses/atrophy.jpg',
    location: 'Yaesha',
    dungeon: `Endaira's End`,
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Atrophy'],
    id: 'a88PFZ',
  },
  {
    name: 'Bane',
    category: 'aberration',
    imagePath: '/bosses/bane.jpg',
    location: 'Root Earth',
    dungeon: 'Twilight Vale',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Bane'],
    id: '73DHnC',
  },
  {
    name: 'Barghest the Vile',
    category: 'aberration',
    imagePath: '/bosses/barghest.jpg',
    location: 'Losomn',
    dungeon: `Harvester's Reach`,
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Barghest+the+Vile'],
    id: '8Xi7nS',
  },
  {
    name: 'Bastion',
    category: 'aberration',
    imagePath: '/bosses/bastion.jpg',
    location: 'Labyrinth',
    dungeon: 'The Labyrinth',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Bastion'],
    id: 'H2iB8c',
  },
  {
    name: 'Cursed Wretch',
    category: 'aberration',
    imagePath: '/bosses/cursed_wretch.jpg',
    location: 'Losomn',
    dungeon: 'The Forgotten Comune',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Cursed+Wretch'],
    id: '8gdAsr',
  },
  {
    name: 'Defiler',
    category: 'aberration',
    imagePath: '/bosses/defiler.jpg',
    location: 'Yaesha',
    dungeon: 'Forgotten Field',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Defiler'],
    id: 'y55dZT',
  },
  {
    name: 'Dire Fiend',
    category: 'aberration',
    imagePath: '/bosses/dire_fiend.jpg',
    location: 'Losomn',
    dungeon: 'Losomn',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Dire+Fiend'],
    id: 'z4NeZM',
  },
  {
    name: 'E.D. Alpha',
    category: 'aberration',
    imagePath: '/bosses/ed_alpha.jpg',
    location: 'Nerud',
    dungeon: 'Tower of the Unseen',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/E+D+Alpha'],
    id: '2yRGvb',
  },
  {
    name: 'Executioner',
    category: 'aberration',
    imagePath: '/bosses/executioner.jpg',
    location: 'Losomn',
    dungeon: 'Fae Palace locations',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/The+Executioner'],
    id: '6o2WBN',
  },
  {
    name: 'Fester',
    category: 'aberration',
    imagePath: '/bosses/fester.jpg',
    location: 'Yaesha',
    dungeon: `Endaira's End`,
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Fester'],
    id: 'Qpta3f',
  },
  {
    name: 'Fetid Corpse',
    category: 'aberration',
    imagePath: '/bosses/fetid_corpse.jpg',
    location: 'Nerud',
    dungeon: 'Void Vessel Facility',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Fetid+Corpse'],
    id: 'WYX6tH',
  },
  {
    name: 'Firth: The Oathkeeper',
    category: 'aberration',
    imagePath: '/bosses/firth.jpg',
    location: 'Losomn',
    dungeon: 'Malefic Palace',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Firth:+The+Oathkeeper'],
    id: '2zRPQ5',
  },
  {
    name: 'Gorecarver',
    category: 'aberration',
    imagePath: '/bosses/gorecarver.jpg',
    location: 'Losomn',
    dungeon: 'Derelict Lighthouse',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Gorecarver'],
    id: 'As28CR',
  },
  {
    name: 'Gorge',
    category: 'aberration',
    imagePath: '/bosses/gorge.jpg',
    location: 'Losomn',
    dungeon: `Cotton's Kiln, Butcher's Quarter, Sunken Haunt, Derelict Lighthouse`,
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Gorge'],
    id: '2zr34P',
  },
  {
    name: 'Little Gorge',
    category: 'aberration',
    imagePath: '/bosses/little_gorge.jpg',
    location: 'Losomn',
    dungeon: 'Forlorn Coast',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Little+Gorge'],
    id: '5QcPV9',
  },
  {
    name: 'Mangled Atoner',
    category: 'aberration',
    imagePath: '/bosses/mangled_atoner.jpg',
    location: 'Losomn',
    dungeon: 'Forlorn Coast',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Mangled+Atoner'],
    id: '3GvXys',
  },
  {
    name: 'Mantagora',
    category: 'aberration',
    imagePath: '/bosses/mantagora.jpg',
    location: 'Yaesha',
    dungeon: 'Imperial Gardens',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Mantagora'],
    id: 'UdHg8g',
  },
  {
    name: 'Progeny',
    category: 'aberration',
    imagePath: '/bosses/progeny.jpg',
    location: 'Nerud',
    dungeon: `The Putrid Domain, Vault of the Formless, Void Vessel Facility, The Hatchery, The Dark Conduit`,
    wikiLinks: ['https://remnant2.wiki.fextralife.com/The+Progeny'],
    id: '2SpwWM',
  },
  {
    name: 'Restless Spirit',
    category: 'aberration',
    imagePath: '/bosses/restless_spirit.jpg',
    location: 'Nerud',
    dungeon: `Astropath's Respite, Spectrum Nexus, Terminus Station, Tower of the Unseen`,
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Restless+Spirit'],
    id: '9sBqhu',
  },
  {
    name: 'Ripsaw',
    category: 'aberration',
    imagePath: '/bosses/ripsaw.jpg',
    location: 'Losomn',
    dungeon: 'Morrow Parish',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Ripsaw'],
    id: '2Af6cZ',
  },
  {
    name: 'Rot',
    category: 'aberration',
    imagePath: '/bosses/rot.jpg',
    location: 'Yaesha',
    dungeon: 'The Chimney, The Twisted Chantry',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Rot'],
    id: 'DZB6Ut',
  },
  {
    name: 'S.D. OA7',
    category: 'aberration',
    imagePath: '/bosses/sd_0a7.jpg',
    location: 'Nerud',
    dungeon: `Dormant N'Erudian Facility`,
    wikiLinks: ['https://remnant2.wiki.fextralife.com/S.D.+0A7'],
    id: 'YwbM9W',
  },
  {
    name: 'Thunderpiercer',
    category: 'aberration',
    imagePath: '/bosses/thunderpiercer.jpg',
    location: 'Losomn',
    dungeon: 'Derelict Lighthouse',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Thunderpiercer'],
    id: '5xJq5F',
  },
  {
    name: 'W.D. 109',
    category: 'aberration',
    imagePath: '/bosses/wd_109.jpg',
    location: 'Nerud',
    dungeon: `Void Vessel Facility, The Putrid Domain, Vault of the Formless, The Hatchery, The Dark Conduit`,
    wikiLinks: ['https://remnant2.wiki.fextralife.com/W+D+109'],
    id: 'FH5Ttb',
  },
  {
    name: 'Weald Stalker and Gnarled Archer',
    category: 'aberration',
    imagePath: '/bosses/gnarled_archer_and_weald_stalker.jpg',
    location: 'Yaesha',
    dungeon: 'Floating Forests',
    wikiLinks: [
      'https://remnant2.wiki.fextralife.com/The+Weald+Stalker+and+The+Gnarled+Archer',
    ],
    id: 'os8Epw',
  },
  {
    name: 'Wither',
    category: 'aberration',
    imagePath: '/bosses/wither.jpg',
    location: 'Yaesha',
    dungeon: 'The Lament',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Wither'],
    id: 'o8tCDP',
  },
  {
    name: 'Wraithliege',
    category: 'aberration',
    imagePath: '/bosses/wraithliege.jpg',
    location: 'Losomn',
    dungeon: 'Pathway of the Fallen',
    wikiLinks: ['https://remnant2.wiki.fextralife.com/Wraithliege'],
    id: '64wuWP',
  },
]
