import { WorldSave } from '@/app/(components)/filters/world-saves/types'

export const worldSaves = [
  {
    bossName: 'Abomination',
    bossAffixes: ['Drain', 'Elemental Resist'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Abomination',
    bossAffixes: ['Drain', 'Skullcracker'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Abomination',
    bossAffixes: ['Empathy', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Annihilation',
    bossAffixes: ['Hearty', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Annihilation',
    bossAffixes: ['Regenerator', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Annihilation',
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Bloat King',
    bossAffixes: ['Drain', 'Hearty'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Bloat King',
    bossAffixes: ['Drain', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Bloat King',
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Bruin, Blade of the King',
    bossAffixes: ['Skullcracker', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Cancer',
    bossAffixes: ['Empathy', 'Regenerator'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Cancer',
    bossAffixes: ['Empathy', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Cancer',
    bossAffixes: ['Skullcracker', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Cancer',
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Cinderclad Forge',
    bossAffixes: ['Regenerator', 'Spiteful'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Cinderclad Forge',
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Drain', 'Hearty'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Drain', 'Regenerator'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Drain', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Drain', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Elemental Resist', 'Skullcracker'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Elemental Resist', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Empathy', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Hearty', 'Regenerator'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Hearty', 'Skullcracker'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Hearty', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Spiteful', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Regenerator', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },

  {
    bossName: 'Corrupted Ravager',
    bossAffixes: ['Thick Skin', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corruptor',
    bossAffixes: ['Drain', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corruptor',
    bossAffixes: ['Elemental Resist', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corruptor',
    bossAffixes: ['Elemental Resist', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corruptor',
    bossAffixes: ['Hearty', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corruptor',
    bossAffixes: ['Regenerator', 'Skullcracker'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corruptor',
    bossAffixes: ['Regenerator', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corruptor',
    bossAffixes: ['Regenerator', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corruptor',
    bossAffixes: ['Skullcracker', 'Spiteful'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Corruptor',
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Corruptor',
    bossAffixes: ['Thick Skin', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Faelin',
    bossAffixes: ['Drain', 'Spiteful'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Faelin',
    bossAffixes: ['Elemental Resist', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Faelin',
    bossAffixes: ['Hearty', 'Thick Skin'],
    release: 'base',
    isCursed: undefined,
  },
  {
    bossName: 'Faerin',
    bossAffixes: ['Drain', 'Hearty'],
    release: 'base',
    isCursed: undefined,
  },
  {
    bossName: 'Faerin',
    bossAffixes: ['Drain', 'Spiteful'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Faerin',
    bossAffixes: ['Spiteful', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Faerin',
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Gwendil: The Unburnt',
    bossAffixes: ['Drain', 'Empathy'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Gwendil: The Unburnt',
    bossAffixes: ['Elemental Resist', 'Regenerator'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Gwendil: The Unburnt',
    bossAffixes: ['Hearty', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: `Kaeula's Shadow`,
    bossAffixes: ['Drain', 'Elemental Resist'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Kaeula's Shadow`,
    bossAffixes: ['Elemental Resist', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Kaeula's Shadow`,
    bossAffixes: ['Elemental Resist', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Kaeula's Shadow`,
    bossAffixes: ['Empathy', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Kaeula's Shadow`,
    bossAffixes: ['Hearty', 'Empathy'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: `Kaeula's Shadow`,
    bossAffixes: ['Hearty', 'Regenerator'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Kaeula's Shadow`,
    bossAffixes: ['Hearty', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Kaeula's Shadow`,
    bossAffixes: ['Skullcracker', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: `Kaeula's Shadow`,
    bossAffixes: ['Spiteful', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Labyrinth Sentinel',
    bossAffixes: [],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Legion',
    bossAffixes: ['Drain', 'Elemental Resist'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Legion',
    bossAffixes: ['Drain', 'Hearty'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Legion',
    bossAffixes: ['Drain', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Legion',
    bossAffixes: ['Drain', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Legion',
    bossAffixes: ['Elemental Resist', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Legion',
    bossAffixes: ['Elemental Resist', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Legion',
    bossAffixes: ['Hearty', 'Regenerator'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Legion',
    bossAffixes: ['Regenerator', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Legion',
    bossAffixes: ['Spiteful', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Legion',
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Lydusa',
    bossAffixes: [],
    release: 'dlc2',
    isCursed: true,
  },
  {
    bossName: 'Magister Dullain',
    bossAffixes: ['Elemental Resist', 'Hearty'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Magister Dullain',
    bossAffixes: ['Regenerator', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Magister Dullain',
    bossAffixes: ['Skullcracker', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Mother Mind',
    bossAffixes: ['Elemental Resist', 'Skullcracker'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Mother Mind',
    bossAffixes: ['Elemental Resist', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Mother Mind',
    bossAffixes: ['Empathy', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Mother Mind',
    bossAffixes: ['Hearty', 'Skullcracker'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Mother Mind',
    bossAffixes: ['Hearty', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Mother Mind',
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Primogenitor',
    bossAffixes: ['Elemental Resist', 'Hearty'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Primogenitor',
    bossAffixes: ['Elemental Resist', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Primogenitor',
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Primogenitor',
    bossAffixes: ['Thick Skin', 'Unstoppable'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Primogenitor',
    bossAffixes: ['Unstoppable', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: `Sha'Hala: Guardian of N'Erud`,
    bossAffixes: ['Drain', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Sha'Hala: Guardian of N'Erud`,
    bossAffixes: ['Drain', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: `Sha'Hala: Guardian of N'Erud`,
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Sha'Hala: Guardian of N'Erud (Phase 2)`,
    bossAffixes: ['Elemental Resist', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Sha'Hala: Guardian of N'Erud (Phase 2)`,
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Sha'Hala: Spectral Guardian of N'Erud`,
    bossAffixes: ['Drain', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Sha'Hala: Spectral Guardian of N'Erud`,
    bossAffixes: ['Elemental Resist', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Sha'Hala: Spectral Guardian of N'Erud`,
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Shrewd',
    bossAffixes: ['Drain', 'Spiteful'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Shrewd',
    bossAffixes: ['Elemental Resist', 'Skullcracker'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Shrewd',
    bossAffixes: ['Hearty', 'Drain'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Shrewd',
    bossAffixes: ['Hearty', 'Regenerator'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Shrewd',
    bossAffixes: ['Hearty', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Shrewd',
    bossAffixes: ['Spiteful', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Tal'Ratha`,
    bossAffixes: ['Drain', 'Skullcracker'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: `Tal'Ratha`,
    bossAffixes: ['Elemental Resist', 'Hearty'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Tal'Ratha (Metaphysical)`,
    bossAffixes: ['Skullcracker', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `Tal'Ratha (Metaphysical)`,
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'The Astropath',
    bossAffixes: ['Elemental Resist', 'Regenerator'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Astropath',
    bossAffixes: ['Regenerator', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `The Custodian's Eye`,
    bossAffixes: ['Hearty', 'Regenerator'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `The Custodian's Eye`,
    bossAffixes: ['Hearty', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `The Custodian's Eye`,
    bossAffixes: ['Regenerator', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `The Custodian's Eye`,
    bossAffixes: ['Skullcracker', 'Spiteful'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: `The Custodian's Eye`,
    bossAffixes: ['Skullcracker', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: `The Custodian's Eye`,
    bossAffixes: ['Thick Skin', 'Regenerator'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'The Huntress',
    bossAffixes: ['Drain', 'Elemental Resist'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Huntress',
    bossAffixes: ['Hearty', 'Spiteful'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'The Nightweaver',
    bossAffixes: ['Drain', 'Elemental Resist'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Nightweaver',
    bossAffixes: ['Elemental Resist', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Nightweaver',
    bossAffixes: ['Empathy', 'Skullcracker'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'The Nightweaver',
    bossAffixes: ['Skullcracker', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Nightweaver',
    bossAffixes: ['Skullcracker', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The One True King',
    bossAffixes: ['Hearty', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The One True King',
    bossAffixes: ['Hearty', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The One True King',
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Red Prince',
    bossAffixes: ['Drain', 'Regenerator'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Red Prince',
    bossAffixes: ['Drain', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Red Prince',
    bossAffixes: ['Drain', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'The Red Prince',
    bossAffixes: ['Elemental Resist', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Red Prince',
    bossAffixes: ['Hearty', 'Spiteful'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'The Red Prince',
    bossAffixes: ['Hearty', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Stonewarden',
    bossAffixes: ['Hearty', 'Thick Skin'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'The Stonewarden',
    bossAffixes: ['Spiteful', 'Thick Skin'],
    release: 'dlc2',
    isCursed: false,
  },
  {
    bossName: 'The Sunken Witch',
    bossAffixes: ['Empathy', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Sunken Witch',
    bossAffixes: ['Regenerator', 'Skullcracker'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Sunken Witch',
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'The Sunken Witch',
    bossAffixes: ['Thick Skin', 'Trapper'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Venom',
    bossAffixes: ['Drain', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Venom',
    bossAffixes: ['Empathy', 'Skullcracker'],
    release: 'dlc2',
    isCursed: undefined,
  },
  {
    bossName: 'Venom',
    bossAffixes: ['Hearty', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Venom',
    bossAffixes: ['Regenerator', 'Spiteful'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Venom',
    bossAffixes: ['Skullcracker', 'Vicious'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Venom',
    bossAffixes: ['Spiteful', 'Thick Skin'],
    release: 'dlc1',
    isCursed: undefined,
  },
  {
    bossName: 'Venom',
    bossAffixes: ['Spiteful', 'Vicious'],
    release: 'dlc2',
    isCursed: undefined,
  },
] as const satisfies WorldSave[]
