import { type FusionItem } from '@/app/(items)/_types/fusion-item';

export const fusionItems: FusionItem[] = [
  {
    category: 'fusion',
    name: 'Athletic',
    fragmentIds: ['c0hy5s', 'kp0rff'],
    imagePath: '/items/fusions/yellow-blue.png',
    id: '62uunk',
    dlc: 'base',
    description: `Movement Speed + Evade Speed`,
  },
  {
    category: 'fusion',
    name: 'Capacitor',
    fragmentIds: ['6tby7d', '3ngjzr'],
    imagePath: '/items/fusions/red-yellow.png',
    id: 'ck7ms0',
    dlc: 'base',
    description: 'Firearm Charge Time + Heat Generation',
  },
  {
    category: 'fusion',
    name: 'Cleric',
    fragmentIds: ['y52c32', 'omefk5'],
    imagePath: '/items/fusions/blue-yellow.png',
    id: 'zr00kz',
    dlc: 'base',
    description: 'Healing Effectiveness + Use Speed',
  },
  {
    category: 'fusion',
    name: 'Flash',
    fragmentIds: ['51y6ih', 'omefk5'],
    imagePath: '/items/fusions/yellow-yellow.png',
    id: '6ybk0o',
    dlc: 'base',
    description: 'Casting Speed + Use Speed',
  },
  {
    category: 'fusion',
    name: 'Grip',
    fragmentIds: ['oiiiu2', 'h9e463'],
    imagePath: '/items/fusions/yellow-yellow.png',
    id: 'd6hgip',
    dlc: 'base',
    description: 'Weapon Spread + Firearm Swap Speed',
  },
  {
    category: 'fusion',
    name: 'Gunfighter',
    fragmentIds: ['w8ruyt', '5wuf2j'],
    imagePath: '/items/fusions/red-yellow.png',
    id: 'w962ng',
    dlc: 'base',
    description: 'Ranged Fire Rate + Reload Speed',
  },
  {
    category: 'fusion',
    name: 'Hulk',
    fragmentIds: ['j87rzn', 'qqmdc0'],
    imagePath: '/items/fusions/blue-blue.png',
    id: 't2myua',
    dlc: 'base',
    description: 'Health Bonus + Stamina Bonus',
    healthPercent: 0.1,
    staminaPercent: 0.15,
  },
  {
    category: 'fusion',
    name: 'Longevity',
    fragmentIds: ['c2t1p6', '7c8uka'],
    imagePath: '/items/fusions/yellow-yellow.png',
    id: 'ynxc2m',
    dlc: 'base',
    description: 'Mod Duration + Skill Duration',
  },
  {
    category: 'fusion',
    name: 'Mage',
    fragmentIds: ['zkr2us', 'pk57hf'],
    imagePath: '/items/fusions/red-yellow.png',
    id: 'm1h26g',
    dlc: 'base',
    description: 'Mod Damage + Mod Generation',
  },
  {
    category: 'fusion',
    name: 'Meta',
    fragmentIds: ['oszz4u', '0qxyqo'],
    imagePath: '/items/fusions/red-red.png',
    id: 'g58d3p',
    dlc: 'base',
    description: 'Weakspot Damage + Critical Damage',
  },
  {
    category: 'fusion',
    name: 'Munitions',
    fragmentIds: ['dp184t', '3aqiq5'],
    imagePath: '/items/fusions/red-yellow.png',
    id: 'wi41h6',
    dlc: 'base',
    description: 'Ranged Critical Chance + Ammo Reserves',
  },
  {
    category: 'fusion',
    name: 'Pirate',
    fragmentIds: ['wlnbc1', 'yu7d57'],
    imagePath: '/items/fusions/red-red.png',
    id: 'n5mt1u',
    dlc: 'base',
    description: 'Ranged Damage + Melee Damage',
  },
  {
    category: 'fusion',
    name: 'Protected',
    fragmentIds: ['alp59n', 'h6sk9p'],
    imagePath: '/items/fusions/blue-blue.png',
    id: 'x59m5x',
    dlc: 'base',
    description: 'Shield Amount + Base Armor',
    armor: 15,
  },
  {
    category: 'fusion',
    name: 'Pugilist',
    fragmentIds: ['t8jgpe', '4gbcn0'],
    imagePath: '/items/fusions/red-blue.png',
    id: 'jeu7d6',
    dlc: 'base',
    description: 'Melee Speed + Base Stamina',
    stamina: 15,
  },
  {
    category: 'fusion',
    name: 'Revitalize',
    fragmentIds: ['bzxa98', '2bqp66'],
    imagePath: '/items/fusions/blue-yellow.png',
    id: '3fenef',
    dlc: 'base',
    description: 'Health Regeneration + Skill Cooldown',
  },
  {
    category: 'fusion',
    name: 'Rogue',
    fragmentIds: ['m16fn9', 'kp0rff'],
    imagePath: '/items/fusions/red-blue.png',
    id: 'q0ox6z',
    dlc: 'base',
    description: 'Melee Critical Chance + Evade Speed',
  },
  {
    category: 'fusion',
    name: 'Sapper',
    fragmentIds: ['73x1rg', '1pddio'],
    imagePath: '/items/fusions/red-blue.png',
    id: 'ht9ok0',
    dlc: 'base',
    description: 'Explosive Damage + Damage Reduction',
  },
  {
    category: 'fusion',
    name: 'Selfless',
    fragmentIds: ['0jam5w', 'y52c32'],
    imagePath: '/items/fusions/blue-blue.png',
    id: '0dm69i',
    dlc: 'base',
    description: `Revive Speed + Healing Effectiveness`,
  },
  {
    category: 'fusion',
    name: 'Sniper',
    fragmentIds: ['wlnbc1', 'i5kymp'],
    imagePath: '/items/fusions/red-yellow.png',
    id: '26o0ys',
    dlc: 'base',
    description: 'Ranged Damage + Weapon Ideal Range',
  },
  {
    category: 'fusion',
    name: 'Tank',
    fragmentIds: ['1pddio', '7u1bma'],
    imagePath: '/items/fusions/blue-blue.png',
    id: '3b43hx',
    dlc: 'base',
    description: 'Damage Reduction + Armor Bonus',
    armorPercent: 0.1,
  },
  {
    category: 'fusion',
    name: 'Threshold',
    fragmentIds: ['j87rzn', 'aci99s'],
    imagePath: '/items/fusions/blue-blue.png',
    id: '6p6ssk',
    dlc: 'base',
    description: 'Health Bonus + Grey Health Conversion',
    healthPercent: 0.1,
  },
  {
    category: 'fusion',
    name: 'Warrior',
    fragmentIds: ['yu7d57', 't8jgpe'],
    imagePath: '/items/fusions/red-red.png',
    id: 'oxap1d',
    dlc: 'base',
    description: 'Melee Damage + Melee Speed',
  },
  {
    category: 'fusion',
    name: 'Wizard',
    fragmentIds: ['iyp5r3', 'o5sd30'],
    imagePath: '/items/fusions/red-red.png',
    id: 'g9u4i3',
    dlc: 'base',
    description: 'Mod Critical Chance + Skill Critical Chance',
  },
];
