import { ArmorItem } from './types/ArmorItem'

export const armorItems: ArmorItem[] = [
  {
    category: 'helm',
    name: "Academic's Hat",
    saveFileSlug: 'armor_head_alchemist',
    imagePath: '/helm/academics_hat.png',
    id: '9qo2gg',
    set: "Academic's Set",
    armor: 12.7,
    weight: 5.2,
    bleedResistance: 1,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 3,
    description: `A soft and durable felt hat fashioned to stylize, not necessarily protect, the most important part of your body. `,
    wikiLinks: [`https://remnant.wiki/Academic%27s_Hat`],
  },
  {
    category: 'helm',
    name: "Bandit's Mask",
    saveFileSlug: 'armor_head_bandit',
    imagePath: '/helm/bandits_mask.png',
    id: 'v66pgu',
    set: 'Bandit Set',
    armor: 6.8,
    weight: 2.7,
    bleedResistance: 2,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 3,
    toxinResistance: 3,
    description: `The helm of the bandit armor is a haunting symbol of the ruthless opportunism that arose after the cataclysmic destruction of Earth. Yet, for those who wear it, it also represents a means of survival in a world where mercy is a scarce commodity`,
    wikiLinks: [`https://remnant.wiki/Bandit%27s_Mask`],
  },
  {
    category: 'helm',
    name: "Battle Helmet",
    saveFileSlug: 'armor_head_battle',
    imagePath: '/helm/battle_helmet.png',
    id: 'nathem',
    dlc:'dlc2',
    set: 'Battle Set',
    armor: 13.1,
    weight: 5.3,
    bleedResistance: 5,
    fireResistance: 2,
    shockResistance: 0,
    blightResistance: 0,
    toxinResistance: 0,
    description: `This helmet looks heavier than it is, which isn't all that surprising, considering it isn't bulletproof. Still, it's useful for protecting against falling debris, and if the angle's just right, it may get lucky and deflect a stray bullet or two. I wouldn't count on it, though.`,
    wikiLinks: [`https://remnant.wiki/Battle_Helmet`],
  },
  {
    category: 'helm',
    name: 'Bruiser Helmet',
    saveFileSlug: 'armor_head_challenger',
    imagePath: '/helm/bruiser_helmet.png',
    id: 'bd4pam',
    set: 'Bruiser Set',
    armor: 17.6,
    weight: 8.1,
    bleedResistance: 1,
    fireResistance: 2,
    shockResistance: 0,
    blightResistance: 0,
    toxinResistance: 1,
    description: `The visibility in this helmet leaves much to be desired, but that's not really the point. It goes a long way in keeping your head on your shoulders.`,
    wikiLinks: [`https://remnant.wiki/Bruiser_Helmet`],
  },
  {
    category: 'helm',
    name: 'Crimson Guard Shroud',
    saveFileSlug: 'armor_head_crimsonguard',
    dlc: 'dlc1',
    imagePath: '/helm/crimson_guard_shroud.png',
    id: 'ce8izt',
    set: 'Crimson Guard Set',
    armor: 15.6,
    weight: 6.7,
    bleedResistance: 2,
    fireResistance: 2,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 0,
    description: `The hooded mask wreathes you in a vicious, fiery visage that evokes both fear and admiration. The incandescent eye slits color your vision with the hues of hellfire.`,
    wikiLinks: [`https://remnant.wiki/Crimson_Guard_Shroud`],
  },
  {
    category: 'helm',
    name: 'Crown of the Red Prince',
    saveFileSlug: 'armor_head_redprince',
    imagePath: '/helm/crown_of_the_red_prince.png',
    id: 'pu3duv',
    armor: 6,
    weight: 6,
    bleedResistance: -6,
    fireResistance: 25,
    shockResistance: -6,
    blightResistance: 13,
    toxinResistance: -6,
    description: `A flashy, flame-hot diadem that demands respect and attention in equal measure...were there any subjects left to offer such sentiments. `,
    wikiLinks: [`https://remnant.wiki/Crown_of_the_Red_Prince`],
  },
  {
    category: 'helm',
    name: 'Cultist Hat',
    saveFileSlug: 'armor_head_cultist',
    imagePath: '/helm/cultist_hat.png',
    id: 'x9jrx1',
    set: 'Cultist Set',
    armor: 11.1,
    weight: 4.6,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 1,
    toxinResistance: 1,
    description: `A simple and unassuming headpiece that belies its storied past. Once worn by members of a secretive and enigmatic cult. It now serves as a symbol of redemption for those who have turned their backs on the group's teachings.`,
    wikiLinks: [`https://remnant.wiki/Cultist_Hat`],
  },
  {
    category: 'helm',
    name: 'Dandy Topper',
    imagePath: '/helm/dandy_topper.png',
    id: 'vZL5tu',
    dlc: 'dlc2',
    armor: 12.8,
    weight: 5.3,
    bleedResistance: 0,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 5,
    toxinResistance: 0,
    description: 'Lovingly crafted by a skilled hatter who clearly takes great pride in their work. After being exposed to endless days of rain, the shell began to separate from the crown, so a woven cord was tied around the center to hold it in place—for now.',
    wikiLinks: ['https://remnant.wiki/Dandy_Topper'],
  },
  {
    category: 'helm',
    name: 'Dendroid Mask',
    saveFileSlug: 'armor_head_invader',
    imagePath: '/helm/dendroid_mask.png',
    id: 'y7fa8n',
    set: 'Dendroid Set',
    armor: 7.7,
    weight: 3.1,
    bleedResistance: 2,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 0,
    toxinResistance: 2,
    description: `It's like putting your head inside the monsters you've been killing all this time. It's comfortable enough though, so long as you don't think about where it's been. `,
    wikiLinks: [`https://remnant.wiki/Dendroid_Mask`],
  },
  {
    category: 'helm',
    name: 'Disciple Headpiece',
    saveFileSlug: 'armor_head_invoker',
    imagePath: '/helm/disciple_headpiece.png',
    id: 'y7fa8d',
    dlc:'dlc2',
    set: 'Disciple Set',
    armor: 16,
    weight: 7.2,
    bleedResistance: 0,
    fireResistance: 2,
    shockResistance: 2,
    blightResistance: 1,
    toxinResistance: 0,
    description: `The unwavering visage of Lydusa carves the shape of this mask. Though her sisters wandered far and wide, Lydusa seldom traveled at all, for stone by its nature is unmoving and lonely.`,
    wikiLinks: [`https://remnant.wiki/Disciple_Headpiece`],
  },
  {
    category: 'helm',
    name: 'Elder Headdress',
    saveFileSlug: 'armor_head_elder',
    imagePath: '/helm/elder_headdress.png',
    id: 'fek1ml',
    set: 'Elder Set',
    armor: 7.5,
    weight: 3,
    bleedResistance: 0,
    fireResistance: 3,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 0,
    description: `This headpiece hails from the wild and mysterious world of Yaesha. Its smooth,
    featureless. design is both eerie and elegant, painted a stark white and adorned
    with luxuriant fur and imposing horns.`,
    wikiLinks: [`https://remnant.wiki/Elder_Headdress`],
  },
  {
    category: 'helm',
    name: 'Fae Royal Headcover',
    saveFileSlug: 'armor_head_faeroyalguard',
    imagePath: '/helm/fae_royal_headcover.png',
    id: '88kdl6',
    set: 'Fae Royal Set',
    armor: 15.4,
    weight: 6.6,
    bleedResistance: 2,
    fireResistance: 2,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 0,
    description: `It feels like you're not wearing any helmet at all - you'd swear you could even feel the wind in your hair. Yet it turns an arrow as effectively as any steel. `,
    wikiLinks: [`https://remnant.wiki/Fae_Royal_Headcover`],
  },
  {
    category: 'helm',
    name: 'Field Medic Hat',
    saveFileSlug: 'armor_head_fieldcap',
    imagePath: '/helm/field_medic_hat.png',
    id: '48nh1x',
    armor: 10.6,
    weight: 4.4,
    bleedResistance: 0,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 1,
    description: `While it may shield your eyes from the sun, it's not particularly protective against the dangers of the Root. `,
    wikiLinks: [`https://remnant.wiki/Field_Medic_Hat`],
  },
  {
    category: 'helm',
    name: 'Field Medic Mask',
    saveFileSlug: 'armor_head_medic',
    imagePath: '/helm/field_medic_mask.png',
    id: 'e1waki',
    set: 'Field Medic Set',
    armor: 10.6,
    weight: 4.4,
    bleedResistance: 0,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 1,
    description: `This face covering protects you from contagions without obstructing your sight. You feel like a creature from another world in this thing. Perhaps that's fitting. `,
    wikiLinks: [`https://remnant.wiki/Field_Medic_Mask`],
  },
  {
    category: 'helm',
    name: 'High Noon Hat',
    saveFileSlug: 'armor_head_gunslinger',
    imagePath: '/helm/high_noon_hat.png',
    id: '94xkn1',
    set: 'High Noon Set',
    armor: 11.7,
    weight: 4.9,
    bleedResistance: 0,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 0,
    toxinResistance: 1,
    description: `Something about this hat just feels right. Paired with a bandana, it keeps the sun and elements from hindering your all-important aim. `,
    wikiLinks: [`https://remnant.wiki/High_Noon_Hat`],
  },
  {
    category: 'helm',
    name: 'Knotted Helm',
    saveFileSlug: 'armor_head_summoner',
    imagePath: '/helm/knotted_helm.png',
    id: 'oab1w0',
    set: 'Knotted Set',
    armor: 15.5,
    weight: 6.9,
    bleedResistance: 0,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 4,
    description: `A hauntingly familiar visage, convincing enough to still be alive. To truly know your enemy, you must get inside its head. Literally. `,
    wikiLinks: [`https://remnant.wiki/Knotted_Helm`],
  },
  {
    category: 'helm',
    name: 'Labyrinth Headplate',
    saveFileSlug: 'armor_head_archon',
    imagePath: '/helm/labyrinth_headplate.png',
    id: 'im7fm2',
    set: 'Labyrinth Set',
    armor: 12.9,
    weight: 5.4,
    bleedResistance: 0,
    fireResistance: 2,
    shockResistance: 3,
    blightResistance: 0,
    toxinResistance: 0,
    description: `This helmet is reminiscent of a statue from a time long, long before. `,
    wikiLinks: [`https://remnant.wiki/Labyrinth_Headplate`],
  },
  {
    category: 'helm',
    name: 'Leto Mark 1 Helmet',
    saveFileSlug: 'armor_head_leto1',
    imagePath: '/helm/leto_mark_i_helmet.png',
    id: 'kc4dc0',
    set: 'Leto Mark 1 Set',
    armor: 22.6,
    weight: 11.9,
    bleedResistance: 3,
    fireResistance: 4,
    shockResistance: 2,
    blightResistance: 2,
    toxinResistance: 4,
    description: `Reinforced and designed to completely enclose the head, providing maximum protection against the dangers of the Root`,
    wikiLinks: [`https://remnant.wiki/Leto_Mark_1_Helmet`],
  },
  {
    category: 'helm',
    name: 'Leto Mark II Helmet',
    saveFileSlug: 'armor_head_leto2',
    imagePath: '/helm/leto_mark_ii_helmet.png',
    id: 'sdsybp',
    set: 'Leto Mark II Set',
    armor: 21.8,
    weight: 11.1,
    bleedResistance: 2,
    fireResistance: 3,
    shockResistance: 1,
    blightResistance: 1,
    toxinResistance: 2,
    description: `While this ironclad helmet is somewhat difficult to breathe in, you feel secure knowing even the heaviest weapon would have little chance of cracking into your skull. `,
    wikiLinks: [`https://remnant.wiki/Leto_Mark_II_Armor`],
  },
  {
    category: 'helm',
    name: 'Lodestone Crown',
    imagePath: '/helm/lodestone_crown.png',
    id: 'pjt7nj',
    armor: 6.5,
    weight: 2.6,
    bleedResistance: -2,
    fireResistance: 0,
    shockResistance: -1,
    blightResistance: 5,
    toxinResistance: 0,
    description: `This crown was worn by King Kolket himself. It could be heresy for a paxultek to wear such an artifact, but there are few left among the Pan who would even recognize it as their own.`,
    wikiLinks: [`https://remnant.wiki/Lodestone_Crown`],
  },
  {
    category: 'helm',
    name: `Mudtooth's Hat`,
    imagePath: '/helm/mudtooths_hat.png',
    id: 'u7PqrJ',
    dlc: 'dlc2',
    armor: 10.6,
    weight: 4.4,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 2,
    toxinResistance: 1,
    wikiLinks: [`https://remnant.wiki/Mudtooth's_Hat`],
    description: `A hat that once belonged to some kind of man in black. Or did it? Mudtooth went through some kind of crazy experience to get this thing, though the details are a little muddled. Either that, or he found it in a dumpster. You're going to choose to believe it's the former.`,
  },
  {
    category: 'helm',
    name: "Navigator's Helm",
    saveFileSlug: 'armor_head_pilotshelm',
    imagePath: '/helm/navigators_helm.png',
    id: 'ovnzhv',
    armor: 16,
    weight: 7.6,
    bleedResistance: -1,
    fireResistance: -1,
    shockResistance: 2,
    blightResistance: -1,
    toxinResistance: 3,
    description: `It's hard to imagine someone piloting an entire world, but that's who this helm was for. The sockets allowed them to speak with N'Erud directly. N'Erud had dozens of pilots, all working in concert-both with each other and with the world itself. `,
    wikiLinks: [`https://remnant.wiki/Navigator%27s_Helm`],
  },
  {
    category: 'helm',
    name: 'Nightstalker Shroud',
    saveFileSlug: 'armor_head_hunter',
    imagePath: '/helm/nightstalker_shroud.png',
    id: 'zy1ce3',
    set: 'Nightstalker Set',
    armor: 10.9,
    weight: 4.5,
    bleedResistance: 0,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 3,
    toxinResistance: 0,
    description: `A hunting mask with advanced respirator capabilities. It purifies yet does nothing to mask the stench of death that permeates the air. `,
    wikiLinks: [`https://remnant.wiki/Nightstalker_Shroud`],
  },
  {
    category: 'helm',
    name: 'Radiant Visage',
    saveFileSlug: 'armor_head_radiant',
    imagePath: '/helm/radiant_visage.png',
    id: 'hv4oqq',
    set: 'Radiant Set',
    armor: 17.2,
    weight: 7.9,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 3,
    blightResistance: 1,
    toxinResistance: 0,
    description: `The cowl is a striking blue, which contrasts with the large, featureless golden mask that covers the face of the wearer. This armor was highly coveted and only granted to those few who were recognized as the "Radiant Ones." `,
    wikiLinks: [`https://remnant.wiki/Radiant_Visage`],
  },
  {
    category: 'helm',
    name: 'Realmwalker Beret',
    saveFileSlug: 'armor_head_explorer',
    imagePath: '/helm/realmwalker_beret.png',
    id: 'abhqna',
    set: 'Realmwalker Set',
    armor: 7.2,
    weight: 2.9,
    bleedResistance: 0,
    fireResistance: 0,
    shockResistance: 1,
    blightResistance: 1,
    toxinResistance: 0,
    description: `This hat once belonged to Founder Ford. He was only a captain then-a much younger Ford, from a long time and many lives ago. `,
    wikiLinks: [`https://remnant.wiki/Realmwalker_Beret`],
  },
  {
    category: 'helm',
    name: 'Red Widow Headdress',
    saveFileSlug: 'armor_head_redwidow',
    imagePath: '/helm/red_widow_headdress.png',
    id: 'k6zlwn',
    set: 'Red Widow Set',
    armor: 13.2,
    weight: 5.6,
    bleedResistance: 2,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 0,
    description: `The horns of this helmet are ornamental, designed to be displayed in addition to the Pan wearer's own horns-which themselves protrude from additional openings in the armor-to create a truly frightening visage. `,
    wikiLinks: [`https://remnant.wiki/Red_Widow_Headdress`],
  },
  {
    category: 'helm',
    name: 'Space Worker Mask',
    saveFileSlug: 'armor_head_spaceworker',
    imagePath: '/helm/space_worker_mask.png',
    id: 'n3vlkq',
    set: 'Space Worker Set',
    armor: 7,
    weight: 2.8,
    bleedResistance: 1,
    fireResistance: 0,
    shockResistance: 2,
    blightResistance: 0,
    toxinResistance: 2,
    description: `People (Mudtooth mostly) tell stories of how, before the Root, humans could fly into space. It's probably not true, but if it were, they'd need something like this to keep them alive out there. `,
    wikiLinks: [`https://remnant.wiki/Space_Worker_Mask`],
  },
  {
    category: 'helm',
    name: 'Technician Helmet',
    saveFileSlug: 'armor_head_engineer',
    imagePath: '/helm/technician_helmet.png',
    id: 'gsctum',
    set: 'Technician Set',
    armor: 16.6,
    weight: 7.5,
    bleedResistance: 0,
    fireResistance: 1,
    shockResistance: 2,
    blightResistance: 0,
    toxinResistance: 2,
    description: `An overwhelming amount of information shines within the helmet's display, the vast majority of it incomprehensible. Whether that's because it's a foreign language or the helmet has been damaged by whatever destroyed this place is anybody's guess. `,
    wikiLinks: [`https://remnant.wiki/Technician_Helmet`],
  },
  {
    category: 'helm',
    name: 'Trainer Cap',
    saveFileSlug: 'armor_head_handler',
    imagePath: '/helm/trainer_cap.png',
    id: 'm8wgy9',
    set: 'Trainer Set',
    armor: 10,
    weight: 4.1,
    bleedResistance: 0,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 0,
    toxinResistance: 1,
    description: `For some reason, your head feels naked without this simple baseball cap with a fox logo. That aside, it keeps the sun out of your eyes, and that's all you ask of it.`,
    wikiLinks: [`https://remnant.wiki/Trainer_Cap`],
  },
  {
    category: 'helm',
    name: 'True Crimson Crown',
    saveFileSlug: 'armor_head_crimson', // TODO I dont know it
    imagePath: '/helm/technician_helmet.png',
    id: 'gsctud',
    dlc:'dlc2',
    set: 'True Crimson Set',
    armor: 16.6,
    weight: 10,
    bleedResistance: -6,
    fireResistance: 35,
    shockResistance: -6,
    blightResistance: -6,
    toxinResistance: -6,
    description: `Inified at long last, this enigmatic mask and flaming diadem signify that its wearer is not only forever loyal to the Red King but stands as his most favoured equal.`,
    wikiLinks: [`https://remnant.wiki/True_Crimson_Crown`],
  },
  {
    category: 'helm',
    name: 'Void Skull',
    saveFileSlug: 'armor_head_void',
    imagePath: '/helm/void_skull.png',
    id: 's7tvfn',
    set: 'Void Set',
    armor: 15.9,
    weight: 7.1,
    bleedResistance: 0,
    fireResistance: 1,
    shockResistance: 2,
    blightResistance: 0,
    toxinResistance: 1,
    description: `The skull-like helm hails from the inhospitable world of Rhom, where survival demands more than just strength and cunning. Fashioned from a mysterious material, its surface glimmers with an otherworldly sheen that seems to shift and change with the light. Its sleek and angular lines, reminiscent of some alien technology, evoke a sense of unease in those who gaze upon it. `,
    wikiLinks: [`https://remnant.wiki/Void_Skull`],
  },
  {
    category: 'helm',
    name: "Zealot's Hat",
    saveFileSlug: 'armor_head_ritualist',
    dlc: 'dlc1',
    imagePath: '/helm/zealots_hat.png',
    id: 'ts1v89',
    set: "Zealot's Set",
    armor: 11.3,
    weight: 4.7,
    bleedResistance: 0,
    fireResistance: 0,
    shockResistance: 1,
    blightResistance: 1,
    toxinResistance: 0,
    description: `A large-brimmed hat that manages to strike fear in those who see it despite its simplistic and unintimidating design. Its main use is to cast its wearer's face in
    a shadow as dark as the deeds they seek to commit under black of night.`,
    wikiLinks: [`https://remnant.wiki/Zealot%27s_Hat`],
  },
  {
    category: 'torso',
    name: "Academic's Overcoat",
    saveFileSlug: 'armor_body_alchemist',
    imagePath: '/torso/academics_overcoat.png',
    id: 'zk8f7a',
    set: `Academic's Set`,
    armor: 49.2,
    weight: 20.8,
    bleedResistance: 2,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 3,
    toxinResistance: 6,
    description: `Donning this uniform makes you feel a touch smarter, and you can't help but straighten the necktie whenever it slips loose.`,
    wikiLinks: [`https://remnant.wiki/Academic%27s_Overcoat`],
  },
  {
    category: 'torso',
    name: 'Bandit Jacket',
    saveFileSlug: 'armor_body_bandit',
    imagePath: '/torso/bandit_jacket.png',
    id: 'h04d6v',
    set: 'Bandit Set',
    armor: 27.2,
    weight: 10.8,
    bleedResistance: 3,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 2,
    description: `Little more than a coat, stitched together from scraps of leather and whatever else could be scavenged from the wasteland. While it may provide a small degree of protection against the elements, it's hardly suitable for combat and is more of a fashion statement than anything else.`,
    wikiLinks: [`https://remnant.wiki/Bandit_Jacket`],
  },
  {
    category: 'torso',
    name: 'Battle Shirt',
    saveFileSlug: 'armor_body_battle',
    imagePath: '/torso/battle_shirt.png',
    id: 'batshi',
    dlc: 'dlc2',
    set: 'Battle Set',
    armor: 31.6,
    weight: 12.8,
    bleedResistance: 2,
    fireResistance: 3,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 2,
    description: `A simple, standard-issue army shirt made from a durable canvas composite. It's seen a lot of action but was clearly carefully maintained. There appears to be some kind of tag above the pocket, but whatever it once said, time washed it away long ago.`,
    wikiLinks: [`https://remnant.wiki/Battle_Shirt`],
  },
  {
    category: 'torso',
    name: 'Bruiser Bodyplate',
    saveFileSlug: 'armor_body_challenger',
    imagePath: '/torso/bruiser_bodyplate.png',
    id: 'trz2cm',
    set: 'Bruiser Set',
    armor: 70.2,
    weight: 32.4,
    bleedResistance: 2,
    fireResistance: 6,
    shockResistance: 0,
    blightResistance: 0,
    toxinResistance: 2,
    description: `This thing is difficult to put on or take off and makes you feel like a walking tank. In the thick of battle, that's exactly what you're looking for.`,
    wikiLinks: [`https://remnant.wiki/Bruiser_Bodyplate`],
  },
  {
    category: 'torso',
    name: 'Crimson Guard Plate',
    saveFileSlug: 'armor_body_crimsonguard',
    dlc: 'dlc1',
    imagePath: '/torso/crimson_guard_plate.png',
    id: 'hz7ddb',
    set: 'Crimson Guard Set',
    armor: 60.8,
    weight: 26.8,
    bleedResistance: 4,
    fireResistance: 3,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 0,
    description: `This heavy suit of armor encumbers your shoulders with weight befitting the burdens of a sovereign. It emits a faint heat, as if forged from an ever-hot metal.`,
    wikiLinks: [`https://remnant.wiki/Crimson_Guard_Plate`],
  },
  {
    category: 'torso',
    name: 'Cultist Duster',
    saveFileSlug: 'armor_body_cultist',
    imagePath: '/torso/cultist_duster.png',
    id: 'w4emjx',
    set: 'Cultist Set',
    armor: 44.6,
    weight: 18.4,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 2,
    blightResistance: 2,
    toxinResistance: 3,
    description: `More symbolic than functional, it's adorned with trinkets and ornaments instead of providing significant protection. The coat's drab color blends in with the bleak, post-apocalyptic landscape, serving as a visible sign of the wearer's allegiance to the Root`,
    wikiLinks: [`https://remnant.wiki/Cultist_Duster`],
  },
  {
    category: 'torso',
    name: 'Dendroid Chest',
    saveFileSlug: 'armor_body_invader',
    imagePath: '/torso/dendroid_chest.png',
    id: 'uoddub',
    set: 'Dendroid Set',
    armor: 30.8,
    weight: 12.4,
    bleedResistance: 4,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 5,
    description: `Fibrous tentacles wrap themselves around your chest. Up until now, you've resolutely avoided this situation.`,
    wikiLinks: [`https://remnant.wiki/Dendroid_Chest`],
  },
  {
    category: 'torso',
    name: 'Disciple Mantle',
    saveFileSlug: 'armor_body_invoker',
    imagePath: '/torso/disciple_mantle.png',
    id: 'ddddub',
    dlc:'dlc2',
    set: 'Disciple Set',
    armor: 64,
    weight: 28.8,
    bleedResistance: 0,
    fireResistance: 4,
    shockResistance: 5,
    blightResistance: 2,
    toxinResistance: 0,
    description: `The pauldrons bear the mirrored faces of Meidra and Kaeula, who always journeyed together in their ethereal wanderings, for Meidra's flowers could not bloom so lovely without Kaeula's rains.`,
    wikiLinks: [`https://remnant.wiki/Disciple_Mantle`],
  },
  {
    category: 'torso',
    name: 'Elder Raiment',
    saveFileSlug: 'armor_body_elder',
    imagePath: '/torso/elder_raiment.png',
    id: 'zu64t4',
    set: 'Elder Set',
    armor: 29.6,
    weight: 12,
    bleedResistance: 0,
    fireResistance: 4,
    shockResistance: 0,
    blightResistance: 4,
    toxinResistance: 2,
    description: `A distinctive piece of protective gear originating from Yaesha. Its vibrant red color and fur adornments make it stand out, serving as a symbol of the wearer's status and skill. While it may not provide as much protection as some other types of armor, its lightweight construction and flexible design allow for exceptional mobility and ease of movement in combat.`,
    wikiLinks: [`https://remnant.wiki/Elder_Raiment`],
  },
  {
    category: 'torso',
    name: 'Fae Royal Bodyplate',
    saveFileSlug: 'armor_body_faeroyalguard',
    imagePath: '/torso/fae_royal_bodyplate.png',
    id: '0sm6sn',
    set: 'Fae Royal Set',
    armor: 60,
    weight: 26.4,
    bleedResistance: 4,
    fireResistance: 3,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 0,
    description: `The royal guard do not wear insignias on their chests nor crests on their shield. It is assumed their identify is clear from their grab and the confidence with which they carry themselves.`,
    wikiLinks: [`https://remnant.wiki/Fae_Royal_Bodyplate`],
  },
  {
    category: 'torso',
    name: 'Field Medic Overcoat',
    saveFileSlug: 'armor_body_medic',
    imagePath: '/torso/field_medic_overcoat.png',
    id: 'm07a0z',
    set: 'Field Medic Set',
    armor: 42.8,
    weight: 17.6,
    bleedResistance: 9,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 3,
    toxinResistance: 0,
    description: `A long coat over a plate of armor. The metal could be thicker, sure, but your primary concern is safe and speedy travel to the wounded.`,
    wikiLinks: [`https://remnant.wiki/Field_Medic_Overcoat`],
  },
  {
    category: 'torso',
    name: 'High Noon Duds',
    saveFileSlug: 'armor_body_gunslinger',
    imagePath: '/torso/high_noon_duds.png',
    id: 'uszg5g',
    set: 'High Noon Set',
    armor: 47.1,
    weight: 19.6,
    bleedResistance: 0,
    fireResistance: 4,
    shockResistance: 4,
    blightResistance: 0,
    toxinResistance: 2,
    description: `A rugged amalgamation of canvas, denim, leather, and steel. These different materials all serve the same purpose of keeping you covered without inhibiting aiming mobility.`,
    wikiLinks: [`https://remnant.wiki/High_Noon_Duds`],
  },
  {
    category: 'torso',
    name: 'Knotted Cage',
    saveFileSlug: 'armor_body_summoner',
    imagePath: '/torso/knotted_cage.png',
    id: 'n92z22',
    set: 'Knotted Set',
    armor: 62.2,
    weight: 27.6,
    bleedResistance: 1,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 3,
    toxinResistance: 7,
    description: `Tightly coiled bark shrouds you like a second ribcage. Its embrace is surprisingly-and frighteningly-comforting.`,
    wikiLinks: [`https://remnant.wiki/Knotted_Cage`],
  },
  {
    category: 'torso',
    name: 'Labyrinth Mantle',
    saveFileSlug: 'armor_body_archon',
    imagePath: '/torso/labyrinth_mantle.png',
    id: 'ivwkr5',
    set: 'Labyrinth Set',
    armor: 51,
    weight: 21.6,
    bleedResistance: 0,
    fireResistance: 4,
    shockResistance: 6,
    blightResistance: 0,
    toxinResistance: 0,
    description: `Though the cloth and tassels possess a seemingly primitive design, the pure energy wracking down your spine reminds you otherwise.`,
    wikiLinks: [`https://remnant.wiki/Labyrinth_Mantle`],
  },
  {
    category: 'torso',
    name: 'Leto Mark 1 Armor',
    saveFileSlug: 'armor_body_leto1',
    imagePath: '/torso/leto_mark_i_armor.png',
    id: 'y1xt79',
    set: 'Leto Mark 1 Set',
    armor: 90.4,
    weight: 47.5,
    bleedResistance: 4,
    fireResistance: 5,
    shockResistance: 5,
    blightResistance: 5,
    toxinResistance: 5,
    description: `An impressive prototype engineered to safeguard against any danger from the Root, but its cutting-edge technology sacrifices agility and mobility in exchange for unparalleled protection `,
    wikiLinks: [`https://remnant.wiki/Leto_Mark_1_Armor`],
  },
  {
    category: 'torso',
    name: 'Leto Mark II Armor',
    saveFileSlug: 'armor_body_leto2',
    imagePath: '/torso/leto_mark_ii_armor.png',
    id: 'ioksvz',
    set: 'Leto Mark II Set',
    armor: 88.8,
    weight: 45.2,
    bleedResistance: 3,
    fireResistance: 4,
    shockResistance: 4,
    blightResistance: 5,
    toxinResistance: 3,
    description: `A masterpiece of impenetrability. Even though quick maneuvering is near impossible in this metal behemoth, you can't help but be impressed by the ingenuity of the design and the inspired craftsmanship.`,
    wikiLinks: [`https://remnant.wiki/Leto_Mark_II_Armor`],
  },
  {
    category: 'torso',
    name: 'Nightstalker Garb',
    saveFileSlug: 'armor_body_hunter',
    imagePath: '/torso/nightstalker_garb.png',
    id: 'lqrdx5',
    set: 'Nightstalker Set',
    armor: 43.8,
    weight: 18,
    bleedResistance: 2,
    fireResistance: 3,
    shockResistance: 2,
    blightResistance: 2,
    toxinResistance: 0,
    description: `This old coat is shabby, but who's really looking? The wealth of interior ammunition pockets more than makes up for it.`,
    wikiLinks: [`https://remnant.wiki/Nightstalker_Garb`],
  },
  {
    category: 'torso',
    name: 'Radiant Protector',
    saveFileSlug: 'armor_body_radiant',
    imagePath: '/torso/radiant_protector.png',
    id: 'dd5s6k',
    set: 'Radiant Set',
    armor: 69,
    weight: 31.6,
    bleedResistance: 2,
    fireResistance: 2,
    shockResistance: 4,
    blightResistance: 1,
    toxinResistance: 0,
    description: `A dazzling sight, its golden surface featuring a stunning sun burst pattern etched into the chest. Adorned with blue gems embedded in the shoulders this armor is fit for only the most esteemed members of the Laemir`,
    wikiLinks: [`https://remnant.wiki/Radiant_Protector`],
  },
  {
    category: 'torso',
    name: 'Realmwalker Tunic',
    saveFileSlug: 'armor_body_explorer',
    imagePath: '/torso/realmwalker_tunic.png',
    id: '2h9xgj',
    set: 'Realmwalker Set',
    armor: 29,
    weight: 11.6,
    bleedResistance: 3,
    fireResistance: 2,
    shockResistance: 3,
    blightResistance: 4,
    toxinResistance: 0,
    description: `It's not even frayed. How is that possible? Unless the World Stones did the same thing to Ford's clothes as they did to Ford himself.`,
    wikiLinks: [`https://remnant.wiki/Realmwalker_Tunic`],
  },
  {
    category: 'torso',
    name: 'Red Widow Raiment',
    saveFileSlug: 'armor_body_redwidow',
    imagePath: '/torso/red_widow_raiment.png',
    id: 'lude4p',
    set: 'Red Widow Set',
    armor: 52.8,
    weight: 22.4,
    bleedResistance: 5,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 4,
    toxinResistance: 1,
    description: `This chest piece must be hundreds -thousands- of years old, yet it shows no signis of rust or decay. One can only imagine a Pan king or queen wearing such  majestic regalia.`,
    wikiLinks: [`https://remnant.wiki/Red_Widow_Raiment`],
  },
  {
    category: 'torso',
    name: 'Space Worker Body',
    saveFileSlug: 'armor_body_spaceworker',
    imagePath: '/torso/space_worker_body.png',
    id: 'jwanjw',
    set: 'Space Worker Set',
    armor: 28,
    weight: 11.2,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 4,
    blightResistance: 0,
    toxinResistance: 2,
    description: `It's made of some material you don't recognize - thick but highly pliable, did the Drzyr expect to get struck by out there?`,
    wikiLinks: [`https://remnant.wiki/Space_Worker_Body`],
  },
  {
    category: 'torso',
    name: 'Survivor Overcoat',
    saveFileSlug: 'armor_body_survivor',
    imagePath: '/torso/survivor_overcoat.png',
    id: 'jr8r1l',
    set: 'Survivor Set',
    armor: 39.2,
    weight: 16,
    bleedResistance: 3,
    fireResistance: 2,
    shockResistance: 2,
    blightResistance: 2,
    toxinResistance: 2,
    description: `A combination of a sturdy metal chest plate and a worn, leather trench coat that provides some protection against the elements. It's clear that the are together with practicality in mind, rather than aesthetics.`,
    wikiLinks: [`https://remnant.wiki/Survivor_Overcoat`],
  },
  {
    category: 'torso',
    name: 'Technician Bodyplate',
    saveFileSlug: 'armor_body_engineer',
    imagePath: '/torso/technician_bodyplate.png',
    id: '0c35xs',
    set: 'Technician Set',
    armor: 66.4,
    weight: 30,
    bleedResistance: 0,
    fireResistance: 2,
    shockResistance: 6,
    blightResistance: 0,
    toxinResistance: 2,
    description: `The Xul were engineers and builders, but this armor was made to withstand a grenade blast. Was this built for safety or something else?`,
    wikiLinks: [`https://remnant.wiki/Technician_Bodyplate`],
  },
  {
    category: 'torso',
    name: 'Trainer Clothes',
    saveFileSlug: 'armor_body_handler',
    imagePath: '/torso/trainer_clothes.png',
    id: 'ldli1k',
    set: 'Trainer Set',
    armor: 40,
    weight: 16.4,
    bleedResistance: 3,
    fireResistance: 0,
    shockResistance: 4,
    blightResistance: 1,
    toxinResistance: 3,
    description: `This isn't just any denim jacket, it's your denim jacket. It's not especial pale. 7 ready, but it's comfortable, and in it you feel ready for anything.`,
    wikiLinks: [`https://remnant.wiki/Trainer_Clothes`],
  },
  {
    category: 'torso',
    name: 'Void Carapace',
    saveFileSlug: 'armor_body_void',
    imagePath: '/torso/void_carapace.png',
    id: 'rmq9je',
    set: 'Void Set',
    armor: 63.6,
    weight: 28.4,
    bleedResistance: 0,
    fireResistance: 3,
    shockResistance: 4,
    blightResistance: 0,
    toxinResistance: 4,
    description: `Crafted from the same mysterious material as the Void gloves, helm, and greaves, the chest armor completes the set's unsettling aesthetic. Its angular design is both practical and intimidating, providing unparalleled protection against the deadly environments and creatures of Rhom.`,
    wikiLinks: [`https://remnant.wiki/Void_Carapace`],
  },
  {
    category: 'torso',
    name: "Zealot's Overcoat",
    saveFileSlug: 'armor_body_ritualist',
    dlc: 'dlc1',
    imagePath: '/torso/zealots_overcoat.png',
    id: 'ym0mau',
    set: "Zealot's Set",
    armor: 45.2,
    weight: 18.8,
    bleedResistance: 3,
    fireResistance: 2,
    shockResistance: 3,
    blightResistance: 4,
    toxinResistance: 0,
    description: `This long and tattered cloak is ideal for skulking about in the dead of night in pursuance of iniquitous aims. If you ever see the back of this cloak ahead of you, you would do well to run. If you ever see its wearer facing you, it is already too late.`,
    wikiLinks: [`https://remnant.wiki/Zealot%27s_Overcoat`],
  },
  {
    category: 'legs',
    name: "Academic's Trousers",
    saveFileSlug: 'armor_legs_alchemist',
    imagePath: '/legs/academics_trousers.png',
    id: '9b43cb',
    set: `Academic's Set`,
    armor: 24.6,
    weight: 10.4,
    bleedResistance: 2,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 1,
    toxinResistance: 4,
    description: `Expensive-looking shoes fit for a lecture hall...that wouldn't last a week outside it.`,
    wikiLinks: [`https://remnant.wiki/Academic%27s_Trousers`],
  },
  {
    category: 'legs',
    name: 'Bandit Trousers',
    saveFileSlug: 'armor_legs_bandit',
    imagePath: '/legs/bandit_trousers.png',
    id: 'zdv44y',
    set: 'Bandit Set',
    armor: 13.6,
    weight: 5.4,
    bleedResistance: 2,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 1,
    toxinResistance: 2,
    description: `Consists of a pair of basic slacks and sturdy boots. While it may not offer much in terms of protection, it allows for easy movement and agility in the dangerous terrain of the ruined cityscapes. The simplicity of the design is a testament to the practicality of the bandits, who prioritize functionality over aesthetics.`,
    wikiLinks: [`https://remnant.wiki/Bandit_Trousers`],
  },
  {
    category: 'legs',
    name: 'Battle Trousers',
    saveFileSlug: 'armor_legs_battle',
    imagePath: '/legs/battle_trousers.png',
    id: 'battra',
    dlc:'dlc2',
    set: 'Battle Set',
    armor: 15.8,
    weight: 6.4,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 0,
    blightResistance: 1,
    toxinResistance: 2,
    description: `A rugged pair of army pants complete with a functional, nondescript belt, a belt buckle, and a set of worn leather boots. They're designed to withstand whatver the mission demands of a soldier.`,
    wikiLinks: [`https://remnant.wiki/Battle_Slacks`],
  },
  {
    category: 'legs',
    name: 'Bruiser Boots',
    saveFileSlug: 'armor_legs_challenger',
    imagePath: '/legs/bruiser_boots.png',
    id: 'pof5ii',
    set: 'Bruiser Set',
    armor: 35,
    weight: 16.2,
    bleedResistance: 1,
    fireResistance: 4,
    shockResistance: 0,
    blightResistance: 0,
    toxinResistance: 2,
    description: `While they're not exactly aesthetic, you're more comfortable in twice-temper steel and repurposed tire tread than you care to admit.`,
    wikiLinks: [`https://remnant.wiki/Bruiser_Boots`],
  },
  {
    category: 'legs',
    name: 'Crimson Guard Sabatons',
    saveFileSlug: 'armor_legs_crimsonguard',
    dlc: 'dlc1',
    imagePath: '/legs/crimson_guard_sabatons.png',
    id: 'zk58sf',
    set: 'Crimson Guard Set',
    armor: 30.4,
    weight: 13.4,
    bleedResistance: 2,
    fireResistance: 3,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 0,
    description: `The crimson greaves clink and clank as you walk, announcing your presence to those honored enough to know it. Each sabaton tapers to a sharp, defiant point.`,
    wikiLinks: [`https://remnant.wiki/Crimson_Guard_Sabatons`],
  },
  {
    category: 'legs',
    name: 'Cultist Britches',
    saveFileSlug: 'armor_legs_cultist',
    imagePath: '/legs/cultist_britches.png',
    id: 'mr4hn3',
    set: 'Cultist Set',
    armor: 22.2,
    weight: 9.2,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 2,
    toxinResistance: 2,
    description: `Simple slacks and boots made of cloth and wrapped in rope. Cultists rely on their unwavering devotion to the Root for their safety instead.`,
    wikiLinks: [`https://remnant.wiki/Cultist_Britches`],
  },
  {
    category: 'legs',
    name: 'Dendroid Leggings',
    saveFileSlug: 'armor_legs_invader',
    imagePath: '/legs/dendroid_leggings.png',
    id: 'zwh3mb',
    set: 'Dendroid Set',
    armor: 15.4,
    weight: 6.2,
    bleedResistance: 3,
    fireResistance: 0,
    shockResistance: 2,
    blightResistance: 2,
    toxinResistance: 0,
    description: `The deadwood boots are surprisingly snug. You're not sure what you expected shodding your feet inside the bloodthirsty branches of the Root, but it wasn't this cushioned comfort.`,
    wikiLinks: [`https://remnant.wiki/Dendroid_Leggings`],
  },
  {
    category: 'legs',
    name: 'Disciple Greaves',
    saveFileSlug: 'armor_body_invoker',
    imagePath: '/torso/disciple_greaves.png',
    id: 'udddub',
    dlc:'dlc2',
    set: 'Disciple Set',
    armor: 32,
    weight: 14.4,
    bleedResistance: 0,
    fireResistance: 2,
    shockResistance: 3,
    blightResistance: 1,
    toxinResistance: 0,
    description: `You can feel all of Yaesha beneath the soles of these heavy greaves: the soft loam of the soil, the plush of green clovers, and the cold chill of a gurgling stream. You walk with the ease of those who were born of the forest.`,
    wikiLinks: [`https://remnant.wiki/Disciple_Greaves`],
  },
  {
    category: 'legs',
    name: 'Elder Leggings',
    saveFileSlug: 'armor_legs_elder',
    imagePath: '/legs/elder_leggings.png',
    id: 'tfvyyg',
    set: 'Elder Set',
    armor: 14.8,
    weight: 6,
    bleedResistance: 0,
    fireResistance: 3,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 1,
    description: `Designed for both form and function. Made from durable yet lightweight materials, they allow for a full range of movement and flexibility in combat.`,
    wikiLinks: [`https://remnant.wiki/Elder_Leggings`],
  },
  {
    category: 'legs',
    name: 'Fae Royal Greaves',
    saveFileSlug: 'armor_legs_faeroyalguard',
    imagePath: '/legs/fae_royal_greaves.png',
    id: 'pi4h8k',
    set: 'Fae Royal Set',
    armor: 30,
    weight: 13.2,
    bleedResistance: 2,
    fireResistance: 3,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 0,
    description: `Although apparently made of steel, they feel lighter than any boots you've eve worn.

    No... you feel lighter when wearing them.`,
    wikiLinks: [`https://remnant.wiki/Fae_Royal_Greaves`],
  },
  {
    category: 'legs',
    name: 'Field Medic Trousers',
    saveFileSlug: 'armor_legs_medic',
    imagePath: '/legs/field_medic_trousers.png',
    id: 'eqcfyt',
    set: 'Field Medic Set',
    armor: 21.4,
    weight: 8.8,
    bleedResistance: 4,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 0,
    description: `With an assortment of pockets, pouches, and loops for your various concoctions you're essentially a walking apothecary.`,
    wikiLinks: [`https://remnant.wiki/Field_Medic_Trousers`],
  },
  {
    category: 'legs',
    name: 'High Noon Soles',
    saveFileSlug: 'armor_legs_gunslinger',
    imagePath: '/legs/high_noon_soles.png',
    id: 'yccols',
    set: 'High Noon Set',
    armor: 23.4,
    weight: 9.8,
    bleedResistance: 0,
    fireResistance: 3,
    shockResistance: 2,
    blightResistance: 0,
    toxinResistance: 2,
    description: `Durable pants with spurred boots and a strip of leather for a belt. The only accent is an imposing skull on the belt buckle, a constant reminder that death is always lurking in the shadows.`,
    wikiLinks: [`https://remnant.wiki/High_Noon_Soles`],
  },
  {
    category: 'legs',
    name: 'Knotted Greaves',
    saveFileSlug: 'armor_legs_summoner',
    imagePath: '/legs/knotted_greaves.png',
    id: 'b48zw1',
    set: 'Knotted Set',
    armor: 31.1,
    weight: 13.8,
    bleedResistance: 1,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 4,
    description: `These boots are surprisingly light and agile, carrying you through foliage and bramble with ease. They seem to know where to go before you even lift you foot.`,
    wikiLinks: [`https://remnant.wiki/Knotted_Greaves`],
  },
  {
    category: 'legs',
    name: 'Labyrinth Treads',
    saveFileSlug: 'armor_legs_archon',
    imagePath: '/legs/labyrinth_treads.png',
    id: 'td29nk',
    set: 'Labyrinth Set',
    armor: 25.5,
    weight: 10.8,
    bleedResistance: 0,
    fireResistance: 3,
    shockResistance: 4,
    blightResistance: 0,
    toxinResistance: 0,
    description: `The grime of a thousand different worlds mars the side of boots that walk in one place where all paths converge.`,
    wikiLinks: [`https://remnant.wiki/Labyrinth_Treads`],
  },
  {
    category: 'legs',
    name: 'Leto Mark 1 Leggings',
    saveFileSlug: 'armor_legs_leto1',
    imagePath: '/legs/leto_mark_1_leggings.png',
    id: '59uhgg',
    set: 'Leto Mark 1 Set',
    armor: 45.2,
    weight: 23.7,
    bleedResistance: 4,
    fireResistance: 3,
    shockResistance: 4,
    blightResistance: 4,
    toxinResistance: 3,
    description: `Offering unparalleled protection at the cost of speed and agility. Although it hinders movement, the armor's strength allows its wearer to withstand even the most vicious attacks without fear of serious injury.`,
    wikiLinks: [`https://remnant.wiki/Leto_Mark_1_Leggings`],
  },
  {
    category: 'legs',
    name: 'Leto Mark II Leggings',
    saveFileSlug: 'armor_legs_leto2',
    imagePath: '/legs/leto_mark_ii_leggings.png',
    id: 't8auqk',
    set: 'Leto Mark II Set',
    armor: 44.4,
    weight: 22.6,
    bleedResistance: 3,
    fireResistance: 2,
    shockResistance: 3,
    blightResistance: 3,
    toxinResistance: 2,
    description: `Strong yet streamlined. Practical yet aesthetic. Although you can't expect to make a quick getaway in these, they're just what you need to stand strong against the looming threat of destruction. The care and attention to detail t| went into them is something to behold.`,
    wikiLinks: [`https://remnant.wiki/Leto_Mark_II_Leggings`],
  },
  {
    category: 'legs',
    name: 'Nightstalker Pants',
    saveFileSlug: 'armor_legs_hunter',
    imagePath: '/legs/nightstalker_pants.png',
    id: 'l6utx1',
    set: 'Nightstalker Set',
    armor: 21.8,
    weight: 9,
    bleedResistance: 2,
    fireResistance: 2,
    shockResistance: 1,
    blightResistance: 1,
    toxinResistance: 0,
    description: `Thin shoes that fit perfectly and feel like they practically disappear on your feet. They're ideal for stealthy maneuvering while stalking your prey.`,
    wikiLinks: [`https://remnant.wiki/Nightstalker_Pants`],
  },
  {
    category: 'legs',
    name: 'Radiant Greaves',
    saveFileSlug: 'armor_legs_radiant',
    imagePath: '/legs/radiant_greaves.png',
    id: 'vsg3ue',
    set: 'Radiant Set',
    armor: 34.5,
    weight: 15.8,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 3,
    blightResistance: 1,
    toxinResistance: 0,
    description: `Gleaming golden plates overlap and protect the wearer's feet and shins. Originally designed to be worn by the Pan, it's impressive how the armor can be adapted to fit human proportions without sacrificing its durability or protective properties.`,
    wikiLinks: [`https://remnant.wiki/Radiant_Greaves`],
  },
  {
    category: 'legs',
    name: 'Realmwalker Pantaloons',
    saveFileSlug: 'armor_legs_explorer',
    imagePath: '/legs/realmwalker_pantaloons.png',
    id: '4sy6z9',
    set: 'Realmwalker Set',
    armor: 14.5,
    weight: 5.8,
    bleedResistance: 2,
    fireResistance: 1,
    shockResistance: 2,
    blightResistance: 3,
    toxinResistance: 0,
    description: `There is hardly a world where these boots haven't tread.`,
    wikiLinks: [`https://remnant.wiki/Realmwalker_Pantaloons`],
  },
  {
    category: 'legs',
    name: 'Red Widow Leggings',
    saveFileSlug: 'armor_legs_redwidow',
    imagePath: '/legs/red_widow_leggings.png',
    id: 'e4fbbu',
    set: 'Red Widow Set',
    armor: 26.2,
    weight: 11.2,
    bleedResistance: 3,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 3,
    toxinResistance: 1,
    description: `Even though this armor was designed to be worn by a Pan warrior, you are still able wear it and benefit from its protection.`,
    wikiLinks: [`https://remnant.wiki/Red_Widow_Leggings`],
  },
  {
    category: 'legs',
    name: 'Space Worker Legs',
    saveFileSlug: 'armor_legs_spaceworker',
    imagePath: '/legs/space_worker_legs.png',
    id: 'rsyilr',
    set: 'Space Worker Set',
    armor: 14,
    weight: 5.6,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 3,
    blightResistance: 0,
    toxinResistance: 2,
    description: `The magnets in the boots are far stronger than those in the gloves. It's unclear how they know when to activate, but they do so on their own. Massive as N'Erud is, it must not provide enough gravity to ensure its workers remain attached to...`,
    wikiLinks: [`https://remnant.wiki/Space_Worker_Legs`],
  },
  {
    category: 'legs',
    name: 'Survivor Leggings',
    saveFileSlug: 'armor_legs_survivor',
    imagePath: '/legs/survivor_leggings.png',
    id: 'gv2eqj',
    set: 'Survivor Set',
    armor: 19.6,
    weight: 8,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 1,
    toxinResistance: 2,
    description: `Provides minimal protection, but serve the purpose of covering up skin to prevent minor cuts and scrapes while trekking through rough terrain.`,
    wikiLinks: [`https://remnant.wiki/Survivor_Leggings`],
  },
  {
    category: 'legs',
    name: 'Technician Greaves',
    saveFileSlug: 'armor_legs_engineer',
    imagePath: '/legs/technician_greaves.png',
    id: 'm16oqd',
    set: 'Technician Set',
    armor: 33.2,
    weight: 15,
    bleedResistance: 0,
    fireResistance: 1,
    shockResistance: 3,
    blightResistance: 0,
    toxinResistance: 2,
    description: `Designed for stability rather than speed. Plant your weight in these things, and you'd be very difficult to move.`,
    wikiLinks: [`https://remnant.wiki/Technician_Greaves`],
  },
  {
    category: 'legs',
    name: 'Trainer Workboots',
    saveFileSlug: 'armor_legs_handler',
    imagePath: '/legs/trainer_workboots.png',
    id: 'olwicb',
    set: 'Trainer Set',
    armor: 20,
    weight: 8.2,
    bleedResistance: 1,
    fireResistance: 0,
    shockResistance: 1,
    blightResistance: 1,
    toxinResistance: 2,
    description: `Durable pants that are used to handling more than a little dirt and fur. The canteen is for your companion, while the flask is all yours.`,
    wikiLinks: [`https://remnant.wiki/Trainer_Workboots`],
  },
  {
    category: 'legs',
    name: 'Void Greaves',
    saveFileSlug: 'armor_legs_void',
    imagePath: '/legs/void_greaves.png',
    id: '73lqjk',
    set: 'Void Set',
    armor: 31.8,
    weight: 14.2,
    bleedResistance: 0,
    fireResistance: 2,
    shockResistance: 2,
    blightResistance: 0,
    toxinResistance: 3,
    description: `A sturdy pair of footwear, expertly crafted from the same unknown material the other Void armor pieces. Their angular design and jagged edges give their wearer an intimidating and fearsome look. But these boots are more than fashion statement-they provided unparalleled protection and stability in the treacherous environments of Rhom.`,
    wikiLinks: [`https://remnant.wiki/Void_Greaves`],
  },
  {
    category: 'legs',
    name: "Zealot's Seaboots",
    saveFileSlug: 'armor_legs_ritualist',
    dlc: 'dlc1',
    imagePath: '/legs/zealots_seaboots.png',
    id: 'sem0s8',
    set: "Zealot's Set",
    armor: 22.6,
    weight: 9.4,
    bleedResistance: 2,
    fireResistance: 1,
    shockResistance: 2,
    blightResistance: 3,
    toxinResistance: 0,
    description: `Tall wading boots and toughened leather may protect your legs from the unruly waters of Losomn, but they will do nothing to guard against the treacherous creatures that lurk just beneath those sullied waves, thirsting for the blood of those who stray too far from shore.`,
    wikiLinks: [`https://remnant.wiki/Zealot%27s_Seaboots`],
  },
  {
    category: 'gloves',
    name: "Academic's Gloves",
    saveFileSlug: 'armor_gloves_alchemist',
    set: "Academic's Set",
    imagePath: '/gloves/academics_gloves.png',
    id: 'f4tb3k',
    armor: 12.3,
    weight: 5.2,
    bleedResistance: 0,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 1,
    toxinResistance: 2,
    description: `The initials of the Dran who once owned these - and misplaced them often - are embroidered on the wool-lined inside.`,
    wikiLinks: [`https://remnant.wiki/Academic%27s_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Bandit Gloves',
    saveFileSlug: 'armor_gloves_bandit',
    imagePath: '/gloves/bandit_gloves2.png',
    id: 'b7j8ys',
    set: 'Bandit Set',
    armor: 6.8,
    weight: 2.7,
    bleedResistance: 2,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 1,
    toxinResistance: 2,
    description: `The bandit gloves are rough, patched together from scraps of leather and cloth, a testament to their owner's resourcefulness, and willingness to do whatever it takes to survive. Despite their rough and worn appearance, the gloves provide unexpected durability and protection amidst the unforgiving ruins of the city.`,
    wikiLinks: [`https://remnant.wiki/Bandit_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Battle Gloves',
    saveFileSlug: 'armor_gloves_battle',
    imagePath: '/gloves/battle_gloves.png',
    id: 'batglo',
    dlc:'dlc2',
    set: 'Battle Set',
    armor: 7.9,
    weight: 3.2,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 0,
    blightResistance: 1,
    toxinResistance: 1,
    description: `This pair of leather army gloves couldn't be more to the point. They help guard against knicks and cuts and will help you keep a strong grip even in extreme conditions. It's not the most effective gear you've ever seen, but it's better than nothing.`,
    wikiLinks: [`https://remnant.wiki/Battle_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Bruiser Gloves',
    saveFileSlug: 'armor_gloves_challenger',
    imagePath: '/gloves/bruiser_gloves.png',
    id: '80xuqr',
    set: 'Bruiser Set',
    armor: 17.6,
    weight: 8.1,
    bleedResistance: 1,
    fireResistance: 2,
    shockResistance: 0,
    blightResistance: 0,
    toxinResistance: 1,
    description: `These gauntlets are as tough as steel, as hard as stone, and up for whatever dangers or challenges come their way. They suit you well.`,
    wikiLinks: [`https://remnant.wiki/Bruiser_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Crimson Guard Gauntlets',
    saveFileSlug: 'armor_gloves_crimsonguard',
    dlc: 'dlc1',
    imagePath: '/gloves/crimson_guard_gauntlets.png',
    id: 'ms9geh',
    set: 'Crimson Guard Set',
    armor: 15.2,
    weight: 6.7,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 1,
    toxinResistance: 0,
    description: `These gauntlets line your forearms with sharp, yet elegant edges, though they lack the sharpened claws that would make a proper bloodthirsty Fae of you.`,
    wikiLinks: [`https://remnant.wiki/Crimson_Guard_Gauntlets`],
  },
  {
    category: 'gloves',
    name: 'Cultist Gloves',
    saveFileSlug: 'armor_gloves_cultist',
    imagePath: '/gloves/cultist_gloves1.png',
    id: '6jrywg',
    set: 'Cultist Set',
    armor: 11.1,
    weight: 4.6,
    bleedResistance: 0,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 1,
    toxinResistance: 1,
    description: `An unusual piece of attire that consist of leather and rope wrappings that encircle the wearer's wrists. These unconventional gloves were favored by the members of a mysterious cult that valued secrecy and esoteric knowledge above all else`,
    wikiLinks: [`https://remnant.wiki/Cultist_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Dendroid Grips',
    saveFileSlug: 'armor_gloves_invader',
    imagePath: '/gloves/dendroid_grips.png',
    id: '6oy3xp',
    set: 'Dendroid Set',
    armor: 7.7,
    weight: 3.1,
    bleedResistance: 1,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 1,
    toxinResistance: 1,
    description: `Against all logic, these gloves feel natural. Like extensions of who you were meant to be.

    Seems like that should bother you more.`,
    wikiLinks: [`https://remnant.wiki/Dendroid_Grips`],
  },
  {
    category: 'gloves',
    name: 'Disciple Vambraces',
    saveFileSlug: 'armor_gloves_invoker',
    imagePath: '/gloves/disciple_vambraces.png',
    id: '6dy3xp',
    dlc:'dlc2',
    set: 'Disciple Set',
    armor: 16,
    weight: 7.2,
    bleedResistance: 0,
    fireResistance: 1,
    shockResistance: 2,
    blightResistance: 0,
    toxinResistance: 0,
    description: `The gauntlets taper to sharp points, reminding one that everything in Yaesha is deadly, even those who seem too beautiful to be so.`,
    wikiLinks: [`https://remnant.wiki/Disciple_Vambraces`],
  },
  {
    category: 'gloves',
    name: 'Elder Gloves',
    saveFileSlug: 'armor_gloves_elder',
    imagePath: '/gloves/elder_gloves.png',
    id: '1ijl54',
    set: 'Elder Set',
    armor: 7.5,
    weight: 3,
    bleedResistance: 0,
    fireResistance: 2,
    shockResistance: 0,
    blightResistance: 1,
    toxinResistance: 1,
    description: `Features striking loops of gold that add an ornate touch to the otherwise plain design. Curiously, these embellishments are only present on the left-hand glove, making it stand out from its counterpart on the right.`,
    wikiLinks: [`https://remnant.wiki/Elder_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Fae Royal Vambraces',
    saveFileSlug: 'armor_gloves_faeroyalguard',
    imagePath: '/gloves/fae_royal_vambraces.png',
    id: '6005lk',
    set: 'Fae Royal Set',
    armor: 15,
    weight: 6.6,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 0,
    blightResistance: 1,
    toxinResistance: 0,
    description: `Suitable for archery or swordplay - for killing of any sort really.`,
    wikiLinks: [`https://remnant.wiki/Fae_Royal_Vambraces`],
  },
  {
    category: 'gloves',
    name: 'Field Medic Gloves',
    saveFileSlug: 'armor_gloves_medic',
    imagePath: '/gloves/field_medic_gloves1.png',
    id: '7ic3gp',
    set: 'Field Medic Set',
    armor: 10.6,
    weight: 4.4,
    bleedResistance: 2,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 1,
    toxinResistance: 1,
    description: `At a glance it's clear that these fingerless gloves won't keep you warm or offer much protection. Even still, you wear them because they provide improved grip without impacting precision.`,
    wikiLinks: [`https://remnant.wiki/Field_Medic_Gloves`],
  },
  {
    category: 'gloves',
    name: 'High Noon Armguards',
    saveFileSlug: 'armor_gloves_gunslinger',
    imagePath: '/gloves/high_noon_armguards.png',
    id: 'afu61j',
    set: 'High Noon Set',
    armor: 11.7,
    weight: 4.9,
    bleedResistance: 0,
    fireResistance: 2,
    shockResistance: 2,
    blightResistance: 0,
    toxinResistance: 1,
    description: `Metal arm guards paired with well-worn gloves that are more comfortable gripping a warm gun than reaching for a handshake. They're tasked with protecting your greatest asset - your trigger finger.`,
    wikiLinks: [`https://remnant.wiki/High_Noon_Armguards`],
  },
  {
    category: 'gloves',
    name: 'Knotted Gloves',
    saveFileSlug: 'armor_gloves_summoner',
    imagePath: '/gloves/knotted_gloves.png',
    id: '07mqqe',
    set: 'Knotted Set',
    armor: 15.5,
    weight: 6.9,
    bleedResistance: 1,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 1,
    toxinResistance: 2,
    description: `The deadwood claws fit you almost too snug, making it difficult to remember where bark ends and your own flesh begins.`,
    wikiLinks: [`https://remnant.wiki/Knotted_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Labyrinth Gauntlets',
    saveFileSlug: 'armor_gloves_archon',
    imagePath: '/gloves/labyrinth_gauntlets.png',
    id: 'bhw19m',
    set: 'Labyrinth Set',
    armor: 12.9,
    weight: 5.4,
    bleedResistance: 0,
    fireResistance: 3,
    shockResistance: 4,
    blightResistance: 0,
    toxinResistance: 0,
    description: `Craggy, uneven stone melds tightly to your hands and forearms, as if the skin of something that once was has at last found new purchase.`,
    wikiLinks: [`https://remnant.wiki/Labyrinth_Gauntlets`],
  },
  {
    category: 'gloves',
    name: 'Leto Mark 1 Gloves',
    saveFileSlug: 'armor_gloves_leto1',
    imagePath: '/gloves/leto_mark_i_gloves.png',
    id: '2lqg9t',
    set: 'Leto Mark 1 Set',
    armor: 22.6,
    weight: 11.9,
    bleedResistance: 2,
    fireResistance: 1,
    shockResistance: 2,
    blightResistance: 2,
    toxinResistance: 3,
    description: `Offering unparalleled protection against the unpredictable dangers of The Root, but the trade-off, is that they can be cumbersome and restrict dexterity, making it difficult to perform intricate tasks.`,
    wikiLinks: [`https://remnant.wiki/Leto_Mark_1_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Leto Mark II Gloves',
    saveFileSlug: 'armor_gloves_leto2',
    imagePath: '/gloves/leto_mark_ii_gloves.png',
    id: 'nfxk7i',
    set: 'Leto Mark II Set',
    armor: 21.8,
    weight: 11.1,
    bleedResistance: 2,
    fireResistance: 1,
    shockResistance: 2,
    blightResistance: 1,
    toxinResistance: 3,
    description: `These gauntlets are sturdy enough to hold up even against the Root: They're tough and intimidating while providing the bare-minimum level of dexterity for,a steady grip on your weapon of choice. Just don't plan on completing any tasks that require subtlety when wearing these.`,
    wikiLinks: [`https://remnant.wiki/Leto_Mark_II_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Nightstalker Gloves',
    saveFileSlug: 'armor_gloves_hunter',
    imagePath: '/gloves/nightstalker_gloves.png',
    id: 'xl7dm2',
    set: 'Nightstalker Set',
    armor: 10.9,
    weight: 4.5,
    bleedResistance: 2,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 7,
    toxinResistance: 0,
    description: `A single glove and arm wrap are all you need or want for arm protection. The only defense you can truly rely on is a loaded gun and a clear shot.`,
    wikiLinks: [`https://remnant.wiki/Nightstalker_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Radiant Bracers',
    saveFileSlug: 'armor_gloves_radiant',
    imagePath: '/gloves/radiant_bracers.png',
    id: 'rjm014',
    set: 'Radiant Set',
    armor: 17.2,
    weight: 7.9,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 2,
    blightResistance: 0,
    toxinResistance: 1,
    description: `The fingerless leather gloves provide exceptional dexterity to the wearer, while the vambraces are adorned with a blue gem that gives the wearer access to the volatile energy stored within.`,
    wikiLinks: [`https://remnant.wiki/Radiant_Bracers`],
  },
  {
    category: 'gloves',
    name: 'Realmwalker Gloves',
    saveFileSlug: 'armor_gloves_explorer',
    imagePath: '/gloves/realmwalker_gloves.png',
    id: '47ak51',
    set: 'Realmwalker Set',
    armor: 7.2,
    weight: 2.9,
    bleedResistance: 0,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 1,
    toxinResistance: 0,
    description: `Ford's gloves were designed for warmth and dexterity. The soldier who wore these was not swinging blades or forging metal. He was pulling triggers and throwing grenades`,
    wikiLinks: [`https://remnant.wiki/Realmwalker_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Red Widow Bracers',
    saveFileSlug: 'armor_gloves_redwidow',
    imagePath: '/gloves/red_widow_bracers.png',
    id: '7uqilq',
    set: 'Red Widow Set',
    armor: 13.1,
    weight: 5.6,
    bleedResistance: 2,
    fireResistance: 0,
    shockResistance: 0,
    blightResistance: 2,
    toxinResistance: 0,
    description: `These gloves are light, with openings for the fingers to allow the wearer maximum dexterity - a neccesary consideration for traditional Pan weaponry.`,
    wikiLinks: [`https://remnant.wiki/Red_Widow_Bracers`],
  },
  {
    category: 'gloves',
    name: 'Space Worker Gloves',
    saveFileSlug: 'armor_gloves_spaceworker',
    imagePath: '/gloves/space_worker_gloves.png',
    id: '6clcha',
    set: 'Space Worker Set',
    armor: 7,
    weight: 2.8,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 0,
    toxinResistance: 1,
    description: `Electromagnets are worked into the grip, activating automatically when the hand closes. Seems like a useful feature, so long as everything/you work with is metal.`,
    wikiLinks: [`https://remnant.wiki/Space_Worker_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Survivor Gloves',
    saveFileSlug: 'armor_gloves_survivor',
    imagePath: '/gloves/survivor_gloves.png',
    id: 'ws5jah',
    set: 'Survivor Set',
    armor: 9.8,
    weight: 4,
    bleedResistance: 1,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 1,
    toxinResistance: 1,
    description: `Made of durable leather and include a makeshift wrist guard consisting of a metal plate secured by leather straps, providing addition protection to the wearer's wrists without sacrificing dexterity.`,
    wikiLinks: [`https://remnant.wiki/Survivor_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Technician Gloves',
    saveFileSlug: 'armor_gloves_engineer',
    imagePath: '/gloves/technician_gloves.png',
    id: '11wear',
    set: 'Technician Set',
    armor: 16.6,
    weight: 7.5,
    bleedResistance: 0,
    fireResistance: 1,
    shockResistance: 2,
    blightResistance: 0,
    toxinResistance: 1,
    description: `A tingle runs across your palm within these gloves - like bugs skittering over your hand.`,
    wikiLinks: [`https://remnant.wiki/Technician_Gloves`],
  },
  {
    category: 'gloves',
    name: 'Trainer Bracer',
    saveFileSlug: 'armor_gloves_handler',
    imagePath: '/gloves/trainer_bracer.png',
    id: 'tgd095',
    set: 'Trainer Set',
    armor: 10.1,
    weight: 4.1,
    bleedResistance: 2,
    fireResistance: 0,
    shockResistance: 3,
    blightResistance: 1,
    toxinResistance: 1,
    description: `An arm guard that also functions as a bite sleeve for training on the subtle nuances of when and who to bite.`,
    wikiLinks: [`https://remnant.wiki/Trainer_Bracer`],
  },
  {
    category: 'gloves',
    name: 'Void Wraps',
    saveFileSlug: 'armor_gloves_void',
    imagePath: '/gloves/void_wraps.png',
    id: 'a527cd',
    set: 'Void Set',
    armor: 15.9,
    weight: 7.1,
    bleedResistance: 0,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 0,
    toxinResistance: 1,
    description: `Crafted from an enigmatic substance that resembles hardened bone in appearance. These gloves are a powerful tool in the hands of those who would wield the void, drawing energy from the emptiness between worlds to unleash devastating attacks. But with great power comes great cost, and those who dare to wear these gloves must be prepared to pay the price.`,
    wikiLinks: [`https://remnant.wiki/Void_Wraps`],
  },
  {
    category: 'gloves',
    name: "Zealot's Wraps",
    saveFileSlug: 'armor_gloves_ritualist',
    dlc: 'dlc1',
    imagePath: '/gloves/zealots_wraps.png',
    id: 'irt51q',
    set: "Zealot's Set",
    armor: 11.3,
    weight: 4.7,
    bleedResistance: 0,
    fireResistance: 1,
    shockResistance: 1,
    blightResistance: 0,
    toxinResistance: 1,
    description: `Long gloves fit like a vice around your arms, the pressure quickening your pulse and increasing your awareness. Your hands are well protected with the exception of a few exposed fingertips, intentionally left unguarded in case a given ritual requires quick access to fresh blood.`,
    wikiLinks: [`https://remnant.wiki/Zealot%27s_Wraps`],
  },
]
