import { RelicFragmentItem } from './types/RelicFragmentItem'

export const relicFragmentItems: RelicFragmentItem[] = [
  {
    category: 'relicfragment',
    name: 'Ammo Pickups',
    imagePath: '/relicfragment/ammo_pickups.png',
    id: 'j1aele',
    dlc: 'base',
    tags: ['Ammo Reserves'],
    description: 'Ammo Pickups, +30% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ammo Reserves',
    imagePath: '/relicfragment/ammo_reserves.png',
    id: '3aqiq5',
    dlc: 'base',
    tags: ['Ammo Reserves'],
    description: 'Ammo Reserves, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Armor Effectiveness',
    imagePath: '/relicfragment/armor_effectiveness.png',
    id: '7u1bma',
    dlc: 'base',
    tags: ['Damage Reduction'],
    description: 'Armor Effectiveness, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    armorPercent: 0.1,
  },
  {
    category: 'relicfragment',
    name: 'Blight Resistance',
    imagePath: '/relicfragment/blight_resistance.png',
    id: '8q8xe3',
    dlc: 'base',
    tags: ['Armor Increase', 'Damage Reduction'],
    description: 'Blight Resistance, +30% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Casting Speed',
    saveFileSlug: 'castspeed',
    imagePath: '/relicfragment/casting_speed.png',
    id: '51y6ih',
    dlc: 'base',
    tags: ['Mod Cast Speed', 'Skill Cast Speed'],
    description: 'Casting Speed, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Charge Melee Cost',
    imagePath: '/relicfragment/charge_melee_cost.png',
    id: 'fuikyq',
    dlc: 'base',
    tags: ['Charged Melee', 'Stamina'],
    description: 'Charge Melee Cost, -30% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Consumable Duration',
    imagePath: '/relicfragment/consumable_duration.png',
    id: 'xqklut',
    dlc: 'base',
    description: 'Consumable Duration, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Consumable Speed',
    imagePath: '/relicfragment/consumable_speed.png',
    id: 'omefk5',
    dlc: 'base',
    tags: ['Relic Use Speed'],
    description: 'Consumable Speed, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Damage Reduction',
    imagePath: '/relicfragment/damage_reduction.png',
    id: '1pddio',
    dlc: 'base',
    tags: ['Damage Reduction'],
    description: 'Damage Reduction, +5% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Elemental Damage',
    imagePath: '/relicfragment/elemental_damage.png',
    id: 'erp2mp',
    dlc: 'base',
    tags: ['Status Effect'],
    description: 'Elemental Damage, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Elemental Resistance',
    imagePath: '/relicfragment/elemental_resistance.png',
    id: 'j7k57r',
    dlc: 'base',
    tags: ['Damage Reduction'],
    description: 'Elemental Resistance, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    bleedResistance: 10,
    fireResistance: 10,
    shockResistance: 10,
    blightResistance: 10,
    toxinResistance: 10,
  },
  {
    category: 'relicfragment',
    name: 'Grey Health Rate',
    imagePath: '/relicfragment/grey_health_rate.png',
    id: 'aci99s',
    dlc: 'base',
    tags: ['Grey Health'],
    description: 'Grey Health Rate, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Healing Effectiveness',
    imagePath: '/relicfragment/healing_effectiveness.png',
    id: 'y52c32',
    dlc: 'base',
    tags: ['Healing Effectiveness'],
    description: 'Healing Effectiveness, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Health',
    imagePath: '/relicfragment/health.png',
    id: 'j87rzn',
    dlc: 'base',
    tags: ['Health'],
    description: 'Health, +15% (x1.15) at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    healthPercent: 0.15,
  },
  {
    category: 'relicfragment',
    name: 'Melee Attack Speed',
    imagePath: '/relicfragment/melee_attack_speed.png',
    id: 't8jgpe',
    dlc: 'base',
    tags: ['Melee Attack Speed'],
    description: 'Melee Attack Speed, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Melee Critical Chance',
    saveFileSlug: 'meleecritchance',
    imagePath: '/relicfragment/melee_critical_chance.png',
    id: 'm16fn9',
    dlc: 'base',
    tags: ['Critical Chance', 'Melee Critical Chance'],
    description: 'Melee Critical Chance, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Melee Critical Damage',
    saveFileSlug: 'meleecritdamage',
    imagePath: '/relicfragment/melee_critical_damage.png',
    id: '77ch7i',
    dlc: 'base',
    tags: ['Melee Critical Damage', 'Critical Damage'],
    description: 'Melee Critical Damage, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Melee Damage',
    imagePath: '/relicfragment/melee_damage.png',
    id: 'yu7d57',
    dlc: 'base',
    tags: ['Melee Damage'],
    description: 'Melee Damage, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Mod Cost',
    imagePath: '/relicfragment/mod_cost.png',
    id: 's8pkj3',
    dlc: 'base',
    tags: ['Mod Cost'],
    description: 'Mod Cost, -10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Mod Damage',
    imagePath: '/relicfragment/mod_damage.png',
    id: 'zkr2us',
    dlc: 'base',
    tags: ['Mod Damage'],
    description: 'Mod Damage, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Mod Duration',
    imagePath: '/relicfragment/mod_duration.png',
    id: 'c2t1p6',
    dlc: 'base',
    tags: ['Mod Duration'],
    description: 'Mod Duration, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ranged Critical Chance',
    saveFileSlug: 'rangedcritchance',
    imagePath: '/relicfragment/ranged_critical_chance.png',
    id: 'dp184t',
    dlc: 'base',
    tags: ['Critical Chance'],
    description: 'Ranged Critical Chance, +7.5% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ranged Critical Damage',
    saveFileSlug: 'rangedcritdamage',
    imagePath: '/relicfragment/ranged_critical_damage.png',
    id: 'w5jmys',
    dlc: 'base',
    tags: ['Critical Damage'],
    description: 'Ranged Critical Damage, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ranged Damage',
    imagePath: '/relicfragment/ranged_damage.png',
    id: 'wlnbc1',
    dlc: 'base',
    tags: ['Ranged Damage'],
    description: 'Ranged Damage, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ranged Fire Rate',
    imagePath: '/relicfragment/ranged_fire_rate.png',
    id: 'w8ruyt',
    dlc: 'base',
    tags: ['Fire Rate'],
    description: 'Ranged Fire Rate, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Recoil',
    imagePath: '/relicfragment/recoil.png',
    id: 'ygdexg',
    dlc: 'base',
    tags: ['Recoil'],
    description: 'Recoil, -30% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Revive Speed',
    imagePath: '/relicfragment/revive_speed.png',
    id: '0jam5w',
    dlc: 'base',
    description: 'Revive Speed, +25% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Shield Effectiveness',
    imagePath: '/relicfragment/shield_effectiveness.png',
    id: 'alp59n',
    dlc: 'base',
    description: 'Shield Effectiveness, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Skill Cooldown',
    imagePath: '/relicfragment/skill_cooldown.png',
    id: '2bqp66',
    dlc: 'base',
    tags: ['Reduce Skill Cooldown'],
    description: 'Skill Cooldown, -10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Skill Damage',
    imagePath: '/relicfragment/skill_damage.png',
    id: 'fuhykd',
    dlc: 'base',
    tags: ['Skill Damage'],
    description: 'Skill Damage, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Skill Duration',
    imagePath: '/relicfragment/skill_duration.png',
    id: '7c8uka',
    dlc: 'base',
    tags: ['Skill Duration'],
    description: 'Skill Duration, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Spread Recovery',
    imagePath: '/relicfragment/spread_recovery.png',
    id: 'yk8dng',
    dlc: 'base',
    tags: ['Spread'],
    description: 'Spread Recovery, +30% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Stagger Damage',
    imagePath: '/relicfragment/stagger_damage.png',
    id: '74x7jt',
    dlc: 'base',
    tags: ['Stagger'],
    description: 'Stagger Damage, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Stamina',
    imagePath: '/relicfragment/stamina.png',
    id: 'qqmdc0',
    dlc: 'base',
    tags: ['Stamina'],
    description: 'Stamina, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    staminaPercent: 0.15,
  },
  {
    category: 'relicfragment',
    name: 'Stamina Cost',
    imagePath: '/relicfragment/stamina_cost.png',
    id: 'lbtjq3',
    dlc: 'base',
    tags: ['Stamina'],
    description: 'Stamina Cost, -20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Stamina Recovery Delay',
    imagePath: '/relicfragment/stamina_recovery_delay.png',
    id: '0y36lm',
    dlc: 'base',
    tags: ['Stamina'],
    description: 'Stamina Recovery Delay, -30% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Weakspot Damage',
    imagePath: '/relicfragment/weakspot_damage.png',
    id: 'oszz4u',
    dlc: 'base',
    tags: ['Weakspot Damage'],
    description: 'Weakspot Damage, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Weapon Spread',
    imagePath: '/relicfragment/weapon_spread.png',
    id: 'oiiiu2',
    dlc: 'base',
    tags: ['Spread'],
    description: 'Weapon Spread, -15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Weapon Swap',
    imagePath: '/relicfragment/weapon_swap.png',
    id: 'h9e463',
    dlc: 'base',
    description: 'Weapon Swap, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
]
