import { RelicFragmentItem } from './types/RelicFragmentItem'

export const relicFragmentItems: RelicFragmentItem[] = [
  {
    category: 'relicfragment',
    name: 'Ammo Pickups',
    imagePath: '/relicfragment/ammo_pickups.png',
    id: 'j1aele',
    tags: ['Ammo Reserves'],
    description: `X% Ammo Pickups (Mythic: Maximum of +30%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ammo Reserves',
    imagePath: '/relicfragment/ammo_reserves.png',
    id: '3aqiq5',
    tags: ['Ammo Reserves'],
    description: `X% Ammo Reserves (Mythic: Maximum of +20%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Armor Effectiveness',
    imagePath: '/relicfragment/armor_effectiveness.png',
    id: '7u1bma',
    tags: ['Damage Reduction'],
    description: `+X% Armor (Mythic: Maximum of +10%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    armorPercent: 0.1,
  },
  {
    category: 'relicfragment',
    name: 'Blight Resistance',
    imagePath: '/relicfragment/blight_resistance.png',
    id: '8q8xe3',
    tags: ['Armor Increase', 'Damage Reduction'],
    description: `+X% Blight Resistance (Mythic: Maximum of +30%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Casting Speed',
    saveFileSlug: 'castspeed',
    imagePath: '/relicfragment/casting_speed.png',
    id: '51y6ih',
    tags: ['Mod Cast Speed', 'Skill Cast Speed'],
    description: `X% Mod & Skill Cast Speed (Mythic: Maximum of +20%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Charge Melee Cost',
    imagePath: '/relicfragment/charge_melee_cost.png',
    id: 'fuikyq',
    tags: ['Charged Melee', 'Stamina'],
    description: `-X% Melee Charge Attack Stamina Cost (Mythic: Maximum of -30%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Consumable Duration',
    imagePath: '/relicfragment/consumable_duration.png',
    id: 'xqklut',
    description: `X% Consumable Duration (Mythic: Maximum of +20%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Consumable Speed',
    imagePath: '/relicfragment/consumable_speed.png',
    id: 'omefk5',
    tags: ['Relic Use Speed'],
    description: `X% Consumable Use Speed (Mythic: Maximum of +15%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Damage Reduction',
    imagePath: '/relicfragment/damage_reduction.png',
    id: '1pddio',
    tags: ['Damage Reduction'],
    description: `X% Damage Reduction (Mythic: Maximum of +5%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Elemental Damage',
    imagePath: '/relicfragment/elemental_damage.png',
    id: 'erp2mp',
    tags: ['Status Effect'],
    description: `X% Elemental Damage (Mythic: Maximum of +10%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Elemental Resistance',
    imagePath: '/relicfragment/elemental_resistance.png',
    id: 'j7k57r',
    tags: ['Damage Reduction'],
    description: `X% Elemental Damage Resistance (Mythic: Maximum of +10%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    bleedResistance: 10,
    fireResistance: 10,
    shockResistance: 10,
    blightResistance: 10,
    toxinResistance: 10,
  },
  {
    category: 'relicfragment',
    name: 'Grey Health Rate',
    imagePath: '/relicfragment/grey_health_rate.png',
    id: 'aci99s',
    tags: ['Grey Health'],
    description: `+X% Health (Mythic: Maximum of +20%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Healing Effectiveness',
    imagePath: '/relicfragment/healing_effectiveness.png',
    id: 'y52c32',
    tags: ['Healing Effectivness'],
    description: `+X% Healing Effectiveness (Mythic: Maximum of +20%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Health',
    imagePath: '/relicfragment/health.png',
    id: 'j87rzn',
    tags: ['Health'],
    description: `+X% Health (Mythic: Maximum of +15%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    healthPercent: 0.15,
  },
  {
    category: 'relicfragment',
    name: 'Melee Attack Speed',
    imagePath: '/relicfragment/melee_attack_speed.png',
    id: 't8jgpe',
    tags: ['Melee Attack Speed'],
    description: `+X% Melee Attack Speed (Mythic: Maximum of +15%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Melee Critical Chance',
    saveFileSlug: 'meleecritchance',
    imagePath: '/relicfragment/melee_critical_chance.png',
    id: 'm16fn9',
    tags: ['Critical Chance', 'Melee Critical Chance'],
    description: `+X% Melee Crit Chance (Mythic: Maximum of +7.5%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Melee Critical Damage',
    saveFileSlug: 'meleecritdamage',
    imagePath: '/relicfragment/melee_critical_damage.png',
    id: '77ch7i',
    tags: ['Melee Critical Damage', 'Critical Damage'],
    description: `+X% Melee Crit Damage (Mythic: Maximum of +15%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Melee Damage',
    imagePath: '/relicfragment/melee_damage.png',
    id: 'yu7d57',
    tags: ['Melee Damage'],
    description: `+X% Melee Damage (Mythic: Maximum of +15%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Mod Cost',
    imagePath: '/relicfragment/mod_cost.png',
    id: 's8pkj3',
    tags: ['Mod Cost'],
    description: `-X% Mod Cost (Mythic: Maximum of -10%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Mod Damage',
    imagePath: '/relicfragment/mod_damage.png',
    id: 'zkr2us',
    tags: ['Mod Damage'],
    description: `X% Mod Damage (Mythic: Maximum of +10%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Mod Duration',
    imagePath: '/relicfragment/mod_duration.png',
    id: 'c2t1p6',
    tags: ['Mod Duration'],
    description: `+X% Mod Duration (Mythic: Maximum of +15%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ranged Critical Chance',
    saveFileSlug: 'rangedcritchance',
    imagePath: '/relicfragment/ranged_critical_chance.png',
    id: 'dp184t',
    tags: ['Critical Chance'],
    description: `+X% Ranged Crit Chance (Mythic: Maximum of +10%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ranged Critical Damage',
    saveFileSlug: 'rangedcritdamage',
    imagePath: '/relicfragment/ranged_critical_damage.png',
    id: 'w5jmys',
    tags: ['Critical Damage'],
    description: `+X% Ranged Crit Damage (Mythic: Maximum of +15%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ranged Damage',
    imagePath: '/relicfragment/ranged_damage.png',
    id: 'wlnbc1',
    tags: ['Ranged Damage'],
    description: `+X% Ranged Damage (Mythic: Maximum of +10%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ranged Fire Rate',
    imagePath: '/relicfragment/ranged_fire_rate.png',
    id: 'w8ruyt',
    tags: ['Fire Rate'],
    description: `+X% Fire Rate (Mythic: Maximum of +10%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Recoil',
    imagePath: '/relicfragment/recoil.png',
    id: 'ygdexg',
    tags: ['Recoil'],
    description: `-X% Recoil (Mythic: Maximum of -30%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Revive Speed',
    imagePath: '/relicfragment/revive_speed.png',
    id: '0jam5w',
    description: `+X% Revive Speed (Mythic: Maximum of +25%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Shield Effectiveness',
    imagePath: '/relicfragment/shield_effectiveness.png',
    id: 'alp59n',
    description: `+X% SHIELD Amount (Mythic: Maximum of +20%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Skill Cooldown',
    imagePath: '/relicfragment/skill_cooldown.png',
    id: '2bqp66',
    tags: ['Reduce Skill Cooldown'],
    description: `+X% Skill Cooldown (Mythic: Maximum of -10%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Skill Damage',
    imagePath: '/relicfragment/skill_damage.png',
    id: 'fuhykd',
    tags: ['Skill Damage'],
    description: `X% Skill Damage (Mythic: Maximum of +10%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Skill Duration',
    imagePath: '/relicfragment/skill_duration.png',
    id: '7c8uka',
    tags: ['Skill Duration'],
    description: `+X% Skill Duration (Mythic: Maximum of +10%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Spread Recovery',
    imagePath: '/relicfragment/spread_recovery.png',
    id: 'yk8dng',
    tags: ['Spread'],
    description: `X% Reticle Spread Recovery (Mythic: Maximum of +30%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Stagger Damage',
    imagePath: '/relicfragment/stagger_damage.png',
    id: '74x7jt',
    tags: ['Stagger'],
    description: `+X% Stagger Damage (Mythic: Maximum of +20%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Stamina',
    imagePath: '/relicfragment/stamina.png',
    id: 'qqmdc0',
    tags: ['Stamina'],
    description: `+X% Stamina (Mythic: Maximum of +15%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    staminaPercent: 0.15,
  },
  {
    category: 'relicfragment',
    name: 'Stamina Cost',
    imagePath: '/relicfragment/stamina_cost.png',
    id: 'lbtjq3',
    tags: ['Stamina'],
    description: `-X% Reduced Stamina Cost (Mythic: Maximum of -20%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Stamina Recovery Delay',
    imagePath: '/relicfragment/stamina_recovery_delay.png',
    id: '0y36lm',
    tags: ['Stamina'],
    description: `-X% Stamina Recovery Delay (Mythic: Maximum of -30%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Weakspot Damage',
    imagePath: '/relicfragment/weakspot_damage.png',
    id: 'oszz4u',
    tags: ['Weakspot Damage'],
    description: `+X% Weakspot Damage (Mythic: Maximum of +15%).`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Weapon Spread',
    imagePath: '/relicfragment/weapon_spread.png',
    id: 'oiiiu2',
    tags: ['Spread'],
    description: `-X% Weapon Spread (Mythic: Maximum of -15%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Weapon Swap',
    imagePath: '/relicfragment/weapon_swap.png',
    id: 'h9e463',
    description: `+X% Weapon Swap Speed (Mythic: Maximum of +20%)`,
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
]
