import { RingItem } from './types/RingItem'

export const ringItems: RingItem[] = [
  {
    category: 'ring',
    name: "A'Taerii Booster",
    imagePath: '/ring/ataerii_booster1.png',
    id: '27gn7b',
    dlc: 'base',
    tags: ['All Damage', 'Critical Chance'],
    description: `Heavy Weapons gain 10% additional damage and gain 10% additional Critical Chance in both Carry and Turret Mode.`,
    wikiLinks: [`https://remnant.wiki/A'Taerii_Booster`],
  },
  {
    category: 'ring',
    name: 'Acid Stone',
    imagePath: '/ring/acid_stone.png',
    id: 'q3qca2',
    dlc: 'base',
    description: `Increases ACID damage by 12% and ACID Resistance by 15%.`,
    wikiLinks: [`https://remnant.wiki/Acid_Stone`],
    toxinResistance: 15,
  },
  {
    category: 'ring',
    name: 'Ahanae Crystal',
    saveFileSlug: 'ring_panmagesigil',
    imagePath: '/ring/ahanae_crystal.png',
    id: 'azy0pj',
    dlc: 'base',
    tags: ['All Damage', 'Status Effect', 'Hardcore Reward'],
    description:
      'Deal 5% additional damage for each Status Effect the target is suffering from.',
    wikiLinks: [`https://remnant.wiki/Ahanae_Crystal`],
  },
  {
    category: 'ring',
    name: 'Akari War Band',
    imagePath: '/ring/akari_war_band.png',
    id: '9siz0d',
    dlc: 'base',
    tags: ['Perfect Dodge', 'Critical Chance'],
    description: `Perfect Dodges increase Critical Chance by 10% and Critical Damage by 10% for 15s.`,
    wikiLinks: [`https://remnant.wiki/Akari_War_Band`],
  },
  {
    category: 'ring',
    name: 'Alchemy Stone',
    imagePath: '/ring/alchemy_stone.png',
    id: 'dgh4g8',
    dlc: 'base',
    tags: ['Lifesteal', 'Status Effect'],
    description: `Increases base Lifesteal by 6% while suffering from a negative STATUS or BLIGHT Effect.`,
    wikiLinks: [`https://remnant.wiki/Alchemy_Stone`],
  },
  {
    category: 'ring',
    name: 'Alumni Ring',
    imagePath: '/ring/alumni_ring.png',
    id: 'll1vsx',
    dlc: 'base',
    tags: ['Elemental Damage'],
    description: 'Increases all Elemental damage dealt by 10%.',
    wikiLinks: [`https://remnant.wiki/Alumni_Ring`],
  },
  {
    category: 'ring',
    name: 'Amber Moonstone',
    imagePath: '/ring/amber_moonstone.png',
    id: 'pqez3b',
    dlc: 'base',
    tags: ['Damage Reduction', 'Status Effect'],
    description:
      'When Health drops below 35%, all incoming damage is reduced by 25% and wearer becomes immune to Temporary Status Effects.',
    wikiLinks: [`https://remnant.wiki/Amber_Moonstone`],
  },
  {
    category: 'ring',
    name: "Anastasija's Inspiration",
    imagePath: '/ring/anastasijas_inspiration.png',
    id: '7fmi47',
    dlc: 'base',
    tags: ['Heal'],
    description: `When receiving healing effects, gain HASTE for 10s.`,
    wikiLinks: [`https://remnant.wiki/Anastasija's_Inspiration`],
  },
  {
    category: 'ring',
    name: "Archer's Crest",
    imagePath: '/ring/archers_crest.png',
    id: '6bqghl',
    dlc: 'base',
    tags: ['Projectile Speed', 'Charged Shot'],
    description: `Increases Projectile Speed by 20% and Decreases Weapon Charge Time by 25%.`,
    wikiLinks: [`https://remnant.wiki/Archer's_Crest`],
  },
  {
    category: 'ring',
    name: "Assassin's Seal",
    imagePath: '/ring/assassins_seal.png',
    id: '8kyyav',
    dlc: 'base',
    tags: ['All Damage'],
    description: `Reduces enemy Awareness Range by 25%. Increases all damage dealt to enemies not targeting wearer by 10%.`,
    wikiLinks: [`https://remnant.wiki/Assassin's_Seal`],
  },
  {
    category: 'ring',
    name: 'Atonement Fold',
    imagePath: '/ring/atonement_fold.png',
    dlc: 'dlc1',
    id: 'ez01nk',
    tags: ['Critical Chance', 'Grey Health'], // The damage it causes is grey health
    description:
      'Self-inflicts BLEEDING Status upon the wearer, causing 1.1 BLEED damage per second. Increases Critical Chance by 5%.',
    wikiLinks: [`https://remnant.wiki/Atonement_Fold`],
  },
  {
    category: 'ring',
    name: 'Band Band',
    imagePath: '/ring/band_band.png',
    id: 'mm6dj8',
    tags: ['Movement Speed', 'Health'],
    description: `Increases Speed of Revive and being Revived by 35%. Increases Downed Health and Downed Movement Speed by 100%.`,
    wikiLinks: [`https://remnant.wiki/Band_Band`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Band of Accord',
    imagePath: '/ring/band_of_accord.png',
    id: 'id6lly',
    tags: ['Ammo Reserves'],
    description: `Ammo acquired on pickup is increased by 50% per ally also wearing this ring and is shared with other allies.`,
    wikiLinks: [`https://remnant.wiki/Band_of_Accord`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Band of the Fanatic',
    imagePath: '/ring/band_of_the_fanatic.png',
    dlc: 'dlc1',
    id: 'gv12gw',
    tags: ['Status Effect', 'Status Duration'],
    description:
      'Increases Status Effect Damage by 30% and reduces Status Effect Duration by 50%.',
    wikiLinks: [`https://remnant.wiki/Band_of_the_Fanatic`],
  },
  {
    category: 'ring',
    name: "Berserker's Crest",
    imagePath: '/ring/berserkers_crest.png',
    id: 'pi2zf8',
    tags: ['Melee Charge Speed', 'Charged Melee', 'Stamina'],
    description:
      'Increases Melee Charge Speed by 10% and reduces Melee Stamina Cost by 30%.',
    wikiLinks: [`https://remnant.wiki/Berserker's_Crest`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Bisected Ring',
    imagePath: '/ring/bisected_ring.png',
    id: '7usn4n',
    tags: ['Stamina'],
    description:
      'Gain Infinite Stamina. All damage received is increased by 15%',
    wikiLinks: [`https://remnant.wiki/Bisected_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Bitter Memento',
    imagePath: '/ring/bitter_memento.png',
    dlc: 'dlc1',
    id: 'eozlwb',
    tags: ['Grey Health'],
    description:
      "Forces 1% of wearer's Max Health to remain as Grey Health. Activating a skill converts 33.5% Max Health into Grey Health. Conversion cannot kill wearer.",
    wikiLinks: [`https://remnant.wiki/Bitter_Memento`],
  },
  {
    category: 'ring',
    name: 'Black Cat Band',
    imagePath: '/ring/black_cat_band.png',
    id: 'ac27lx',
    tags: ['Movement Speed'],
    description: `When taking fatal damage, instead of dying, the wearer's Health will drop to 1, and Movement Speed will increase by 25% for 10s. 2m cooldown.`,
    wikiLinks: [`https://remnant.wiki/Black_Cat_Band`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Black Pawn Stamp',
    imagePath: '/ring/black_pawn_stamp.png',
    id: '7kbu25',
    tags: ['Reduce Skill Cooldown'],
    description: `Reduces Cooldowns of Skills by 10%.`,
    wikiLinks: [`https://remnant.wiki/Black_Pawn_Stamp`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Black Spinel',
    imagePath: '/ring/black_spinel.png',
    id: 'sq8ZUN',
    dlc: 'dlc2',
    tags: ['Status Effect', 'Heal'],
    description: `Applying a Negative Status Effect grants 2% Max Health per second for 3s. Applying or refreshing a Negative Status Effect while buff is active will increase the duration by 1.5s. Max 15s.`,
    wikiLinks: ['https://remnant.wiki/Black_Spinel'],
  },
  {
    category: 'ring',
    name: 'Blackout Ring',
    imagePath: '/ring/blackout_ring.png',
    id: '6pzq37',
    tags: ['Reload Speed'],
    description:
      'Increases Reload Speed by 3% for every 20% of Magazine missing.',
    wikiLinks: [`https://remnant.wiki/Blackout_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Blasting Cap Ring',
    imagePath: '/ring/blasting_cap_ring.png',
    id: 'ep14lr',
    description: 'Increases Explosive damage by 15%.',
    externalTokens: [`Explosive Damage`],
    wikiLinks: [`https://remnant.wiki/Blasting_Cap_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Blessed Ring',
    imagePath: '/ring/blessed_ring.png',
    id: 'empffm',
    tags: ['Damage Reduction'],
    description: `After receiving a benefit from a Relic, gain 2 Stacks of BULWARK for 30s.`,
    wikiLinks: [`https://remnant.wiki/Blessed_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: `Bloodless King's Vow`,
    imagePath: '/ring/bloodless_kings_vow.png',
    id: 'WHgN93',
    dlc: 'dlc2',
    tags: ['Ranged Damage', 'Lifesteal'],
    description: `Gain 4% of base Ranged Damage dealt as Lifesteal.`,
    wikiLinks: [`https://remnant.wiki/Bloodless_King's_Vow`],
  },
  {
    category: 'ring',
    name: 'Blood Jewel',
    imagePath: '/ring/blood_jewel.png',
    id: 'rw8rn0',
    tags: ['Charged Melee'],
    description:
      'Charged Melee Attacks apply BLEEDING, dealing 520 BLEED damage over 20s.',
    wikiLinks: [`https://remnant.wiki/Blood_Jewel`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Blood Tinged Ring',
    imagePath: '/ring/blood_tinged_ring.png',
    id: 'pj7i9a',
    tags: ['Heal'],
    description: `Gain 2 Health Regeneration per second when within 25m of a BLEEDING entity.`,
    wikiLinks: [`https://remnant.wiki/Blood_Tinged_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Booster Ring',
    imagePath: '/ring/booster_ring.png',
    id: 'sdkwq2',
    description: `Increases all Status Resistances by 25.`,
    wikiLinks: [`https://remnant.wiki/Booster_Ring`],
    bleedResistance: 25,
    fireResistance: 25,
    shockResistance: 25,
    toxinResistance: 25,
    blightResistance: 25,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Braided Thorns',
    imagePath: '/ring/braided_thorns.png',
    id: 'zdkh54',
    tags: ['Critical Chance'],
    description: 'Increases Critical Chance by 10%.',
    wikiLinks: [`https://remnant.wiki/Braided_Thorns`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Brawler's Pride",
    imagePath: '/ring/brawlers_pride.png',
    id: '17ckov',
    tags: ['Melee Attack Speed'],
    description:
      'Increases Melee Attack Speed by 15% and Melee Critical Chance by 5%.',
    wikiLinks: [`https://remnant.wiki/Brawler's_Pride`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: `Bridge Warden's Crest`,
    imagePath: '/ring/bridge_wardens_crest.png',
    dlc: 'dlc1',
    id: 't7sqw7',
    tags: ['Perfect Dodge', 'Damage Reduction', 'Melee Damage'],
    description: `Perfect Dodge increases Melee Damage by 20% for 10s. Perfect Evade Flop also gains 10% Damage Reduction for the duration.`,
    wikiLinks: [`https://remnant.wiki/Bridge_Warden's_Crest`],
  },
  {
    category: 'ring',
    name: 'Burden of the Audacious',
    imagePath: '/ring/burden_of_the_audacious.png',
    id: 'k45qer',
    tags: ['Heal', 'Perfect Dodge'],
    description: `Decreases all healing by 50%. Perfect Dodges heal for 25% of Max Health.`,
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Audacious`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Departed',
    imagePath: '/ring/burden_of_the_departed.png',
    dlc: 'dlc1',
    id: 'syutk7',
    tags: ['All Damage'],
    description:
      'Reduces Total Relic Charges by 33%. Increases All Damage dealt by 10%.',
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Departed`],
  },
  {
    category: 'ring',
    name: 'Burden of the Destroyer',
    imagePath: '/ring/burden_of_the_destroyer.png',
    id: 'dgb0s9',
    tags: ['All Damage', 'Range'],
    description:
      'Decreases Range of all Firearms by 35%. Increases all damage dealt by 15%.',
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Destroyer`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Divine',
    imagePath: '/ring/burden_of_the_divine.png',
    id: 'tvfpo7',
    description:
      'All damage dealt by the wearer is reduced by 15%. 30% of self healing applies to allies.',
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Divine`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Follower',
    imagePath: '/ring/burden_of_the_follower.png',
    id: 'b76cdv',
    tags: ['Fire Rate', 'Mod Power'],
    description:
      'Reduces Fire Rate by 15%. Increases Mod Power Generation by 30%.',
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Follower`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Gambler',
    imagePath: '/ring/burden_of_the_gambler.png',
    id: 'ctv31c',
    tags: ['Weakspot Damage', 'Critical Chance'],
    description: `Disables Weakspots. Increases Critical Chance by 10% and Critical Damage by 15%.`,
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Gambler`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Mariner',
    imagePath: '/ring/burden_of_the_mariner.png',
    id: 'k89bxv',
    tags: ['Mod Power'],
    description: `Increases Skill Cooldowns by 15%. Generate 15% additional Mod Power for each Skill on Cooldown.`,
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Mariner`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Mason',
    imagePath: '/ring/burden_of_the_mason.png',
    id: 'k89bxz',
    dlc: 'dlc2',
    tags: ['Encumbrance', 'Melee Damage', 'Damage Reduction'],
    description: `Impairs Dodges by 1 Weight Class. Increases Melee damage by 35% of the wearer's total Damage Reduction.`,
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Mason`],
  },
  {
    category: 'ring',
    name: 'Burden of the Mesmer',
    imagePath: '/ring/burden_of_the_mesmer1.png',
    id: 'fGFm6B',
    dlc: 'dlc2',
    tags: ['Health', 'All Damage', 'Damage Reduction'],
    description:
      "Reduces Max Health by 20%. Increases All Damage by 1% for every 5% of the wearer's total Damage Reduction.",
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Mesmer`],
  },
  {
    category: 'ring',
    name: 'Burden of the Rebel',
    imagePath: '/ring/burden_of_the_rebel.png',
    id: 'z169p0',
    tags: ['Reduce Skill Cooldown', 'Relic Use Speed'],
    description:
      'Reduces Relic Use Speed by 25%. Reduces Skill Cooldowns by 15%.',
    wikiLinks: [`https://remnant.wiki/Burden_Of_The_Rebel`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Sciolist',
    imagePath: '/ring/burden_of_the_sciolist.png',
    dlc: 'dlc1',
    id: '7xb5zr',
    tags: ['Mod Damage', 'Skill Damage', 'Ammo Reserves'],
    description:
      'Reduces Ammo Reserves by 20%. Increases Mod and Skill Damage by 15%.',
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Sciolist`],
  },
  {
    category: 'ring',
    name: 'Burden of the Stargazer',
    imagePath: '/ring/burden_of_the_stargazer.png',
    id: 'kj85yo',
    tags: ['Reduce Skill Cooldown'],
    description: `Reduces Skill Cooldowns by 15%. Activating a Skill costs 15% Health.`,
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Stargazer`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Warlock',
    imagePath: '/ring/burden_of_the_warlock.png',
    id: 'mdu1f6',
    tags: ['Mod Power', 'Grey Health'],
    description:
      'Reduces Mod Power Requirement by 15%. Activating a Mod costs 15% Health as Grey Health. Conversion cannot kill wearer.',
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Warlock`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Captain's Insignia",
    imagePath: '/ring/captains_insignia.png',
    id: 'cu0w65',
    tags: ['Relic Use Speed'],
    description: `Increases Revive Speed and Relic Consume Speed by 25% per downed or dead ally. Max 2 stacks.`,
    wikiLinks: [`https://remnant.wiki/Captain's_Insignia`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Cataloger's Jewel",
    imagePath: '/ring/catalogers_jewel.png',
    id: 'e6da79',
    tags: ['Mod Power'],
    description: `Automatically generates 10 Mod Power per second.`,
    wikiLinks: [`https://remnant.wiki/Cataloger's_Jewel`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Celerity Stone',
    imagePath: '/ring/celerity_stone.png',
    id: 'kt5ag1',
    tags: ['Relic Use Speed'],
    description: `Increases Consumable and Relic Use Speed by 25%.`,
    wikiLinks: [`https://remnant.wiki/Celerity_Stone`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Closed Loop',
    imagePath: '/ring/closed_loop.png',
    dlc: 'dlc2',
    id: 'Sm4o3R',
    tags: ['Charged Shot'],
    description: `Gain 5% of Max Health as SHIELD for 10s after a Charged Shot. Accumulation resets after 10s of inaction. Max 25% SHIELD.`,
    wikiLinks: [`https://remnant.wiki/Closed_Loop`],
  },
  {
    category: 'ring',
    name: 'Compulsion Loop',
    imagePath: '/ring/compulsion_loop.png',
    id: '6p71zo',
    tags: ['Fire Rate', 'Melee Attack Speed'],
    description: `After killing an enemy, gain 5% Fire Rate and Melee Attack Speed for 10s. Stacks 3x.`,
    wikiLinks: [`https://remnant.wiki/Compulsion_Loop`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Conjurer's Circle",
    imagePath: '/ring/conjurers_circle.png',
    id: 'k89bxd',
    dlc: 'dlc2',
    tags: ['Stagger', 'Grey Health', 'Summon'],
    description:
      "When the wearer's Summon enters the battlefield, conjure a 5m Summoning Circle. Allies in the Summoning Circle have their Stagger Level reduced by 1 and regenerates 5 Grey Health per second. Lasts 10s.\n" +
      '\n' +
      'Can only happen once every 10s after expiring.',
    externalTokens: [`Amplitude`],
    wikiLinks: [`https://remnant.wiki/Conjurer's_Circle`],
  },
  {
    category: 'ring',
    name: 'Conservation Seal',
    imagePath: '/ring/conservation_seal.png',
    id: 'fa7066',
    tags: ['Healing Effectiveness'],
    description:
      'For every 10% of Health missing [Max 50%], gain 10% chance to not consume Relic and 5% increased Relic Efficacy on next use.',
    wikiLinks: [`https://remnant.wiki/Conservation_Seal`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Constant Variable Ring',
    imagePath: '/ring/constant_variable_ring.png',
    id: 'dyr6ej',
    tags: ['Ranged Damage', 'Heat Generation'],
    description: `Increases Ranged damage up to 20% based on current Weapon's Overheat value.`,
    wikiLinks: [`https://remnant.wiki/Constant_Variable_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Crimson Dreamstone',
    imagePath: '/ring/crimson_dreamstone.png',
    dlc: 'dlc1',
    id: 's916uj',
    tags: ['Critical Hit', 'Skill Damage'],
    description:
      'Critical Hits increase Skill Damage by 2% for 5s. Max 10 stacks.',
    wikiLinks: [`https://remnant.wiki/Crimson_Dreamstone`],
  },
  {
    category: 'ring',
    name: 'Dark Sea Armada Crest',
    imagePath: '/ring/dark_sea_armada_crest.png',
    id: 'Zj9qF5',
    dlc: 'dlc2',
    tags: ['Elemental Damage'],
    description: `On Relic Use, increases All Elemental Damage dealt by 15% for 15s.`,
    wikiLinks: [`https://remnant.wiki/Dark_Sea_Armada_Crest`],
  },
  {
    category: 'ring',
    name: "Dead King's Memento",
    imagePath: '/ring/dead_kings_memento.png',
    id: 'vbxfcp',
    tags: ['Health'],
    description: `Increases Health by 15.`,
    wikiLinks: [`https://remnant.wiki/Dead_King's_Memento`],
    health: 15,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Deceiver's Band",
    imagePath: '/ring/deceivers_band.png',
    id: '1dmpt8',
    tags: ['Movement Speed'],
    description:
      'After performing a Slide, gain 15% Evade Speed and 10% Movement Speed for 12s.',
    wikiLinks: [`https://remnant.wiki/Deceiver's_Band`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Deep Pocket Ring',
    imagePath: '/ring/deep_pocket_ring.png',
    id: '9bnfhm',
    tags: ['Ammo Reserves'],
    description: `Increases Ammo Reserves by 35%.`,
    wikiLinks: [`https://remnant.wiki/Deep_Pocket_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Defensive Action Loop',
    imagePath: '/ring/defensive_action_loop.png',
    id: '3krgp4',
    tags: ['Damage Reduction'],
    description: `While reloading, and for 3s after reload completes, incoming damage is reduced by 10%.`,
    wikiLinks: [`https://remnant.wiki/Defensive_Action_Loop`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dense Silicon Ring',
    imagePath: '/ring/dense_silicon_ring.png',
    id: 'b91hx9',
    tags: ['Mod Power'],
    description: `Gain 200% of Health Regenerated as Mod Power.`,
    wikiLinks: [`https://remnant.wiki/Dense_Silicon_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Devoured Loop',
    imagePath: '/ring/devoured_loop.png',
    saveFileSlug: 'devouringloop',
    id: 'l8a2e1',
    tags: ['Critical Hit', 'Reduce Skill Cooldown'],
    description: `Critical Hits have a 1% chance to reset Skill Cooldowns. Can only occur once every 10s. Increases all incoming damage by 10%`,
    wikiLinks: [`https://remnant.wiki/Devoured_Loop`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Digested Hog Lure',
    imagePath: '/ring/digested_hog_lure.png',
    dlc: 'dlc1',
    id: 'v4yzc6',
    tags: ['Mod Damage'],
    description: 'Reloading increases Mod Damage by 15% for 7s.',
    wikiLinks: [`https://remnant.wiki/Digested_Hog_Lure`],
  },
  {
    category: 'ring',
    name: 'Drakestone Pearl',
    imagePath: '/ring/drakestone_pearl.png',
    id: 'r1dqm9',
    tags: ['Stamina', 'Melee Damage'],
    description: `Enables Stamina Regeneration during Melee Attacks at 20% of the normal rate.`,
    wikiLinks: [`https://remnant.wiki/Drakestone_Pearl`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dran Memento',
    imagePath: '/ring/dran_memento.png',
    id: 'fojjag',
    tags: ['Stamina', 'Encumbrance'],
    description: `Increases Max Stamina by 20 and reduces Encumbrance by 5.`,
    wikiLinks: [`https://remnant.wiki/Dran_Memento`],
    weight: -5,
    stamina: 20,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dran Scavenger Ring',
    saveFileSlug: 'dranscavengersigil',
    imagePath: '/ring/dran_scavenger_ring.png',
    id: '5pwtei',
    tags: ['Heal', 'All Damage', 'Hardcore Reward'],
    description:
      'Collecting Scrap, Iron, and Ammo Pickups regenerates 50% of Max Health and increases all damage dealt by 8% for 30s.',
    wikiLinks: [`https://remnant.wiki/Dran_Scavenger_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dread Font',
    imagePath: '/ring/dread_font.png',
    id: '5k6zdd',
    tags: ['Grey Health', 'Heal'],
    description: `Increases Grey Health Regeneration rate by 2 per second.`,
    wikiLinks: [`https://remnant.wiki/Dread_Font`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dried Clay Ring',
    imagePath: '/ring/dried_clay_ring.png',
    id: 'ez6z8b',
    tags: ['Damage Reduction', 'All Damage'],
    description:
      'Grants 1 stack of BULWARK. Increases All Damage by 50% of the Total Damage Reduction granted by BULWARK stacks.',
    wikiLinks: [`https://remnant.wiki/Dried_Clay_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Drzyr Sniper Sigil',
    imagePath: '/ring/drzyr_sniper_sigil.png',
    id: 'gtli7e',
    tags: ['Hardcore Reward'],
    description:
      'Increases the minimum damage at Max Falloff Range from 20% to 40%.',
    wikiLinks: [`https://remnant.wiki/Drzyr_Sniper_Sigil`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dull Steel Ring',
    saveFileSlug: 'brightsteelring',
    imagePath: '/ring/dull_steel_ring1.png',
    id: 's76ytc',
    tags: ['Encumbrance'],
    description: 'Improves Dodges by 1 Weight Class.',
    wikiLinks: [`https://remnant.wiki/Dull_Steel_Ring`],
    weightThreshold: 25,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dying Ember',
    imagePath: '/ring/dying_ember.png',
    id: 'mv9b18',
    tags: ['Melee Damage', 'Lifesteal'],
    description: `Gain 6% of base Melee damage dealt as Lifesteal.`,
    wikiLinks: [`https://remnant.wiki/Dying_Ember`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Elevated Ring',
    imagePath: '/ring/elevated_ring.png',
    dlc: 'dlc1',
    id: '5dipaq',
    tags: ['Encumbrance'],
    description:
      'Increases Dodge Weight Threshold by 10. Reduces Encumbrance by 10.',
    wikiLinks: [`https://remnant.wiki/Elevated_Ring`],
    weight: -10,
    weightThreshold: 10,
  },
  {
    category: 'ring',
    name: "Embrace of Sha'Hala",
    saveFileSlug: 'ring_downgradedring',
    imagePath: '/ring/embrace_of_shahala.png',
    id: 'h2g5z3',
    tags: ['Damage Reduction', 'Status Effect'],
    description:
      'Wearer gains 7.5% incoming Damage Reduction when suffering from a unique Negative Status Effect or Blight. Max 2 stacks.',
    wikiLinks: [`https://remnant.wiki/Embrace_of_Sha'Hala`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Encrypted Ring',
    saveFileSlug: 'ring_encryptedloop',
    imagePath: '/ring/encrypted_ring.png',
    id: 'g1u6gi',
    tags: ['Heal'],
    description:
      'Using a Mod regenerates 20% of Max Health over 10s. Can stack up to 30s.',
    wikiLinks: [`https://remnant.wiki/Encrypted_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Endaira's Endless Loop",
    imagePath: '/ring/endairas_endless_loop.png',
    id: 'bx0ulq',
    tags: ['Heal'],
    description: `After Sprinting for 1s, the wearer gains 2 Health Regeneration per second until they stop Sprinting.`,
    wikiLinks: [`https://remnant.wiki/Endaira's_Endless_Loop`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Excess Coil',
    imagePath: '/ring/excess_coil.png',
    id: 'l5gfd1',
    description: `Activating a Skill grants a SHIELD for 25% of Max Health. Cannot stack with itself. Lasts 15s.`,
    wikiLinks: [`https://remnant.wiki/Excess_Coil`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Fae Bruiser Ring',
    imagePath: '/ring/fae_bruiser_ring.png',
    id: 't2ct6r',
    tags: ['Melee Damage', 'Damage Reduction'],
    description:
      'Dealing Melee damage grants 2 Stacks of BULWARK for 15s. Does not stack with itself.',
    wikiLinks: [`https://remnant.wiki/Fae_Bruiser_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Fae Hunter Ring',
    imagePath: '/ring/fae_hunter_ring.png',
    id: 'i4wkw2',
    tags: ['Range'],
    description: `Increases Range of Firearms by 35%.`,
    wikiLinks: [`https://remnant.wiki/Fae_Hunter_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Fae Protector Signet',
    imagePath: '/ring/fae_protector_signet.png',
    id: 'f2j9er',
    tags: ['Health', 'Stamina', 'Encumbrance'],
    description: `Increases Max Health and Stamina by 10 and Reduces Encumbrance by 5.`,
    wikiLinks: [`https://remnant.wiki/Fae_Protector_Signet`],
    health: 10,
    stamina: 10,
    weight: -5,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Fae Shaman Ring',
    imagePath: '/ring/fae_shaman_ring.png',
    id: '7okl48',
    tags: ['Heal', 'Relic Use Speed'],
    description:
      'Increases Health Regeneration by 0.35 and Relic Use Speed by 25%.',
    wikiLinks: [`https://remnant.wiki/Fae_Shaman_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Fae Warrior Ring',
    imagePath: '/ring/fae_warrior_ring.png',
    id: '6ypnyx',
    tags: ['Melee Damage'],
    description: `Increases Melee Damage by 15%.`,
    wikiLinks: [`https://remnant.wiki/Fae_Warrior_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Faelin's Sigil",
    imagePath: '/ring/faelins_sigil.png',
    id: 'drjm15',
    tags: ['Melee Damage', 'Mod Power'],
    description: `Melee Damage generates 15% additional Mod Power.`,
    wikiLinks: [`https://remnant.wiki/Faelin's_Sigil`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Faerin's Sigil",
    imagePath: '/ring/faerins_sigil.png',
    id: '02wal9',
    tags: ['Critical Hit', 'Weakspot Damage', 'Mod Power'],
    description:
      'Critical and Weakspot Hits generate 12.5% additional Mod Power.',
    wikiLinks: [`https://remnant.wiki/Faerin's_Sigil`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Feastmaster's Signet",
    imagePath: '/ring/feastmasters_signet.png',
    id: '5q53ke',
    tags: ['Concoction'],
    description: `Increases active Concoction Limit by 1.`,
    wikiLinks: [`https://remnant.wiki/Feastmaster's_Signet`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Feathery Binding',
    imagePath: '/ring/feathery_binding.png',
    id: 'zXq2H7',
    dlc: 'dlc2',
    tags: ['Charged Shot', 'Projectile Speed'],
    description: `Increases Projectile Speed by 15% and Decreases Weapon Charge Time by 10%. Bonus is doubled when HASTE is active.`,
    wikiLinks: [`https://remnant.wiki/Feathery_Binding`],
  },
  {
    category: 'ring',
    name: 'Feedback Loop',
    imagePath: '/ring/feedback_loop.png',
    id: 'j13xrf',
    tags: ['Perfect Dodge'],
    description:
      'Perfect Dodge triggers a 3m AOE blast that deals 55-155 SHOCK Damage and applies OVERLOADED which deals 55-155 SHOCK damage every 5s.',
    externalTokens: [`Amplitude`],
    wikiLinks: [`https://remnant.wiki/Feedback_Loop`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Fire Stone',
    imagePath: '/ring/fire_stone.png',
    id: 'go5hz8',
    description: `Increases FIRE damage by 12% and FIRE Resistance by 15.`,
    wikiLinks: [`https://remnant.wiki/Fire_Stone`],
    fireResistance: 15,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Floodlit Diamond',
    imagePath: '/ring/floodlit_diamond.png',
    id: 'z9YJih',
    dlc: 'dlc2',
    tags: [],
    description: `Increases Weakspot Damage by 12%. Bonus is doubled against EXPOSED targets.`,
    wikiLinks: ['https://remnant.wiki/Floodlit_Diamond'],
  },
  {
    category: 'ring',
    name: "Flyweight's Sting",
    imagePath: '/ring/flyweights_sting.png',
    id: '1qg7a8',
    tags: ['Melee Damage', 'Encumbrance'],
    description: `Increases Melee damage while Armor Encumbrance is below 50. Damage bonus increases with lower Encumbrance, up to 25% at 0 Weight.`,
    wikiLinks: [`https://remnant.wiki/Flyweight's_Sting`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Focusing Shard',
    saveFileSlug: 'ring_focusedjewel',
    imagePath: '/ring/focusing_shard.png',
    id: 'o7grsg',
    tags: ['Recoil', 'Spread'],
    description: 'Aiming Down Sights gradually reduces Spread by 70% over 4s.',
    wikiLinks: [`https://remnant.wiki/Focusing_Shard`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Frivolous Band',
    imagePath: '/ring/frivolous_band.png',
    id: '4j9wo9',
    tags: ['Perfect Dodge', 'Fire Rate', 'Melee Speed'],
    description: `Increases Evade Speed by 10%. Perfect Evades increase Fire Rate by 10% and Melee Speed by 10% for 7s.`,
    wikiLinks: [`https://remnant.wiki/Frivolous_Band`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Galvanized Resupply Band',
    imagePath: '/ring/galvanized_resupply_band.png',
    id: 'y23znz',
    tags: ['Ammo Reserves'],
    description: `Increases Ammo Pickups by 100%.`,
    wikiLinks: [`https://remnant.wiki/Galvanized_Resupply_Band`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: `Game Master's Pride`,
    imagePath: '/ring/game_masters_pride.png',
    id: '4dstmt',
    tags: ['Heal', 'Damage Reduction'],
    description: `Reduces all healing by 50%. Splits all damage and remaining healing evenly among all allies wearing this ring.`,
    wikiLinks: [`https://remnant.wiki/Game_Master's_Pride`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Generating Band',
    imagePath: '/ring/generating_band.png',
    id: 'fg8su2',
    tags: ['Heal'],
    description: `Regenerate 3% of Max Health per second while a SHIELD is active.`,
    wikiLinks: [`https://remnant.wiki/Generating_Band`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Grounding Stone',
    imagePath: '/ring/grounding_stone.png',
    id: 'o7vaf6',
    description: `Increases SHOCK damage by 12% and SHOCK Resistance by 15.`,
    wikiLinks: [`https://remnant.wiki/Grounding_Stone`],
    shockResistance: 15,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: `Guardian's Ring`,
    imagePath: '/ring/guardians_ring.png',
    id: 'yvo3jd',
    tags: ['Damage Reduction'],
    description:
      'Adds 1 Stack of BULWARK when within 15m of an enemy. Increases to 2 Stacks for 15s after taking Melee damage.',
    externalTokens: [`Amplitude`],
    wikiLinks: [`https://remnant.wiki/Guardian's_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Gul Signet',
    imagePath: '/ring/gul_signet.png',
    dlc: 'dlc2',
    id: 'xG9CQJ',
    tags: ['Encumbrance', 'Damage Reduction'],
    description: `Increases Damage Reduction by 10%. Each Weight Class above LIGHT reduces Damage Reduction bonus by 2.5% (up to 3x).`,
    wikiLinks: [`https://remnant.wiki/Gul_Signet`],
  },
  {
    category: 'ring',
    name: `Gunslinger's Ring`,
    imagePath: '/ring/gunslingers_ring.png',
    id: '976r2x',
    tags: ['Reload Speed', 'Firearm Swap Speed'],
    description: `Increases Firearm Swap Speed by 30% and Reload Speed by 10%.`,
    wikiLinks: [`https://remnant.wiki/Gunslinger's_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Hardcore Metal Band',
    imagePath: '/ring/hardcore_metal_band.png',
    id: 'f2ooga',
    tags: ['Damage Reduction'],
    description:
      'Taking damage adds 1 stack of BULWARK which individually falls off after 10s. Max 5 stacks.',
    wikiLinks: [`https://remnant.wiki/Hardcore_Metal_Band`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Hardened Coil',
    imagePath: '/ring/hardened_coil.png',
    id: 'pvwud6',
    tags: ['Damage Reduction'],
    description:
      'Reduces all incoming damage by 3% for each 10% of missing Health. Max 15% reduction.',
    wikiLinks: [`https://remnant.wiki/Hardened_Coil`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: `Haymaker's Ring`,
    imagePath: '/ring/haymakers_ring.png',
    id: '8azdr4',
    tags: ['Melee Damage', 'Encumbrance'],
    description:
      'Increase Melee damage by 0.2% for every 1 point of Armor Encumbrance.',
    wikiLinks: [`https://remnant.wiki/Haymaker's_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Heart of the Wolf',
    imagePath: '/ring/heart_of_the_wolf.png',
    id: 'x74y2q',
    tags: ['Stamina', 'Movement Speed'],
    description: `Increases Max Stamina by 25 and Movement Speed by 10%.`,
    wikiLinks: [`https://remnant.wiki/Heart_Of_The_Wolf`],
    stamina: 25,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Hex Ward',
    imagePath: '/ring/hex_ward.png',
    id: 'y45ad6',
    description: 'Prevents CURSE.',
    wikiLinks: [`https://remnant.wiki/Hex_Ward`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Jewel of the Beholden',
    imagePath: '/ring/jewel_of_the_beholden.png',
    dlc: 'dlc1',
    id: 'sosywj',
    tags: ['Mod Damage'],
    description: 'On Relic Use, increase Mod Damage by 15% for 15s.',
    wikiLinks: [`https://remnant.wiki/Jewel_of_the_Beholden`],
  },
  {
    category: 'ring',
    name: 'Kinetic Cycle Stone',
    imagePath: '/ring/kinetic_cycle_stone.png',
    id: 'kpxowa',
    tags: ['Mod Cast Speed', 'Skill Cast Speed'],
    description: `Increases Mod and Skill Cast Speed by 20%.`,
    wikiLinks: [`https://remnant.wiki/Kinetic_Cycle_Stone`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Kolket Eyelet',
    imagePath: '/ring/kolket_eyelet.png',
    id: 'dp4w2B',
    dlc: 'dlc2',
    tags: [],
    description: `Grants 1 stack of BULWARK. Increases Health Regeneration by 0.3 per second for each stack of BULWARK.`,
    wikiLinks: [`https://remnant.wiki/Kolket_Eyelet`],
  },
  {
    category: 'ring',
    name: 'Leaking Gemstone',
    imagePath: '/ring/leaking_gemstone.png',
    id: 't5dv6X',
    dlc: 'dlc2',
    tags: [],
    description: `Allows 20% of Mod Power Generation to continue during an active mod.`,
    wikiLinks: [`https://remnant.wiki/Leaking_Gemstone`],
  },
  {
    category: 'ring',
    name: "Lighthouse Keeper's Ring",
    imagePath: '/ring/lighthouse_keepers_ring.png',
    dlc: 'dlc1',
    id: 't8u4k1',
    tags: ['Mod Power', 'Status Effect'],
    description: `Automatically generate 4 Mod Power per second for each entity within 15m suffering from a Negative Status Effect. Max 5 stacks.`,
    wikiLinks: [`https://remnant.wiki/Lighthouse_Keeper's_Ring`],
  },
  {
    category: 'ring',
    name: 'Lithic Signet',
    imagePath: '/ring/lithic_signet.png',
    id: 'hs5tok',
    tags: ['Damage Reduction'],
    description: `Reduces all incoming damage by 7%.`,
    wikiLinks: [`https://remnant.wiki/Lithic_Signet`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Lodestone Ring',
    imagePath: '/ring/lodestone_ring.png',
    id: 'sye1ay',
    tags: ['All Damage'],
    description: `Increases all damage dealt against illuminated enemies by 5%.`,
    wikiLinks: [`https://remnant.wiki/Lodestone_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Low Yield Recovery Ring',
    imagePath: '/ring/low_yield_recovery_ring.png',
    id: 'l2dwy4',
    tags: ['Heal'],
    description: `Killing an enemy regenerates 6% Max Health over 6s. Additional kills increase duration by 6s. Max 30s.`,
    wikiLinks: [`https://remnant.wiki/Low_Yield_Recovery_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Mark of the Destroyer',
    imagePath: '/ring/mark_of_the_destroyer.png',
    id: 'E7fQdZ',
    dlc: 'dlc2',
    tags: ['Perfect Dodge'],
    description:
      'Perfect Dodge triggers a 3m AOE blast that deals 110 - 310 Explosive Damage.',
    externalTokens: [`Amplitude`, `Explosive Damage`],
    wikiLinks: [`https://remnant.wiki/Mark_of_the_Destroyer`],
  },
  {
    category: 'ring',
    name: `Matriarch's Ring`,
    imagePath: '/ring/matriarchs_ring.png',
    id: 'R3fM4y',
    dlc: 'dlc2',
    tags: ['Perfect Dodge', 'Charged Melee', 'Stamina'],
    description:
      'Perfect Dodge reduces Charge Melee Stamina Cost by 100% for 7s.',
    wikiLinks: [`https://remnant.wiki/Matriarch's_Ring`],
  },
  {
    category: 'ring',
    name: "Mechanic's Cog",
    imagePath: '/ring/mechanics_cog.png',
    id: 'ngue5b',
    tags: ['Movement Speed', 'Damage Reduction'],
    description:
      'While carrying an Engineer Heavy Weapon, gain 15% Movement Speed and 1 Stack of BULWARK.',
    wikiLinks: [`https://remnant.wiki/Mechanic's_Cog`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Metal Driver',
    imagePath: '/ring/metal_driver.png',
    id: 'o7byap',
    tags: ['Reload Speed'],
    description: `Killing Blows increase Reload Speed by 10% for 15s. Stacks 3x.`,
    wikiLinks: [`https://remnant.wiki/Metal_Driver`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Meteorite Shard Ring',
    imagePath: '/ring/meteorite_shard_ring.png',
    id: 'ayje99',
    tags: ['Encumbrance'],
    description: `Increases Encumbrance by 50. Increases Unarmed damage by 50%.`,
    wikiLinks: [`https://remnant.wiki/Meteorite_Shard_Ring`],
    weight: 50,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Microcompressor',
    imagePath: '/ring/microcompressor.png',
    id: 'rtfwr5',
    tags: ['Heat Generation'],
    description:
      'Reduces Heat Generation per round when firing Weapons that Overheat by 30%. Increases Heat decay Rate by 30%.',
    wikiLinks: [`https://remnant.wiki/Microcompressor`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Momentum Driver',
    imagePath: '/ring/momentum_driver.png',
    id: 'la9qe1',
    tags: ['Movement Speed', 'Stagger'],
    description: `After Sprinting for 1.5s, Movement Speed is increased by 15% and Stagger Level reduced by 1.`,
    wikiLinks: [`https://remnant.wiki/Momentum_Driver`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Offering Stone',
    imagePath: '/ring/offering_stone.png',
    id: 'p71mik',
    tags: ['Ranged Damage', 'All Damage'],
    description: `Dealing Ranged Damage increases all Damage by 1% for 1s. Stacks 15x. After killing an enemy, extends the duration to 10s.`,
    wikiLinks: [`https://remnant.wiki/Offering_Stone`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Outcast Ring',
    imagePath: '/ring/outcast_ring.png',
    id: 'b195vq',
    tags: ['Reload Speed'],
    description: `Increases Reload Speed by 5% for 10s after reloading. Stacks 5x.`,
    wikiLinks: [`https://remnant.wiki/Outcast_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Painless Obsidian',
    imagePath: '/ring/painless_obsidian.png',
    id: '6y14c4',
    tags: ['Grey Health', 'Damage Reduction'],
    description:
      'When Grey Health is present gain HASTE and 1 stack of BULWARK.',
    wikiLinks: [`https://remnant.wiki/Painless_Obsidian`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Pan War Band',
    imagePath: '/ring/pan_war_band.png',
    id: 'eBxG7w',
    dlc: 'dlc2',
    tags: ['Movement Speed', 'Reload Speed', 'Fire Rate'],
    description: `Increases Movement Speed and Reload Speed by 3% and Fire Rate by 2% for each ally wearing this ring.`,
    wikiLinks: [`https://remnant.wiki/Pan_War_Band`],
  },
  {
    category: 'ring',
    name: 'Point Focus Ring',
    imagePath: '/ring/point_focus_ring.png',
    id: 'gg6srx',
    tags: ['Recoil', 'Spread'],
    description: 'Reduces Weapon Spread and Recoil by 30%.',
    wikiLinks: [`https://remnant.wiki/Point_Focus_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Power Complex',
    imagePath: '/ring/power_complex.png',
    id: 'oavdxw',
    tags: ['All Damage'],
    description:
      'Increases All Damage dealt by 1% per second to a maximum of 15%. Dodging resets Power Complex to 0%.',
    wikiLinks: [`https://remnant.wiki/Power_Complex`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Power Saver',
    imagePath: '/ring/power_saver.png',
    id: '7i0yzu',
    description: `At Max Health, gain a 35% chance to not use a Relic charge.`,
    wikiLinks: [`https://remnant.wiki/Power_Saver`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Probability Cord',
    imagePath: '/ring/probability_cord.png',
    id: '0k8d0g',
    tags: ['Critical Hit'],
    description: `Increases Crit Damage by 20%.`,
    wikiLinks: [`https://remnant.wiki/Probability_Cord`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Propulsion Loop',
    imagePath: '/ring/propulsion_loop.png',
    id: 'uydz9a',
    tags: ['Movement Speed', 'Relic Use Speed'],
    description: `After killing an enemy, increases Movement Speed by 5% and Consumable Use Speed by 10% for 10s. Stacks 3x.`,
    wikiLinks: [`https://remnant.wiki/Propulsion_Loop`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Provisioner Ring',
    imagePath: '/ring/provisioner_ring.png',
    id: '8i7o4p',
    tags: ['Reload Speed', 'Hardcore Reward'],
    description: `Firearms reload over time while stowed.`,
    wikiLinks: [`https://remnant.wiki/Provisioner_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Rally Band',
    imagePath: '/ring/rally_band.png',
    id: '7XdP4g',
    dlc: 'dlc2',
    tags: ['Health', 'Grey Health', 'Melee Hit'],
    description: `Melee Strikes convert Grey Health into Health. Each melee strike converts up to 10% of Max Health`,
    wikiLinks: [`https://remnant.wiki/Rally_Band`],
  },
  {
    category: 'ring',
    name: "Ravager's Bargain",
    imagePath: '/ring/ravagers_bargain.png',
    id: 'kqddup',
    dlc: 'dlc2',
    tags: ['All Damage', 'Critical Chance', 'Status Effect'],
    description: `Increases All Damage and All Critical Chance by 5% while BLEEDING.`,
    wikiLinks: [`https://remnant.wiki/Ravager's_Bargain`],
  },
  {
    category: 'ring',
    name: 'Reaping Stone',
    imagePath: '/ring/reaping_stone.png',
    id: 'kqdoup',
    tags: ['Status Effect', 'Lifesteal'],
    description: `After an Elemental Status Effect is removed from wearer, they become immune to all Elemental Status Effects and gain 5% of base damage dealt as Lifesteal for 10s.`,
    wikiLinks: [`https://remnant.wiki/Reaping_Stone`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Red Ring of Death',
    imagePath: '/ring/red_ring_of_death.png',
    id: '9ng83z',
    tags: ['Status Effect'],
    description:
      'Duplicates the last damaging Negative Status applied to the target. Reduces outgoing Status Effect Damage by 10%.',
    wikiLinks: [`https://remnant.wiki/Red_Ring_of_Death`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Rerouting Cable',
    imagePath: '/ring/rerouting_cable.png',
    id: '48r4bl',
    description: `Gain 5% of Max Health as a SHIELD for 5s after spending 20 Stamina. Accumulation resets after 5s of inaction. Max 50% SHIELD.`,
    wikiLinks: [`https://remnant.wiki/Rerouting_Cable`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Reserve Boosting Gem',
    imagePath: '/ring/reserve_boosting_gem.png',
    id: 'ucm4yv',
    tags: ['Heal'],
    description: `Increases Health Regeneration by 0.5 per second. 1s after going below 50% Health, increases regeneration value to 2.5 per second until 50% Health is reached.`,
    wikiLinks: [`https://remnant.wiki/Reserve_Boosting_Gem`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Restriction Cord',
    imagePath: '/ring/restriction_cord.png',
    id: 'eznhcv',
    tags: ['Damage Reduction', 'Health'],
    description: `Restricts the wearer from Healing above 50% of their Max Health and reduces all incoming damage by 15%.`,
    wikiLinks: [`https://remnant.wiki/Restriction_Cord`],
    healthCap: 0.5,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Ring of Crisis',
    imagePath: '/ring/ring_of_crisis.png',
    id: '378qz0',
    tags: ['Health'],
    description:
      "When wearer's Health drops below 25%, gain a Shield for 25% of Max Health. Lasts 10s.",
    wikiLinks: [`https://remnant.wiki/Ring_of_Crisis`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Ring of Deflection',
    imagePath: '/ring/ring_of_deflection.png',
    id: 'ie648z',
    tags: ['Grey Health'],
    description:
      'Direct damage against wearer has a 50% chance to be converted entirely to Grey Health.',
    wikiLinks: [`https://remnant.wiki/Ring_of_Deflection`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Ring of Diversion',
    imagePath: '/ring/ring_of_diversion.png',
    id: 'ubqgie',
    description: `Increases invulnerability window while evading and sliding.`,
    wikiLinks: [`https://remnant.wiki/Ring_of_Diversion`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Ring of Flawed Beauty',
    imagePath: '/ring/ring_of_flawed_beauty.png',
    id: 'lx6all',
    tags: ['Weakspot Damage', 'Ranged Damage'],
    description:
      'Ranged Weakspot damage is increased by 25%. Ranged damage is reduced by 15% when failing to hit a Weakspot.',
    wikiLinks: [`https://remnant.wiki/Ring_of_Flawed_Beauty`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Ring of Grace',
    imagePath: '/ring/ring_of_grace.png',
    id: 'ne83ro',
    tags: ['Heal'],
    description: `Taking enemy damage causes 15% of Maximum Health to regenerate over 10s.`,
    wikiLinks: [`https://remnant.wiki/Ring_of_Grace`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Ring of Infinite Damage',
    imagePath: '/ring/ring_of_infinite_damage.png',
    dlc: 'dlc1',
    id: '0yfahk',
    tags: ['Fire Rate'],
    description: 'Increases fire rate by 8. ',
    wikiLinks: [`https://remnant.wiki/Ring_of_Infinite_Damage`],
  },
  {
    category: 'ring',
    name: 'Ring of Omens',
    imagePath: '/ring/ring_of_omens.png',
    id: '1gnt2c',
    tags: ['Grey Health', 'Stamina'],
    description: `Evades cost 15% Max Health as Grey Health instead of Stamina.`,
    wikiLinks: [`https://remnant.wiki/Ring_of_Omens`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Ring Of Ordnance',
    imagePath: '/ring/ring_of_ordnance.png',
    id: 'RDi2ad',
    dlc: 'dlc2',
    tags: [],
    description: `Allows Heavy Weapon Ammo to gradually regenerate while in both Heavy Carry or Turret modes. Doubles the stowed Ammo Regeneration Rate of Heavy Weapons.`,
    wikiLinks: [`https://remnant.wiki/Ring_Of_Ordnance`],
  },
  {
    category: 'ring',
    name: 'Ring of Restocking',
    imagePath: '/ring/ring_of_restocking.png',
    id: '3aryrr',
    tags: ['Reload Speed', 'Critical Hit', 'Weakspot Damage'],
    description:
      'Reloads within 5s of a Critical Kill or Weakspot Kill are 20% faster.',
    wikiLinks: [`https://remnant.wiki/Ring_of_Restocking`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Ring of Retribution',
    imagePath: '/ring/ring_of_retribution.png',
    id: '8ejbuu',
    tags: ['Reload Speed', 'All Damage'],
    description: `Incoming enemy damage increases Reload Speed and all outgoing damage by 15%. Lasts 15s.`,
    wikiLinks: [`https://remnant.wiki/Ring_of_Retribution`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Ring of Spirits',
    dlc: 'dlc2',
    imagePath: '/ring/ring_of_spirits.png',
    id: 'ic39X7',
    tags: ['Mod Power'],
    description: `Increases Mod Generation by 3% for each active consumable. Max 5 stacks.`,
    wikiLinks: [`https://remnant.wiki/Ring_of_Spirits`],
  },
  {
    category: 'ring',
    name: 'Ring of the Castaway',
    imagePath: '/ring/ring_of_the_castaway.png',
    dlc: 'dlc1',
    id: 'aqo8pe',
    description: 'Increases base Consumable Duration by 50%.',
    wikiLinks: [`https://remnant.wiki/Ring_of_the_Castaway`],
  },
  {
    category: 'ring',
    name: 'Ring of the Damned',
    saveFileSlug: 'ring_strongarmband',
    imagePath: '/ring/ring_of_the_damned.png',
    id: 'jbfxsb',
    tags: ['All Damage', 'Grey Health', 'Critical Chance'],
    description:
      'Increases All Damage by 0.4% for each 1% of Grey Health. Increase Critical Chance by 5% if at least 50% of Max Health is Grey.',
    wikiLinks: [`https://remnant.wiki/Ring_of_the_Damned`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Ring of the Forest Spirit',
    imagePath: '/ring/ring_of_the_forest_spirit.png',
    id: 'wvtzrn',
    tags: ['Healing Effectiveness'],
    description: `Relic Healing Effectiveness is increased by 15%.`,
    wikiLinks: [`https://remnant.wiki/Ring_of_the_Forest_Spirit`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Ring of the Robust',
    imagePath: '/ring/ring_of_the_robust.png',
    id: 'qdxm42',
    tags: ['Health'],
    description: 'Increases Max Health by 10 and Armor by 20.',
    wikiLinks: [`https://remnant.wiki/Ring_Of_The_Robust`],
    health: 10,
    armor: 20,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Ring of the Vain',
    imagePath: '/ring/ring_of_the_vain.png',
    id: 'g61t33',
    tags: ['Movement Speed'],
    description:
      'Reduces Invulnerability Window on Evade and Combat Slide by 35%. Increases Movement Speed while aiming by 35%.',
    wikiLinks: [`https://remnant.wiki/Ring_of_the_Vain`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Rock of Anguish',
    imagePath: '/ring/rock_of_anguish.png',
    id: 'lr4wxu',
    tags: ['Movement Speed', 'Reload Speed'],
    description: `Gain 5% Movement Speed and 7.5% Reload Speed for every 25% of Max Health missing.`,
    wikiLinks: [`https://remnant.wiki/Rock_of_Anguish`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Rotward',
    imagePath: '/ring/rotward.png',
    id: 'hvhbv9',
    description: `Prevents ROOT ROT Blight.`,
    wikiLinks: [`https://remnant.wiki/Rotward`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Rusted Heirloom',
    imagePath: '/ring/rusted_heirloom.png',
    id: 'i544v3',
    tags: ['Damage Reduction'],
    description: `Grants 2 Stacks of BULWARK below 50% Max HP.`,
    wikiLinks: [`https://remnant.wiki/Rusted_Heirloom`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Sagestone',
    imagePath: '/ring/sagestone.png',
    id: 'pl1g6b',
    description: `Increases earned Experience by 10%.`,
    wikiLinks: [`https://remnant.wiki/Sagestone`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Sapphire Dreamstone',
    imagePath: '/ring/sapphire_dreamstone.png',
    id: 'v65mav',
    tags: ['Reduce Skill Cooldown', 'Critical Hit'],
    description: `Critical Hits reduce Skill Cooldowns by 4%. Can only happen once every 2s.`,
    wikiLinks: [`https://remnant.wiki/Sapphire_Dreamstone`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Sealed Resin Loop',
    imagePath: '/ring/sealed_resin_loop.png',
    id: 'RA6NZn',
    dlc: 'dlc2',
    tags: [],
    description: `Melee Attacks can be cancelled mid action by Dodging.`,
    wikiLinks: [`https://remnant.wiki/Sealed_Resin_Loop`],
  },
  {
    category: 'ring',
    name: 'Seal of the Empress',
    imagePath: '/ring/seal_of_the_empress.png',
    id: 'pqd4vp',
    tags: ['Health', 'Stamina'],
    description: `Increases Max Health by 20. Reduces Max Stamina by 5.`,
    wikiLinks: [`https://remnant.wiki/Seal_of_the_Empress`],
    health: 20,
    stamina: -5,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Shadow of Misery',
    imagePath: '/ring/shadow_of_misery.png',
    id: '8bhhzo',
    tags: ['Status Effect'],
    description: 'Increase Status Effect Damage by 20%.',
    wikiLinks: [`https://remnant.wiki/Shadow_of_Misery`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Shaed Stone',
    imagePath: '/ring/shaed_stone.png',
    dlc: 'dlc1',
    id: 'ylif78',
    tags: ['Skill Damage'],
    description: 'Increase Skill Damage by 15%.',
    wikiLinks: [`https://remnant.wiki/Shaed_Stone`],
  },
  {
    category: 'ring',
    name: 'Shard Banded Ring',
    imagePath: '/ring/shard_banded_ring.png',
    id: '13vsn5',
    tags: ['Mod Damage'],
    description: 'Increases Mod damage by 12%',
    wikiLinks: [`https://remnant.wiki/Shard_Banded_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Shiny Hog Lure',
    imagePath: '/ring/shiny_hog_lure.png',
    id: '08cb3s',
    tags: ['Mod Power'],
    description: `Reloading grants 25-50 Mod Power to both weapons based on percentage of Magazine reloaded.`,
    wikiLinks: [`https://remnant.wiki/Shiny_Hog_Lure`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Singed Ring',
    imagePath: '/ring/singed_ring.png',
    id: 'cpxk1d',
    tags: ['All Damage'],
    description: `Increases all damage dealt to BURNING enemies by 12%.`,
    wikiLinks: [`https://remnant.wiki/Singed_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Slayer's Crest",
    imagePath: '/ring/slayers_crest.png',
    id: '0e7ll0',
    tags: ['Melee Damage'],
    description:
      'Increases Melee damage by 25% when attacking enemies from behind.',
    wikiLinks: [`https://remnant.wiki/Slayer's_Crest`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Soul Feast',
    imagePath: '/ring/soul_feast.png',
    dlc: 'dlc2',
    id: '8kotd5',
    tags: ['Summon', 'Reduce Skill Cooldown'],
    description: `When a Human, Companion, or Minion is downed or killed, reduce Skill Cooldowns by 8%.`,
    wikiLinks: [`https://remnant.wiki/Soul_Feast`],
  },
  {
    category: 'ring',
    name: 'Soul Guard',
    imagePath: '/ring/soul_guard.png',
    id: '8kotg5',
    tags: ['Damage Reduction', 'Summon'],
    description: `Gain a stack of BULWARK for each active Summon.`,
    wikiLinks: [`https://remnant.wiki/Soul_Guard`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Soul Link',
    imagePath: '/ring/soul_link.png',
    id: 'ohlt19',
    tags: ['Summon', 'Lifesteal'],
    description: `Summons Lifesteal 5% of base damage dealt which returns to the wearer as Health.`,
    wikiLinks: [`https://remnant.wiki/Soul_Link`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Soul Shard',
    imagePath: '/ring/soul_shard1.png',
    id: 'uswo9w',
    tags: ['Summon', 'All Damage'],
    description:
      'Increases All Damage dealt by 5% for each active Summon. Max 15%.',
    wikiLinks: [`https://remnant.wiki/Soul_Shard`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Spirit Stone',
    imagePath: '/ring/spirit_stone.png',
    id: '58hv43',
    tags: ['Mod Power'],
    description: `Increases Mod Power generation by 10%.`,
    wikiLinks: [`https://remnant.wiki/Spirit_Stone`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Stockpile Charger',
    imagePath: '/ring/stockpile_charger.png',
    id: '0jnimt',
    tags: ['Ranged Damage'],
    description: `After picking up ammo, increases the damage of that Ammo Type by 15% for 20s.`,
    wikiLinks: [`https://remnant.wiki/Stockpile_Charger`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Stone of Balance',
    imagePath: '/ring/stone_of_balance.png',
    id: 'c20p9b',
    tags: ['All Damage'],
    description: `Increases all damage by 7%.`,
    wikiLinks: [`https://remnant.wiki/Stone_of_Balance`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Stone of Continuance',
    imagePath: '/ring/stone_of_continuance.png',
    id: 'leuefm',
    tags: ['Skill Duration'],
    description: `Increases Skill Duration by 15%.`,
    wikiLinks: [`https://remnant.wiki/Stone_of_Continuance`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Stone of Expanse',
    imagePath: '/ring/stone_of_expanse.png',
    id: 'efdw51',
    tags: ['Ranged Damage'],
    description: `Increases Ranged damage by 12%. Reduces all other damage dealt by 5%.`,
    wikiLinks: [`https://remnant.wiki/Stone_of_Expanse`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Stone of Malevolence',
    imagePath: '/ring/stone_of_malevolence.png',
    id: 'kx65km',
    tags: ['Status Effect', 'Mod Power'],
    description: 'Elemental damage generates 15% additional Mod Power.',
    wikiLinks: [`https://remnant.wiki/Stone_Of_Malevolence`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Stream Coupler',
    imagePath: '/ring/stream_coupler.png',
    id: 'jq4dje',
    tags: ['Heal'],
    description: `Using a Skill regenerates 25% of Max Health over 10s.`,
    wikiLinks: [`https://remnant.wiki/Stream_Coupler`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Subterfuge Link',
    imagePath: '/ring/subterfuge_link.png',
    id: 'al5vs8',
    tags: ['Skill Cast Speed', 'Mod Cast Speed'],
    description: `After killing an enemy, increases the Cast Speed of the next Mod or Skill Cast by 35%. Lasts 15s or until consumed.`,
    wikiLinks: [`https://remnant.wiki/Subterfuge_Link`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Suppression Ward',
    imagePath: '/ring/suppression_ward.png',
    id: '44my16',
    description: `Prevents SUPPRESSION Blight.`,
    wikiLinks: [`https://remnant.wiki/Suppression_Ward`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Targeting Jewel',
    imagePath: '/ring/targeting_jewel.png',
    id: 'm2uqsh',
    tags: ['Range', 'Spread'],
    description: `Increases Range on all Firearms by 4m. Reduces Spread by 15%.`,
    wikiLinks: [`https://remnant.wiki/Targeting_Jewel`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Tarnished Ring',
    imagePath: '/ring/tarnished_ring.png',
    id: 'w4xzfq',
    tags: ['Melee Damage'],
    description: `Increases damage of Unarmed Attacks by 30%.`,
    wikiLinks: [`https://remnant.wiki/Tarnished_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Tear of Kaeula',
    imagePath: '/ring/tear_of_kaeula.png',
    id: 'qv7e2g',
    description: 'Increases Relic capacity by 2 while equipped.',
    wikiLinks: [`https://remnant.wiki/Tear_of_Kaeula`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Tear of Lydusa',
    imagePath: '/ring/tear_of_lydusa.png',
    id: 'k90sex',
    dlc: 'dlc2',
    tags: ['Lifesteal', 'Healing Effectiveness', 'Heal'],
    description: `Increases Healing and Lifesteal Efficacy by 20%. Reduces Healing Efficacy bonus by 1.5% for each 10% of missing Relic Capacity.`,
    wikiLinks: [`https://remnant.wiki/Tear_of_Lydusa`],
  },
  {
    category: 'ring',
    name: 'Tempest Conduit',
    imagePath: '/ring/tempest_conduit.png',
    id: '4bb4gf',
    tags: ['Elemental Damage', 'All Damage'],
    description: `After receiving Elemental Damage, increases all damage dealt by 15% and Resistance to the received Element by 20 for 15s.`,
    wikiLinks: [`https://remnant.wiki/Tempest_Conduit`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Thalos Eyelet',
    imagePath: '/ring/thalos_eyelet.png',
    dlc: 'dlc2',
    id: '6mopod',
    tags: ['Stamina', 'Damage Reduction'],
    description: `Grants 1 stack of BULWARK and 2 Stamina Regen per second for each BULWARK stack. Increases BULWARK maximum stacks to 6.`,
    wikiLinks: [`https://remnant.wiki/Thalos_Eyelet`],
  },
  {
    category: 'ring',
    name: 'Tightly Wound Coil',
    imagePath: '/ring/tightly_wound_coil.png',
    id: '3pe83i',
    description: `When spending 75% or more of current magazine, gain a SHIELD for 15% of Max Health for 5s. Does not stack with itself.`,
    wikiLinks: [`https://remnant.wiki/Tightly_Wound_Coil`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Timekeeper's Jewel",
    imagePath: '/ring/timekeepers_jewel.png',
    id: '3uggz9',
    tags: ['Status Effect', 'Status Duration'],
    description:
      'Increases the duration of all Status Effects applied by the wearer. Duration varies per Status.',
    wikiLinks: [`https://remnant.wiki/Timekeeper's_Jewel`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Token of Favor',
    imagePath: '/ring/token_of_favor.png',
    dlc: 'dlc2',
    id: 'qv7e2gx',
    description:
      'Increases All Damage by 5%. Gain 10% Critical Chance against EXPOSED targets.',
    wikiLinks: [`https://remnant.wiki/Token_of_Favor`],
  },
  {
    category: 'ring',
    name: "Tomb Dweller's Ring",
    imagePath: '/ring/tomb_dwellers_ring.png',
    id: '6mopou',
    tags: ['Movement Speed', 'Damage Reduction'],
    description: `Increases Movement Speed by 10% for 15s after Vaulting, Climbing, Leaping, and entering Water, stacks 3x. Reduces Fall Damage by 50%.`,
    wikiLinks: [`https://remnant.wiki/Tomb_Dweller's_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Vacuum Seal',
    imagePath: '/ring/vacuum_seal.png',
    id: 'hnkpp0',
    description:
      'Increases Automatic Pickup Range for Scrap by 150%. Picking up Scrap, Iron, or Ammo grants a SHIELD for 15% of Max Health for 15s. Does not stack.',
    wikiLinks: [`https://remnant.wiki/Vacuum_Seal`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Vestige of Power',
    imagePath: '/ring/vestige_of_power.png',
    id: 'e6zmo5',
    tags: ['Ranged Damage', 'Melee Damage'],
    description: `After 5s of not being damaged, increases Ranged and Melee Damage by 10%.`,
    wikiLinks: [`https://remnant.wiki/Vestige_of_Power`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Wax Sealed Ring',
    imagePath: '/ring/wax_sealed_ring.png',
    id: 'ekm1hx',
    tags: ['Ranged Damage', 'Melee Damage'],
    description:
      'Killing blows increase Ranged and Melee Damage by 4% for 15s. Stacks 3x',
    wikiLinks: [`https://remnant.wiki/Wax_Sealed_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'White Glass Bead',
    imagePath: '/ring/white_glass_bead.png',
    dlc: 'dlc1',
    id: 'etgc4h',
    tags: ['Perfect Dodge'],
    description:
      'Perfect Dodge applies a SHIELD for 15% of Max Health. Lasts 10s. Cannot stack with itself.',
    wikiLinks: [`https://remnant.wiki/White_Glass_Bead`],
  },
  {
    category: 'ring',
    name: 'White Pawn Stamp',
    imagePath: '/ring/white_pawn_stamp.png',
    id: 'irhphl',
    tags: ['Mod Power'],
    description: `Reduces Mod Power Requirement by 10%.`,
    wikiLinks: [`https://remnant.wiki/White_Pawn_Stamp`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Wind Hollow Circlet',
    imagePath: '/ring/wind_hollow_circlet.png',
    id: 'tx475e',
    tags: ['Reload Speed'],
    description: `Increases Reload Speed by 12%.`,
    wikiLinks: [`https://remnant.wiki/Wind_Hollow_Circlet`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Wood Ring',
    imagePath: '/ring/wood_ring.png',
    dlc: 'dlc1',
    id: 'uwq264',
    tags: ['Stagger'],
    description: 'Increases Stagger Damage by 15%.',
    wikiLinks: [`https://remnant.wiki/Wood_Ring`],
  },
  {
    category: 'ring',
    name: "Worn Admiral's Ring",
    saveFileSlug: 'ringoftheadmiral',
    imagePath: '/ring/worn_admirals_ring.png',
    id: '9kcrxa',
    tags: ['All Damage'],
    description: `All damage received is increased by 200%. All damage dealt is increased by 15%.`,
    wikiLinks: [`https://remnant.wiki/Worn_Admiral's_Ring`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Zania's Malice",
    imagePath: '/ring/zanias_malice.png',
    id: 'ukufrn',
    tags: ['Weakspot Damage'],
    description:
      'Dealing Weakspot damage increases Weakspot damage by 5% for 5s. Stacks 4x',
    wikiLinks: [`https://remnant.wiki/Zania's_Malice`],
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Zohee's Ring",
    imagePath: '/ring/zohees_ring.png',
    id: '9fe9kj',
    tags: ['Mod Duration'],
    description: `Increases Mod Duration by 20%.`,
    wikiLinks: [`https://remnant.wiki/Zohee's_Ring`],
    dlc: 'base',
  },
]
