import { WeaponItem } from './types/WeaponItem'

export const weaponItems: WeaponItem[] = [
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Alpha / Omega',
    imagePath: '/mainhand/alpha_omega.png',
    id: '1ub6k9',
    description: `After charging, fires an accurate high-damage rail which penetrates any target. Each successful hit reduces the charge time by 0.1s and increases damage by 10% for 1.5s. Stacks 5x.`,
    wikiLinks: [`https://remnant.wiki/Alpha_/_Omega`],
    location: { world: 'Root Earth', dungeon: ['Blackened Citadel'] },
    linkedItems: {
      mod: {
        name: 'Beta Ray',
      },
    },
    // TODO Check this; 15 -> 14
    damage: 14,
    rps: 7.2,
    magazine: 55,
    accuracy: 95,
    ideal: 24,
    falloff: 70,
    ammo: 275,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Aphelion',
    saveFileSlug: '/weapon_aphelion',
    imagePath: '/mainhand/aphelion1.png',
    id: '3wprfw',
    description: `Fires a hypercharged wide-arcing line that passes through targets.`,
    wikiLinks: [`https://remnant.wiki/Aphelion`],
    linkedItems: {
      mod: {
        name: 'Supernova',
      },
    },
    damage: 62,
    rps: 2,
    magazine: 7,
    accuracy: 95,
    ideal: 20,
    falloff: 65,
    ammo: 49,
    crit: 10,
    weakspot: 100,
    stagger: -25,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'AS-10 "Bulldog"',
    saveFileSlug: 'weapon_autoshotgun',
    imagePath: '/mainhand/as_10_bulldog.png',
    id: 'va7cfd',
    description: `A brutal drum-fed fully-automatic 10 gauge shotgun designed for close-quarters combat.`,
    wikiLinks: [`https://remnant.wiki/AS-10_%22Bulldog%22`],
    damage: 60,
    rps: 2.5,
    magazine: 12,
    accuracy: 60,
    ideal: 10,
    falloff: 32,
    ammo: 60,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Blackmaw AR-47',
    saveFileSlug: 'weapon_assaultrifle',
    imagePath: '/mainhand/blackmaw_ar_47.png',
    id: 'phh1xe',
    description: `A fully automatic rifle with a medium capacity. Highly effective with controlled bursts.`,
    wikiLinks: [`https://remnant.wiki/Blackmaw_AR-47`],
    damage: 17,
    rps: 7.3,
    magazine: 38,
    accuracy: 95,
    ideal: 20,
    falloff: 60,
    ammo: 190,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Chicago Typewriter',
    saveFileSlug: 'weapon_tommygun',
    imagePath: '/mainhand/chicago_typewriter.png',
    id: '59oddb',
    description: `A classic Tommy Gun with large ammo capacity and a slow reload. Poor initial accuracy which improves while holding down the trigger.`,
    wikiLinks: [`hhttps://remnant.wiki/Chicago_Typewriter`],
    damage: 10,
    rps: 11,
    magazine: 80,
    accuracy: 80,
    ideal: 17,
    falloff: 55,
    ammo: 320,
    crit: 10,
    weakspot: 105,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Coach Gun',
    imagePath: '/mainhand/coach_gun.png',
    id: 'i0hvy8',
    description: `A double-barrel over/under shotgun modified to fire powerful slugs. High damage with a decent fire rate, but very low magazine capacity.`,
    wikiLinks: [`https://remnant.wiki/Coach_Gun`],
    damage: 115,
    rps: 2.3,
    magazine: 2,
    accuracy: 95,
    ideal: 15,
    falloff: 33,
    ammo: 28,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Corrupted Aphelion',
    imagePath: '/mainhand/corrupted_aphelion1.png',
    id: 'w85ya8',
    description: `Fires a hypercharged wide-arcing line that passes through targets.`,
    wikiLinks: [`https://remnant.wiki/Corrupted_Aphelion`],
    linkedItems: {
      mod: {
        name: 'Micronova',
      },
    },
    damage: 33,
    rps: 1.45,
    magazine: 8,
    accuracy: 95,
    ideal: 15,
    falloff: 40,
    ammo: 40,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Corrupted Arbalest',
    imagePath: '/mainhand/corrupted_arbalest.png',
    saveFileSlug: 'corruptedtwistedarbalest',
    id: 'Gkemt8',
    description: `Fully automatic mechanisms launch a bouncing Energy Disc that can hit up to 2 enemies in close proximity. Damage is reduced after bouncing.`,
    damage: 69,
    rps: 1.3,
    magazine: 8,
    accuracy: 95,
    ideal: 20,
    falloff: 70,
    // TODO Check this; 48 -> 40
    ammo: 40,
    crit: 5,
    weakspot: 100,
    stagger: 5,
    wikiLinks: ['https://remnant.wiki/Corrupted_Arbalest'],
    linkedItems: {
      mod: {
        name: `Guardian's Fury`,
      },
    },
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Corrupted Deceit',
    imagePath: '/mainhand/corrupted_deceit1.png',
    id: 'k9w4yh',
    description: `A pinpoint accurate split-barreled rifle that fires two penetrating rails. High base damage, but cannot score Weakspot hits. Charge to fire.`,
    wikiLinks: [`https://remnant.wiki/Corrupted_Deceit`],
    linkedItems: {
      mod: {
        name: 'Windfall',
      },
    },
    damage: 66,
    rps: 3,
    magazine: 12,
    accuracy: 95,
    ideal: 26,
    falloff: 75,
    ammo: 48,
    crit: 10,
    weakspot: 90,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Corrupted Merciless',
    imagePath: '/mainhand/corrupted_merciless1.png',
    id: '8i85za',
    description: `Fires high-powered nails. Limited magazine size.`,
    wikiLinks: [`https://remnant.wiki/Corrupted_Merciless`],
    linkedItems: {
      mod: {
        name: 'Bloodshot',
      },
    },
    damage: 90,
    rps: 1.3,
    magazine: 3,
    accuracy: 90,
    ideal: 25,
    falloff: 70,
    ammo: 36,
    crit: 5,
    // TODO Check this; 100 -> 105
    weakspot: 105,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Corrupted Savior',
    imagePath: '/mainhand/corrupted_savior.png',
    id: 'W6n2mT',
    tags: ['Hardcore Reward'],
    description: `Black crystal weapon which increases Fire Rate as mod power is generated. Mod power slowly drains after 2s of not dealing damage.`,
    wikiLinks: ['https://remnant.wiki/Corrupted_Savior'],
    linkedItems: {
      mod: {
        name: 'Fusion Cannon',
      },
    },
    damage: 17,
    rps: 3,
    // TODO Check this; 50 -> 40
    magazine: 40,
    accuracy: 95,
    ideal: 20,
    falloff: 60,
    // TODO Check this; 300 -> 200
    ammo: 200,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Crescent Moon',
    imagePath: '/mainhand/crescent_moon.png',
    id: 'p7wc7k',
    description: `An ethereal weapon that seems to resonate. Can be charged for more damage. Perfect release after Charge for maximum damage.`,
    wikiLinks: [`https://remnant.wiki/Crescent_Moon`],
    linkedItems: {
      mod: {
        name: 'Moonlight Barrage',
      },
    },
    damage: 261,
    rps: 4.1,
    magazine: 1,
    accuracy: 100,
    ideal: 25,
    falloff: 65,
    ammo: 38,
    crit: 5,
    weakspot: 70,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Crossbow',
    imagePath: '/mainhand/crossbow.png',
    id: 'x94ze2',
    description: `An accurate and deadly single-shot crossbow with a low sound profile.`,
    wikiLinks: [`https://remnant.wiki/Crossbow`],
    // TODO Check this; increased damage from 115 -> 120
    damage: 120,
    rps: 3.4,
    magazine: 1,
    accuracy: 100,
    ideal: 23,
    falloff: 70,
    ammo: 27,
    crit: 10,
    // TODO Check this; I think this is the same thing as weakspot modifier? Notes say 110% -> 115%, but it was already 115%.
    weakspot: 115,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Deceit',
    saveFileSlug: '/weapon_deceit',
    imagePath: '/mainhand/deceit.png',
    id: 'hlmpjl',
    description: `A pinpoint accurate split-barreled rifle that fires two penetrating rails. High base damage, but cannot score Weakspot hits. Charge to fire`,
    wikiLinks: [`https://remnant.wiki/Deceit`],
    linkedItems: {
      mod: {
        name: 'Ouroboros',
      },
    },
    damage: 120,
    rps: 2,
    magazine: 6,
    accuracy: 95,
    ideal: 28,
    falloff: 75,
    ammo: 30,
    crit: 15,
    weakspot: 90,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: "Ford's Scattergun",
    saveFileSlug: 'weapon_shotgun',
    imagePath: '/mainhand/fords_scattergun.png',
    id: '8n3e07',
    description: `An incredibly powerful 12 gauge shotgun with a wide spread. High damage, slow reload.`,
    wikiLinks: [`https://remnant.wiki/Ford%27s_Scattergun`],
    damage: 130,
    rps: 1.1,
    magazine: 7,
    accuracy: 95,
    ideal: 10,
    falloff: 35,
    ammo: 28,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Huntmaster M1',
    saveFileSlug: 'weapon_huntmaster',
    imagePath: '/mainhand/huntmaster_m1.png',
    id: 'cda7lb',
    description: `A powerful single-shot sniper rifle with excellent range and pinpoint accuracy. Comes with a 3x scope. Tap SCOPE to toggle.`,
    wikiLinks: [`https://remnant.wiki/Huntmaster_M1`],
    damage: 70,
    rps: 1.5,
    magazine: 7,
    accuracy: 95,
    ideal: 27,
    falloff: 75,
    // TODO Check this; reserves increased by 7, 42 -> 49
    ammo: 49,
    crit: 5,
    weakspot: 110,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Merciless',
    saveFileSlug: '/weapon_merciless',
    imagePath: '/mainhand/merciless.png',
    id: 'g3esv1',
    description: `Fires tooth-like flechettes. When weapon reticle is fully compressed, flechettes apply 250 BLEEDING Damage over 10s.`,
    wikiLinks: [`https://remnant.wiki/Merciless`],
    linkedItems: {
      mod: {
        name: 'Bloodline',
      },
    },
    damage: 13,
    rps: 8.6,
    magazine: 50,
    accuracy: 90,
    ideal: 20,
    falloff: 45,
    ammo: 250,
    crit: 10,
    weakspot: 100,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Monarch',
    imagePath: '/mainhand/monarch.png',
    dlc: 'dlc1',
    id: '76622z',
    description: `An once-beautiful weapon, rumored to corrupt its wielder with absolute power.`,
    wikiLinks: [`https://remnant.wiki/Monarch`],
    linkedItems: {
      mod: {
        name: 'Chain of Command',
      },
    },
    damage: 12,
    rps: 10.5,
    magazine: 60,
    accuracy: 95,
    ideal: 20,
    falloff: 45,
    ammo: 300,
    crit: 10,
    weakspot: 105,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Monolith',
    imagePath: '/mainhand/monolith.png',
    dlc: 'dlc2',
    id: 'WjE2nZ',
    description: `Fires concentrated sand. Sustained primary fire and Sandstorm hits apply EXPOSED for 1s. Max 15s.

    EXPOSED: Target receives 15% additional damage from all sources.`,
    wikiLinks: [`https://remnant.wiki/Monolith`],
    linkedItems: {
      mod: {
        name: 'Sandstorm',
      },
    },
    damage: 11,
    rps: 12,
    magazine: 80,
    accuracy: 95,
    ideal: 17,
    falloff: 30,
    ammo: 320,
    crit: 5,
    weakspot: 85,
    stagger: -20,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Nightfall',
    imagePath: '/mainhand/nightfall.png',
    id: '2fdvrf',
    description: `A device forged of pure evil. Fires hardened bone shards at bonus stagger. Semi-automatic with a medium kick.`,
    wikiLinks: [`https://remnant.wiki/Nightfall`],
    linkedItems: {
      mod: {
        name: 'Dreadwalker',
      },
    },
    // TODO Check this; 31 -> 28
    damage: 28,
    // TODO Check this; 4.35 -> 5.25
    rps: 5.25,
    // TODO Check this; 10 -> 13
    magazine: 13,
    accuracy: 95,
    ideal: 18,
    falloff: 50,
    // TODO Check this; 90 -> 117
    ammo: 117,
    crit: 5,
    weakspot: 105,
    stagger: 15,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Plasma Cutter',
    imagePath: '/mainhand/plasma_cutter.png',
    id: '7nwwzn',
    description: `An energy-based cutting tool that increases damage when focused on a target. Can overheat.`,
    wikiLinks: [`https://remnant.wiki/Plasma_Cutter`],
    linkedItems: {
      mod: {
        name: 'Heat Sink',
      },
    },
    damage: 7,
    rps: 13,
    magazine: 100,
    accuracy: 95,
    ideal: 17,
    falloff: 30,
    // TODO Check this; 400 -> 300
    ammo: 300,
    crit: 5,
    // TODO Check this; 75 -> 80
    weakspot: 80,
    stagger: -20,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Polygun',
    imagePath: '/mainhand/polygun.png',
    id: 'polgun',
    dlc: 'dlc2',
    description: `ERROR: Unable to load description.`,
    wikiLinks: [`https://remnant.wiki/Polygun`],
    linkedItems: {
      mod: {
        name: '77 79 68',
      },
    },
    damage: 69,
    rps: 2.15,
    magazine: 99,
    accuracy: 95,
    ideal: 26,
    falloff: 70,
    ammo: 999,
    crit: 10,
    weakspot: 110,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Pulse Rifle',
    imagePath: '/mainhand/pulse_rifle.png',
    id: 'vldebv',
    description: `An extremely accurate, high-tech pulse rifle which shoots quick three-round bursts.`,
    wikiLinks: [`https://remnant.wiki/Pulse_Rifle`],
    damage: 16,
    rps: 7.8,
    magazine: 30,
    accuracy: 75,
    ideal: 22,
    falloff: 65,
    ammo: 210,
    crit: 10,
    weakspot: 105,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Repulsor',
    imagePath: '/mainhand/repulsor1.png',
    id: 'v6zmn3',
    description: `Converted from experimental Dreamer tech, ideal for mid-range combat. Weapon becomes more accurate the longer AIM is held.`,
    wikiLinks: [`https://remnant.wiki/Repulsor`],
    linkedItems: {
      mod: {
        name: 'Banish',
      },
    },
    damage: 100,
    rps: 1.6,
    magazine: 5,
    accuracy: 95,
    ideal: 13,
    falloff: 35,
    ammo: 35,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Royal Hunting Bow',
    saveFileSlug: 'weapon_bow',
    imagePath: '/mainhand/royal_hunting_bow.png',
    id: '8ouocq',
    description: `The Postulant grants these to those who can defeat him. None know why. Some suspect that the game is mere preamble-that perhaps the true game is what its players do next.`,
    wikiLinks: [`https://remnant.wiki/Royal_Hunting_Bow`],
    damage: 80,
    // TODO Check this; 4.3 -> 5.3
    rps: 5.3,
    magazine: 1,
    accuracy: 100,
    ideal: 25,
    falloff: 65,
    ammo: 40,
    crit: 10,
    weakspot: 115,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Rusty Lever Action',
    isRusty: true,
    saveFileSlug: 'weapon_leveraction_rusty',
    imagePath: '/mainhand/rusty_lever_action.png',
    id: 'gv6yzu',
    description: `A well-worn lever-action rifle.`,
    wikiLinks: [`https://remnant.wiki/Rusty_Lever_Action`],
    damage: 55,
    rps: 1.8,
    magazine: 10,
    accuracy: 80,
    ideal: 30,
    falloff: 80,
    ammo: 60,
    crit: 0,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Sagittarius',
    imagePath: '/mainhand/sagittarius.png',
    id: 't0cb8d',
    description: `A high-powered Bow which deals bonus damage to Weakspots. Can be charged for increased effect. Perfect release after Charge for maximum damage`,
    wikiLinks: [`https://remnant.wiki/Sagittarius`],
    linkedItems: {
      mod: {
        name: 'Starfall',
      },
    },
    damage: 98,
    rps: 4.5,
    magazine: 1,
    accuracy: 100,
    ideal: 25,
    falloff: 65,
    ammo: 32,
    crit: 10,
    weakspot: 115,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Savior',
    saveFileSlug: '/weapon_savior',
    imagePath: '/mainhand/savior1.png',
    id: '2jrbvl',
    tags: ['Hardcore Reward'],
    description: `A old Fusion Rifle refactored to store and violently release energy in each shot. Can be charged for more damage. Perfect release after Charge for maximum damage.`,
    wikiLinks: [`https://remnant.wiki/Savior`],
    linkedItems: {
      mod: {
        name: 'Shatterstar',
      },
    },
    // TODO Check this; 72 -> 50
    damage: 50,
    // TODO Check this; 1.9 -> 2.1
    rps: 2.1,
    magazine: 6,
    accuracy: 95,
    ideal: 25,
    falloff: 75,
    // TODO Check this; 42 -> 36
    ammo: 36,
    crit: 10,
    weakspot: 115,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Sparkfire Shotgun',
    dlc: 'dlc1',
    saveFileSlug: 'weapon_sparkfire',
    imagePath: '/mainhand/sparkfire_shotgun.png',
    id: '3r9jm7',
    description: `Fires incendiary shells that apply BURNING which deals 30 FIRE damage over 3.0 seconds.`,
    wikiLinks: [`https://remnant.wiki/Sparkfire_Shotgun`],
    damage: 100,
    rps: 1.3,
    magazine: 7,
    accuracy: 98,
    ideal: 12,
    falloff: 30,
    ammo: 35,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Sporebloom',
    imagePath: '/mainhand/sporebloom1.png',
    id: 'q3fgj2',
    description: `An exceptionally powerful single-shot weapon that deals bonus stagger damage. Must reload after each round fired.`,
    wikiLinks: [`https://remnant.wiki/Sporebloom`],
    linkedItems: {
      mod: {
        name: 'Spore Shot',
      },
    },
    damage: 200,
    rps: 1.95,
    magazine: 1,
    accuracy: 95,
    ideal: 10,
    falloff: 25,
    ammo: 21,
    crit: 5,
    weakspot: 100,
    stagger: 20,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Starkiller',
    imagePath: '/mainhand/starkiller1.png',
    id: 'hzmyu1',
    description: `Alien rifle that shoots high velocity beams which penetrate enemies. Equipped with
    a 2.5x magnification scope. Double Tap AIM to Scope.`,
    wikiLinks: [`https://remnant.wiki/Starkiller`],
    linkedItems: {
      mod: {
        name: 'Gravity Core',
      },
    },
    damage: 80,
    rps: 1.5,
    magazine: 5,
    accuracy: 95,
    ideal: 30,
    falloff: 80,
    ammo: 40,
    crit: 5,
    weakspot: 110,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Thorn',
    saveFileSlug: '/weapon_Thorn',
    dlc: 'dlc2',
    imagePath: '/mainhand/thorn.png',
    id: '13hsqd',
    description: `Fires homing needles which deal 5 Explosive [E] Damage after sticking for 2s. When 5 needles are stuck in a target at once, BLOWBACK triggers, dealing 50 Explosive [E] Damage instead.`,
    wikiLinks: [`https://remnant.wiki/Thorn`],
    linkedItems: {
      mod: {
        name: 'Deadwood',
      },
    },
    damage: 7,
    rps: 8.85,
    magazine: 30,
    accuracy: 95,
    ideal: 19,
    falloff: 39,
    ammo: 300,
    crit: 10,
    weakspot: 100,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Twisted Arbalest',
    saveFileSlug: '/weapon_twistedarbalest',
    imagePath: '/mainhand/twisted_arbalest.png',
    id: '13hsq0',
    description: `A strange device which fires a bouncing Energy Disc that can hit up to 5 enemies in close proximity. Damage is reduced with each bounce.`,
    wikiLinks: [`https://remnant.wiki/Twisted_Arbalest`],
    linkedItems: {
      mod: {
        name: "Guardian's Call",
      },
    },
    damage: 80,
    rps: 2,
    magazine: 1,
    accuracy: 85,
    ideal: 20,
    falloff: 70,
    ammo: 22,
    crit: 5,
    weakspot: 100,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Trinity Crossbow',
    saveFileSlug: '/weapon_trinitycrossbow',
    imagePath: '/mainhand/trinity_crossbow.png',
    id: '13hsq6',
    dlc: 'dlc2',
    description: `A powerful Pan crossbow designed for mid-range combat. Fires 3 bolts at a time.`,
    wikiLinks: [`https://remnant.wiki/Trinity_Crossbow`],
    damage: 42,
    rps: 0.63,
    magazine: 18,
    accuracy: 100,
    ideal: 22,
    falloff: 65,
    ammo: 90,
    crit: 10,
    weakspot: 115,
    stagger: -65,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Widowmaker',
    saveFileSlug: 'weapon_sniperrifle',
    imagePath: '/mainhand/widowmaker.png',
    id: 'fqdvas',
    description: `A powerful single-shot sniper rifle with excellent range and pinpoint accuracy. Comes with a 3x scope. Tap SCOPE to toggle.`,
    wikiLinks: [`https://remnant.wiki/Widowmaker`],
    damage: 125,
    rps: 2.4,
    magazine: 1,
    accuracy: 95,
    ideal: 35,
    falloff: 85,
    ammo: 27,
    crit: 10,
    weakspot: 120,
    stagger: 20,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Wrangler 1860',
    saveFileSlug: 'weapon_leveraction',
    imagePath: '/mainhand/wrangler_1860.png',
    id: '5aninv',
    description: `A well-rounded lever-action rifle effective at most ranges, hampered only by a slow reload.`,
    wikiLinks: [`https://remnant.wiki/Wrangler_1860`],
    damage: 55,
    rps: 2.1,
    magazine: 10,
    accuracy: 80,
    ideal: 25,
    falloff: 70,
    // TODO Check this; reserves +10, 50 -> 60
    ammo: 60,
    crit: 10,
    weakspot: 110,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'XMG57 "Bonesaw"',
    saveFileSlug: 'weapon_lmg',
    imagePath: '/mainhand/xmg57_bonesaw.png',
    id: 'rbpz53',
    description: `An experimental infantry support weapon used for prolonged suppressive fire. High capacity, long reload, and prone to overheating. Becomes more accurate while holding down the trigger.`,
    wikiLinks: [`https://remnant.wiki/XMG57_%22Bonesaw%22`],
    damage: 12,
    rps: 9.5,
    magazine: 150,
    accuracy: 75,
    ideal: 19,
    falloff: 55,
    ammo: 300,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Abyssal Hook',
    imagePath: '/melee/abyssal_hook.png',
    dlc: 'dlc1',
    id: 'sd4nzf',
    description: `A hammer-like anchor that swings with an exceptionally irregular ferocity.`,
    wikiLinks: [`https://remnant.wiki/Abyssal_Hook`],
    linkedItems: {
      mod: {
        name: 'Fathomless Deep',
      },
    },
    damage: 101,
    crit: 6,
    weakspot: 85,
    stagger: 80,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: "Assassin's Dagger",
    imagePath: '/melee/assassins_dagger.png',
    id: 'bv9wps',
    // TODO Check this; `always deals weakspot damage from behind the enemy` - not sure how this is represented in the description
    // TODO Check this; `removed additional damage buff when attacking Bleeding targets` - not sure how this is represented in the description
    description: `Lightweight. Silent. Deadly. It's rumored that the blade is meant to bestow a slow, agonizing death.`,
    wikiLinks: [`https://remnant.wiki/Assassin%27s_Dagger`],
    linkedItems: {
      mod: {
        name: 'Bloodthirst',
      },
    },
    // TODO: Check this; base damage 41 -> 35
    damage: 35,
    crit: -3,
    weakspot: 110,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Atom Smasher',
    imagePath: '/melee/atom_smasher.png',
    id: 'lrk5hf',
    description: `A powerful crushing device that harnesses rocket technology to increase smashing force.`,
    wikiLinks: [`https://remnant.wiki/Atom_Smasher`],
    linkedItems: {
      mod: {
        name: 'Accelerator',
      },
    },
    damage: 72,
    crit: 5,
    weakspot: 95,
    stagger: 11,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Atom Splitter',
    imagePath: '/melee/atom_splitter.png',
    id: 'e7c88o',
    description: `A giant tool for splitting heavy rocks.`,
    wikiLinks: [`https://remnant.wiki/Atom_Splitter`],
    linkedItems: {
      mod: {
        name: 'Fission Strike',
      },
    },
    damage: 100,
    // TODO Check this; crit 5% -> 6%
    crit: 6,
    // TODO Check this; weakspot 90 -> 95
    weakspot: 95,
    // TODO Check this; stagger 6% -> 7%
    stagger: 7,
  },
  // This weapon appears to be unobtainable
  // {
  //   category: 'weapon',
  //   type: 'melee',
  //   name: 'Blade of Adventure',
  //   imagePath: '/melee/blade_of_adventure.png',
  //   id: '7ob842',
  // },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Blade of Gul',
    imagePath: '/melee/blade_of_gul.png',
    id: 'nxfxlp',
    description: `A short, but thick sword, used by Gul Warriors. It's compact design makes for swift yet hard-hitting blows. An excellent close-range option.`,
    wikiLinks: [`https://remnant.wiki/Blade_of_Gul`],
    damage: 57,
    crit: 4,
    weakspot: 100,
    stagger: 6,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Bone Chopper',
    imagePath: '/melee/bone_chopper.png',
    id: 'e6y7fy',
    description: `A razor-sharp hand axe. Excellent for separating flesh from bone. Charge for double attacks.`,
    wikiLinks: [`https://remnant.wiki/Bone_Chopper`],
    damage: 58,
    crit: 7,
    weakspot: 105,
    stagger: -3,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Crystal Staff',
    imagePath: '/melee/crystal_staff.png',
    id: 'CMo9vJ',
    dlc: 'dlc2',
    description: `The staff hums with energy. A destructive power within yearns to be released.`,
    damage: 58,
    crit: 5,
    weakspot: 95,
    stagger: 3,
    linkedItems: {
      mod: {
        name: 'Power Stone',
      },
    },
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Decayed Claws',
    imagePath: '/melee/decayed_claws.png',
    id: 'y1a0bu',
    description: `Makeshift claws fashioned from decayed root and rusted metal.`,
    wikiLinks: [`https://remnant.wiki/Decayed_Claws`],
    damage: 49,
    crit: 16,
    weakspot: 110,
    stagger: -4,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Dreamcatcher',
    imagePath: '/melee/dreamcatcher.png',
    id: '3sxr9y',
    description: `There is an ethereal lightness to this weapon, as though it were made of paper or breath.
    Though it strikes its foes forcibly enough.`,
    wikiLinks: [`https://remnant.wiki/Dreamcatcher`],
    linkedItems: {
      mod: {
        name: 'Dreamwave',
      },
    },
    damage: 58,
    crit: 5,
    weakspot: 95,
    stagger: 3,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Edge of the Forest',
    imagePath: '/melee/edge_of_the_forest.png',
    id: '6c7rqm',
    description: `An elegant, yet light blade, designed to bring beauty to bloodshed. Unstoppable in the hands of a master swordsman.`,
    wikiLinks: [`https://remnant.wiki/Edge_of_the_Forest`],
    damage: 59,
    crit: 9,
    weakspot: 105,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Feral Judgement',
    saveFileSlug: 'weapon_feraljudgment',
    imagePath: '/melee/feral_judgement.png',
    id: 'umb305',
    description: `A pair of gauntlets with sharp crystal blades that strike with vicious speed and velocity.`,
    wikiLinks: [`https://remnant.wiki/Feral_Judgement`],
    linkedItems: {
      mod: {
        name: 'Death Sentence',
      },
    },
    damage: 53,
    crit: 13,
    weakspot: 110,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Gas Giant',
    saveFileSlug: 'weapon_talratha_hammer',
    imagePath: '/melee/gas_giant.png',
    id: 'c58759',
    description: `Dealing damage unleashes the dormant Toxic Gas within the head. When infused, Basic Attacks apply CORRODED for 5s.`,
    wikiLinks: [`https://remnant.wiki/Gas_Giant`],
    linkedItems: {
      mod: {
        name: 'Dying Breath',
      },
    },
    damage: 74,
    crit: 3,
    weakspot: 95,
    stagger: 8,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Godsplitter',
    imagePath: '/melee/godsplitter.png',
    id: 'a23oaa',
    description: `An expertly balanced blade that is the product of advanced Fae metallurgy.`,
    wikiLinks: [`https://remnant.wiki/Godsplitter`],
    linkedItems: {
      mod: {
        name: 'Fracture',
      },
    },
    damage: 38,
    crit: 2,
    weakspot: 50,
    stagger: -20,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: "Hero's Sword",
    imagePath: '/melee/heros_sword1.png',
    id: '5o3cq4',
    description: `An ancient, quick, and versatile blade suited for many situations. Charge attacks cast a projectile for dealing melee damage at range.`,
    wikiLinks: [`https://remnant.wiki/Hero%27s_Sword`],
    linkedItems: {
      mod: {
        name: 'Energy Wave',
      },
    },
    damage: 51,
    crit: 5,
    weakspot: 90,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Huntress Spear',
    imagePath: '/melee/huntress_spear.png',
    id: '0jefkc',
    description: `A battle-worn spear worthy of the finest hunters. Charge Melee Attacks apply CORROSION dealing 600 ACID damage over 5s.`,
    wikiLinks: [`https://remnant.wiki/Huntress_Spear`],
    linkedItems: {
      mod: {
        name: 'Javelin',
      },
    },
    damage: 189,
    // TODO Check this; 6% -> 5%
    crit: 5,
    // TODO Check this; 100% -> 110%
    weakspot: 110,
    stagger: -5,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Iron Greatsword',
    imagePath: '/melee/iron_greatsword.png',
    id: '5wy88e',
    description: `A giant broadsword made from flattened railroad tracks. Dozens of ridges cut in the side for causing irreparable damage.`,
    wikiLinks: [`https://remnant.wiki/Iron_Greatsword`],
    damage: 105,
    crit: 5,
    weakspot: 95,
    stagger: 13,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Knuckle Dusters',
    imagePath: '/melee/knuckle_dusters.png',
    id: 'as4bt4',
    description: `Steel knuckles with rusty sawblade tips, designed to boost Unarmed damage.`,
    wikiLinks: [`https://remnant.wiki/Knuckle_Dusters`],
    damage: 43,
    crit: 5,
    weakspot: 110,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Krell Axe',
    imagePath: '/melee/krell_axe.png',
    id: '5gl3la',
    description: `Infused with Krell Shock magic, can be thrown if the wielder has stamina. Axe will magically reappear in-hand. Charge to throw.`,
    wikiLinks: [`https://remnant.wiki/Krell_Axe`],
    linkedItems: {
      mod: {
        name: 'Krell Edge',
      },
    },
    damage: 54,
    crit: 3,
    weakspot: 85,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Labyrinth Staff',
    imagePath: '/melee/labyrinth_staff.png',
    id: 'gts5dh',
    description: `Basic Strikes generate 10% additional Mod Power. Charge Attacks perform an AOE which strikes all enemies within 2m [A], dealing 75 Damage. AOE Damage generates 50% additional Mod Power.`,
    wikiLinks: [`https://remnant.wiki/Labyrinth_Staff`],
    damage: 64,
    crit: 8,
    weakspot: 95,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Mirage',
    imagePath: '/melee/mirage.png',
    dlc: 'dlc2',
    id: '6j7c6k',
    description: `The mace whirs as if living harmonics hold its shape. When swung, a breath of sand tethers to the rock crown for extended reach and lethal momentum.`,
    wikiLinks: [`https://remnant.wiki/Mirage`],
    linkedItems: {
      mod: {
        name: 'Cyclone',
      },
    },
    damage: 56,
    crit: 3,
    weakspot: 100,
    stagger: -5,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Nightshade',
    imagePath: '/melee/nightshade.png',
    id: '6j7czk',
    description: `Fast striking claws with a high Critical Hit Chance.
    Neutral Dodge grants the power  of Lifesteal.`,
    wikiLinks: [`https://remnant.wiki/Nightshade`],
    linkedItems: {
      mod: {
        name: 'Beyond the Veil',
      },
    },
    damage: 47,
    crit: 18,
    weakspot: 110,
    stagger: -20,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Ornate Blade',
    imagePath: '/melee/ornate_blade.png',
    id: '0wto7p',
    description: `An intricately-forged elongated sword. Designed to keep stronger enemies at bay, while remaining light enough for agile maneuvers.`,
    wikiLinks: [`https://remnant.wiki/Ornate_Blade`],
    damage: 52,
    crit: 11,
    weakspot: 105,
    stagger: -5,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Ornate Flail',
    imagePath: '/melee/ornate_flail.png',
    id: 'pwuhho',
    description: `An intricately-forged mace with uniquely designed airways. Allows smaller wielders to get the mace up to speed much quicker.`,
    wikiLinks: [`https://remnant.wiki/Ornate_Flail`],
    damage: 63,
    crit: 11,
    weakspot: 100,
    stagger: -3,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Rebellion Spear',
    imagePath: '/melee/rebellion_spear.png',
    id: 'qy94qr',
    description: `A spear perfect for staying at a distance. Has excellent range, great recovery, and focused direct damage for one on one combat.`,
    wikiLinks: [`https://remnant.wiki/Rebellion_Spear`],
    damage: 60,
    crit: 13,
    weakspot: 110,
    stagger: 2,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Red Doe Staff',
    imagePath: '/melee/red_doe_staff.png',
    id: 'oazjm0',
    description: `A magical stave rumored to contain a healing spirit within. Strikes with wide swings.`,
    wikiLinks: [`https://remnant.wiki/Red_Doe_Staff`],
    linkedItems: {
      mod: {
        name: 'Lifeline',
      },
    },
    damage: 62,
    crit: 3,
    weakspot: 95,
    stagger: 8,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Ritualist Scythe',
    dlc: 'dlc1',
    imagePath: '/melee/ritualist_scythe.png',
    id: '7hoogs',
    description: `An evil-fueled reaping tool that deals additional damage to suffering targets`,
    wikiLinks: [`https://remnant.wiki/Ritualist_Scythe`],
    linkedItems: {
      mod: {
        name: 'Reaver',
      },
    },
    damage: 51,
    crit: 5,
    weakspot: 100,
    stagger: -19,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Royal Broadsword',
    imagePath: '/melee/royal_broadsword.png',
    id: 'wogdou',
    description: `Standard issue Greatsword for the Empress's Royal Guards. Razor-sharp edges, extremely heavy, yet perfectly balanced.`,
    wikiLinks: [`https://remnant.wiki/Royal_Broadsword`],
    damage: 102,
    crit: 7,
    weakspot: 95,
    stagger: 11,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Rusted Claws',
    imagePath: '/melee/rusted_claws.png',
    id: '6odjqi',
    description: `A pair of old-canine training bracers converted into deadly claws. Used for slashing and ripping.`,
    wikiLinks: [`https://remnant.wiki/Rusted_Claws`],
    damage: 51,
    crit: 14,
    weakspot: 110,
    stagger: -9,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Scrap Hammer',
    saveFileSlug: 'weapon_hammer',
    imagePath: '/melee/scrap_hammer.png',
    id: 'a88cg7',
    description: `A large, heavy warhammer cobbled together from engine components. It is a slow- but-devastating weapon meant to destroy anything it hits.`,
    wikiLinks: [`https://remnant.wiki/Scrap_Hammer`],
    damage: 83,
    crit: 8,
    weakspot: 95,
    stagger: 9,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Scrap Hatchet',
    saveFileSlug: 'weapon_hatchet',
    imagePath: '/melee/scrap_hatchet.png',
    id: 'wtj6mq',
    description: `A common chopping tool that has been repurposed for combat. Rapidly cycles attacks from right to left. Charge attacks strike twice.`,
    wikiLinks: [`https://remnant.wiki/Scrap_Hatchet`],
    damage: 57,
    crit: 6,
    weakspot: 105,
    stagger: 1,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Scrap Staff',
    saveFileSlug: 'weapon_staff',
    imagePath: '/melee/scrap_staff.png',
    id: 'fp5yi4',
    description: `A staff made from old plumbing parts used for controlling wide swaths in front of the wielder.`,
    wikiLinks: [`https://remnant.wiki/Scrap_Staff`],
    damage: 65,
    crit: 6,
    weakspot: 95,
    stagger: 8,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Shovel',
    imagePath: '/melee/shovel.png',
    id: 'vpEWS5',
    dlc: 'dlc2',
    description: `It's a shovel.`,
    wikiLinks: [`https://remnant.wiki/Shovel`],
    damage: 55,
    crit: 15,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Smolder',
    imagePath: '/melee/smolder1.png',
    id: 'd0usz6',
    description: `A scorched blade imbued with FIRE.`,
    wikiLinks: [`https://remnant.wiki/Smolder`],
    linkedItems: {
      mod: {
        name: 'Blaze',
      },
    },
    damage: 46,
    crit: 4,
    weakspot: 95,
    stagger: 1,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Spectral Blade',
    imagePath: '/melee/spectral_blade.png',
    id: 'l3zte1',
    description: `A super-heated laser sword with an infinitely sharp edge. Perfect for cutting... anything.`,
    wikiLinks: [`https://remnant.wiki/Spectral_Blade`],
    linkedItems: {
      mod: {
        name: 'Whirlwind',
      },
    },
    damage: 159,
    crit: 8,
    weakspot: 105,
    stagger: -25,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Steel Flail',
    saveFileSlug: 'weapon_flail',
    imagePath: '/melee/steel_flail.png',
    id: 'ji6tpl',
    description: `An unorthodox weapon meant to convert momentum into destruction. Some attacks can continuously chain overhead swings.`,
    wikiLinks: [`https://remnant.wiki/Steel_Flail`],
    damage: 69,
    crit: 4,
    weakspot: 100,
    stagger: 6,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Steel Katana',
    saveFileSlug: 'weapon_katana',
    imagePath: '/melee/steel_katana.png',
    id: '0cnwdx',
    description: `An old piece of steel with serrations cut into one side. Pipe handle provides limited grip.`,
    wikiLinks: [`https://remnant.wiki/Steel_Katana`],
    damage: 56,
    crit: 10,
    weakspot: 105,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Steel Scythe',
    saveFileSlug: 'weapon_scythe',
    imagePath: '/melee/steel_scythe.png',
    id: '2po1q8',
    description: `A ruthless threshing device.`,
    wikiLinks: [`https://remnant.wiki/Steel_Scythe`],
    damage: 55,
    crit: 10,
    weakspot: 100,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Steel Spear',
    saveFileSlug: 'weapon_spear',
    imagePath: '/melee/steel_spear.png',
    id: 'vbzlfk',
    description: `A spear perfect for staying at range with quick, focused attacks. High, single-target damage.`,
    wikiLinks: [`https://remnant.wiki/Steel_Spear`],
    damage: 61,
    crit: 9,
    weakspot: 110,
    stagger: -4,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Steel Sword',
    saveFileSlug: 'weapon_sword',
    imagePath: '/melee/steel_sword.png',
    id: 'zsb5g1',
    description: `A long, sharp blade hammered out of vehicle leaf springs. Well-rounded for most situations.`,
    wikiLinks: [`https://remnant.wiki/Steel_Sword`],
    damage: 56,
    crit: 7,
    weakspot: 100,
    stagger: 2,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Stonebreaker',
    imagePath: '/melee/stonebreaker.png',
    id: 'b4g4q0',
    // TODO Check this; `removed Double Damage Stacking on Charge Attacks` - not sure how this is represented in the description
    description: `A massive Greatsword which contains the harnessed magic of a corrupted Guardian. Can summon small shockwaves.`,
    wikiLinks: [`https://remnant.wiki/Stonebreaker`],
    linkedItems: {
      mod: {
        name: 'Faultline',
      },
    },
    damage: 103,
    crit: 4,
    weakspot: 95,
    // TODO Check this; `reduced Impact Scalar from 10% to 5%`
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Vice Grips',
    imagePath: '/melee/vice_grips.png',
    id: 'ygwrpd',
    description: `A N'Erudian tool converted into a ruthless ripping device. High raw damage.`,
    wikiLinks: [`https://remnant.wiki/Vice_Grips`],
    damage: 55,
    crit: 6,
    weakspot: 110,
    stagger: -18,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: "World's Edge",
    imagePath: '/melee/worlds_edge1.png',
    id: 'gilcfn',
    // TODO Check this; `reduced base damage on Wave` - not sure how this is represented in the description
    description: `A glowing Greatsword forged from shards of a shattered Worldstone. Charge attacks cast waves.`,
    wikiLinks: [`https://remnant.wiki/World%27s_Edge`],
    linkedItems: {
      mod: {
        name: 'Horizon Strike',
      },
    },
    damage: 101,
    // TODO Check this; `reduced critical chance from 6% to 3%`
    crit: 3,
    weakspot: 85,
    // TODO Check this; `reduced abnormally high impact/stagger scalar`, no numbers though
    stagger: 80,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Wrathbringer',
    dlc: 'dlc1',
    imagePath: '/melee/wrathbringer.png',
    id: 'mq5fnr',
    description: `A massive hammer infused with the souls of deceased Dran. Its dormant power can be awakened by taking damage.`,
    wikiLinks: [`https://remnant.wiki/Wrathbringer`],
    linkedItems: {
      mod: {
        name: 'Awakening',
      },
    },
    damage: 101,
    crit: 6,
    weakspot: 85,
    stagger: 80,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Anguish',
    imagePath: '/offhand/anguish.png',
    dlc: 'dlc1',
    id: 'r2o474',
    description: `Fires heated bits of molten slag. Can be charged to fire a single explosive rod [E] at the cost of causing damage to the wielder while charging.`,
    wikiLinks: [`https://remnant.wiki/Anguish`],
    linkedItems: {
      mod: {
        name: 'Loathe the Weak',
      },
    },
    damage: 92,
    rps: 1.7,
    magazine: 5,
    accuracy: 95,
    ideal: 16,
    falloff: 35,
    ammo: 35,
    crit: 5,
    weakspot: 100,
    stagger: 0,
  },
  // TODO Check this; `incrased fire rate from 3.5 to 3.65` - not sure how this is represented in the data
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Bolt Driver',
    imagePath: '/offhand/bolt_driver.png',
    id: 'd388ma',
    description: `An ingenius Gul rifle designed to harness energy from Pan crystals. Charge to fire a 3-shot burst`,
    wikiLinks: [`https://remnant.wiki/Bolt_Driver`],
    damage: 26,
    // TODO Check this; 7.4 -> 7.63
    rps: 7.63,
    magazine: 24,
    accuracy: 99,
    ideal: 17,
    falloff: 52,
    ammo: 96,
    crit: 10,
    weakspot: 105,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Corrupted Cube Gun',
    imagePath: '/offhand/corrupted_cube_gun.png',
    id: 'mSSxW6',
    description: `Fusion charged auto-cannon generates cubes which penetrate. Infininte ammo capacity. Can overheat. Cannot score weakspot hits.`,
    wikiLinks: ['https://remnant.wiki/Corrupted_Cube_Gun'],
    damage: 66,
    rps: 2.2,
    magazine: 99,
    accuracy: 95,
    ideal: 15,
    falloff: 35,
    ammo: 105,
    crit: 5,
    weakspot: 0,
    stagger: 0,
    linkedItems: {
      mod: {
        name: 'Cube Room',
      },
    },
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Corrupted Meridian',
    imagePath: '/offhand/corrupted_meridian1.png',
    id: 'yw1btj',
    description: `Fires rocket that deals AOE damage [E] within 2m. [A] Charging the weapon can load additional rockets.  (Max 3). Cannot Weakspot`,
    wikiLinks: [`https://remnant.wiki/Corrupted_Meridian`],
    linkedItems: {
      mod: {
        name: 'Deadpoint',
      },
    },
    damage: 90,
    rps: 1.9,
    magazine: 6,
    accuracy: 98,
    ideal: 15,
    falloff: 30,
    ammo: 36,
    crit: 0,
    weakspot: 0,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Corrupted Nebula',
    imagePath: '/offhand/corrupted_nebula.png',
    id: '8u8j4G',
    description: `Semi-automatic laser weapon. Weakspot hits and kills create a Nano-bot for 8s that seeks enemies within 20m and repeatedly attacks dealing 6-12 ACID damage per hit. Max 5 Nano-bots.`,
    wikiLinks: ['https://remnant.wiki/Corrupted_Nebula'],
    linkedItems: {
      mod: {
        name: 'Nano Phase',
      },
    },
    damage: 24,
    rps: 5.2,
    magazine: 15,
    accuracy: 95,
    ideal: 17,
    falloff: 56,
    ammo: 105,
    crit: 5,
    weakspot: 105,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Corrupted Rune Pistol',
    imagePath: '/offhand/corrupted_rune_pistol1.png',
    id: 'id5pbt',
    description: `A pistol infused with erroneous properties. Fires energy, allowing the trigger to be held for continuous fire.`,
    wikiLinks: [`https://remnant.wiki/Corrupted_Rune_Pistol`],
    linkedItems: {
      mod: {
        name: 'Death Brand',
      },
    },
    // TODO Check this; 16 -> 17
    damage: 17,
    rps: 6.3,
    magazine: 25,
    accuracy: 95,
    ideal: 17,
    falloff: 53,
    ammo: 150,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Corrupted Sorrow',
    id: 'zrP64k',
    imagePath: '/offhand/corrupted_sorrow.png',
    description:
      'Innately cannot harm allies. Fires bolts which anchor to targets for 6s. Max 10 bolts anchored at once.',
    linkedItems: {
      mod: {
        name: 'Will of the Wisp',
      },
    },
    wikiLinks: ['https://remnant.wiki/Corrupted_Sorrow'],
    damage: 42,
    // TODO Check this; 2.3 -> 2.6
    rps: 2.6,
    magazine: 10,
    accuracy: 95,
    ideal: 17,
    falloff: 52,
    ammo: 60,
    crit: 7.5,
    weakspot: 105,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Cube Gun',
    saveFileSlug: '/weapon_cubegun',
    imagePath: '/offhand/cube_gun.png',
    id: 'zn3boo',
    description: `Projectiles return on hit or after reaching max range. Reloading retrieves shot projectiles. Max 5 fired projectiles. Infinite Ammo. Can overheat.`,
    wikiLinks: [`https://remnant.wiki/Cube_Gun`],
    linkedItems: {
      mod: {
        name: 'Cube Shield',
      },
    },
    damage: 15,
    rps: 7.5,
    magazine: 5,
    accuracy: 90,
    ideal: 20,
    falloff: 50,
    ammo: 105,
    crit: 5,
    weakspot: 85,
    stagger: 0,
  },
  // TODO Check this; `slightly reduced reload speed (~5%)` - not sure how this is represented in our data
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Double Barrel',
    saveFileSlug: 'weapon_shortbarrel',
    imagePath: '/offhand/double_barrel.png',
    id: 'ztz84h',
    description: `A double barrel shotgun which can deal massive damage at close range with back to back shots.`,
    wikiLinks: [`https://remnant.wiki/Double_Barrel`],
    // TODO Check this; 110 -> 105
    damage: 105,
    // TODO Check this; 2.3 -> 2.25
    rps: 2.25,
    magazine: 2,
    accuracy: 60,
    // TODO Check this; maximum falloff 7m -> 8m
    ideal: 8,
    falloff: 20,
    ammo: 24,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Enigma',
    imagePath: '/offhand/enigma.png',
    id: 'd06hjq',
    description: `Fires an electrical stream that jumps to nearby targets within 7.5m [A], dealing 30% reduced damage per jump. Applies OVERLOADED, dealing 30 SHOCK damage every 5 seconds for 5.2s.`,
    wikiLinks: [`https://remnant.wiki/Enigma`],
    linkedItems: {
      mod: {
        name: 'Chaos Driver',
      },
    },
    damage: 22,
    rps: 4,
    magazine: 25,
    accuracy: 60,
    ideal: 12,
    falloff: 12,
    ammo: 125,
    crit: -10,
    weakspot: 0,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Hellfire',
    imagePath: '/offhand/hellfire.png',
    id: '797iqq',
    description: `Spews flames that apply BURNING which deals 300 FIRE damage over 10 seconds.`,
    wikiLinks: [`https://remnant.wiki/Hellfire`],
    linkedItems: {
      mod: {
        name: 'Explosive Shot',
      },
    },
    damage: 13,
    rps: 6,
    magazine: 60,
    accuracy: 15,
    ideal: 8,
    falloff: 8,
    ammo: 180,
    crit: 0,
    weakspot: 0,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Meridian',
    saveFileSlug: '/weapon_meridian',
    imagePath: '/offhand/meridian.png',
    id: '1ziutf',
    description: `Fires volatile grenades that explode [E] on direct contact with enemies and deal AOE damage within 4m. [A] Dormant grenades eventually explode and can also be shot to detonate early.`,
    wikiLinks: [`https://remnant.wiki/Meridian`],
    linkedItems: {
      mod: {
        name: 'Screamer',
      },
    },
    damage: 82,
    rps: 1.9,
    magazine: 5,
    accuracy: 100,
    ideal: 15,
    falloff: 30,
    ammo: 40,
    crit: 0,
    weakspot: 0,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'MP60-R',
    imagePath: '/offhand/mp60_r.png',
    id: 'ty2gsi',
    description: `A small-caliber submachine gun best suited for close range skirmishes.`,
    wikiLinks: [`https://remnant.wiki/MP60-R`],
    damage: 9,
    rps: 14.2,
    magazine: 42,
    accuracy: 95,
    ideal: 17,
    falloff: 50,
    // TODO Check this; `increased reserves by 42 (+1 Magazine)`
    ammo: 294,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Nebula',
    saveFileSlug: '/weapon_nebula',
    imagePath: '/offhand/nebula.png',
    id: 'p7tsxr',
    description: `Fires a stream of superhot ACID gas which applies the CORRODED effect, dealing 300 CORROSIVE Damage over 15s. Killing targets CORRODED by Nebula spawns a gas cloud which applies its on-hit effect. Gas clouds last 2s and can be refreshed.`,
    wikiLinks: [`https://remnant.wiki/Nebula`],
    linkedItems: {
      mod: {
        name: 'Nano Swarm',
      },
    },
    damage: 12,
    rps: 8,
    magazine: 55,
    accuracy: 15,
    ideal: 8,
    falloff: 8,
    ammo: 220,
    crit: 0,
    weakspot: 0,
    stagger: -15,
  },
  // TODO Check this; `fire rate from 7.5 to 8.1` - not sure how this is represented in our stats
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Repeater Pistol',
    saveFileSlug: 'weapon_repeater',
    imagePath: '/offhand/repeater_pistol.png',
    id: 'pbtmmj',
    description: `An accurate semi-automatic pistol that can rapidly fire small-caliber bullets.`,
    wikiLinks: [`https://remnant.wiki/Repeater_Pistol`],
    damage: 15,
    rps: 7.5,
    // TODO Check this; 15 -> 20
    magazine: 20,
    accuracy: 95,
    ideal: 18,
    falloff: 52,
    ammo: 150,
    crit: 5,
    weakspot: 105,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Rune Pistol',
    saveFileSlug: '/weapon_runepistol',
    imagePath: '/offhand/rune_pistol.png',
    id: '2pblgq',
    description: `A pistol infused with mysterious Fae magic. Rapidly fires 3-round bursts of energy. Trigger can be held to continuously fire.`,
    wikiLinks: [`https://remnant.wiki/Rune_Pistol`],
    linkedItems: {
      mod: {
        name: 'Soul Brand',
      },
    },
    // TODO Check this; 15 -> 16
    damage: 16,
    rps: 6.6,
    magazine: 42,
    accuracy: 95,
    ideal: 18,
    falloff: 53,
    ammo: 168,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Rupture Cannon',
    imagePath: '/offhand/rupture_cannon.png',
    id: 'xzlpao',
    description: `A mid-range Pistol Shotgun with a brisk fire rate and medium recoil Slower reload.`,
    wikiLinks: [`https://remnant.wiki/Rupture_Cannon`],
    location: { world: `N'Erud`, dungeon: [`Vault of the Formless`] },
    damage: 42,
    // TODO Check this; 3.1 -> 2.75
    rps: 2.75,
    magazine: 12,
    accuracy: 90,
    // TODO Check this; 13m -> 14m
    ideal: 14,
    falloff: 35,
    ammo: 60,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Rusty Repeater',
    isRusty: true,
    saveFileSlug: 'weapon_repeater_rusty',
    imagePath: '/offhand/rusty_repeater1.png',
    id: 't412us',
    description: `An old antique pistol.`,
    wikiLinks: [`https://remnant.wiki/Rusty_Repeater`],
    damage: 15,
    rps: 7.2,
    magazine: 15,
    accuracy: 95,
    ideal: 17,
    falloff: 55,
    ammo: 180,
    crit: 0,
    weakspot: 100,
    stagger: -10,
  },
  // TODO Check this; `increased reload speed` - not sure how this is represented in our data
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Service Pistol',
    imagePath: '/offhand/service_pistol.png',
    id: 'g34ywl',
    description: `A standard issue military spec sidearm known for its reliability and accuracy.`,
    wikiLinks: [`https://remnant.wiki/Service_Pistol`],
    damage: 24,
    rps: 6.5,
    // TODO Check this; 9 -> 10
    magazine: 10,
    accuracy: 85,
    ideal: 20,
    falloff: 50,
    ammo: 90,
    crit: 5,
    weakspot: 105,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Silverback Model 500',
    saveFileSlug: 'weapon_magnum',
    imagePath: '/offhand/silverback_model_500.png',
    id: '46cwa6',
    description: `A powerful hand cannon with a low capacity cylinder. High damage and a heavy kick.`,
    wikiLinks: [`https://remnant.wiki/Silverback_Model_500`],
    damage: 55,
    rps: 2.4,
    // TODO Check this; `increased cylinder capacity from 5 to 6`
    magazine: 6,
    accuracy: 95,
    ideal: 20,
    falloff: 60,
    // TODO Check this; `incrased total ammo from 45 to 48`
    ammo: 48,
    crit: 5,
    weakspot: 105,
    stagger: 20,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Sorrow',
    saveFileSlug: '/weapon_sorrow',
    imagePath: '/offhand/sorrow.png',
    id: 'u2z8i3',
    description: `The last vestiges of a fallen sister, this mystical crossbow pistol has the ability to recall its bolts to heal the wielder.`,
    wikiLinks: [`https://remnant.wiki/Sorrow`],
    linkedItems: {
      mod: {
        name: 'Eulogy',
      },
    },
    damage: 45,
    rps: 2.6,
    magazine: 5,
    accuracy: 95,
    ideal: 16,
    falloff: 52,
    ammo: 45,
    crit: 10,
    weakspot: 115,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Star Shot',
    imagePath: '/offhand/star_shot.png',
    id: 'tldnuq',
    description: `Fires a fast moving projectile which explodes [E] on contact. Explosion has no damage falloff. [A]`,
    wikiLinks: [`https://remnant.wiki/Star_Shot`],
    linkedItems: {
      mod: {
        name: 'Big Bang',
      },
    },
    damage: 22,
    rps: 2.5,
    magazine: 10,
    accuracy: 95,
    ideal: 21,
    falloff: 54,
    ammo: 60,
    crit: 5,
    weakspot: 110,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Sureshot',
    saveFileSlug: 'weapon_huntingpistol',
    imagePath: '/offhand/sureshot.png',
    id: '50i9nj',
    description: `A high-caliber single-shot hunting pistol that inflicts heavy damage at mid to long range.`,
    wikiLinks: [`https://remnant.wiki/Sureshot`],
    damage: 110,
    rps: 3,
    magazine: 1,
    accuracy: 80,
    ideal: 22,
    falloff: 75,
    ammo: 24,
    crit: 10,
    weakspot: 110,
    stagger: 10,
  },
  // TODO Check this; `increased reload speed` - not sure how this is represented in our data
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Tech 22',
    imagePath: '/offhand/tech_22.png',
    id: 'xj5syj',
    description: `A suppressed small-caliber automatic pistol with medium magazine capacity and a high fire rate.`,
    wikiLinks: [`https://remnant.wiki/Tech_22`],
    damage: 8,
    rps: 16,
    magazine: 30,
    accuracy: 95,
    ideal: 15,
    falloff: 45,
    // TODO Check this; `increased reserves by 60 (+2 Magazines)`
    ammo: 330,
    crit: 10,
    weakspot: 100,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Western Classic',
    saveFileSlug: 'weapon_revolver',
    imagePath: '/offhand/western_classic.png',
    id: 'hk5uls',
    description: `A classic six-shooter. Tough. Dependable.`,
    wikiLinks: [`https://remnant.wiki/Western_Classic`],
    damage: 36,
    rps: 5.75,
    magazine: 6,
    accuracy: 95,
    ideal: 18,
    falloff: 48,
    ammo: 72,
    crit: 5,
    weakspot: 105,
    stagger: 5,
  },
]
