import { WeaponItem } from './types/WeaponItem'

export const weaponItems: WeaponItem[] = [
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Alpha / Omega',
    imagePath: '/items/weapons/alphaomega.png',
    id: '1ub6k9',
    dlc: 'base',
    description:
      'Charge shot fires a burst of five energy bolts. Each hit reduces charge time by 0.1s and increases damage by 10% for 1.5s. Stacks 5x.',
    wikiLinks: [`https://remnant.wiki/Alpha_/_Omega`],
    location: { world: 'Root Earth', dungeon: ['Blackened Citadel'] },
    linkedItems: {
      mod: {
        name: 'Beta Ray',
      },
    },
    damage: 14,
    rps: 6.89,
    magazine: 55,
    accuracy: 95,
    ideal: 24,
    falloff: 70,
    ammo: 275,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Aphelion',
    saveFileSlug: '/weapon_aphelion',
    imagePath: '/items/weapons/aphelion.png',
    id: '3wprfw',
    dlc: 'base',
    description: `Fires a hypercharged wide-arching line that passes through targets.`,
    wikiLinks: [`https://remnant.wiki/Aphelion`],
    linkedItems: {
      mod: {
        name: 'Supernova',
      },
    },
    damage: 62,
    rps: 2,
    magazine: 7,
    accuracy: 95,
    ideal: 20,
    falloff: 65,
    ammo: 49,
    crit: 10,
    weakspot: 100,
    stagger: -25,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'AS-10 "Bulldog"',
    saveFileSlug: 'weapon_autoshotgun',
    imagePath: '/items/weapons/bulldog.png',
    id: 'va7cfd',
    dlc: 'base',
    description: `A brutal drum-fed fully-automatic 10 gauge shotgun designed for close-quarters combat.`,
    wikiLinks: [`https://remnant.wiki/AS-10_"Bulldog"`],
    damage: 60,
    rps: 2.5,
    magazine: 12,
    accuracy: 60,
    ideal: 10,
    falloff: 32,
    ammo: 60,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Blackmaw AR-47',
    saveFileSlug: 'weapon_assaultrifle',
    imagePath: '/items/weapons/blackmawar47.png',
    id: 'phh1xe',
    dlc: 'base',
    description: `A fully automatic rifle with a medium capacity. Highly effective with controlled bursts.`,
    wikiLinks: [`https://remnant.wiki/Blackmaw_AR-47`],
    damage: 17,
    rps: 7.3,
    magazine: 38,
    accuracy: 95,
    ideal: 20,
    falloff: 60,
    ammo: 190,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Chicago Typewriter',
    saveFileSlug: 'weapon_tommygun',
    imagePath: '/items/weapons/tommygun.png',
    id: '59oddb',
    dlc: 'base',
    description: `A classic Tommy Gun with large ammo capacity and a slow reload. Poor initial accuracy which improves while holding down the trigger.`,
    wikiLinks: [`https://remnant.wiki/Chicago_Typewriter`],
    damage: 10,
    rps: 11,
    magazine: 80,
    accuracy: 80,
    ideal: 17,
    falloff: 55,
    ammo: 320,
    crit: 10,
    weakspot: 105,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Coach Gun',
    imagePath: '/items/weapons/coachgun.png',
    id: 'i0hvy8',
    dlc: 'base',
    description: `A double-barrel over/under shotgun modified to fire powerful slugs. High damage with a decent fire rate, but very low magazine capacity.`,
    wikiLinks: [`https://remnant.wiki/Coach_Gun`],
    damage: 115,
    rps: 2.3,
    magazine: 2,
    accuracy: 95,
    ideal: 15,
    falloff: 33,
    ammo: 28,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Corrupted Aphelion',
    imagePath: '/items/weapons/corruptedaphelion.png',
    id: 'w85ya8',
    dlc: 'base',
    description: `A laser shotgun that fires three hypercharged arc lines that penetrate targets.`,
    wikiLinks: [`https://remnant.wiki/Corrupted_Aphelion`],
    linkedItems: {
      mod: {
        name: 'Micronova',
      },
    },
    damage: 33,
    rps: 1.45,
    magazine: 8,
    accuracy: 95,
    ideal: 15,
    falloff: 40,
    ammo: 40,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Corrupted Arbalest',
    imagePath: '/items/weapons/corruptedarbalest.png',
    saveFileSlug: 'corruptedtwistedarbalest',
    id: 'Gkemt8',
    dlc: 'base',
    description: `Fully automatic mechanisms launch a bouncing Energy Disc that can hit up to 2 enemies in close proximity. Damage is reduced after bouncing.`,
    damage: 69,
    rps: 1.3,
    magazine: 8,
    accuracy: 95,
    ideal: 20,
    falloff: 70,
    ammo: 40,
    crit: 5,
    weakspot: 100,
    stagger: 0,
    wikiLinks: ['https://remnant.wiki/Corrupted_Arbalest'],
    linkedItems: {
      mod: {
        name: `Guardian's Fury`,
      },
    },
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Corrupted Deceit',
    imagePath: '/items/weapons/corrupteddeceit.png',
    id: 'k9w4yh',
    dlc: 'base',
    description: `A pinpoint accurate split-barreled rifle that fires two penetrating rails. High base damage, but cannot score Weakspot hits. Charge to fire.`,
    wikiLinks: [`https://remnant.wiki/Corrupted_Deceit`],
    linkedItems: {
      mod: {
        name: 'Windfall',
      },
    },
    damage: 66,
    rps: 3,
    magazine: 12,
    accuracy: 95,
    ideal: 26,
    falloff: 75,
    ammo: 48,
    crit: 10,
    weakspot: 90,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Corrupted Merciless',
    imagePath: '/items/weapons/corruptedmerciless.png',
    id: '8i85za',
    dlc: 'base',
    description: `Fires high-powered nails. Limited magazine size.`,
    wikiLinks: [`https://remnant.wiki/Corrupted_Merciless`],
    linkedItems: {
      mod: {
        name: 'Bloodshot',
      },
    },
    damage: 90,
    rps: 1.7,
    magazine: 3,
    accuracy: 90,
    ideal: 25,
    falloff: 70,
    ammo: 36,
    crit: 5,
    weakspot: 105,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Corrupted Savior',
    imagePath: '/items/weapons/corruptedsavior.png',
    id: 'W6n2mT',
    dlc: 'base',
    tags: ['Hardcore Reward'],
    description: `A Black Crystal weapon which gains increased Fire Rate as Mod Power is generated. Mod power drains after 3s of not dealing damage.`,
    wikiLinks: ['https://remnant.wiki/Corrupted_Savior'],
    linkedItems: {
      mod: {
        name: 'Fusion Cannon',
      },
    },
    damage: 17,
    rps: 3.15,
    magazine: 40,
    accuracy: 95,
    ideal: 20,
    falloff: 60,
    ammo: 200,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Crescent Moon',
    imagePath: '/items/weapons/crescentmoon.png',
    id: 'p7wc7k',
    dlc: 'base',
    description:
      'An ethereal weapon that seems to resonate.\n' +
      '\n' +
      'Can be charged for more damage. Perfect release after Charge for maximum damage.',
    wikiLinks: [`https://remnant.wiki/Crescent_Moon`],
    linkedItems: {
      mod: {
        name: 'Moonlight Barrage',
      },
    },
    damage: 87,
    rps: 4.1,
    magazine: 1,
    accuracy: 100,
    ideal: 25,
    falloff: 65,
    ammo: 38,
    crit: 5,
    weakspot: 70,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Crossbow',
    imagePath: '/items/weapons/crossbow.png',
    id: 'x94ze2',
    dlc: 'base',
    description: `An accurate and deadly single-shot crossbow with a low sound profile.`,
    wikiLinks: [`https://remnant.wiki/Crossbow`],
    damage: 120,
    rps: 2.5,
    magazine: 1,
    accuracy: 100,
    ideal: 23,
    falloff: 70,
    ammo: 27,
    crit: 10,
    weakspot: 120,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Deceit',
    saveFileSlug: '/weapon_deceit',
    imagePath: '/items/weapons/deceit.png',
    id: 'hlmpjl',
    dlc: 'base',
    description: `A pinpoint accurate split-barreled rifle that fires two penetrating rails. High base damage, but cannot score Weakspot hits. Charge to fire.`,
    wikiLinks: [`https://remnant.wiki/Deceit`],
    linkedItems: {
      mod: {
        name: 'Ouroboros',
      },
    },
    damage: 120,
    rps: 2,
    magazine: 6,
    accuracy: 95,
    ideal: 28,
    falloff: 75,
    ammo: 30,
    crit: 15,
    weakspot: 90,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: "Ford's Scattergun",
    saveFileSlug: 'weapon_shotgun',
    imagePath: '/items/weapons/shotgun.png',
    id: '8n3e07',
    dlc: 'base',
    description: `An incredibly powerful 12 gauge shotgun with a wide spread. High damage, slow reload.`,
    wikiLinks: [`https://remnant.wiki/Ford's_Scattergun`],
    damage: 130,
    rps: 1.1,
    magazine: 7,
    accuracy: 95,
    ideal: 10,
    falloff: 35,
    ammo: 28,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Huntmaster M1',
    saveFileSlug: 'weapon_huntmaster',
    imagePath: '/items/weapons/huntmaster.png',
    id: 'cda7lb',
    dlc: 'base',
    description: `A high-powered long range bolt-action rifle with exceptional accuracy and a 2.5x magnification scope.`,
    wikiLinks: [`https://remnant.wiki/Huntmaster_M1`],
    damage: 70,
    rps: 1.5,
    magazine: 7,
    accuracy: 95,
    ideal: 27,
    falloff: 75,
    ammo: 49,
    crit: 5,
    weakspot: 110,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Merciless',
    saveFileSlug: '/weapon_merciless',
    imagePath: '/items/weapons/merciless.png',
    id: 'g3esv1',
    dlc: 'base',
    description: `Fires tooth-like flechettes. When weapon reticle is fully compressed, flechettes apply 200 - 600 BLEEDING damage over 10s.`,
    wikiLinks: [`https://remnant.wiki/Merciless`],
    linkedItems: {
      mod: {
        name: 'Bloodline',
      },
    },
    damage: 13,
    rps: 8.6,
    magazine: 50,
    accuracy: 90,
    ideal: 20,
    falloff: 45,
    ammo: 250,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Monarch',
    imagePath: '/items/weapons/monarch.png',
    dlc: 'dlc1',
    id: '76622z',
    description: `An once-beautiful weapon, rumored to corrupt its wielder with absolute power.`,
    wikiLinks: [`https://remnant.wiki/Monarch`],
    linkedItems: {
      mod: {
        name: 'Chain of Command',
      },
    },
    damage: 12,
    rps: 10.5,
    magazine: 60,
    accuracy: 95,
    ideal: 20,
    falloff: 45,
    ammo: 300,
    crit: 10,
    weakspot: 105,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Monolith',
    imagePath: '/items/weapons/monolith.png',
    dlc: 'dlc2',
    id: 'WjE2nZ',
    description:
      'Fires concentrated sand. Sustained primary fire and Sandstorm hits apply EXPOSED for 1s. Max 15s.\n' +
      '\n' +
      'EXPOSED: Target receives 15% additional damage from all sources.',
    wikiLinks: [`https://remnant.wiki/Monolith`],
    linkedItems: {
      mod: {
        name: 'Sandstorm',
      },
    },
    damage: 11,
    rps: 12,
    magazine: 80,
    accuracy: 95,
    ideal: 17,
    falloff: 30,
    ammo: 320,
    crit: 5,
    weakspot: 85,
    stagger: -20,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Nightfall',
    imagePath: '/items/weapons/nightfall.png',
    id: '2fdvrf',
    dlc: 'base',
    description: `A device forged of pure evil. Fires hardened bone shards at a brisk rate dealing bonus stagger. Semi-automatic with a medium kick.`,
    wikiLinks: [`https://remnant.wiki/Nightfall`],
    linkedItems: {
      mod: {
        name: 'Dreadwalker',
      },
    },
    damage: 28,
    rps: 4.95,
    magazine: 13,
    accuracy: 95,
    ideal: 18,
    falloff: 50,
    ammo: 117,
    crit: 5,
    weakspot: 105,
    stagger: 15,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Plasma Cutter',
    imagePath: '/items/weapons/plasmacutter.png',
    id: '7nwwzn',
    dlc: 'base',
    description: `An energy-based cutting tool that increases damage when focused on a target. Can overheat.`,
    wikiLinks: [`https://remnant.wiki/Plasma_Cutter`],
    linkedItems: {
      mod: {
        name: 'Heat Sink',
      },
    },
    damage: 7,
    rps: 13,
    magazine: 100,
    accuracy: 95,
    ideal: 17,
    falloff: 30,
    ammo: 300,
    crit: 5,
    weakspot: 80,
    stagger: -20,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Polygun',
    imagePath: '/items/weapons/polygun.png',
    id: 'polgun',
    dlc: 'dlc2',
    description: `ERROR: Unable to load description.ERROR: Unable to load description.`,
    wikiLinks: [`https://remnant.wiki/Polygun`],
    linkedItems: {
      mod: {
        name: '77 79 68',
      },
    },
    damage: 69,
    rps: 2.15,
    magazine: 99,
    accuracy: 95,
    ideal: 15,
    falloff: 30,
    ammo: 999,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Pulse Rifle',
    imagePath: '/items/weapons/pulserifle.png',
    id: 'vldebv',
    dlc: 'base',
    description: `An extremely accurate, high-tech pulse rifle which shoots quick three-round bursts.`,
    wikiLinks: [`https://remnant.wiki/Pulse_Rifle`],
    damage: 16,
    rps: 7.8,
    magazine: 30,
    accuracy: 75,
    ideal: 22,
    falloff: 65,
    ammo: 210,
    crit: 10,
    weakspot: 105,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Repulsor',
    imagePath: '/items/weapons/repulsor.png',
    id: 'v6zmn3',
    dlc: 'base',
    description: `Converted from experimental Dreamer tech, ideal for mid-range combat. Weapon becomes more accurate the longer AIM is held.`,
    wikiLinks: [`https://remnant.wiki/Repulsor`],
    linkedItems: {
      mod: {
        name: 'Banish',
      },
    },
    damage: 100,
    rps: 1.6,
    magazine: 5,
    accuracy: 95,
    ideal: 13,
    falloff: 35,
    ammo: 35,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Royal Hunting Bow',
    saveFileSlug: 'weapon_bow',
    imagePath: '/items/weapons/royalhuntingbow.png',
    id: '8ouocq',
    dlc: 'base',
    description:
      'A lightweight, easy handling bow designed for hunting. High critical chance, bonus damage on Weakspot hits, and a low sound profile.\n' +
      'Can be charged for more damage. Perfect release after Charge for maximum damage.',
    wikiLinks: [`https://remnant.wiki/Royal_Hunting_Bow`],
    damage: 80,
    rps: 5.3,
    magazine: 1,
    accuracy: 100,
    ideal: 25,
    falloff: 65,
    ammo: 40,
    crit: 10,
    weakspot: 115,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Rusty Lever Action',
    isRusty: true,
    saveFileSlug: 'weapon_leveraction_rusty',
    imagePath: '/items/weapons/leveractionrusted.png',
    id: 'gv6yzu',
    dlc: 'base',
    description: `A well-worn lever-action rifle.`,
    wikiLinks: [`https://remnant.wiki/Rusty_Lever_Action`],
    damage: 55,
    rps: 1.8,
    magazine: 10,
    accuracy: 80,
    ideal: 30,
    falloff: 80,
    ammo: 60,
    crit: 0,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Sagittarius',
    imagePath: '/items/weapons/sagittarius.png',
    id: 't0cb8d',
    dlc: 'base',
    description:
      'A high-powered Bow which deals bonus damage to Weakspots. Can be charged for increased effect. Perfect release after Charge for maximum damage.',
    wikiLinks: [`https://remnant.wiki/Sagittarius`],
    linkedItems: {
      mod: {
        name: 'Starfall',
      },
    },
    damage: 98,
    rps: 4.5,
    magazine: 1,
    accuracy: 100,
    ideal: 25,
    falloff: 65,
    ammo: 32,
    crit: 10,
    weakspot: 115,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Savior',
    saveFileSlug: '/weapon_savior',
    imagePath: '/items/weapons/savior.png',
    id: '2jrbvl',
    dlc: 'base',
    tags: ['Hardcore Reward'],
    description:
      'An old Fusion Rifle refactored to store and violently release energy in each shot. Can be charged for more damage. Perfect release after Charge for maximum damage.',
    wikiLinks: [`https://remnant.wiki/Savior`],
    linkedItems: {
      mod: {
        name: 'Shatterstar',
      },
    },
    damage: 50,
    rps: 2.1,
    magazine: 6,
    accuracy: 95,
    ideal: 25,
    falloff: 75,
    ammo: 36,
    crit: 10,
    weakspot: 115,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Sparkfire Shotgun',
    dlc: 'dlc1',
    saveFileSlug: 'weapon_sparkfire',
    imagePath: '/items/weapons/sparkfireshotgun.png',
    id: '3r9jm7',
    description:
      'Fires incendiary shells that apply BURNING which deals 30 - 90 FIRE damage over 3 seconds.',
    wikiLinks: [`https://remnant.wiki/Sparkfire_Shotgun`],
    damage: 100,
    rps: 1.3,
    magazine: 7,
    accuracy: 98,
    ideal: 12,
    falloff: 30,
    ammo: 35,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Sporebloom',
    imagePath: '/items/weapons/sporebloom.png',
    id: 'q3fgj2',
    dlc: 'base',
    description: `An exceptionally powerful single-shot weapon that deals bonus stagger damage. Must reload after each round fired.`,
    wikiLinks: [`https://remnant.wiki/Sporebloom`],
    linkedItems: {
      mod: {
        name: 'Spore Shot',
      },
    },
    damage: 200,
    rps: 1.95,
    magazine: 1,
    accuracy: 95,
    ideal: 10,
    falloff: 25,
    ammo: 21,
    crit: 5,
    weakspot: 100,
    stagger: 20,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Starkiller',
    imagePath: '/items/weapons/starkiller.png',
    id: 'hzmyu1',
    dlc: 'base',
    description:
      'Alien rifle that shoots high velocity rails which penetrate enemies. Equipped with a 2.5x magnification scope. Double Tap AIM to Scope.',
    wikiLinks: [`https://remnant.wiki/Starkiller`],
    linkedItems: {
      mod: {
        name: 'Gravity Core',
      },
    },
    damage: 80,
    rps: 1.5,
    magazine: 5,
    accuracy: 95,
    ideal: 30,
    falloff: 80,
    ammo: 40,
    crit: 5,
    weakspot: 110,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Thorn',
    saveFileSlug: '/weapon_thorn',
    dlc: 'dlc2',
    imagePath: '/items/weapons/thorn.png',
    id: '13hsqd',
    description:
      'Fires homing needles which deal 5 - 15 Explosive Damage after sticking for 2s. When 5  needles are stuck in a target at once, BLOWBACK triggers, dealing 50 - 150 Explosive Damage instead.',
    externalTokens: [`Explosive Damage`],
    wikiLinks: [`https://remnant.wiki/Thorn`],
    linkedItems: {
      mod: {
        name: 'Deadwood',
      },
    },
    damage: 7,
    rps: 8.85,
    magazine: 30,
    accuracy: 95,
    ideal: 19,
    falloff: 39,
    ammo: 300,
    crit: 10,
    weakspot: 100,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Twisted Arbalest',
    saveFileSlug: '/weapon_twistedarbalest',
    imagePath: '/items/weapons/twistedarbalest.png',
    id: '13hsq0',
    dlc: 'base',
    description: `A strange device which fires a bouncing Energy Disc that can hit up to 5 enemies in close proximity. Damage is reduced with each bounce.`,
    wikiLinks: [`https://remnant.wiki/Twisted_Arbalest`],
    linkedItems: {
      mod: {
        name: "Guardian's Call",
      },
    },
    damage: 80,
    rps: 2,
    magazine: 1,
    accuracy: 85,
    ideal: 20,
    falloff: 70,
    ammo: 22,
    crit: 5,
    weakspot: 100,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Trinity Crossbow',
    saveFileSlug: '/weapon_trinitycrossbow',
    imagePath: '/items/weapons/trinitycrossbow.png',
    id: '13hsq6',
    dlc: 'dlc2',
    description: `A powerful Pan crossbow designed for mid-range combat. Fires 3 bolts at a time.`,
    wikiLinks: [`https://remnant.wiki/Trinity_Crossbow`],
    damage: 44,
    rps: 0.63,
    magazine: 18,
    accuracy: 100,
    ideal: 22,
    falloff: 65,
    ammo: 90,
    crit: 10,
    weakspot: 115,
    stagger: -65,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Widowmaker',
    saveFileSlug: 'weapon_sniperrifle',
    imagePath: '/items/weapons/sniperrifle.png',
    id: 'fqdvas',
    dlc: 'base',
    description:
      'A powerful single-shot sniper rifle with excellent range and pinpoint accuracy. Comes with a 3x scope. Tap SCOPE to toggle.',
    wikiLinks: [`https://remnant.wiki/Widowmaker`],
    damage: 125,
    rps: 2.4,
    magazine: 1,
    accuracy: 95,
    ideal: 35,
    falloff: 85,
    ammo: 27,
    crit: 10,
    weakspot: 120,
    stagger: 20,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'Wrangler 1860',
    saveFileSlug: 'weapon_leveraction',
    imagePath: '/items/weapons/leveraction.png',
    id: '5aninv',
    dlc: 'base',
    description: `A well-rounded lever-action rifle effective at most ranges, hampered only by a slow reload.`,
    wikiLinks: [`https://remnant.wiki/Wrangler_1860`],
    damage: 55,
    rps: 2.1,
    magazine: 10,
    accuracy: 80,
    ideal: 25,
    falloff: 70,
    ammo: 60,
    crit: 10,
    weakspot: 110,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'long gun',
    name: 'XMG57 "Bonesaw"',
    saveFileSlug: 'weapon_lmg',
    imagePath: '/items/weapons/bonesaw.png',
    id: 'rbpz53',
    dlc: 'base',
    description: `An experimental infantry support weapon used for prolonged suppressive fire. High capacity, long reload, and prone to overheating. Becomes more accurate while holding down the trigger.`,
    wikiLinks: [`https://remnant.wiki/XMG57_"Bonesaw"`],
    damage: 12,
    rps: 9.5,
    magazine: 150,
    accuracy: 75,
    ideal: 19,
    falloff: 55,
    ammo: 300,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Abyssal Hook',
    imagePath: '/items/weapons/abyssalhook.png',
    dlc: 'dlc1',
    id: 'sd4nzf',
    description: `A hammer-like anchor that swings with an exceptionally irregular ferocity.`,
    wikiLinks: [`https://remnant.wiki/Abyssal_Hook`],
    linkedItems: {
      mod: {
        name: 'Fathomless Deep',
      },
    },
    damage: 101,
    crit: 6,
    weakspot: 85,
    stagger: 80,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: "Assassin's Dagger",
    imagePath: '/items/weapons/assassinsdagger.png',
    id: 'bv9wps',
    dlc: 'base',
    description: `Lightweight. Silent. Deadly. It's rumored that the blade is meant to bestow a slow, agonizing death.`,
    wikiLinks: [`https://remnant.wiki/Assassin's_Dagger`],
    linkedItems: {
      mod: {
        name: 'Bloodthirst',
      },
    },
    damage: 35,
    crit: -3,
    weakspot: 110,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Atom Smasher',
    imagePath: '/items/weapons/atomsmasher.png',
    id: 'lrk5hf',
    dlc: 'base',
    description: `A powerful crushing device that harnesses rocket technology to increase smashing force.`,
    wikiLinks: [`https://remnant.wiki/Atom_Smasher`],
    linkedItems: {
      mod: {
        name: 'Accelerator',
      },
    },
    damage: 72,
    crit: 5,
    weakspot: 95,
    stagger: 11,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Atom Splitter',
    imagePath: '/items/weapons/atomsplitter.png',
    id: 'e7c88o',
    dlc: 'base',
    description: `A giant tool for splitting heavy rocks.`,
    wikiLinks: [`https://remnant.wiki/Atom_Splitter`],
    linkedItems: {
      mod: {
        name: 'Fission Strike',
      },
    },
    damage: 100,
    crit: 6,
    weakspot: 95,
    stagger: 7,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Blade of Gul',
    imagePath: '/items/weapons/bladeofgul.png',
    id: 'nxfxlp',
    dlc: 'base',
    description:
      'A short, but thick sword, used by Gul Warriors. Its compact design makes for swift yet hard-hitting blows. An excellent close-range option.',
    wikiLinks: [`https://remnant.wiki/Blade_of_Gul`],
    damage: 57,
    crit: 4,
    weakspot: 100,
    stagger: 6,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Bone Chopper',
    imagePath: '/items/weapons/bonechopper.png',
    id: 'e6y7fy',
    dlc: 'base',
    description: `A razor-sharp hand axe. Excellent for separating flesh from bone. Charge for double attacks.`,
    wikiLinks: [`https://remnant.wiki/Bone_Chopper`],
    damage: 58,
    crit: 7,
    weakspot: 105,
    stagger: -3,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Crystal Staff',
    imagePath: '/items/weapons/crystalstaff.png',
    id: 'CMo9vJ',
    dlc: 'dlc2',
    description: `The staff hums with energy. A destructive power within yearns to be released.`,
    damage: 58,
    crit: 5,
    weakspot: 95,
    stagger: 3,
    wikiLinks: [`https://remnant.wiki/Crystal_Staff`],
    linkedItems: {
      mod: {
        name: 'Power Stone',
      },
    },
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Decayed Claws',
    imagePath: '/items/weapons/decayedclaws.png',
    id: 'y1a0bu',
    dlc: 'base',
    description: `Makeshift claws fashioned from decayed root and rusted metal.`,
    wikiLinks: [`https://remnant.wiki/Decayed_Claws`],
    damage: 49,
    crit: 16,
    weakspot: 110,
    stagger: -4,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Dreamcatcher',
    imagePath: '/items/weapons/dreamcatcher.png',
    id: '3sxr9y',
    dlc: 'base',
    description:
      'A magical stave capable of harnessing the energy of nearby enemies.',
    wikiLinks: [`https://remnant.wiki/Dreamcatcher`],
    linkedItems: {
      mod: {
        name: 'Dreamwave',
      },
    },
    damage: 58,
    crit: 5,
    weakspot: 95,
    stagger: 3,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Edge of the Forest',
    imagePath: '/items/weapons/edgeoftheforest.png',
    id: '6c7rqm',
    dlc: 'base',
    description: `An elegant, yet light blade, designed to bring beauty to bloodshed. Unstoppable in the hands of a master swordsman.`,
    wikiLinks: [`https://remnant.wiki/Edge_of_the_Forest`],
    damage: 59,
    crit: 11,
    weakspot: 105,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Feral Judgement',
    saveFileSlug: 'weapon_feraljudgment',
    imagePath: '/items/weapons/feraljudgement.png',
    id: 'umb305',
    dlc: 'base',
    description:
      'A pair of gauntlets with sharp bone blades that strike with vicious speed and velocity.',
    wikiLinks: [`https://remnant.wiki/Feral_Judgement`],
    linkedItems: {
      mod: {
        name: 'Death Sentence',
      },
    },
    damage: 53,
    crit: 13,
    weakspot: 110,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Gas Giant',
    saveFileSlug: 'weapon_talratha_hammer',
    imagePath: '/items/weapons/gasgiant.png',
    id: 'c58759',
    dlc: 'base',
    description: `Dealing damage unleashes the dormant Toxic Gas within the head. When infused, Basic Attacks apply CORRODED for 5s.`,
    wikiLinks: [`https://remnant.wiki/Gas_Giant`],
    linkedItems: {
      mod: {
        name: 'Dying Breath',
      },
    },
    damage: 74,
    crit: 3,
    weakspot: 95,
    stagger: 8,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Godsplitter',
    imagePath: '/items/weapons/godsplitter.png',
    id: 'a23oaa',
    dlc: 'base',
    description:
      'An expertly balanced blade that is the product of advanced Fae metallurgy. Cannot score Weakspot hits without its Mod behavior.',
    wikiLinks: [`https://remnant.wiki/Godsplitter`],
    linkedItems: {
      mod: {
        name: 'Fracture',
      },
    },
    damage: 38,
    crit: 2,
    weakspot: 50,
    stagger: -20,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: "Hero's Sword",
    imagePath: '/items/weapons/herossword.png',
    id: '5o3cq4',
    dlc: 'base',
    description:
      'An ancient, quick, and versatile blade suited for many situations. Contains a hidden power.',
    wikiLinks: [`https://remnant.wiki/Hero's_Sword`],
    linkedItems: {
      mod: {
        name: 'Energy Wave',
      },
    },
    damage: 51,
    crit: 5,
    weakspot: 90,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Huntress Spear',
    imagePath: '/items/weapons/huntressspear.png',
    id: '0jefkc',
    dlc: 'base',
    description:
      'A battle-worn spear worthy of the finest hunters. Charge Melee Attacks apply CORROSION dealing 100 ACID damage over 5s.',
    wikiLinks: [`https://remnant.wiki/Huntress_Spear`],
    linkedItems: {
      mod: {
        name: 'Javelin',
      },
    },
    damage: 63,
    crit: 5,
    weakspot: 110,
    stagger: -5,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Iron Greatsword',
    imagePath: '/items/weapons/irongreatsword.png',
    id: '5wy88e',
    dlc: 'base',
    description: `A giant broadsword made from flattened railroad tracks. Dozens of ridges cut in the side for causing irreparable damage.`,
    wikiLinks: [`https://remnant.wiki/Iron_Greatsword`],
    damage: 105,
    crit: 5,
    weakspot: 95,
    stagger: 13,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Knuckle Dusters',
    imagePath: '/items/weapons/knuckledusters.png',
    id: 'as4bt4',
    dlc: 'base',
    description: `Steel knuckles with rusty sawblade tips, designed to boost Unarmed damage.`,
    wikiLinks: [`https://remnant.wiki/Knuckle_Dusters`],
    damage: 43,
    crit: 5,
    weakspot: 110,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Krell Axe',
    imagePath: '/items/weapons/krellaxe.png',
    id: '5gl3la',
    dlc: 'base',
    description:
      'Infused with Krell Shock magic, can be thrown if the wielder has stamina. Axe will magically reappear in hand. Charge to throw.',
    wikiLinks: [`https://remnant.wiki/Krell_Axe`],
    linkedItems: {
      mod: {
        name: 'Krell Edge',
      },
    },
    damage: 54,
    crit: 3,
    weakspot: 85,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Labyrinth Staff',
    imagePath: '/items/weapons/labyrinthstaff.png',
    id: 'gts5dh',
    dlc: 'base',
    description: `Basic Strikes generate 10% additional Mod Power. Charge Attacks perform an AOE which strikes all enemies within 2m, dealing 75 Damage. AOE Damage generates 50% additional Mod Power.`,
    externalTokens: [`Amplitude`],
    wikiLinks: [`https://remnant.wiki/Labyrinth_Staff`],
    damage: 64,
    crit: 8,
    weakspot: 95,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Mirage',
    imagePath: '/items/weapons/mirage.png',
    dlc: 'dlc2',
    id: '6j7c6k',
    description: `The mace whirs as if living harmonics hold its shape. When swung, a breath of sand tethers to the rock crown for extended reach and lethal momentum.`,
    wikiLinks: [`https://remnant.wiki/Mirage`],
    linkedItems: {
      mod: {
        name: 'Cyclone',
      },
    },
    damage: 56,
    crit: 3,
    weakspot: 100,
    stagger: -5,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Nightshade',
    imagePath: '/items/weapons/nightshade.png',
    id: '6j7czk',
    dlc: 'base',
    description:
      'Fast striking claws with a high Critical Hit chance. Neutral Dodge grants the power of Lifesteal.',
    wikiLinks: [`https://remnant.wiki/Nightshade`],
    linkedItems: {
      mod: {
        name: 'Beyond the Veil',
      },
    },
    damage: 47,
    crit: 18,
    weakspot: 110,
    stagger: -20,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Ornate Blade',
    imagePath: '/items/weapons/ornateblade.png',
    id: '0wto7p',
    dlc: 'base',
    description: `An intricately-forged elongated sword. Designed to keep stronger enemies at bay, while remaining light enough for agile maneuvers.`,
    wikiLinks: [`https://remnant.wiki/Ornate_Blade`],
    damage: 52,
    crit: 11,
    weakspot: 105,
    stagger: -5,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Ornate Flail',
    imagePath: '/items/weapons/ornateflail.png',
    id: 'pwuhho',
    dlc: 'base',
    description:
      'An intricately-forged flail with uniquely designed airways. Allows smaller wielders to get the weapon up to speed much quicker.',
    wikiLinks: [`https://remnant.wiki/Ornate_Flail`],
    damage: 63,
    crit: 11,
    weakspot: 100,
    stagger: -3,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Rebellion Spear',
    imagePath: '/items/weapons/rebellionspear.png',
    id: 'qy94qr',
    dlc: 'base',
    description: `A spear perfect for staying at a distance. Has excellent range, great recovery, and focused direct damage for one on one combat.`,
    wikiLinks: [`https://remnant.wiki/Rebellion_Spear`],
    damage: 60,
    crit: 13,
    weakspot: 110,
    stagger: 2,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Red Doe Staff',
    imagePath: '/items/weapons/reddoestaff.png',
    id: 'oazjm0',
    dlc: 'base',
    description: `A magical stave rumored to contain a healing spirit within. Strikes with wide swings.`,
    wikiLinks: [`https://remnant.wiki/Red_Doe_Staff`],
    linkedItems: {
      mod: {
        name: 'Lifeline',
      },
    },
    damage: 62,
    crit: 3,
    weakspot: 95,
    stagger: 8,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Ritualist Scythe',
    dlc: 'dlc1',
    imagePath: '/items/weapons/scytheritualist.png',
    id: '7hoogs',
    description:
      'An evil-fueled reaping tool that deals additional damage to suffering targets.',
    wikiLinks: [`https://remnant.wiki/Ritualist_Scythe`],
    linkedItems: {
      mod: {
        name: 'Reaver',
      },
    },
    damage: 51,
    crit: 5,
    weakspot: 100,
    stagger: -19,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Royal Broadsword',
    imagePath: '/items/weapons/royalbroadsword.png',
    id: 'wogdou',
    dlc: 'base',
    description:
      "Standard issue Greatsword for the Empress' Royal Guards. Razor-sharp edges, extremely heavy, yet perfectly balanced.",
    wikiLinks: [`https://remnant.wiki/Royal_Broadsword`],
    damage: 102,
    crit: 7,
    weakspot: 95,
    stagger: 11,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Rusted Claws',
    imagePath: '/items/weapons/rustedclaws.png',
    id: '6odjqi',
    dlc: 'base',
    description: `A pair of old-canine training bracers converted into deadly claws. Used for slashing and ripping.`,
    wikiLinks: [`https://remnant.wiki/Rusted_Claws`],
    damage: 51,
    crit: 14,
    weakspot: 110,
    stagger: -9,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Scrap Hammer',
    saveFileSlug: 'weapon_hammer',
    imagePath: '/items/weapons/hammer.png',
    id: 'a88cg7',
    dlc: 'base',
    description:
      'A large, heavy warhammer cobbled together from engine components. It is a slow-but-devastating weapon meant to destroy anything it hits.',
    wikiLinks: [`https://remnant.wiki/Scrap_Hammer`],
    damage: 83,
    crit: 8,
    weakspot: 95,
    stagger: 9,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Scrap Hatchet',
    saveFileSlug: 'weapon_hatchet',
    imagePath: '/items/weapons/hatchet.png',
    id: 'wtj6mq',
    dlc: 'base',
    description: `A common chopping tool that has been repurposed for combat. Rapidly cycles attacks from right to left. Charge attacks strike twice.`,
    wikiLinks: [`https://remnant.wiki/Scrap_Hatchet`],
    damage: 57,
    crit: 6,
    weakspot: 105,
    stagger: 1,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Scrap Staff',
    saveFileSlug: 'weapon_staff',
    imagePath: '/items/weapons/scrapstaff.png',
    id: 'fp5yi4',
    dlc: 'base',
    description: `A staff made from old plumbing parts used for controlling wide swaths in front of the wielder.`,
    wikiLinks: [`https://remnant.wiki/Scrap_Staff`],
    damage: 65,
    crit: 6,
    weakspot: 95,
    stagger: 8,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Shovel',
    imagePath: '/items/weapons/shovel.png',
    id: 'vpEWS5',
    dlc: 'dlc2',
    description: `It's a shovel.`,
    wikiLinks: [`https://remnant.wiki/Shovel`],
    damage: 55,
    crit: 15,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Smolder',
    imagePath: '/items/weapons/smolder.png',
    id: 'd0usz6',
    dlc: 'base',
    description: `A scorched blade imbued with FIRE.`,
    wikiLinks: [`https://remnant.wiki/Smolder`],
    linkedItems: {
      mod: {
        name: 'Blaze',
      },
    },
    damage: 46,
    crit: 4,
    weakspot: 95,
    stagger: 1,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Spectral Blade',
    imagePath: '/items/weapons/spectralblade.png',
    id: 'l3zte1',
    dlc: 'base',
    description: `A super-heated laser sword with an infinitely sharp edge. Perfect for cutting... anything.`,
    wikiLinks: [`https://remnant.wiki/Spectral_Blade`],
    linkedItems: {
      mod: {
        name: 'Whirlwind',
      },
    },
    damage: 53,
    crit: 8,
    weakspot: 105,
    stagger: -25,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Steel Flail',
    saveFileSlug: 'weapon_flail',
    imagePath: '/items/weapons/steelflail.png',
    id: 'ji6tpl',
    dlc: 'base',
    description: `An unorthodox weapon meant to convert momentum into destruction. Some attacks can continuously chain overhead swings.`,
    wikiLinks: [`https://remnant.wiki/Steel_Flail`],
    damage: 69,
    crit: 4,
    weakspot: 100,
    stagger: 6,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Steel Katana',
    saveFileSlug: 'weapon_katana',
    imagePath: '/items/weapons/steelkatana.png',
    id: '0cnwdx',
    dlc: 'base',
    description: `An old piece of steel with serrations cut into one side. Pipe handle provides limited grip.`,
    wikiLinks: [`https://remnant.wiki/Steel_Katana`],
    damage: 56,
    crit: 13,
    weakspot: 105,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Steel Scythe',
    saveFileSlug: 'weapon_scythe',
    imagePath: '/items/weapons/scythescrap.png',
    id: '2po1q8',
    dlc: 'base',
    description: `A ruthless threshing device.`,
    wikiLinks: [`https://remnant.wiki/Steel_Scythe`],
    damage: 55,
    crit: 10,
    weakspot: 100,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Steel Spear',
    saveFileSlug: 'weapon_spear',
    imagePath: '/items/weapons/steelspear.png',
    id: 'vbzlfk',
    dlc: 'base',
    description: `A spear perfect for staying at range with quick, focused attacks. High, single-target damage.`,
    wikiLinks: [`https://remnant.wiki/Steel_Spear`],
    damage: 61,
    crit: 9,
    weakspot: 110,
    stagger: -4,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Steel Sword',
    saveFileSlug: 'weapon_sword',
    imagePath: '/items/weapons/sword.png',
    id: 'zsb5g1',
    dlc: 'base',
    description: `A long, sharp blade hammered out of vehicle leaf springs. Well-rounded for most situations.`,
    wikiLinks: [`https://remnant.wiki/Steel_Sword`],
    damage: 56,
    crit: 7,
    weakspot: 100,
    stagger: 2,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Stonebreaker',
    imagePath: '/items/weapons/stonebreaker.png',
    id: 'b4g4q0',
    dlc: 'base',
    description: `A massive Greatsword which contains the harnessed magic of a corrupted Guardian. Can summon small shockwaves.`,
    wikiLinks: [`https://remnant.wiki/Stonebreaker`],
    linkedItems: {
      mod: {
        name: 'Faultline',
      },
    },
    damage: 103,
    crit: 4,
    weakspot: 95,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Vice Grips',
    imagePath: '/items/weapons/vicegrips.png',
    id: 'ygwrpd',
    dlc: 'base',
    description: `A N'Erudian tool converted into a ruthless ripping device. High raw damage.`,
    wikiLinks: [`https://remnant.wiki/Vice_Grips`],
    damage: 55,
    crit: 6,
    weakspot: 110,
    stagger: -18,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: "World's Edge",
    imagePath: '/items/weapons/worldsedge.png',
    id: 'gilcfn',
    dlc: 'base',
    description:
      'A glowing Greatsword forged from shards of a shattered Worldstone. Charge attacks cast waves.',
    wikiLinks: [`https://remnant.wiki/World's_Edge`],
    linkedItems: {
      mod: {
        name: 'Horizon Strike',
      },
    },
    damage: 96,
    crit: 3,
    weakspot: 85,
    stagger: -20,
  },
  {
    category: 'weapon',
    type: 'melee',
    name: 'Wrathbringer',
    dlc: 'dlc1',
    imagePath: '/items/weapons/wrathbringer.png',
    id: 'mq5fnr',
    description: `A massive hammer infused with the souls of deceased Dran. Its dormant power can be awakened by taking damage.`,
    wikiLinks: [`https://remnant.wiki/Wrathbringer`],
    linkedItems: {
      mod: {
        name: 'Awakening',
      },
    },
    damage: 101,
    crit: 6,
    weakspot: 85,
    stagger: 80,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Anguish',
    imagePath: '/items/weapons/anguish.png',
    dlc: 'dlc1',
    id: 'r2o474',
    description: `Fires heated bits of molten slag. Can be charged to fire a single explosive rod at the cost of causing damage to the wielder while charging.`,
    externalTokens: [`Explosive Damage`],
    wikiLinks: [`https://remnant.wiki/Anguish`],
    linkedItems: {
      mod: {
        name: 'Loathe the Weak',
      },
    },
    damage: 92,
    rps: 1.7,
    magazine: 5,
    accuracy: 95,
    ideal: 16,
    falloff: 35,
    ammo: 35,
    crit: 5,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Bolt Driver',
    imagePath: '/items/weapons/boltdriver.png',
    id: 'd388ma',
    dlc: 'base',
    description:
      'An ingenius Gul rifle designed to harness energy from Pan crystals. Charge to fire a 3-shot burst.',
    wikiLinks: [`https://remnant.wiki/Bolt_Driver`],
    damage: 26,
    rps: 7.63,
    magazine: 24,
    accuracy: 99,
    ideal: 17,
    falloff: 52,
    ammo: 96,
    crit: 10,
    weakspot: 105,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Corrupted Cube Gun',
    imagePath: '/items/weapons/corruptedcubegun.png',
    id: 'mSSxW6',
    dlc: 'base',
    description:
      'Fusion charged auto-cannon generates cubes which penetrate. Infinite ammo capacity. Can overheat. Cannot score Weakspot hits.',
    wikiLinks: ['https://remnant.wiki/Corrupted_Cube_Gun'],
    damage: 66,
    rps: 2.2,
    magazine: 99,
    accuracy: 95,
    ideal: 15,
    falloff: 35,
    ammo: 105,
    crit: 5,
    weakspot: 0,
    stagger: 0,
    linkedItems: {
      mod: {
        name: 'Cube Room',
      },
    },
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Corrupted Meridian',
    imagePath: '/items/weapons/corruptedmeridian.png',
    id: 'yw1btj',
    dlc: 'base',
    description:
      'Fires rocket that deals AOE damage within 2m. Charging the weapon can load additional rockets. (Max 3). Cannot Weakspot.',
    externalTokens: [`Amplitude`, `Explosive Damage`],
    wikiLinks: [`https://remnant.wiki/Corrupted_Meridian`],
    linkedItems: {
      mod: {
        name: 'Deadpoint',
      },
    },
    damage: 90,
    rps: 1.9,
    magazine: 6,
    accuracy: 98,
    ideal: 15,
    falloff: 30,
    ammo: 36,
    crit: 0,
    weakspot: 0,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Corrupted Nebula',
    imagePath: '/items/weapons/corruptednebula.png',
    id: '8u8j4G',
    dlc: 'base',
    description:
      'Semi-automatic laser weapon. Weakspot hits and kills create a Nano-bot for 8s that seeks enemies within 20m and repeatedly attacks dealing 6 - 18 ACID damage per hit. Max 5 Nano-bots.',
    wikiLinks: ['https://remnant.wiki/Corrupted_Nebula'],
    linkedItems: {
      mod: {
        name: 'Nano Phase',
      },
    },
    damage: 24,
    rps: 5.2,
    magazine: 15,
    accuracy: 95,
    ideal: 17,
    falloff: 56,
    ammo: 105,
    crit: 5,
    weakspot: 105,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Corrupted Rune Pistol',
    imagePath: '/items/weapons/corruptedrunepistol.png',
    id: 'id5pbt',
    dlc: 'base',
    description: `A pistol infused with erroneous properties. Fires energy, allowing the trigger to be held for continuous fire.`,
    wikiLinks: [`https://remnant.wiki/Corrupted_Rune_Pistol`],
    linkedItems: {
      mod: {
        name: 'Death Brand',
      },
    },
    damage: 17,
    rps: 6.3,
    magazine: 25,
    accuracy: 95,
    ideal: 17,
    falloff: 53,
    ammo: 150,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Corrupted Sorrow',
    id: 'zrP64k',
    dlc: 'base',
    imagePath: '/items/weapons/corruptedsorrow.png',
    description:
      'Innately cannot harm allies. Fires bolts which anchor to targets for 6s. Max 10 bolts anchored at once.',
    linkedItems: {
      mod: {
        name: 'Will of the Wisp',
      },
    },
    wikiLinks: ['https://remnant.wiki/Corrupted_Sorrow'],
    damage: 42,
    rps: 2.6,
    magazine: 10,
    accuracy: 95,
    ideal: 17,
    falloff: 52,
    ammo: 60,
    crit: 7,
    weakspot: 105,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Cube Gun',
    saveFileSlug: '/weapon_cubegun',
    imagePath: '/items/weapons/cubegun.png',
    id: 'zn3boo',
    dlc: 'base',
    description:
      'Projectiles return on hit or after reaching max range. Reloading retrieves shot projectiles. Max 5 fired projectiles. Infinite ammo. Can overheat.',
    wikiLinks: [`https://remnant.wiki/Cube_Gun`],
    linkedItems: {
      mod: {
        name: 'Cube Shield',
      },
    },
    damage: 15,
    rps: 7.5,
    magazine: 5,
    accuracy: 90,
    ideal: 20,
    falloff: 50,
    ammo: 105,
    crit: 5,
    weakspot: 85,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Double Barrel',
    saveFileSlug: 'weapon_shortbarrel',
    imagePath: '/items/weapons/shortbarrel.png',
    id: 'ztz84h',
    dlc: 'base',
    description:
      'A double-barrel shotgun which can deal massive damage at close range with back to back shots.',
    wikiLinks: [`https://remnant.wiki/Double_Barrel`],
    damage: 105,
    rps: 2.25,
    magazine: 2,
    accuracy: 60,
    ideal: 8,
    falloff: 20,
    ammo: 24,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Enigma',
    imagePath: '/items/weapons/enigma.png',
    id: 'd06hjq',
    dlc: 'base',
    description:
      'Fires an electrical stream that jumps to nerby targets within 7.5m, dealing 30% reduced damage per jump. Applies OVERLOADED.',
    externalTokens: [`Amplitude`],
    wikiLinks: [`https://remnant.wiki/Enigma`],
    linkedItems: {
      mod: {
        name: 'Chaos Driver',
      },
    },
    damage: 22,
    rps: 4,
    magazine: 25,
    accuracy: 60,
    ideal: 12,
    falloff: 12,
    ammo: 125,
    crit: -10,
    weakspot: 0,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Hellfire',
    imagePath: '/items/weapons/hellfire.png',
    id: '797iqq',
    dlc: 'base',
    description:
      'Spews flames that apply BURNING which deals 300 - 900 FIRE damage over 10 seconds.',
    wikiLinks: [`https://remnant.wiki/Hellfire`],
    linkedItems: {
      mod: {
        name: 'Explosive Shot',
      },
    },
    damage: 13,
    rps: 6,
    magazine: 60,
    accuracy: 15,
    ideal: 8,
    falloff: 8,
    ammo: 180,
    crit: 0,
    weakspot: 0,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Meridian',
    saveFileSlug: '/weapon_meridian',
    imagePath: '/items/weapons/meridian.png',
    id: '1ziutf',
    dlc: 'base',
    description:
      'Fires grenades that explode on contact with enemies and deal AOE damage within 4m. Dormant grenades eventually explode and can be shot to detonate early. Cannot Weakspot.',
    externalTokens: [`Amplitude`, `Explosive Damage`],
    wikiLinks: [`https://remnant.wiki/Meridian`],
    linkedItems: {
      mod: {
        name: 'Screamer',
      },
    },
    damage: 82,
    rps: 1.9,
    magazine: 5,
    accuracy: 100,
    ideal: 15,
    falloff: 30,
    ammo: 40,
    crit: 0,
    weakspot: 0,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'MP60-R',
    imagePath: '/items/weapons/mp60r.png',
    id: 'ty2gsi',
    dlc: 'base',
    description:
      'A small-caliber sub-machine gun best suited for close range skirmishes.',
    wikiLinks: [`https://remnant.wiki/MP60-R`],
    damage: 9,
    rps: 14.2,
    magazine: 42,
    accuracy: 95,
    ideal: 17,
    falloff: 50,
    ammo: 294,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Nebula',
    saveFileSlug: '/weapon_nebula',
    imagePath: '/items/weapons/nebula.png',
    id: 'p7tsxr',
    dlc: 'base',
    description:
      'Fires a stream of superhot ACID gas which applies CORRODED effect, dealing 300 - 900 CORROSIVE Damage over 15s. Killing targets CORRODED by Nebula spawns a gas cloud which applies its on-hit effect. Gas clouds lasts 2s and can be refreshed.',
    wikiLinks: [`https://remnant.wiki/Nebula`],
    linkedItems: {
      mod: {
        name: 'Nano Swarm',
      },
    },
    damage: 12,
    rps: 8,
    magazine: 55,
    accuracy: 15,
    ideal: 8,
    falloff: 8,
    ammo: 220,
    crit: 0,
    weakspot: 0,
    stagger: -15,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Repeater Pistol',
    saveFileSlug: 'weapon_repeater',
    imagePath: '/items/weapons/repeater.png',
    id: 'pbtmmj',
    dlc: 'base',
    description: `An accurate semi-automatic pistol that can rapidly fire small-caliber bullets.`,
    wikiLinks: [`https://remnant.wiki/Repeater_Pistol`],
    damage: 15,
    rps: 8.1,
    magazine: 20,
    accuracy: 95,
    ideal: 18,
    falloff: 52,
    ammo: 160,
    crit: 5,
    weakspot: 105,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Rune Pistol',
    saveFileSlug: '/weapon_runepistol',
    imagePath: '/items/weapons/runepistol.png',
    id: '2pblgq',
    dlc: 'base',
    description: `A pistol infused with mysterious Fae magic. Rapidly fires 3-round bursts of energy. Trigger can be held to continuously fire.`,
    wikiLinks: [`https://remnant.wiki/Rune_Pistol`],
    linkedItems: {
      mod: {
        name: 'Soul Brand',
      },
    },
    damage: 16,
    rps: 6.6,
    magazine: 42,
    accuracy: 95,
    ideal: 18,
    falloff: 53,
    ammo: 168,
    crit: 10,
    weakspot: 100,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Rupture Cannon',
    imagePath: '/items/weapons/rupturecannon.png',
    id: 'xzlpao',
    dlc: 'base',
    description:
      'A mid-range Pistol Shotgun with a brisk fire rate and medium recoil. Slower reload.',
    wikiLinks: [`https://remnant.wiki/Rupture_Cannon`],
    location: { world: `N'Erud`, dungeon: [`Vault of the Formless`] },
    damage: 42,
    rps: 2.75,
    magazine: 12,
    accuracy: 90,
    ideal: 14,
    falloff: 35,
    ammo: 60,
    crit: 5,
    weakspot: 100,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Rusty Repeater',
    isRusty: true,
    saveFileSlug: 'weapon_repeater_rusty',
    imagePath: '/items/weapons/rustyrepeater.png',
    id: 't412us',
    dlc: 'base',
    description: `An old antique pistol.`,
    wikiLinks: [`https://remnant.wiki/Rusty_Repeater`],
    damage: 15,
    rps: 7.2,
    magazine: 15,
    accuracy: 95,
    ideal: 17,
    falloff: 55,
    ammo: 180,
    crit: 0,
    weakspot: 100,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Service Pistol',
    imagePath: '/items/weapons/servicepistol.png',
    id: 'g34ywl',
    dlc: 'base',
    description: `A standard issue military spec sidearm known for its reliability and accuracy.`,
    wikiLinks: [`https://remnant.wiki/Service_Pistol`],
    damage: 24,
    rps: 6.5,
    magazine: 10,
    accuracy: 85,
    ideal: 20,
    falloff: 50,
    ammo: 110,
    crit: 5,
    weakspot: 105,
    stagger: 0,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Silverback Model 500',
    saveFileSlug: 'weapon_magnum',
    imagePath: '/items/weapons/magnum.png',
    id: '46cwa6',
    dlc: 'base',
    description: `A powerful hand cannon with a low capacity cylinder. High damage and a heavy kick.`,
    wikiLinks: [`https://remnant.wiki/Silverback_Model_500`],
    damage: 55,
    rps: 2.4,
    magazine: 6,
    accuracy: 95,
    ideal: 20,
    falloff: 60,
    ammo: 48,
    crit: 5,
    weakspot: 105,
    stagger: 20,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Sorrow',
    saveFileSlug: '/weapon_sorrow',
    imagePath: '/items/weapons/sorrow.png',
    id: 'u2z8i3',
    dlc: 'base',
    description: `The last vestiges of a fallen sister, this mystical crossbow pistol has the ability to recall its bolts to heal the wielder.`,
    wikiLinks: [`https://remnant.wiki/Sorrow`],
    linkedItems: {
      mod: {
        name: 'Eulogy',
      },
    },
    damage: 45,
    rps: 2.6,
    magazine: 5,
    accuracy: 95,
    ideal: 19,
    falloff: 52,
    ammo: 45,
    crit: 10,
    weakspot: 115,
    stagger: 5,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Star Shot',
    imagePath: '/items/weapons/starshot.png',
    id: 'tldnuq',
    dlc: 'base',
    description: `Fires a fast moving projectile which explodes on contact. Explosion has no damage falloff.`,
    externalTokens: [`Amplitude`, `Explosive Damage`],
    wikiLinks: [`https://remnant.wiki/Star_Shot`],
    linkedItems: {
      mod: {
        name: 'Big Bang',
      },
    },
    damage: 22,
    rps: 2.5,
    magazine: 10,
    accuracy: 95,
    ideal: 21,
    falloff: 54,
    ammo: 60,
    crit: 5,
    weakspot: 110,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Sureshot',
    saveFileSlug: 'weapon_huntingpistol',
    imagePath: '/items/weapons/huntingpistol.png',
    id: '50i9nj',
    dlc: 'base',
    description: `A high-caliber single-shot hunting pistol that inflicts heavy damage at mid to long range.`,
    wikiLinks: [`https://remnant.wiki/Sureshot`],
    damage: 110,
    rps: 3,
    magazine: 1,
    accuracy: 80,
    ideal: 22,
    falloff: 75,
    ammo: 24,
    crit: 10,
    weakspot: 110,
    stagger: 10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Tech 22',
    imagePath: '/items/weapons/tech22.png',
    id: 'xj5syj',
    dlc: 'base',
    description: `A suppressed small-caliber automatic pistol with medium magazine capacity and a high fire rate.`,
    wikiLinks: [`https://remnant.wiki/Tech_22`],
    damage: 8,
    rps: 16,
    magazine: 30,
    accuracy: 95,
    ideal: 15,
    falloff: 45,
    ammo: 330,
    crit: 10,
    weakspot: 100,
    stagger: -10,
  },
  {
    category: 'weapon',
    type: 'hand gun',
    name: 'Western Classic',
    saveFileSlug: 'weapon_revolver',
    imagePath: '/items/weapons/westernclassic.png',
    id: 'hk5uls',
    dlc: 'base',
    description: `A classic six-shooter. Tough. Dependable.`,
    wikiLinks: [`https://remnant.wiki/Western_Classic`],
    damage: 36,
    rps: 5.75,
    magazine: 6,
    accuracy: 95,
    ideal: 18,
    falloff: 48,
    ammo: 72,
    crit: 5,
    weakspot: 105,
    stagger: 5,
  },
]
