import { type PrismItem } from '@/app/(items)/_types/prism-item';

export const prismItems: PrismItem[] = [
  {
    category: 'prism',
    name: 'Prism of Greed',
    id: 'zn2x47',
    dlc: 'base',
    imagePath: '/items/prisms/prismofgreed.png',
    saveFileSlug: 'PrismOfGreed_C',
    description: '',
    wikiLinks: ['https://remnant.wiki/Prism'],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
  },
  {
    category: 'prism',
    name: 'Prism of Hatred',
    id: 't15adx',
    dlc: 'base',
    imagePath: '/items/prisms/prismofhatred.png',
    saveFileSlug: 'PrismOfHatred_C',
    description: '',
    wikiLinks: ['https://remnant.wiki/Prism'],
    location: { world: 'Any', dungeon: 'Quest' },
  },
  {
    category: 'prism',
    name: 'Prism of Jealousy',
    id: 'ked8b3',
    dlc: 'base',
    imagePath: '/items/prisms/prismofjealousy.png',
    saveFileSlug: 'PrismOfJealousy_C',
    description: '',
    wikiLinks: ['https://remnant.wiki/Prism'],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
  },
  {
    category: 'prism',
    name: 'Prism of Lethargy',
    id: '0nbaj2',
    dlc: 'base',
    imagePath: '/items/prisms/prismoflethargy.png',
    saveFileSlug: 'PrismOfLethargy_C',
    description: '',
    wikiLinks: ['https://remnant.wiki/Prism'],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
  },
  {
    category: 'prism',
    name: 'Prism of Passion',
    id: 'j2uus8',
    dlc: 'base',
    imagePath: '/items/prisms/prismofpassion.png',
    saveFileSlug: 'PrismOfPassion_C',
    description: '',
    wikiLinks: ['https://remnant.wiki/Prism'],
    location: { world: 'Any', dungeon: 'Quest' },
  },
  {
    category: 'prism',
    name: 'Prism of Pride',
    id: '03034f',
    dlc: 'base',
    imagePath: '/items/prisms/prismofpride.png',
    saveFileSlug: 'PrismOfPride_C',
    description: '',
    wikiLinks: ['https://remnant.wiki/Prism'],
    location: { world: 'Any', dungeon: 'Quest' },
  },
  {
    category: 'prism',
    name: 'Prism of Voracity',
    id: '16tce1',
    dlc: 'base',
    imagePath: '/items/prisms/prismofvoracity.png',
    saveFileSlug: 'PrismOfVoracity_C',
    description: '',
    wikiLinks: ['https://remnant.wiki/Prism'],
    location: { world: 'Any', dungeon: 'Quest' },
  },
];
