import type { PylonItem } from '@/app/(items)/_types/pylons';

export const pylonItems: PylonItem[] = [
  {
    category: 'pylon',
    name: 'Accelerator',
    imagePath: '/items/pylons/accelerator.png',
    id: '92Ros5',
    dlc: 'base',
    tags: [],
    description: 'Increases melee speed by 7.5% -> 37.5%',
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Charger',
    imagePath: '/items/pylons/charger.png',
    id: 'iuLVM7',
    dlc: 'base',
    tags: [],
    description: `Increases mod buildup by 20% -> 100%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Chopper',
    imagePath: '/items/pylons/chopper.png',
    id: '2GyUmM',
    dlc: 'base',
    tags: [],
    description: `Increases all melee damage by 15% -> 75%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Detonate',
    imagePath: '/items/pylons/detonate.png',
    id: 'D04fKt',
    dlc: 'base',
    tags: [],
    description: `Buildup, then release a shockwave when taking direct damage`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Explosive',
    imagePath: '/items/pylons/explosive.png',
    id: '5KmdJi',
    dlc: 'base',
    tags: [],
    description: `Enemies explode on death`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Frantic',
    imagePath: '/items/pylons/frantic.png',
    id: 'wtc7JH',
    dlc: 'base',
    tags: [],
    description: `Reduces skill cooldown by -10% -> -50%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Hardened',
    imagePath: '/items/pylons/hardened.png',
    id: 'kO0r7o',
    dlc: 'base',
    tags: [],
    description: `Increases damage reduction by 5% -> 25%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Healer',
    imagePath: '/items/pylons/healer.png',
    id: 'Rv407e',
    dlc: 'base',
    tags: [],
    description: `Increases healing effectiveness by 10% -> 50%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Healing Orbs',
    imagePath: '/items/pylons/healing-orbs.png',
    id: 'n2ooKj',
    dlc: 'base',
    tags: [],
    description: `Chance to spawn healing orbs on kill`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Hexer',
    imagePath: '/items/pylons/hexer.png',
    id: '9dgyUD',
    dlc: 'base',
    tags: [],
    description: `Fire homing projectiles when taking Direct damage`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Intensity',
    imagePath: '/items/pylons/intensity.png',
    id: 'VLw3Bt',
    dlc: 'base',
    tags: [],
    description: `Increases status damage by 10% -> 50%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Magnify',
    imagePath: '/items/pylons/magnify.png',
    id: 'tQ82Lm',
    dlc: 'base',
    tags: [],
    description: `Increases Critical Hit Damage by 10% -> 50%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Magus',
    imagePath: '/items/pylons/magus.png',
    id: '5e2NTe',
    dlc: 'base',
    tags: [],
    description: `Increases mod damage by 10% -> 50%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Nimble Hands',
    imagePath: '/items/pylons/nimble-hands.png',
    id: 'M8RcjQ',
    dlc: 'base',
    tags: [],
    description: `Increases reload speed by 20% -> 100%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Precision',
    imagePath: '/items/pylons/precision.png',
    id: 'kZ0vG7',
    dlc: 'base',
    tags: [],
    description: `Increases weakspot damage by 10% -> 50%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Ranger',
    imagePath: '/items/pylons/ranger.png',
    id: 'F5FId6',
    dlc: 'base',
    tags: [],
    description: `Increases all ranged damage by 10% -> 50%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Renewal',
    imagePath: '/items/pylons/renewal.png',
    id: 'PVXD5h',
    dlc: 'base',
    tags: [],
    description: `Increases health regeneration by 0.4% -> 2%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Reserve',
    imagePath: '/items/pylons/reserve.png',
    id: '6qLosL',
    dlc: 'base',
    tags: [],
    description: `Increases ammo reserves by 30% -> 150%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Shocking',
    imagePath: '/items/pylons/shocking.png',
    id: 'RYWP5h',
    dlc: 'base',
    tags: [],
    description: `Create lightning strikes on successful charged melee`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Spinner',
    imagePath: '/items/pylons/spinner.png',
    id: 'J9Fg4X',
    dlc: 'base',
    tags: [],
    description: `Gain Spinning Orbs to Damage enemies on contact`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Stamina',
    imagePath: '/items/pylons/stamina.png',
    id: '9Q0Cpt',
    dlc: 'base',
    tags: [],
    description: `Increases maximum stamina by 10 -> 50`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Staves',
    imagePath: '/items/pylons/staves.png',
    id: 'MmH8iM',
    dlc: 'base',
    tags: [],
    description: `Chance to summon a root staff on kill`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Technique',
    imagePath: '/items/pylons/technique.png',
    id: '901wcX',
    dlc: 'base',
    tags: [],
    description: `Increases skill damage by 10% -> 50%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Trapper',
    imagePath: '/items/pylons/trapper.png',
    id: '3Umm36',
    dlc: 'base',
    tags: [],
    description: `Chance to drop glitch puddles on hit`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Trigger Finger',
    imagePath: '/items/pylons/trigger-finger.png',
    id: 'Ka0EgY',
    dlc: 'base',
    tags: [],
    description: `Increases fire rate by 7.5% -> 37.5%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Velocity',
    imagePath: '/items/pylons/velocity.png',
    id: 'dRhU3j',
    dlc: 'base',
    tags: ['Movement Speed'],
    description: `Increases movement speed by 10% -> 50%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Vigor',
    imagePath: '/items/pylons/vigor.png',
    id: 'A9dgyw',
    dlc: 'base',
    tags: ['Health'],
    description: `Increases maximum health by 10 -> 50`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Volatile',
    imagePath: '/items/pylons/volatile.png',
    id: '6yhiBu',
    dlc: 'base',
    tags: [],
    externalTokens: ['Explosive Damage'],
    description: `Increases explosive damage by 10% -> 50%`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
  {
    category: 'pylon',
    name: 'Vortex',
    imagePath: '/items/pylons/vortex.png',
    id: 'w1eARX',
    dlc: 'base',
    tags: [],
    description: `Chance to spawn a black hole on hit`,
    wikiLinks: [`https://remnant.wiki/Boss_rush`],
  },
];
