import { type RelicFragmentItem } from '@/app/(items)/_types/relic-fragment-item';

export const relicFragmentItems: RelicFragmentItem[] = [
  {
    category: 'relicfragment',
    name: 'Ammo Pickups',
    imagePath: '/items/relicfragments/ammo_pickups.png',
    saveFileSlug: 'RelicFragment_AmmoPickups_C',
    id: 'j1aele',
    dlc: 'base',
    tags: ['Ammo Reserves'],
    description: 'Ammo Pickups, +30% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ammo Reserves',
    imagePath: '/items/relicfragments/ammo_reserves.png',
    saveFileSlug: 'RelicFragment_AmmoReserves_C',
    id: '3aqiq5',
    dlc: 'base',
    tags: ['Ammo Reserves'],
    description: 'Ammo Reserves, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Armor Effectiveness',
    imagePath: '/items/relicfragments/armor_effectiveness.png',
    saveFileSlug: 'RelicFragment_ArmorEffectiveness_C',
    id: '7u1bma',
    dlc: 'base',
    tags: ['Damage Reduction'],
    description: 'Armor Effectiveness, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    armorPercent: 0.1,
  },
  {
    category: 'relicfragment',
    name: 'Blight Resistance',
    imagePath: '/items/relicfragments/blight_resistance.png',
    saveFileSlug: 'RelicFragment_BlightResistance_C',
    id: '8q8xe3',
    dlc: 'base',
    tags: ['Armor Increase', 'Damage Reduction'],
    description: 'Blight Resistance, +30% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    blightResistance: 30,
  },
  {
    category: 'relicfragment',
    name: 'Casting Speed',
    imagePath: '/items/relicfragments/casting_speed.png',
    saveFileSlug: 'RelicFragment_CastSpeed_C',
    id: '51y6ih',
    dlc: 'base',
    tags: ['Mod Cast Speed', 'Skill Cast Speed'],
    description: 'Casting Speed, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Charge Melee Cost',
    imagePath: '/items/relicfragments/charge_melee_cost.png',
    saveFileSlug: 'RelicFragment_ChargeMeleeCost_C',
    id: 'fuikyq',
    dlc: 'base',
    tags: ['Charged Melee', 'Stamina'],
    description: 'Charge Melee Cost, -30% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Consumable Duration',
    imagePath: '/items/relicfragments/consumable_duration.png',
    saveFileSlug: 'RelicFragment_ConsumableDuration_C',
    id: 'xqklut',
    dlc: 'base',
    description: 'Consumable Duration, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Consumable Speed',
    imagePath: '/items/relicfragments/consumable_speed.png',
    saveFileSlug: 'RelicFragment_ConsumableSpeed_C',
    id: 'omefk5',
    dlc: 'base',
    tags: ['Relic Use Speed'],
    description: 'Consumable Speed, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Damage Reduction',
    imagePath: '/items/relicfragments/damage_reduction.png',
    saveFileSlug: 'RelicFragment_DamageReduction_C',
    id: '1pddio',
    dlc: 'base',
    tags: ['Damage Reduction'],
    description: 'Damage Reduction, +5% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Elemental Damage',
    imagePath: '/items/relicfragments/elemental_damage.png',
    saveFileSlug: 'RelicFragment_ElementalDamage_C',
    id: 'erp2mp',
    dlc: 'base',
    tags: ['Status Effect'],
    description: 'Elemental Damage, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Elemental Resistance',
    imagePath: '/items/relicfragments/elemental_resistance.png',
    saveFileSlug: 'RelicFragment_ElementalResistance_C',
    id: 'j7k57r',
    dlc: 'base',
    tags: ['Damage Reduction'],
    description: 'Elemental Resistance, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    bleedResistance: 0,
    fireResistance: 10,
    shockResistance: 10,
    blightResistance: 0,
    toxinResistance: 10,
  },
  {
    category: 'relicfragment',
    name: 'Grey Health Rate',
    imagePath: '/items/relicfragments/grey_health_rate.png',
    saveFileSlug: 'RelicFragment_GreyHealthRate_C',
    id: 'aci99s',
    dlc: 'base',
    tags: ['Grey Health'],
    description: 'Grey Health Rate, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Healing Effectiveness',
    imagePath: '/items/relicfragments/healing_effectiveness.png',
    saveFileSlug: 'RelicFragment_HealingEffectiveness_C',
    id: 'y52c32',
    dlc: 'base',
    tags: ['Healing Effectiveness'],
    description: 'Healing Effectiveness, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Health',
    imagePath: '/items/relicfragments/health.png',
    saveFileSlug: 'RelicFragment_Health_C',
    id: 'j87rzn',
    dlc: 'base',
    tags: ['Health'],
    description: 'Health, +15% (x1.15) at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    healthPercent: 0.15,
  },
  {
    category: 'relicfragment',
    name: 'Melee Speed',
    imagePath: '/items/relicfragments/melee_attack_speed.png',
    saveFileSlug: 'RelicFragment_MeleeAttackSpeed_C',
    id: 't8jgpe',
    dlc: 'base',
    tags: ['Melee Attack Speed'],
    description: 'Melee Speed, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Melee Critical Chance',
    saveFileSlug: 'RelicFragment_MeleeCritChance_C',
    imagePath: '/items/relicfragments/melee_critical_chance.png',
    id: 'm16fn9',
    dlc: 'base',
    tags: ['Critical Chance', 'Melee Critical Chance'],
    description: 'Melee Critical Chance, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Melee Critical Damage',
    saveFileSlug: 'RelicFragment_MeleeCritDamage_C',
    imagePath: '/items/relicfragments/melee_critical_damage.png',
    id: '77ch7i',
    dlc: 'base',
    tags: ['Melee Critical Damage', 'Critical Damage'],
    description: 'Melee Critical Damage, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Melee Damage',
    imagePath: '/items/relicfragments/melee_damage.png',
    saveFileSlug: 'RelicFragment_MeleeDamage_C',
    id: 'yu7d57',
    dlc: 'base',
    tags: ['Melee Damage'],
    description: 'Melee Damage, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Mod Cost',
    imagePath: '/items/relicfragments/mod_cost.png',
    saveFileSlug: 'RelicFragment_ModCost_C',
    id: 's8pkj3',
    dlc: 'base',
    tags: ['Mod Cost'],
    description: 'Mod Cost, -10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Mod Damage',
    imagePath: '/items/relicfragments/mod_damage.png',
    saveFileSlug: 'RelicFragment_ModDamage_C',
    id: 'zkr2us',
    dlc: 'base',
    tags: ['Mod Damage'],
    description: 'Mod Damage, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Mod Duration',
    imagePath: '/items/relicfragments/mod_duration.png',
    saveFileSlug: 'RelicFragment_ModDuration_C',
    id: 'c2t1p6',
    dlc: 'base',
    tags: ['Mod Duration'],
    description: 'Mod Duration, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ranged Critical Chance',
    saveFileSlug: 'RelicFragment_RangedCritChance_C',
    imagePath: '/items/relicfragments/ranged_critical_chance.png',
    id: 'dp184t',
    dlc: 'base',
    tags: ['Critical Chance'],
    description: 'Ranged Critical Chance, +7.5% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ranged Critical Damage',
    saveFileSlug: 'RelicFragment_RangedCritDamage_C',
    imagePath: '/items/relicfragments/ranged_critical_damage.png',
    id: 'w5jmys',
    dlc: 'base',
    tags: ['Critical Damage'],
    description: 'Ranged Critical Damage, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ranged Damage',
    imagePath: '/items/relicfragments/ranged_damage.png',
    saveFileSlug: 'RelicFragment_RangedDamage_C',
    id: 'wlnbc1',
    dlc: 'base',
    tags: ['Ranged Damage'],
    description: 'Ranged Damage, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Ranged Fire Rate',
    imagePath: '/items/relicfragments/ranged_fire_rate.png',
    saveFileSlug: 'RelicFragment_RangedFireRate_C',
    id: 'w8ruyt',
    dlc: 'base',
    tags: ['Fire Rate'],
    description: 'Ranged Fire Rate, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Recoil',
    imagePath: '/items/relicfragments/recoil.png',
    saveFileSlug: 'RelicFragment_Recoil_C',
    id: 'ygdexg',
    dlc: 'base',
    tags: ['Recoil'],
    description: 'Recoil, -30% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Revive Speed',
    imagePath: '/items/relicfragments/revive_speed.png',
    saveFileSlug: 'RelicFragment_ReviveSpeed_C',
    id: '0jam5w',
    dlc: 'base',
    description: 'Revive Speed, +25% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Shield Effectiveness',
    imagePath: '/items/relicfragments/shield_effectiveness.png',
    saveFileSlug: 'RelicFragment_ShieldEffectiveness_C',
    id: 'alp59n',
    dlc: 'base',
    description: 'Shield Effectiveness, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Skill Cooldown',
    imagePath: '/items/relicfragments/skill_cooldown.png',
    saveFileSlug: 'RelicFragment_SkillCooldown_C',
    id: '2bqp66',
    dlc: 'base',
    tags: ['Reduce Skill Cooldown'],
    description: 'Skill Cooldown, -10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Skill Damage',
    imagePath: '/items/relicfragments/skill_damage.png',
    saveFileSlug: 'RelicFragment_SkillDamage_C',
    id: 'fuhykd',
    dlc: 'base',
    tags: ['Skill Damage'],
    description: 'Skill Damage, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Skill Duration',
    imagePath: '/items/relicfragments/skill_duration.png',
    saveFileSlug: 'RelicFragment_SkillDuration_C',
    id: '7c8uka',
    dlc: 'base',
    tags: ['Skill Duration'],
    description: 'Skill Duration, +10% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Spread Recovery',
    imagePath: '/items/relicfragments/spread_recovery.png',
    saveFileSlug: 'RelicFragment_SpreadRecovery_C',
    id: 'yk8dng',
    dlc: 'base',
    tags: ['Spread'],
    description: 'Spread Recovery, +30% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Stagger Damage',
    imagePath: '/items/relicfragments/stagger_damage.png',
    saveFileSlug: 'RelicFragment_StaggerDamage_C',
    id: '74x7jt',
    dlc: 'base',
    tags: ['Stagger'],
    description: 'Stagger Damage, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Stamina',
    imagePath: '/items/relicfragments/stamina.png',
    saveFileSlug: 'RelicFragment_Stamina_C',
    id: 'qqmdc0',
    dlc: 'base',
    tags: ['Stamina'],
    description: 'Stamina, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
    staminaPercent: 0.15,
  },
  {
    category: 'relicfragment',
    name: 'Stamina Cost',
    imagePath: '/items/relicfragments/stamina_cost.png',
    saveFileSlug: 'RelicFragment_StaminaCosts_C',
    id: 'lbtjq3',
    dlc: 'base',
    tags: ['Stamina'],
    description: 'Stamina Cost, -20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Stamina Recovery Delay',
    imagePath: '/items/relicfragments/stamina_recovery_delay.png',
    saveFileSlug: 'RelicFragment_StaminaRecoveryDelay_C',
    id: '0y36lm',
    dlc: 'base',
    tags: ['Stamina'],
    description: 'Stamina Recovery Delay, -30% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Weakspot Damage',
    imagePath: '/items/relicfragments/weakspot_damage.png',
    saveFileSlug: 'RelicFragment_RangedWeakspotDamage_C',
    id: 'oszz4u',
    dlc: 'base',
    tags: ['Weakspot Damage'],
    description: 'Weakspot Damage, +15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Weapon Spread',
    imagePath: '/items/relicfragments/weapon_spread.png',
    saveFileSlug: 'RelicFragment_WeaponSpread_C',
    id: 'oiiiu2',
    dlc: 'base',
    tags: ['Spread'],
    description: 'Weapon Spread, -15% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
  {
    category: 'relicfragment',
    name: 'Weapon Swap',
    imagePath: '/items/relicfragments/weapon_swap.png',
    saveFileSlug: 'RelicFragment_WeaponSwapSpeed_C',
    id: 'h9e463',
    dlc: 'base',
    description: 'Weapon Swap, +20% at max level.',
    wikiLinks: [`https://remnant.wiki/Relic_Fragment`],
  },
];
