import { RingItem } from './types/RingItem'

export const ringItems: RingItem[] = [
  {
    category: 'ring',
    name: "A'Taerii Booster",
    imagePath: '/items/rings/ataeriibooster.png',
    saveFileSlug: 'Ring_AtaeriiBooster_C',
    id: '27gn7b',
    dlc: 'base',
    tags: ['All Damage', 'Critical Chance'],
    description: `Heavy Weapons gain 10% additional damage and gain 10% additional Critical Chance in both Carry and Turret Mode.`,
    wikiLinks: [`https://remnant.wiki/A'Taerii_Booster`],
    location: { world: `N'Erud`, dungeon: `World Drop` },
  },
  {
    category: 'ring',
    name: 'Acid Stone',
    imagePath: '/items/rings/acidstone.png',
    saveFileSlug: 'Ring_AcidStone_C',
    id: 'q3qca2',
    dlc: 'base',
    description: `Increases ACID damage by 15% and ACID Resistance by 20%.`,
    wikiLinks: [`https://remnant.wiki/Acid_Stone`],
    location: { world: `Ward 13`, dungeon: 'Vendor' },
    toxinResistance: 15,
  },
  {
    category: 'ring',
    name: 'Ahanae Crystal',
    saveFileSlug: 'Ring_PanMageSigil_C',
    imagePath: '/items/rings/ahanaecrystal.png',
    id: 'azy0pj',
    dlc: 'base',
    tags: ['All Damage', 'Status Effect', 'Hardcore Reward'],
    description:
      'Deal 5% additional damage for each Status Effect the target is suffering from.',
    wikiLinks: [`https://remnant.wiki/Ahanae_Crystal`],
    location: { world: `Ward 13`, dungeon: 'Vendor' },
  },
  {
    category: 'ring',
    name: 'Akari War Band',
    imagePath: '/items/rings/akariwarband.png',
    saveFileSlug: 'Ring_AkariWarBand_C',
    id: '9siz0d',
    dlc: 'base',
    tags: ['Perfect Dodge', 'Critical Chance'],
    description: `Perfect Dodges increase Critical Chance by 10% and Critical Damage by 10% for 15s.`,
    wikiLinks: [`https://remnant.wiki/Akari_War_Band`],
    location: { world: `Ward 13`, dungeon: 'Vendor' },
  },
  {
    category: 'ring',
    name: 'Alchemy Stone',
    imagePath: '/items/rings/alchemystone.png',
    saveFileSlug: 'Ring_AlchemyStone_C',
    id: 'dgh4g8',
    dlc: 'base',
    tags: ['Lifesteal', 'Status Effect'],
    description: `Increases base Lifesteal by 6% while suffering from a negative STATUS or BLIGHT Effect.`,
    wikiLinks: [`https://remnant.wiki/Alchemy_Stone`],
    location: { world: 'Losomn', dungeon: `World Drop` },
  },
  {
    category: 'ring',
    name: 'Alumni Ring',
    imagePath: '/items/rings/alumniring.png',
    saveFileSlug: 'Ring_AlumniRing_C',
    id: 'll1vsx',
    dlc: 'base',
    tags: ['Elemental Damage'],
    description: 'Increases all Elemental damage dealt by 10%.',
    wikiLinks: [`https://remnant.wiki/Alumni_Ring`],
    location: { world: 'Losomn', dungeon: ['Morrow Parish'] },
  },
  {
    category: 'ring',
    name: 'Amber Moonstone',
    imagePath: '/items/rings/ambermoonstone.png',
    saveFileSlug: 'Ring_AmberMoonstone_C',
    id: 'pqez3b',
    dlc: 'base',
    tags: ['Damage Reduction', 'Status Effect'],
    description:
      'When Health drops below 35%, all incoming damage is reduced by 25% and wearer becomes immune to Temporary Status Effects.',
    wikiLinks: [`https://remnant.wiki/Amber_Moonstone`],
    location: { world: `Ward 13`, dungeon: 'Vendor' },
  },
  {
    category: 'ring',
    name: "Anastasija's Inspiration",
    imagePath: '/items/rings/anastasijasinspiration.png',
    saveFileSlug: 'Ring_AnastasijasInspiration_C',
    id: '7fmi47',
    dlc: 'base',
    tags: ['Heal'],
    description: `When receiving healing effects, gain HASTE for 10s.`,
    wikiLinks: [`https://remnant.wiki/Anastasija's_Inspiration`],
    location: { world: `Ward 13`, dungeon: 'Vendor' },
  },
  {
    category: 'ring',
    name: "Archer's Crest",
    imagePath: '/items/rings/archerscrest.png',
    saveFileSlug: 'Ring_ArchersCrest_C',
    id: '6bqghl',
    dlc: 'base',
    tags: ['Projectile Speed', 'Charged Shot'],
    description: `Increases Projectile Speed by 20% and Decreases Weapon Charge Time by 25%.`,
    wikiLinks: [`https://remnant.wiki/Archer's_Crest`],
    location: {
      world: 'Yaesha',
      biome: 'Ziggurats',
      injectable: 'Hidden Chamber',
    },
  },
  {
    category: 'ring',
    name: "Assassin's Seal",
    imagePath: '/items/rings/assassinsseal.png',
    saveFileSlug: 'Ring_AssassinsSeal_C',
    id: '8kyyav',
    dlc: 'base',
    tags: ['All Damage'],
    description: `Reduces enemy Awareness Range by 25%. Increases all damage dealt to enemies not targeting wearer by 10%.`,
    wikiLinks: [`https://remnant.wiki/Assassin's_Seal`],
    location: { world: 'Losomn', dungeon: ['Council Chamber'] },
  },
  {
    category: 'ring',
    name: 'Atonement Fold',
    imagePath: '/items/rings/atonementfold.png',
    saveFileSlug: 'Ring_AtonementFold_C',
    dlc: 'dlc1',
    id: 'ez01nk',
    tags: ['Critical Chance', 'Grey Health'], // The damage it causes is grey health
    description:
      'Self-inflicts BLEEDING Status upon the wearer, causing 1.1 BLEED damage per second. Increases Critical Chance by 5%.',
    wikiLinks: [`https://remnant.wiki/Atonement_Fold`],
    location: { world: 'Losomn', dungeon: ['Forlorn Coast'] },
  },
  {
    category: 'ring',
    name: 'Band Band',
    imagePath: '/items/rings/bandband.png',
    saveFileSlug: 'Ring_BandBand_C',
    id: 'mm6dj8',
    tags: ['Movement Speed', 'Health'],
    description: `Increases Speed of Revive and being Revived by 35%. Increases Downed Health and Downed Movement Speed by 100%.`,
    wikiLinks: [`https://remnant.wiki/Band_Band`],
    location: {
      world: 'Yaesha',
      biome: 'Ziggurats',
      injectable: 'Wind Hollow',
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Band of Accord',
    imagePath: '/items/rings/bandofaccord.png',
    saveFileSlug: 'Ring_BandOfAccord_C',
    id: 'id6lly',
    tags: ['Ammo Reserves'],
    description: `Ammo acquired on pickup is increased by 50% per ally also wearing this ring and is shared with other allies.`,
    wikiLinks: [`https://remnant.wiki/Band_of_Accord`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Band of the Fanatic',
    imagePath: '/items/rings/bandofthefanatic.png',
    saveFileSlug: 'Ring_BandOfTheFanatic_C',
    dlc: 'dlc1',
    id: 'gv12gw',
    tags: ['Status Effect', 'Status Duration'],
    description:
      'Increases Status Effect Damage by 30% and reduces Status Effect Duration by 50%.',
    wikiLinks: [`https://remnant.wiki/Band_of_the_Fanatic`],
    location: { world: 'Losomn', dungeon: ['Forlorn Coast'] },
  },
  {
    category: 'ring',
    name: "Berserker's Crest",
    imagePath: '/items/rings/berserkerscrest.png',
    saveFileSlug: 'Ring_BerserkersCrest_C',
    id: 'pi2zf8',
    tags: ['Melee Charge Speed', 'Charged Melee', 'Stamina'],
    description:
      'Increases Melee Speed by 10% and reduces Melee Stamina Cost by 30%.',
    wikiLinks: [`https://remnant.wiki/Berserker's_Crest`],
    dlc: 'base',
    location: {
      world: 'Yaesha',
      biome: 'Undead Tombs',
      injectable: 'Sarcophagus',
    },
  },
  {
    category: 'ring',
    name: 'Bisected Ring',
    imagePath: '/items/rings/bisectedring.png',
    saveFileSlug: 'Ring_BisectedRing_C',
    id: '7usn4n',
    tags: ['Stamina'],
    description:
      'Gain Infinite Stamina. All damage received is increased by 15%',
    wikiLinks: [`https://remnant.wiki/Bisected_Ring`],
    location: { world: 'Labyrinth', dungeon: ['Labyrinth'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Bitter Memento',
    imagePath: '/items/rings/bittermemento.png',
    saveFileSlug: 'Ring_BitterMemento_C',
    dlc: 'dlc1',
    id: 'eozlwb',
    tags: ['Grey Health'],
    description:
      "Forces 1% of wearer's Max Health to remain as Grey Health. Activating a skill converts 33.5% Max Health into Grey Health. Conversion cannot kill wearer.",
    wikiLinks: [`https://remnant.wiki/Bitter_Memento`],
    location: { world: 'Losomn', dungeon: ['Pathway of the Fallen'] },
  },
  {
    category: 'ring',
    name: 'Black Cat Band',
    imagePath: '/items/rings/blackcatband.png',
    saveFileSlug: 'Ring_BlackCatBand_C',
    id: 'ac27lx',
    tags: ['Movement Speed'],
    description: `When taking fatal damage, instead of dying, the wearer's Health will drop to 1, and Movement Speed will increase by 25% for 10s. 2m cooldown.`,
    wikiLinks: [`https://remnant.wiki/Black_Cat_Band`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Black Pawn Stamp',
    imagePath: '/items/rings/blackpawnstamp.png',
    saveFileSlug: 'Ring_BlackPawnStamp_C',
    id: '7kbu25',
    tags: ['Reduce Skill Cooldown'],
    description: `Reduces Cooldowns of Skills by 10%.`,
    wikiLinks: [`https://remnant.wiki/Black_Pawn_Stamp`],
    dlc: 'base',
    location: {
      world: 'Losomn',
      biome: 'Fae Palace',
      injectable: 'The Flames Event',
    },
  },
  {
    category: 'ring',
    name: 'Black Spinel',
    imagePath: '/items/rings/blackspinel.png',
    saveFileSlug: 'Ring_BlackSpinel.Ring_BlackSpinel_C',
    id: 'sq8ZUN',
    dlc: 'dlc2',
    tags: ['Status Effect', 'Heal'],
    description: `Applying a Negative Status Effect grants 2% Max Health per second for 3s. Applying or refreshing a Negative Status Effect while buff is active will increase the duration by 1.5s. Max 15s.`,
    wikiLinks: ['https://remnant.wiki/Black_Spinel'],
    location: { world: 'Losomn', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Blackout Ring',
    imagePath: '/items/rings/blackoutring.png',
    saveFileSlug: 'Ring_BlackoutRing_C',
    id: '6pzq37',
    tags: ['Reload Speed'],
    description:
      'Increases Reload Speed by 3% for every 20% of Magazine missing.',
    wikiLinks: [`https://remnant.wiki/Blackout_Ring`],
    location: {
      world: `N'Erud`,
      biome: `N'Erud Underworld`,
      injectable: 'Shockwire',
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Blasting Cap Ring',
    imagePath: '/items/rings/blastingcap.png',
    saveFileSlug: 'Ring_BlastingCapRing_C',
    id: 'ep14lr',
    description: 'Increases Explosive damage by 15%.',
    externalTokens: [`Explosive Damage`],
    wikiLinks: [`https://remnant.wiki/Blasting_Cap_Ring`],
    location: {
      world: `N'Erud`,
      dungeon: ['The Eon Vault', 'Timeless Horizon'],
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Blessed Ring',
    imagePath: '/items/rings/blessedring.png',
    saveFileSlug: 'Ring_BlessedRing_C',
    id: 'empffm',
    tags: ['Damage Reduction'],
    description: `After receiving a benefit from a Relic, gain 2 Stacks of BULWARK for 30s.`,
    wikiLinks: [`https://remnant.wiki/Blessed_Ring`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: `Bloodless King's Vow`,
    imagePath: '/items/rings/bloodlesskingsvow.png',
    saveFileSlug: 'Ring_BloodlessKingsVow.Ring_BloodlessKingsVow_C',
    id: 'WHgN93',
    dlc: 'dlc2',
    tags: ['Ranged Damage', 'Lifesteal'],
    description: `Gain 4% of base Ranged Damage dealt as Lifesteal.`,
    wikiLinks: [`https://remnant.wiki/Bloodless_King's_Vow`],
    location: { world: 'Yaesha', dungeon: [`Goddess's Rest`] },
  },
  {
    category: 'ring',
    name: 'Blood Jewel',
    imagePath: '/items/rings/bloodjewel.png',
    saveFileSlug: 'Ring_BloodJewel_C',
    id: 'rw8rn0',
    tags: ['Charged Melee'],
    description:
      'Charged Melee Attacks apply BLEEDING, dealing 520 BLEED damage over 20s.',
    wikiLinks: [`https://remnant.wiki/Blood_Jewel`],
    location: { world: 'Yaesha', dungeon: ['The Forbidden Grove'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Blood Tinged Ring',
    imagePath: '/items/rings/bloodtingedring.png',
    saveFileSlug: 'Ring_BloodTingedRing_C',
    id: 'pj7i9a',
    tags: ['Heal'],
    description: `Gain 2 Health Regeneration per second when within 25m of a BLEEDING entity.`,
    wikiLinks: [`https://remnant.wiki/Blood_Tinged_Ring`],
    location: { world: 'Yaesha', dungeon: ['The Lament'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Booster Ring',
    imagePath: '/items/rings/boosterring.png',
    saveFileSlug: 'Ring_BoosterRing_C',
    id: 'sdkwq2',
    description: `Increases all Status Resistances by 25.`,
    wikiLinks: [`https://remnant.wiki/Booster_Ring`],
    location: { world: 'Losomn', dungeon: 'World Drop' },
    bleedResistance: 25,
    fireResistance: 25,
    shockResistance: 25,
    toxinResistance: 25,
    blightResistance: 25,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Braided Thorns',
    imagePath: '/items/rings/braidedthorns.png',
    saveFileSlug: 'Ring_BraidedThorns_C',
    id: 'zdkh54',
    tags: ['Critical Chance'],
    description: 'Increases Critical Chance by 10%.',
    wikiLinks: [`https://remnant.wiki/Braided_Thorns`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Brawler's Pride",
    imagePath: '/items/rings/brawlerspride.png',
    saveFileSlug: 'Ring_BrawlersPride_C',
    id: '17ckov',
    tags: ['Melee Attack Speed'],
    description:
      'Increases Melee Attack Speed by 15% and Melee Critical Chance by 5%.',
    wikiLinks: [`https://remnant.wiki/Brawler's_Pride`],
    location: { world: 'Yaesha', dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: `Bridge Warden's Crest`,
    imagePath: '/items/rings/bridgewardenscrest.png',
    saveFileSlug: 'Ring_BridgeWardensCrest_C',
    dlc: 'dlc1',
    id: 't7sqw7',
    tags: ['Perfect Dodge', 'Damage Reduction', 'Melee Damage'],
    description: `Perfect Dodge increases Melee Damage by 20% for 10s. Perfect Evade Flop also gains 10% Damage Reduction for the duration.`,
    wikiLinks: [`https://remnant.wiki/Bridge_Warden's_Crest`],
    location: { world: 'Losomn', dungeon: ['Forlorn Coast'] },
  },
  {
    category: 'ring',
    name: 'Burden of the Audacious',
    imagePath: '/items/rings/burdenoftheaudacious.png',
    saveFileSlug: 'Ring_BurdenOfTheAudacious_C',
    id: 'k45qer',
    tags: ['Heal', 'Perfect Dodge'],
    description: `Decreases all healing by 50%. Perfect Dodges heal for 25% of Max Health.`,
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Audacious`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Departed',
    imagePath: '/items/rings/burdenofthedeparted.png',
    saveFileSlug: 'Ring_BurdenOfTheDeparted_C',
    dlc: 'dlc1',
    id: 'syutk7',
    tags: ['All Damage'],
    description:
      'Reduces Total Relic Charges by 33%. Increases All Damage dealt by 10%.',
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Departed`],
    location: { world: 'Losomn', dungeon: ['Chamber of the Faithless'] },
  },
  {
    category: 'ring',
    name: 'Burden of the Destroyer',
    imagePath: '/items/rings/burdenofthedestroyer.png',
    saveFileSlug: 'Ring_BurdenOfTheDestroyer_C',
    id: 'dgb0s9',
    tags: ['All Damage', 'Range'],
    description:
      'Decreases Range of all Firearms by 35%. Increases all damage dealt by 15%.',
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Destroyer`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Divine',
    imagePath: '/items/rings/burdenofthedivine.png',
    id: 'tvfpo7',
    saveFileSlug: 'Ring_BurdenOfTheDivine_C',
    description:
      'All damage dealt by the wearer is reduced by 15%. 30% of self healing applies to allies.',
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Divine`],
    location: {
      world: 'Losomn',
      biome: 'Losomn Sewers',
      injectable: 'Rising Tides',
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Follower',
    imagePath: '/items/rings/burdenofthefollower.png',
    saveFileSlug: 'Ring_BurdenOfTheFollower_C',
    id: 'b76cdv',
    tags: ['Fire Rate', 'Mod Power'],
    description:
      'Reduces Fire Rate by 15%. Increases Mod Power Generation by 30%.',
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Follower`],
    location: {
      world: 'Yaesha',
      biome: 'Ziggurats',
      injectable: 'Library',
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Gambler',
    imagePath: '/items/rings/burdenofthegambler.png',
    saveFileSlug: 'Ring_BurdenOfTheGambler_C',
    id: 'ctv31c',
    tags: ['Weakspot Damage', 'Critical Chance'],
    description: `Disables Weakspots. Increases Critical Chance by 10% and Critical Damage by 15%.`,
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Gambler`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Mariner',
    imagePath: '/items/rings/burdenofthemariner.png',
    saveFileSlug: 'Ring_BurdenOfTheMariner_C',
    id: 'k89bxv',
    tags: ['Mod Power'],
    description: `Increases Skill Cooldowns by 15%. Generate 15% additional Mod Power for each Skill on Cooldown.`,
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Mariner`],
    location: {
      world: `N'Erud`,
      biome: `N'Erud Wasteland`,
      injectable: `Ascension Spire`,
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Mason',
    imagePath: '/items/rings/burdenofthemason.png',
    saveFileSlug: 'Ring_BurdenOfTheMason.Ring_BurdenOfTheMason_C',
    id: 'k89bxz',
    dlc: 'dlc2',
    tags: ['Encumbrance', 'Melee Damage', 'Damage Reduction'],
    description: `Impairs Dodges by 1 Weight Class. Increases Melee damage by 35% of the wearer's total Damage Reduction.`,
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Mason`],
    location: { world: 'Yaesha', dungeon: ['Luminous Vale'] },
  },
  {
    category: 'ring',
    name: 'Burden of the Mesmer',
    imagePath: '/items/rings/burdenofthemesmer.png',
    saveFileSlug: 'Ring_BurdenOfTheMesmer.Ring_BurdenOfTheMesmer_C',
    id: 'fGFm6B',
    dlc: 'dlc2',
    tags: ['Health', 'All Damage', 'Damage Reduction'],
    description:
      "Reduces Max Health by 20%. Increases All Damage by 1% for every 5% of the wearer's total Damage Reduction.",
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Mesmer`],
    location: { world: 'Yaesha', dungeon: ['Ancient Canopy', 'Luminous Vale'] },
    healthCap: 0.2,
  },
  {
    category: 'ring',
    name: 'Burden of the Rebel',
    imagePath: '/items/rings/burdenoftherebel.png',
    saveFileSlug: 'Ring_BurdenOfTheRebel_C',
    id: 'z169p0',
    tags: ['Reduce Skill Cooldown', 'Relic Use Speed'],
    description:
      'Reduces Relic Use Speed by 25%. Reduces Skill Cooldowns by 15%.',
    wikiLinks: [`https://remnant.wiki/Burden_Of_The_Rebel`],
    location: { world: 'Yaesha', dungeon: ['The Red Throne'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Sciolist',
    imagePath: '/items/rings/burdenofthesciolist.png',
    saveFileSlug: 'Ring_BurdenOfTheSciolist_C',
    dlc: 'dlc1',
    id: '7xb5zr',
    tags: ['Mod Damage', 'Skill Damage', 'Ammo Reserves'],
    description:
      'Reduces Ammo Reserves by 20%. Increases Mod and Skill Damage by 15%.',
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Sciolist`],
    location: { world: 'Losomn', dungeon: ['Forlorn Coast'] },
  },
  {
    category: 'ring',
    name: 'Burden of the Stargazer',
    imagePath: '/items/rings/burdenofthestargazer.png',
    saveFileSlug: 'Ring_BurdenOfTheStargazer_C',
    id: 'kj85yo',
    tags: ['Reduce Skill Cooldown'],
    description: `Reduces Skill Cooldowns by 15%. Activating a Skill costs 15% Health.`,
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Stargazer`],
    location: {
      world: `N'Erud`,
      dungeon: [
        `Astropath's Respite`,
        'Spectrum Nexus',
        'Terminus Station',
        'Tower of the Unseen',
      ],
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Burden of the Warlock',
    imagePath: '/items/rings/burdenofthewarlock.png',
    saveFileSlug: 'Ring_BurdenOfTheWarlock_C',
    id: 'mdu1f6',
    tags: ['Mod Power', 'Grey Health'],
    description:
      'Reduces Mod Power Requirement by 15%. Activating a Mod costs 15% Health as Grey Health. Conversion cannot kill wearer.',
    wikiLinks: [`https://remnant.wiki/Burden_of_the_Warlock`],
    location: {
      world: 'Losomn',
      biome: 'Burning City',
      injectable: 'Fiery Graveyard',
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Captain's Insignia",
    imagePath: '/items/rings/captaininsignia.png',
    saveFileSlug: 'Ring_CaptainsInsignia_C',
    id: 'cu0w65',
    tags: ['Relic Use Speed'],
    description: `Increases Revive Speed and Relic Consume Speed by 25% per downed or dead ally. Max 2 stacks.`,
    wikiLinks: [`https://remnant.wiki/Captain's_Insignia`],
    location: { world: 'Yaesha', dungeon: [`Endaira's End`] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Cataloger's Jewel",
    imagePath: '/items/rings/catalogerjewel.png',
    saveFileSlug: 'Ring_CatalogersJewel_C',
    id: 'e6da79',
    tags: ['Mod Power'],
    description: `Automatically generates 10 Mod Power per second.`,
    wikiLinks: [`https://remnant.wiki/Cataloger's_Jewel`],
    location: {
      world: 'Losomn',
      dungeon: ['Malefic Palace', 'Beatific Palace'],
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Celerity Stone',
    imagePath: '/items/rings/celeritystone.png',
    saveFileSlug: 'Ring_CelerityStone_C',
    id: 'kt5ag1',
    tags: ['Relic Use Speed'],
    description: `Increases Consumable and Relic Use Speed by 25%.`,
    wikiLinks: [`https://remnant.wiki/Celerity_Stone`],
    location: { world: 'Yaesha', dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Closed Loop',
    imagePath: '/items/rings/closedloop.png',
    saveFileSlug: 'Ring_ClosedLoop.Ring_ClosedLoop_C',
    dlc: 'dlc2',
    id: 'Sm4o3R',
    tags: ['Charged Shot'],
    description: `Gain 5% of Max Health as SHIELD for 10s after a Charged Shot. Accumulation resets after 10s of inaction. Max 25% SHIELD.`,
    wikiLinks: [`https://remnant.wiki/Closed_Loop`],
    location: { world: `N'Erud`, dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Compulsion Loop',
    imagePath: '/items/rings/compulsionloop.png',
    saveFileSlug: 'Ring_CompulsionLoop_C',
    id: '6p71zo',
    tags: ['Fire Rate', 'Melee Attack Speed'],
    description: `After killing an enemy, gain 5% Fire Rate and Melee Attack Speed for 10s. Stacks 3x.`,
    wikiLinks: [`https://remnant.wiki/Compulsion_Loop`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Conjurer's Circle",
    imagePath: '/items/rings/conjurerscircle.png',
    saveFileSlug: 'Ring_ConjurersCircle.Ring_ConjurersCircle_C',
    id: 'k89bxd',
    dlc: 'dlc2',
    tags: ['Stagger', 'Grey Health', 'Summon'],
    description:
      "When the wearer's Summon enters the battlefield, conjure a 5m Summoning Circle. Allies in the Summoning Circle have their Stagger Level reduced by 1 and regenerates 5 Grey Health per second. Lasts 10s.\n" +
      '\n' +
      'Can only happen once every 10s after expiring.',
    externalTokens: [`Amplitude`],
    wikiLinks: [`https://remnant.wiki/Conjurer's_Circle`],
    location: { world: 'Yaesha', dungeon: ['Infested Abyss'] },
  },
  {
    category: 'ring',
    name: 'Conservation Seal',
    imagePath: '/items/rings/conservationseal.png',
    saveFileSlug: 'Ring_ConservationSeal_C',
    id: 'fa7066',
    tags: ['Healing Effectiveness'],
    description:
      'For every 10% of Health missing [Max 50%], gain 10% chance to not consume Relic and 5% increased Relic Efficacy on next use.',
    wikiLinks: [`https://remnant.wiki/Conservation_Seal`],
    location: { world: `N'Erud`, dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Constant Variable Ring',
    imagePath: '/items/rings/constantvariable.png',
    saveFileSlug: 'Ring_ConstantVariableRing_C',
    id: 'dyr6ej',
    tags: ['Ranged Damage', 'Heat Generation'],
    description: `Increases Ranged damage up to 20% based on current Weapon's Overheat value.`,
    wikiLinks: [`https://remnant.wiki/Constant_Variable_Ring`],
    location: {
      world: `N'Erud`,
      biome: `Towers of N'Erud`,
      injectable: `Remains Below`,
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Crimson Dreamstone',
    imagePath: '/items/rings/crimsondreamstone.png',
    saveFileSlug: 'Ring_CrimsonDreamstone_C',
    dlc: 'dlc1',
    id: 's916uj',
    tags: ['Critical Hit', 'Skill Damage'],
    description:
      'Critical Hits increase Skill Damage by 2% for 5s. Max 10 stacks.',
    wikiLinks: [`https://remnant.wiki/Crimson_Dreamstone`],
    location: {
      world: 'Losomn',
      biome: 'Burning City',
      injectable: 'Ethereal Manor',
    },
  },
  {
    category: 'ring',
    name: 'Dark Sea Armada Crest',
    imagePath: '/items/rings/darkseaarmadacrest.png',
    saveFileSlug: 'Ring_DarkSeaArmadaCrest.Ring_DarkSeaArmadaCrest_C',
    id: 'Zj9qF5',
    dlc: 'dlc2',
    tags: ['Elemental Damage'],
    description: `On Relic Use, increases All Elemental Damage dealt by 15% for 15s.`,
    wikiLinks: [`https://remnant.wiki/Dark_Sea_Armada_Crest`],
    location: { world: 'Yaesha', dungeon: ['Proving Grounds'] },
  },
  {
    category: 'ring',
    name: "Dead King's Memento",
    imagePath: '/items/rings/deadkingsmemento.png',
    saveFileSlug: 'Ring_DeadKingsMemento_C',
    id: 'vbxfcp',
    tags: ['Health'],
    description: `Increases Health by 15.`,
    wikiLinks: [`https://remnant.wiki/Dead_King's_Memento`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    health: 15,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Deceiver's Band",
    imagePath: '/items/rings/deceiversband.png',
    saveFileSlug: 'Ring_DeceiversBand_C',
    id: '1dmpt8',
    tags: ['Movement Speed'],
    description:
      'After performing a Slide, gain 15% Evade Speed and 10% Movement Speed for 12s.',
    wikiLinks: [`https://remnant.wiki/Deceiver's_Band`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Deep Pocket Ring',
    imagePath: '/items/rings/deeppocketring.png',
    saveFileSlug: 'Ring_DeepPocketRing_C',
    id: '9bnfhm',
    tags: ['Ammo Reserves'],
    description: `Increases Ammo Reserves by 35%.`,
    wikiLinks: [`https://remnant.wiki/Deep_Pocket_Ring`],
    location: { world: `N'Erud`, dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Defensive Action Loop',
    imagePath: '/items/rings/defensiveactionloop.png',
    saveFileSlug: 'Ring_DefensiveActionLoop_C',
    id: '3krgp4',
    tags: ['Damage Reduction'],
    description: `While reloading, and for 3s after reload completes, incoming damage is reduced by 10%.`,
    wikiLinks: [`https://remnant.wiki/Defensive_Action_Loop`],
    location: { world: `N'Erud`, dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dense Silicon Ring',
    imagePath: '/items/rings/densesilicon.png',
    saveFileSlug: 'Ring_DenseSiliconRing_C',
    id: 'b91hx9',
    tags: ['Mod Power'],
    description: `Gain 200% of Health Regenerated as Mod Power.`,
    wikiLinks: [`https://remnant.wiki/Dense_Silicon_Ring`],
    location: { world: 'Labyrinth', dungeon: ['Labyrinth'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Devoured Loop',
    imagePath: '/items/rings/devouredloop.png',
    saveFileSlug: 'Ring_DevouringLoop_C',
    id: 'l8a2e1',
    tags: ['Critical Hit', 'Reduce Skill Cooldown'],
    description: `Critical Hits have a 1% chance to reset Skill Cooldowns. Can only occur once every 10s. Increases all incoming damage by 10%`,
    wikiLinks: [`https://remnant.wiki/Devoured_Loop`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Digested Hog Lure',
    imagePath: '/items/rings/digestedhoglure.png',
    saveFileSlug: 'Ring_DigestedHogLure_C',
    dlc: 'dlc1',
    id: 'v4yzc6',
    tags: ['Mod Damage'],
    description: 'Reloading increases Mod Damage by 15% for 7s.',
    wikiLinks: [`https://remnant.wiki/Digested_Hog_Lure`],
    location: { world: 'Losomn', dungeon: ['Forlorn Coast'] },
  },
  {
    category: 'ring',
    name: 'Drakestone Pearl',
    imagePath: '/items/rings/drakestonepearl.png',
    saveFileSlug: 'Ring_DrakestonePearl_C',
    id: 'r1dqm9',
    tags: ['Stamina', 'Melee Damage'],
    description: `Enables Stamina Regeneration during Melee Attacks at 20% of the normal rate.`,
    wikiLinks: [`https://remnant.wiki/Drakestone_Pearl`],
    location: {
      world: 'Losomn',
      dungeon: ['The Great Sewers', `Tiller's Rest`],
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dran Memento',
    imagePath: '/items/rings/dranmemento.png',
    saveFileSlug: 'Ring_DranMemento_C',
    id: 'fojjag',
    tags: ['Stamina', 'Encumbrance'],
    description: `Increases Max Stamina by 20 and reduces Encumbrance by 5.`,
    wikiLinks: [`https://remnant.wiki/Dran_Memento`],
    location: { world: 'Losomn', dungeon: [`Butcher's Quarter`] },
    weight: -5,
    stamina: 20,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dran Scavenger Ring',
    saveFileSlug: 'Ring_DranScavengerSigil_C',
    imagePath: '/items/rings/dranscavengersigil.png',
    id: '5pwtei',
    tags: ['Heal', 'All Damage', 'Hardcore Reward'],
    description:
      'Collecting Scrap, Iron, and Ammo Pickups regenerates 50% of Max Health and increases all damage dealt by 8% for 30s.',
    wikiLinks: [`https://remnant.wiki/Dran_Scavenger_Ring`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dread Font',
    imagePath: '/items/rings/dreadfont.png',
    saveFileSlug: 'Ring_DreadFont_C',
    id: '5k6zdd',
    tags: ['Grey Health', 'Heal'],
    description: `Increases Grey Health Regeneration rate by 2 per second.`,
    wikiLinks: [`https://remnant.wiki/Dread_Font`],
    location: { world: 'Losomn', dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dried Clay Ring',
    imagePath: '/items/rings/driedclayring.png',
    saveFileSlug: 'Ring_DriedClayRing_C',
    id: 'ez6z8b',
    tags: ['Damage Reduction', 'All Damage'],
    description:
      'Grants 1 stack of BULWARK. Increases All Damage by 50% of the Total Damage Reduction granted by BULWARK stacks.',
    wikiLinks: [`https://remnant.wiki/Dried_Clay_Ring`],
    location: { world: 'Losomn', dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Drzyr Sniper Sigil',
    imagePath: '/items/rings/drzyrsnipersigil.png',
    saveFileSlug: 'Ring_DrzyrSniperSigil_C',
    id: 'gtli7e',
    tags: ['Hardcore Reward'],
    description:
      'Increases the minimum damage at Max Falloff Range from 20% to 40%.',
    wikiLinks: [`https://remnant.wiki/Drzyr_Sniper_Sigil`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dull Steel Ring',
    saveFileSlug: 'Ring_BrightSteelRing_C',
    imagePath: '/items/rings/dullsteelring.png',
    id: 's76ytc',
    tags: ['Encumbrance'],
    description: 'Improves Dodges by 1 Weight Class.',
    wikiLinks: [`https://remnant.wiki/Dull_Steel_Ring`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    weightThreshold: 25,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Dying Ember',
    imagePath: '/items/rings/dyingember.png',
    saveFileSlug: 'Ring_DyingEmber_C',
    id: 'mv9b18',
    tags: ['Melee Damage', 'Lifesteal'],
    description: `Gain 6% of base Melee damage dealt as Lifesteal.`,
    wikiLinks: [`https://remnant.wiki/Dying_Ember`],
    location: { world: 'Root Earth', dungeon: ['Ashen Wasteland'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Elevated Ring',
    imagePath: '/items/rings/elevatedring.png',
    saveFileSlug: 'Ring_ElevatedRing_C',
    dlc: 'dlc1',
    id: '5dipaq',
    tags: ['Encumbrance'],
    description:
      'Increases Dodge Weight Threshold by 10. Reduces Encumbrance by 10.',
    wikiLinks: [`https://remnant.wiki/Elevated_Ring`],
    location: { world: 'Losomn', dungeon: ['Forlorn Coast'] },
    weight: -10,
    weightThreshold: 10,
  },
  {
    category: 'ring',
    name: "Embrace of Sha'Hala",
    saveFileSlug: 'Ring_DowngradedRing_C',
    imagePath: '/items/rings/embraceofshahala.png',
    id: 'h2g5z3',
    tags: ['Damage Reduction', 'Status Effect'],
    description:
      'Wearer gains 7.5% incoming Damage Reduction when suffering from a unique Negative Status Effect or Blight. Max 2 stacks.',
    wikiLinks: [`https://remnant.wiki/Embrace_of_Sha'Hala`],
    location: {
      world: `N'Erud`,
      biome: `N'Erud Wasteland`,
      injectable: `Ascension Spire`,
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Encrypted Ring',
    saveFileSlug: 'Ring_EncryptedLoop_C',
    imagePath: '/items/rings/encryptedring.png',
    id: 'g1u6gi',
    tags: ['Heal'],
    description:
      'Using a Mod regenerates 20% of Max Health over 10s. Can stack up to 30s.',
    wikiLinks: [`https://remnant.wiki/Encrypted_Ring`],
    location: { world: 'Labyrinth', dungeon: ['Labyrinth'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Endaira's Endless Loop",
    imagePath: '/items/rings/endairasendlessloop.png',
    saveFileSlug: 'Ring_EndairasEndlessLoop_C',
    id: 'bx0ulq',
    tags: ['Heal'],
    description: `After Sprinting for 1s, the wearer gains 2 Health Regeneration per second until they stop Sprinting.`,
    wikiLinks: [`https://remnant.wiki/Endaira's_Endless_Loop`],
    location: { world: 'Yaesha', dungeon: [`Endaira's End`] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Excess Coil',
    imagePath: '/items/rings/excesscoil.png',
    saveFileSlug: 'Ring_ExcessCoil_C',
    id: 'l5gfd1',
    description: `Activating a Skill grants a SHIELD for 25% of Max Health. Cannot stack with itself. Lasts 15s.`,
    wikiLinks: [`https://remnant.wiki/Excess_Coil`],
    location: {
      world: `N'Erud`,
      biome: `N'Erud Underworld`,
      injectable: `Robot Hangar`,
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Fae Bruiser Ring',
    imagePath: '/items/rings/faebruiserring.png',
    saveFileSlug: 'Ring_FaeBruiserRing_C',
    id: 't2ct6r',
    tags: ['Melee Damage', 'Damage Reduction'],
    description:
      'Dealing Melee damage grants 2 Stacks of BULWARK for 15s. Does not stack with itself.',
    wikiLinks: [`https://remnant.wiki/Fae_Bruiser_Ring`],
    location: { world: 'Losomn', dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Fae Hunter Ring',
    imagePath: '/items/rings/faehunterring.png',
    saveFileSlug: 'Ring_FaeHunterRing_C',
    id: 'i4wkw2',
    tags: ['Range'],
    description: `Increases Range of Firearms by 35%.`,
    wikiLinks: [`https://remnant.wiki/Fae_Hunter_Ring`],
    location: { world: 'Losomn', dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Fae Protector Signet',
    imagePath: '/items/rings/faeprotectorsignet.png',
    saveFileSlug: 'Ring_FaeProtectorSignet_C',
    id: 'f2j9er',
    tags: ['Health', 'Stamina', 'Encumbrance'],
    description: `Increases Max Health and Stamina by 10 and Reduces Encumbrance by 5.`,
    wikiLinks: [`https://remnant.wiki/Fae_Protector_Signet`],
    location: { world: 'Losomn', dungeon: ['Council Chamber'] },
    health: 10,
    stamina: 10,
    weight: -5,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Fae Shaman Ring',
    imagePath: '/items/rings/faeshamanring.png',
    saveFileSlug: 'Ring_FaeShamanRing_C',
    id: '7okl48',
    tags: ['Heal', 'Relic Use Speed'],
    description:
      'Increases Health Regeneration by 0.35 and Relic Use Speed by 25%.',
    wikiLinks: [`https://remnant.wiki/Fae_Shaman_Ring`],
    location: { world: 'Losomn', dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Fae Warrior Ring',
    imagePath: '/items/rings/faewarriorring.png',
    saveFileSlug: 'Ring_FaeWarriorRing_C',
    id: '6ypnyx',
    tags: ['Melee Damage'],
    description: `Increases Melee Damage by 15%.`,
    wikiLinks: [`https://remnant.wiki/Fae_Warrior_Ring`],
    location: { world: 'Losomn', dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Faelin's Sigil",
    imagePath: '/items/rings/faelinsigil.png',
    saveFileSlug: 'Ring_FaelinsSigil_C',
    id: 'drjm15',
    tags: ['Melee Damage', 'Mod Power'],
    description: `Melee Damage generates 15% additional Mod Power.`,
    wikiLinks: [`https://remnant.wiki/Faelin's_Sigil`],
    location: {
      world: 'Losomn',
      dungeon: ['Malefic Gallery', 'Beatific Gallery'],
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Faerin's Sigil",
    imagePath: '/items/rings/faerinsigil.png',
    saveFileSlug: 'Ring_FaerinsSigil_C',
    id: '02wal9',
    tags: ['Critical Hit', 'Weakspot Damage', 'Mod Power'],
    description:
      'Critical and Weakspot Hits generate 12.5% additional Mod Power.',
    wikiLinks: [`https://remnant.wiki/Faerin's_Sigil`],
    location: {
      world: 'Losomn',
      dungeon: ['Beatific Gallery', 'Malefic Gallery'],
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: "Feastmaster's Signet",
    imagePath: '/items/rings/feastmastersignet.png',
    saveFileSlug: 'Ring_FeastmastersSignet_C',
    id: '5q53ke',
    tags: ['Concoction'],
    description: `Increases active Concoction Limit by 1.`,
    wikiLinks: [`https://remnant.wiki/Feastmaster's_Signet`],
    location: { world: 'Losomn', dungeon: ['The Great Hall'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Feathery Binding',
    imagePath: '/items/rings/featherybinding.png',
    saveFileSlug: 'Ring_FeatheryBinding.Ring_FeatheryBinding_C',
    id: 'zXq2H7',
    dlc: 'dlc2',
    tags: ['Charged Shot', 'Projectile Speed'],
    description: `Increases Projectile Speed by 15% and Decreases Weapon Charge Time by 10%. Bonus is doubled when HASTE is active.`,
    wikiLinks: [`https://remnant.wiki/Feathery_Binding`],
    location: { world: 'Yaesha', dungeon: ['Ancient Canopy', 'Luminous Vale'] },
  },
  {
    category: 'ring',
    name: 'Feedback Loop',
    imagePath: '/items/rings/feedbackloop.png',
    saveFileSlug: 'Ring_FeedbackLoop_C',
    id: 'j13xrf',
    tags: ['Perfect Dodge'],
    description:
      'Perfect Dodge triggers a 3m AOE blast that deals 55-155 SHOCK Damage and applies OVERLOADED which deals 55-155 SHOCK damage every 5s.',
    externalTokens: [`Amplitude`],
    wikiLinks: [`https://remnant.wiki/Feedback_Loop`],
    location: { world: `N'Erud`, dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Fire Stone',
    imagePath: '/items/rings/firestone.png',
    saveFileSlug: 'Ring_FireStone_C',
    id: 'go5hz8',
    description: `Increases FIRE damage by 15% and FIRE Resistance by 20.`,
    wikiLinks: [`https://remnant.wiki/Fire_Stone`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    fireResistance: 15,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Floodlit Diamond',
    imagePath: '/items/rings/floodlitdiamond.png',
    saveFileSlug: 'Ring_FloodlitDiamond.Ring_FloodlitDiamond_C',
    id: 'z9YJih',
    dlc: 'dlc2',
    tags: [],
    description: `Increases Weakspot Damage by 12%. Bonus is doubled against EXPOSED targets.`,
    wikiLinks: ['https://remnant.wiki/Floodlit_Diamond'],
    location: { world: 'Yaesha', dungeon: ['Proving Grounds'] },
  },
  {
    category: 'ring',
    name: "Flyweight's Sting",
    imagePath: '/items/rings/flyweightsting.png',
    saveFileSlug: 'Ring_FlyweightsSting_C',
    id: '1qg7a8',
    tags: ['Melee Damage', 'Encumbrance'],
    description: `Increases Melee damage while Armor Encumbrance is below 50. Damage bonus increases with lower Encumbrance, up to 25% at 0 Weight.`,
    wikiLinks: [`https://remnant.wiki/Flyweight's_Sting`],
    location: { world: 'Root Earth', dungeon: ['Corrupted Harbor'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Focusing Shard',
    saveFileSlug: 'Ring_FocusedJewel_C',
    imagePath: '/items/rings/focusedjewel.png',
    id: 'o7grsg',
    tags: ['Recoil', 'Spread'],
    description: 'Aiming Down Sights gradually reduces Spread by 70% over 4s.',
    wikiLinks: [`https://remnant.wiki/Focusing_Shard`],
    location: {
      world: `N'Erud`,
      biome: `N'Erud Underworld`,
      injectable: `Black Hole`,
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Frivolous Band',
    imagePath: '/items/rings/frivolousband.png',
    saveFileSlug: 'Ring_FrivolousBand_C',
    id: '4j9wo9',
    tags: ['Perfect Dodge', 'Fire Rate', 'Melee Speed'],
    description: `Increases Evade Speed by 10%. Perfect Evades increase Fire Rate by 10% and Melee Speed by 10% for 7s.`,
    wikiLinks: [`https://remnant.wiki/Frivolous_Band`],
    location: { world: 'Yaesha', dungeon: ['The Forbidden Grove'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Galvanized Resupply Band',
    imagePath: '/items/rings/galvanizedresupplyband.png',
    saveFileSlug: 'Ring_GalvanizedResupplyBand_C',
    id: 'y23znz',
    tags: ['Ammo Reserves'],
    description: `Increases Ammo Pickups by 100%.`,
    wikiLinks: [`https://remnant.wiki/Galvanized_Resupply_Band`],
    location: { world: `N'Erud`, dungeon: ['The Dark Conduit'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: `Game Master's Pride`,
    imagePath: '/items/rings/gamemasterspride.png',
    saveFileSlug: 'Ring_GameMastersPride_C',
    id: '4dstmt',
    tags: ['Heal', 'Damage Reduction'],
    description: `Reduces all healing by 50%. Splits all damage and remaining healing evenly among all allies wearing this ring.`,
    wikiLinks: [`https://remnant.wiki/Game_Master's_Pride`],
    location: { world: 'Losomn', dungeon: [`Postulant's Parlor`] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Generating Band',
    imagePath: '/items/rings/generatingband.png',
    saveFileSlug: 'Ring_GeneratingBand_C',
    id: 'fg8su2',
    tags: ['Heal'],
    description: `Regenerate 3% of Max Health per second while a SHIELD is active.`,
    wikiLinks: [`https://remnant.wiki/Generating_Band`],
    location: {
      world: `N'Erud`,
      biome: `N'Erud Underworld`,
      injectable: 'Sewage Facility',
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Grounding Stone',
    imagePath: '/items/rings/groundingstone.png',
    saveFileSlug: 'Ring_GroundingStone_C',
    id: 'o7vaf6',
    description: `Increases SHOCK damage by 15% and SHOCK Resistance by 20.`,
    wikiLinks: [`https://remnant.wiki/Grounding_Stone`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    shockResistance: 15,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: `Guardian's Ring`,
    imagePath: '/items/rings/guardiansring.png',
    saveFileSlug: 'Ring_GuardiansRing_C',
    id: 'yvo3jd',
    tags: ['Damage Reduction'],
    description:
      'Adds 1 Stack of BULWARK when within 15m of an enemy. Increases to 2 Stacks for 15s after taking Melee damage.',
    externalTokens: [`Amplitude`],
    wikiLinks: [`https://remnant.wiki/Guardian's_Ring`],
    location: { world: 'Yaesha', dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Gul Signet',
    imagePath: '/items/rings/gulsignet.png',
    saveFileSlug: 'Ring_GulSignet.Ring_GulSignet_C',
    dlc: 'dlc2',
    id: 'xG9CQJ',
    tags: ['Encumbrance', 'Damage Reduction'],
    description: `Increases Damage Reduction by 10%. Each Weight Class above LIGHT reduces Damage Reduction bonus by 2.5% (up to 3x).`,
    wikiLinks: [`https://remnant.wiki/Gul_Signet`],
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: `Gunslinger's Ring`,
    imagePath: '/items/rings/gunslingersring.png',
    saveFileSlug: 'Ring_GunslingersRing_C',
    id: '976r2x',
    tags: ['Reload Speed', 'Firearm Swap Speed'],
    description: `Increases Firearm Swap Speed by 30% and Reload Speed by 10%.`,
    wikiLinks: [`https://remnant.wiki/Gunslinger's_Ring`],
    location: { world: 'Ward 13', dungeon: 'Quest' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Hardcore Metal Band',
    imagePath: '/items/rings/hardcoremetalband.png',
    saveFileSlug: 'Ring_HardcoreMetalBand_C',
    id: 'f2ooga',
    tags: ['Damage Reduction'],
    description:
      'Taking damage adds 1 stack of BULWARK which individually falls off after 10s. Max 5 stacks.',
    wikiLinks: [`https://remnant.wiki/Hardcore_Metal_Band`],
    location: {
      world: `N'Erud`,
      dungeon: ['The Eon Vault', 'Timeless Horizon'],
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Hardened Coil',
    imagePath: '/items/rings/hardenedcoil.png',
    saveFileSlug: 'Ring_HardenedCoil_C',
    id: 'pvwud6',
    tags: ['Damage Reduction'],
    description:
      'Reduces all incoming damage by 3% for each 10% of missing Health. Max 15% reduction.',
    wikiLinks: [`https://remnant.wiki/Hardened_Coil`],
    location: {
      world: 'Yaesha',
      biome: 'Floating Forests',
      injectable: 'Broken Tomb',
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: `Haymaker's Ring`,
    imagePath: '/items/rings/haymakersring.png',
    saveFileSlug: 'Ring_HaymakersRing_C',
    id: '8azdr4',
    tags: ['Melee Damage', 'Encumbrance'],
    description:
      'Increase Melee damage by 0.2% for every 1 point of Armor Encumbrance.',
    wikiLinks: [`https://remnant.wiki/Haymaker's_Ring`],
    location: { world: 'Root Earth', dungeon: ['Ashen Wasteland'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Heart of the Wolf',
    imagePath: '/items/rings/heartofthewolf.png',
    saveFileSlug: 'Ring_HeartOfTheWolf_C',
    id: 'x74y2q',
    tags: ['Stamina', 'Movement Speed'],
    description: `Increases Max Stamina by 25 and Movement Speed by 10%.`,
    wikiLinks: [`https://remnant.wiki/Heart_Of_The_Wolf`],
    location: { world: 'Yaesha', dungeon: 'World Drop' },
    stamina: 25,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Hex Ward',
    imagePath: '/items/rings/hexward.png',
    saveFileSlug: 'Ring_HexWard_C',
    id: 'y45ad6',
    description: 'Prevents CURSE.',
    wikiLinks: [`https://remnant.wiki/Hex_Ward`],
    location: { world: 'Losomn', dungeon: [`Nimue's Retreat`] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Jewel of the Beholden',
    imagePath: '/items/rings/jewelofthebeholden.png',
    saveFileSlug: 'Ring_JewelOfTheBeholden_C',
    dlc: 'dlc1',
    id: 'sosywj',
    tags: ['Mod Damage'],
    description: 'On Relic Use, increase Mod Damage by 15% for 15s.',
    wikiLinks: [`https://remnant.wiki/Jewel_of_the_Beholden`],
    location: { world: 'Losomn', dungeon: ['Chamber of the Faithless'] },
  },
  {
    category: 'ring',
    name: 'Kinetic Cycle Stone',
    imagePath: '/items/rings/kineticcyclestone.png',
    saveFileSlug: 'Ring_KineticCycleStone_C',
    id: 'kpxowa',
    tags: ['Mod Cast Speed', 'Skill Cast Speed'],
    description: `Increases Mod and Skill Cast Speed by 20%.`,
    wikiLinks: [`https://remnant.wiki/Kinetic_Cycle_Stone`],
    location: { world: 'Root Earth', dungeon: ['Corrupted Harbor'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Kolket Eyelet',
    imagePath: '/items/rings/kolketeyelet.png',
    saveFileSlug: 'Ring_KolketEyelet.Ring_KolketEyelet_C',
    id: 'dp4w2B',
    dlc: 'dlc2',
    tags: [],
    description: `Grants 1 stack of BULWARK. Increases Health Regeneration by 0.3 per second for each stack of BULWARK.`,
    wikiLinks: [`https://remnant.wiki/Kolket_Eyelet`],
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Leaking Gemstone',
    imagePath: '/items/rings/leakinggemstone.png',
    saveFileSlug: 'Ring_LeakingGemstone.Ring_LeakingGemstone_C',
    id: 't5dv6X',
    dlc: 'dlc2',
    tags: [],
    description: `Allows 20% of Mod Power Generation to continue during an active mod.`,
    wikiLinks: [`https://remnant.wiki/Leaking_Gemstone`],
    location: { world: 'Losomn', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: "Lighthouse Keeper's Ring",
    imagePath: '/items/rings/lighthousekeepersring.png',
    saveFileSlug: 'Ring_LighthouseKeepersRing_C',
    dlc: 'dlc1',
    id: 't8u4k1',
    tags: ['Mod Power', 'Status Effect'],
    description: `Automatically generate 4 Mod Power per second for each entity within 15m suffering from a Negative Status Effect. Max 5 stacks.`,
    wikiLinks: [`https://remnant.wiki/Lighthouse_Keeper's_Ring`],
    location: { world: 'Losomn', dungeon: ['Derelict Lighthouse'] },
  },
  {
    category: 'ring',
    name: 'Lithic Signet',
    imagePath: '/items/rings/lithicsignet.png',
    saveFileSlug: 'Ring_LithicSignet_C',
    id: 'hs5tok',
    tags: ['Damage Reduction'],
    description: `Reduces all incoming damage by 7%.`,
    wikiLinks: [`https://remnant.wiki/Lithic_Signet`],
    location: {
      world: 'Yaesha',
      biome: 'Undead Tombs',
      injectable: 'Living Stone',
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Lodestone Ring',
    imagePath: '/items/rings/lodestonering.png',
    saveFileSlug: 'Ring_LodestoneRing_C',
    id: 'sye1ay',
    tags: ['All Damage'],
    description: `Increases all damage dealt against illuminated enemies by 5%.`,
    wikiLinks: [`https://remnant.wiki/Lodestone_Ring`],
    location: { world: 'Yaesha', dungeon: ['The Forbidden Grove'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Low Yield Recovery Ring',
    imagePath: '/items/rings/lowyieldrecovery.png',
    saveFileSlug: 'Ring_LowYieldRecoveryRing_C',
    id: 'l2dwy4',
    tags: ['Heal'],
    description: `Killing an enemy regenerates 6% Max Health over 6s. Additional kills increase duration by 6s. Max 30s.`,
    wikiLinks: [`https://remnant.wiki/Low_Yield_Recovery_Ring`],
    location: {
      world: `N'Erud`,
      biome: `Towers of N'Erud`,
      injectable: `Elevator Shaft`,
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Mark of the Destroyer',
    imagePath: '/items/rings/markofthedestroyer.png',
    saveFileSlug: 'Ring_MarkOfTheDestroyer.Ring_MarkOfTheDestroyer_C',
    id: 'E7fQdZ',
    dlc: 'dlc2',
    tags: ['Perfect Dodge'],
    description:
      'Perfect Dodge triggers a 3m AOE blast that deals 110 - 310 Explosive Damage.',
    externalTokens: [`Amplitude`, `Explosive Damage`],
    wikiLinks: [`https://remnant.wiki/Mark_of_the_Destroyer`],
    location: {
      world: 'Yaesha',
      biome: 'Ziggurats',
      injectable: `Moon's Path`,
    },
  },
  {
    category: 'ring',
    name: `Matriarch's Ring`,
    imagePath: '/items/rings/matriarchsring.png',
    saveFileSlug: 'Ring_MatriarchsRing.Ring_MatriarchsRing_C',
    id: 'R3fM4y',
    dlc: 'dlc2',
    tags: ['Perfect Dodge', 'Charged Melee', 'Stamina'],
    description:
      'Perfect Dodge reduces Charge Melee Stamina Cost by 100% for 7s.',
    wikiLinks: [`https://remnant.wiki/Matriarch's_Ring`],
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: "Mechanic's Cog",
    imagePath: '/items/rings/mechaniccog.png',
    saveFileSlug: 'Ring_MechanicsCog_C',
    id: 'ngue5b',
    tags: ['Movement Speed', 'Damage Reduction'],
    description:
      'While carrying an Engineer Heavy Weapon, gain 15% Movement Speed and 1 Stack of BULWARK.',
    wikiLinks: [`https://remnant.wiki/Mechanic's_Cog`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Metal Driver',
    imagePath: '/items/rings/metaldriver.png',
    saveFileSlug: 'Ring_MetalDriver_C',
    id: 'o7byap',
    tags: ['Reload Speed'],
    description: `Killing Blows increase Reload Speed by 10% for 15s. Stacks 3x.`,
    wikiLinks: [`https://remnant.wiki/Metal_Driver`],
    location: { world: `N'Erud`, dungeon: ['Vault of the Formless'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Meteorite Shard Ring',
    imagePath: '/items/rings/meteoriteshardring.png',
    saveFileSlug: 'Ring_MeteoriteShardRing_C',
    id: 'ayje99',
    tags: ['Encumbrance'],
    description: `Increases Encumbrance by 50. Increases Unarmed damage by 50%.`,
    wikiLinks: [`https://remnant.wiki/Meteorite_Shard_Ring`],
    location: {
      world: `N'Erud`,
      biome: `N'Erud Wasteland`,
      injectable: 'Ascension Spire',
    },
    weight: 50,
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Microcompressor',
    imagePath: '/items/rings/microcompressor.png',
    saveFileSlug: 'Ring_Microcompressor_C',
    id: 'rtfwr5',
    tags: ['Heat Generation'],
    description:
      'Reduces Heat Generation per round when firing Weapons that Overheat by 30%. Increases Heat decay Rate by 30%.',
    wikiLinks: [`https://remnant.wiki/Microcompressor`],
    location: {
      world: `N'Erud`,
      biome: `N'Erud Wasteland`,
      injectable: 'Ascension Spire',
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Momentum Driver',
    imagePath: '/items/rings/momentumdriver.png',
    saveFileSlug: 'Ring_MomentumDriver_C',
    id: 'la9qe1',
    tags: ['Movement Speed', 'Stagger'],
    description: `After Sprinting for 1.5s, Movement Speed is increased by 15% and Stagger Level reduced by 1.`,
    wikiLinks: [`https://remnant.wiki/Momentum_Driver`],
    location: {
      world: `N'Erud`,
      dungeon: [
        'The Putrid Domain',
        'Vault of the Formless',
        'Void Vessel Facility',
        'The Hatchery',
        'The Dark Conduit',
      ],
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Offering Stone',
    imagePath: '/items/rings/offeringstone.png',
    saveFileSlug: 'Ring_OfferingStone_C',
    id: 'p71mik',
    tags: ['Ranged Damage', 'All Damage'],
    description: `Dealing Ranged Damage increases all Damage by 1% for 1s. Stacks 15x. After killing an enemy, extends the duration to 10s.`,
    wikiLinks: [`https://remnant.wiki/Offering_Stone`],
    location: { world: 'Losomn', dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Outcast Ring',
    imagePath: '/items/rings/outcastring.png',
    saveFileSlug: 'Ring_OutcastRing_C',
    id: 'b195vq',
    tags: ['Reload Speed'],
    description: `Increases Reload Speed by 5% for 10s after reloading. Stacks 5x.`,
    wikiLinks: [`https://remnant.wiki/Outcast_Ring`],
    location: { world: 'Losomn', dungeon: [`Tiller's Rest`] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Painless Obsidian',
    imagePath: '/items/rings/painlessobsidian.png',
    saveFileSlug: 'Ring_PainlessObsidian_C',
    id: '6y14c4',
    tags: ['Grey Health', 'Damage Reduction'],
    description:
      'When Grey Health is present gain HASTE and 1 stack of BULWARK.',
    wikiLinks: [`https://remnant.wiki/Painless_Obsidian`],
    location: { world: 'Losomn', dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Pan War Band',
    imagePath: '/items/rings/panwarband.png',
    saveFileSlug: 'Ring_PanWarBand.Ring_PanWarBand_C',
    id: 'eBxG7w',
    dlc: 'dlc2',
    tags: ['Movement Speed', 'Reload Speed', 'Fire Rate'],
    description: `Increases Movement Speed and Reload Speed by 3% and Fire Rate by 2% for each ally wearing this ring.`,
    wikiLinks: [`https://remnant.wiki/Pan_War_Band`],
    location: {
      world: `Yaesha`,
      biome: `Undead Tombs`,
      injectable: 'Pillar Hall',
    },
  },
  {
    category: 'ring',
    name: 'Point Focus Ring',
    imagePath: '/items/rings/pointfocusring.png',
    saveFileSlug: 'Ring_PointFocusRing_C',
    id: 'gg6srx',
    tags: ['Recoil', 'Spread'],
    description: 'Reduces Weapon Spread and Recoil by 30%.',
    wikiLinks: [`https://remnant.wiki/Point_Focus_Ring`],
    location: { world: `N'Erud`, dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Power Complex',
    imagePath: '/items/rings/powercomplex.png',
    saveFileSlug: 'Ring_PowerComplex_C',
    id: 'oavdxw',
    tags: ['All Damage'],
    description:
      'Increases All Damage dealt by 1% per second to a maximum of 15%. Dodging resets Power Complex to 0%.',
    wikiLinks: [`https://remnant.wiki/Power_Complex`],
    location: { world: `N'Erud`, dungeon: 'World Drop' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Power Saver',
    imagePath: '/items/rings/powersaver.png',
    saveFileSlug: 'Ring_PowerSaver_C',
    id: '7i0yzu',
    description: `At Max Health, gain a 35% chance to not use a Relic charge.`,
    wikiLinks: [`https://remnant.wiki/Power_Saver`],
    location: { world: `N'Erud`, dungeon: [`Sentinel's Keep`] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Probability Cord',
    imagePath: '/items/rings/probabilitycord.png',
    saveFileSlug: 'Ring_ProbabilityCord_C',
    id: '0k8d0g',
    tags: ['Critical Hit'],
    description: `Increases Crit Damage by 20%.`,
    wikiLinks: [`https://remnant.wiki/Probability_Cord`],
    location: { world: 'Root Earth', dungeon: ['Corrupted Harbor'] },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Propulsion Loop',
    imagePath: '/items/rings/propulsionloop.png',
    saveFileSlug: 'Ring_PropulsionLoop_C',
    id: 'uydz9a',
    tags: ['Movement Speed', 'Relic Use Speed'],
    description: `After killing an enemy, increases Movement Speed by 5% and Consumable Use Speed by 10% for 10s. Stacks 3x.`,
    wikiLinks: [`https://remnant.wiki/Propulsion_Loop`],
    location: {
      world: `N'Erud`,
      biome: `Towers of N'Erud`,
      injectable: `Elevator Shaft`,
    },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Provisioner Ring',
    imagePath: '/items/rings/provisionerring.png',
    saveFileSlug: 'Ring_ProvisionerRing_C',
    id: '8i7o4p',
    tags: ['Reload Speed', 'Hardcore Reward'],
    description: `Firearms reload over time while stowed.`,
    wikiLinks: [`https://remnant.wiki/Provisioner_Ring`],
    location: { world: 'Ward 13', dungeon: 'Vendor' },
    dlc: 'base',
  },
  {
    category: 'ring',
    name: 'Rally Band',
    imagePath: '/items/rings/rallyband.png',
    saveFileSlug: 'Ring_RallyBand.Ring_RallyBand_C',
    id: '7XdP4g',
    dlc: 'dlc2',
    tags: ['Health', 'Grey Health', 'Melee Hit'],
    description: `Melee Strikes convert Grey Health into Health. Each melee strike converts up to 10% of Max Health`,
    wikiLinks: [`https://remnant.wiki/Rally_Band`],
    location: { world: 'Yaesha', dungeon: ['Luminous Vale'] },
  },
  {
    category: 'ring',
    name: "Ravager's Bargain",
    imagePath: '/items/rings/ravagersbargain.png',
    saveFileSlug: 'Ring_RavagersBargain.Ring_RavagersBargain_C',
    id: 'kqddup',
    dlc: 'dlc2',
    tags: ['All Damage', 'Critical Chance', 'Status Effect'],
    description: `Increases All Damage and All Critical Chance by 5% while BLEEDING.`,
    wikiLinks: [`https://remnant.wiki/Ravager's_Bargain`],
    location: { world: 'Yaesha', dungeon: [`Ancient Canopy`, `Luminous Vale`] },
  },
  {
    category: 'ring',
    name: 'Reaping Stone',
    imagePath: '/items/rings/reapingstone.png',
    saveFileSlug: 'Ring_ReapingStone_C',
    id: 'kqdoup',
    tags: ['Status Effect', 'Lifesteal'],
    description: `After an Elemental Status Effect is removed from wearer, they become immune to all Elemental Status Effects and gain 5% of base damage dealt as Lifesteal for 10s.`,
    wikiLinks: [`https://remnant.wiki/Reaping_Stone`],
    dlc: 'base',
    location: { world: 'Root Earth', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Red Ring of Death',
    imagePath: '/items/rings/redringofdeath.png',
    saveFileSlug: 'Ring_RedRingOfDeath_C',
    id: '9ng83z',
    tags: ['Status Effect'],
    description:
      'Duplicates the last damaging Negative Status applied to the target. Reduces outgoing Status Effect Damage by 10%.',
    wikiLinks: [`https://remnant.wiki/Red_Ring_of_Death`],
    dlc: 'base',
    location: { world: 'Losomn', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Rerouting Cable',
    imagePath: '/items/rings/reroutingcable.png',
    saveFileSlug: 'Ring_ReroutingCable_C',
    id: '48r4bl',
    description: `Gain 5% of Max Health as a SHIELD for 5s after spending 20 Stamina. Accumulation resets after 5s of inaction. Max 50% SHIELD.`,
    wikiLinks: [`https://remnant.wiki/Rerouting_Cable`],
    dlc: 'base',
    location: {
      world: `N'Erud`,
      biome: `N'Erud Underworld`,
      injectable: 'Shockwire',
    },
  },
  {
    category: 'ring',
    name: 'Reserve Boosting Gem',
    imagePath: '/items/rings/reserveboostinggem.png',
    saveFileSlug: 'Ring_ReserveBoostingGem_C',
    id: 'ucm4yv',
    tags: ['Heal'],
    description: `Increases Health Regeneration by 0.5 per second. 1s after going below 50% Health, increases regeneration value to 2.5 per second until 50% Health is reached.`,
    wikiLinks: [`https://remnant.wiki/Reserve_Boosting_Gem`],
    dlc: 'base',
    location: { world: `N'Erud`, dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Restriction Cord',
    imagePath: '/items/rings/restrictioncord.png',
    saveFileSlug: 'Ring_RestrictionCord_C',
    id: 'eznhcv',
    tags: ['Damage Reduction', 'Health'],
    description: `Restricts the wearer from Healing above 50% of their Max Health and reduces all incoming damage by 15%.`,
    wikiLinks: [`https://remnant.wiki/Restriction_Cord`],
    // healthCap: 0.5,
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: ['The Forgotten Grove'] },
  },
  {
    category: 'ring',
    name: 'Ring of Crisis',
    imagePath: '/items/rings/ringofcrisis.png',
    saveFileSlug: 'Ring_RingOfCrisis_C',
    id: '378qz0',
    tags: ['Health'],
    description:
      "When wearer's Health drops below 25%, gain a Shield for 25% of Max Health. Lasts 10s.",
    wikiLinks: [`https://remnant.wiki/Ring_of_Crisis`],
    dlc: 'base',
    location: {
      world: `N'Erud`,
      biome: `N'Erud Underworld`,
      injectable: `Store Room`,
    },
  },
  {
    category: 'ring',
    name: 'Ring of Deflection',
    imagePath: '/items/rings/ringofdeflection.png',
    saveFileSlug: 'Ring_RingOfDeflection_C',
    id: 'ie648z',
    tags: ['Grey Health'],
    description:
      'Direct damage against wearer has a 50% chance to be converted entirely to Grey Health.',
    wikiLinks: [`https://remnant.wiki/Ring_of_Deflection`],
    dlc: 'base',
    location: {
      world: `N'Erud`,
      biome: `N'Erud Underworld`,
      injectable: `Black Hole`,
    },
  },
  {
    category: 'ring',
    name: 'Ring of Diversion',
    imagePath: '/items/rings/ringofdiversion.png',
    saveFileSlug: 'Ring_RingOfDiversion_C',
    id: 'ubqgie',
    description: `Increases invulnerability window while evading and sliding.`,
    wikiLinks: [`https://remnant.wiki/Ring_of_Diversion`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: ['The Lament'] },
  },
  {
    category: 'ring',
    name: 'Ring of Flawed Beauty',
    imagePath: '/items/rings/flawedbeauty.png',
    saveFileSlug: 'Ring_RingOfFlawedBeauty_C',
    id: 'lx6all',
    tags: ['Weakspot Damage', 'Ranged Damage'],
    description:
      'Ranged Weakspot damage is increased by 25%. Ranged damage is reduced by 15% when failing to hit a Weakspot.',
    wikiLinks: [`https://remnant.wiki/Ring_of_Flawed_Beauty`],
    dlc: 'base',
    location: { world: 'Ward 13', dungeon: 'Vendor' },
  },
  {
    category: 'ring',
    name: 'Ring of Grace',
    imagePath: '/items/rings/ringofgrace.png',
    saveFileSlug: 'Ring_RingOfGrace_C',
    id: 'ne83ro',
    tags: ['Heal'],
    description: `Taking enemy damage causes 15% of Maximum Health to regenerate over 10s.`,
    wikiLinks: [`https://remnant.wiki/Ring_of_Grace`],
    dlc: 'base',
    location: { world: 'Losomn', dungeon: [`Harvester's Reach`] },
  },
  {
    category: 'ring',
    name: 'Ring of Infinite Damage',
    imagePath: '/items/rings/ringofinfinitedamage.png',
    saveFileSlug: 'Ring_RingOfInfiniteDamage_C',
    dlc: 'dlc1',
    id: '0yfahk',
    tags: ['Fire Rate'],
    description: 'Increases fire rate by 8. ',
    wikiLinks: [`https://remnant.wiki/Ring_of_Infinite_Damage`],
    location: { world: 'Losomn', dungeon: ['Forlorn Coast'] },
  },
  {
    category: 'ring',
    name: 'Ring of Omens',
    imagePath: '/items/rings/ringofomens.png',
    saveFileSlug: 'Ring_RingOfOmens_C',
    id: '1gnt2c',
    tags: ['Grey Health', 'Stamina'],
    description: `Evades cost 15% Max Health as Grey Health instead of Stamina.`,
    wikiLinks: [`https://remnant.wiki/Ring_of_Omens`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: ['Cathedral of Omens'] },
  },
  {
    category: 'ring',
    name: 'Ring Of Ordnance',
    imagePath: '/items/rings/ringofordnance.png',
    saveFileSlug: 'Ring_RingOfOrdnance.Ring_RingOfOrdnance_C',
    id: 'RDi2ad',
    dlc: 'dlc2',
    tags: [],
    description: `Allows Heavy Weapon Ammo to gradually regenerate while in both Heavy Carry or Turret modes. Doubles the stowed Ammo Regeneration Rate of Heavy Weapons.`,
    wikiLinks: [`https://remnant.wiki/Ring_Of_Ordnance`],
    location: { world: `N'Erud`, dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Ring of Restocking',
    imagePath: '/items/rings/ringofrestocking.png',
    saveFileSlug: 'Ring_RingOfRestocking_C',
    id: '3aryrr',
    tags: ['Reload Speed', 'Critical Hit', 'Weakspot Damage'],
    description:
      'Reloads within 5s of a Critical Kill or Weakspot Kill are 20% faster.',
    wikiLinks: [`https://remnant.wiki/Ring_of_Restocking`],
    dlc: 'base',
    location: { world: `N'Erud`, dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Ring of Retribution',
    imagePath: '/items/rings/ringofretribution.png',
    saveFileSlug: 'Ring_RingOfRetribution_C',
    id: '8ejbuu',
    tags: ['Reload Speed', 'All Damage'],
    description: `Incoming enemy damage increases Reload Speed and all outgoing damage by 15%. Lasts 15s.`,
    wikiLinks: [`https://remnant.wiki/Ring_of_Retribution`],
    dlc: 'base',
    location: { world: 'Losomn', dungeon: [`Harvester's Reach`] },
  },
  {
    category: 'ring',
    name: 'Ring of Spirits',
    dlc: 'dlc2',
    imagePath: '/items/rings/ringofspirits.png',
    saveFileSlug: 'Ring_RingOfSpirits.Ring_RingOfSpirits_C',
    id: 'ic39X7',
    tags: ['Mod Power'],
    description: `Increases Mod Generation by 3% for each active consumable. Max 5 stacks.`,
    wikiLinks: [`https://remnant.wiki/Ring_of_Spirits`],
    location: {
      world: 'Yaesha',
      biome: 'Undead Tombs',
      injectable: 'Pillar Hall',
    },
  },
  {
    category: 'ring',
    name: 'Ring of the Castaway',
    imagePath: '/items/rings/ringofthecastaway.png',
    saveFileSlug: 'Ring_RingOfTheCastaway_C',
    dlc: 'dlc1',
    id: 'aqo8pe',
    description: 'Increases base Consumable Duration by 50%.',
    wikiLinks: [`https://remnant.wiki/Ring_of_the_Castaway`],
    location: {
      world: 'Losomn',
      biome: 'Losomn Sewers',
      injectable: 'Corpse Drop',
    },
  },
  {
    category: 'ring',
    name: 'Ring of the Damned',
    saveFileSlug: 'Ring_StrongArmBand_C',
    imagePath: '/items/rings/ringofthedamned.png',
    id: 'jbfxsb',
    tags: ['All Damage', 'Grey Health', 'Critical Chance'],
    description:
      'Increases All Damage by 0.4% for each 1% of Grey Health. Increase Critical Chance by 5% if at least 50% of Max Health is Grey.',
    wikiLinks: [`https://remnant.wiki/Ring_of_the_Damned`],
    dlc: 'base',
    location: { world: 'Losomn', dungeon: ['The Great Sewers'] },
  },
  {
    category: 'ring',
    name: 'Ring of the Forest Spirit',
    imagePath: '/items/rings/ringoftheforestspirit.png',
    saveFileSlug: 'Ring_RingOfTheForestSpirit_C',
    id: 'wvtzrn',
    tags: ['Healing Effectiveness'],
    description: `Relic Healing Effectiveness is increased by 15%.`,
    wikiLinks: [`https://remnant.wiki/Ring_of_the_Forest_Spirit`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Ring of the Robust',
    imagePath: '/items/rings/ringoftherobust.png',
    saveFileSlug: 'Ring_RingOfTheRobust_C',
    id: 'qdxm42',
    tags: ['Health'],
    description: 'Increases Max Health by 10 and Armor by 20.',
    wikiLinks: [`https://remnant.wiki/Ring_Of_The_Robust`],
    health: 10,
    armor: 20,
    dlc: 'base',
    location: { world: 'Losomn', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Ring of the Vain',
    imagePath: '/items/rings/ringofthevain.png',
    saveFileSlug: 'Ring_RingOfTheVain_C',
    id: 'g61t33',
    tags: ['Movement Speed'],
    description:
      'Reduces Invulnerability Window on Evade and Combat Slide by 35%. Increases Movement Speed while aiming by 35%.',
    wikiLinks: [`https://remnant.wiki/Ring_of_the_Vain`],
    dlc: 'base',
    location: { world: 'Losomn', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Rock of Anguish',
    imagePath: '/items/rings/rockofanguish.png',
    saveFileSlug: 'Ring_RockOfAnguish_C',
    id: 'lr4wxu',
    tags: ['Movement Speed', 'Reload Speed'],
    description: `Gain 5% Movement Speed and 7.5% Reload Speed for every 25% of Max Health missing.`,
    wikiLinks: [`https://remnant.wiki/Rock_of_Anguish`],
    dlc: 'base',
    location: { world: 'Ward 13', dungeon: 'Vendor' },
  },
  {
    category: 'ring',
    name: 'Rotward',
    imagePath: '/items/rings/rotward.png',
    saveFileSlug: 'Ring_Rotward_C',
    id: 'hvhbv9',
    description: `Prevents ROOT ROT Blight.`,
    wikiLinks: [`https://remnant.wiki/Rotward`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: ['The Forbidden Grove'] },
  },
  {
    category: 'ring',
    name: 'Rusted Heirloom',
    imagePath: '/items/rings/rustedheirloom.png',
    saveFileSlug: 'Ring_RustedHeirloom_C',
    id: 'i544v3',
    tags: ['Damage Reduction'],
    description: `Grants 2 Stacks of BULWARK below 50% Max HP.`,
    wikiLinks: [`https://remnant.wiki/Rusted_Heirloom`],
    dlc: 'base',
    location: {
      world: 'Losomn',
      biome: 'Losomn Sewers',
      injectable: 'Dran Safe',
    },
  },
  {
    category: 'ring',
    name: 'Sagestone',
    imagePath: '/items/rings/sagestone.png',
    saveFileSlug: 'Ring_Sagestone_C',
    id: 'pl1g6b',
    description: `Increases earned Experience by 10%.`,
    wikiLinks: [`https://remnant.wiki/Sagestone`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Sapphire Dreamstone',
    imagePath: '/items/rings/sapphiredreamstone.png',
    saveFileSlug: 'Ring_SapphireDreamstone_C',
    id: 'v65mav',
    tags: ['Reduce Skill Cooldown', 'Critical Hit'],
    description: `Critical Hits reduce Skill Cooldowns by 4%. Can only happen once every 2s.`,
    wikiLinks: [`https://remnant.wiki/Sapphire_Dreamstone`],
    dlc: 'base',
    location: {
      world: 'Losomn',
      dungeon: [
        'Council Chamber',
        'Gilded Chambers',
        'The Great Hall',
        'Shattered Gallery',
      ],
    },
  },
  {
    category: 'ring',
    name: 'Sealed Resin Loop',
    imagePath: '/items/rings/sealedresinloop.png',
    saveFileSlug: 'Ring_SealedResinLoop.Ring_SealedResinLoop_C',
    id: 'RA6NZn',
    dlc: 'dlc2',
    tags: [],
    description: `Melee Attacks can be cancelled mid action by Dodging.`,
    wikiLinks: [`https://remnant.wiki/Sealed_Resin_Loop`],
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Seal of the Empress',
    imagePath: '/items/rings/sealoftheempress.png',
    saveFileSlug: 'Ring_SealOfTheEmpress_C',
    id: 'pqd4vp',
    tags: ['Health', 'Stamina'],
    description: `Increases Max Health by 20. Reduces Max Stamina by 5.`,
    wikiLinks: [`https://remnant.wiki/Seal_of_the_Empress`],
    health: 20,
    stamina: -5,
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: ['The Red Throne'] },
  },
  {
    category: 'ring',
    name: 'Shadow of Misery',
    imagePath: '/items/rings/shadowofmisery.png',
    saveFileSlug: 'Ring_ShadowOfMisery_C',
    id: '8bhhzo',
    tags: ['Status Effect'],
    description: 'Increase Status Effect Damage by 20%.',
    wikiLinks: [`https://remnant.wiki/Shadow_of_Misery`],
    dlc: 'base',
    location: { world: 'Losomn', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Shaed Stone',
    imagePath: '/items/rings/shaedstone.png',
    saveFileSlug: 'Ring_ShaedStone_C',
    dlc: 'dlc1',
    id: 'ylif78',
    tags: ['Skill Damage'],
    description: 'Increase Skill Damage by 15%.',
    wikiLinks: [`https://remnant.wiki/Shaed_Stone`],
    location: {
      world: 'Losomn',
      dungeon: [
        'Glistering Cloister',
        `Gilded Chambers`,
        `Pathway of the Fallen`,
        `Shattered Gallery`,
      ],
    },
  },
  {
    category: 'ring',
    name: 'Shard Banded Ring',
    imagePath: '/items/rings/shardbandedring.png',
    saveFileSlug: 'Ring_ShardBandedRing_C',
    id: '13vsn5',
    tags: ['Mod Damage'],
    description: 'Increases Mod damage by 12%',
    wikiLinks: [`https://remnant.wiki/Shard_Banded_Ring`],
    dlc: 'base',
    location: { world: 'Labyrinth', dungeon: ['Fractured Ingress'] },
  },
  {
    category: 'ring',
    name: 'Shiny Hog Lure',
    imagePath: '/items/rings/shinyhoglure.png',
    saveFileSlug: 'Ring_ShinyHogLure_C',
    id: '08cb3s',
    tags: ['Mod Power'],
    description: `Reloading grants 25-50 Mod Power to both weapons based on percentage of Magazine reloaded.`,
    wikiLinks: [`https://remnant.wiki/Shiny_Hog_Lure`],
    dlc: 'base',
    location: {
      world: 'Losomn',
      dungeon: [
        `Butcher's Quarter`,
        `Cotton's Kiln`,
        `Derelict Lighthouse`,
        `Sunken Haunt`,
      ],
    },
  },
  {
    category: 'ring',
    name: 'Singed Ring',
    imagePath: '/items/rings/singedring.png',
    saveFileSlug: 'Ring_SingedRing_C',
    id: 'cpxk1d',
    tags: ['All Damage'],
    description: `Increases all damage dealt to BURNING enemies by 12%.`,
    wikiLinks: [`https://remnant.wiki/Singed_Ring`],
    dlc: 'base',
    location: { world: 'Losomn', dungeon: [`Butcher's Quarter`] },
  },
  {
    category: 'ring',
    name: "Slayer's Crest",
    imagePath: '/items/rings/slayerscrest.png',
    saveFileSlug: 'Ring_SlayersCrest_C',
    id: '0e7ll0',
    tags: ['Melee Damage'],
    description:
      'Increases Melee damage by 25% when attacking enemies from behind.',
    wikiLinks: [`https://remnant.wiki/Slayer's_Crest`],
    dlc: 'base',
    location: {
      world: 'Yaesha',
      dungeon: ['The Nameless Nest', 'The Expanding Glade', 'Forgotten Field'],
    },
  },
  {
    category: 'ring',
    name: 'Soul Feast',
    imagePath: '/items/rings/soulfeast.png',
    saveFileSlug: 'Ring_SoulFeast.Ring_SoulFeast_C',
    dlc: 'dlc2',
    id: '8kotd5',
    tags: ['Summon', 'Reduce Skill Cooldown'],
    description: `When a Human, Companion, or Minion is downed or killed, reduce Skill Cooldowns by 8%.`,
    wikiLinks: [`https://remnant.wiki/Soul_Feast`],
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Soul Guard',
    imagePath: '/items/rings/soulguard.png',
    saveFileSlug: 'Ring_SoulGuard_C',
    id: '8kotg5',
    tags: ['Damage Reduction', 'Summon'],
    description: `Gain a stack of BULWARK for each active Summon.`,
    wikiLinks: [`https://remnant.wiki/Soul_Guard`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: 'Vendor' },
  },
  {
    category: 'ring',
    name: 'Soul Link',
    imagePath: '/items/rings/soullink.png',
    saveFileSlug: 'Ring_SoulLink_C',
    id: 'ohlt19',
    tags: ['Summon', 'Lifesteal'],
    description: `Summons Lifesteal 5% of base damage dealt which returns to the wearer as Health.`,
    wikiLinks: [`https://remnant.wiki/Soul_Link`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Soul Shard',
    imagePath: '/items/rings/soulshard.png',
    saveFileSlug: 'Ring_SoulShard_C',
    id: 'uswo9w',
    tags: ['Summon', 'All Damage'],
    description:
      'Increases All Damage dealt by 5% for each active Summon. Max 15%.',
    wikiLinks: [`https://remnant.wiki/Soul_Shard`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Spirit Stone',
    imagePath: '/items/rings/spiritstone.png',
    saveFileSlug: 'Ring_SpiritStone_C',
    id: '58hv43',
    tags: ['Mod Power'],
    description: `Increases Mod Power generation by 10%.`,
    wikiLinks: [`https://remnant.wiki/Spirit_Stone`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Stockpile Charger',
    imagePath: '/items/rings/stockpilecharger.png',
    saveFileSlug: 'Ring_StockpileCharger_C',
    id: '0jnimt',
    tags: ['Ranged Damage'],
    description: `After picking up ammo, increases the damage of that Ammo Type by 15% for 20s.`,
    wikiLinks: [`https://remnant.wiki/Stockpile_Charger`],
    dlc: 'base',
    location: { world: 'Losomn', dungeon: [`Tiller's Rest`] },
  },
  {
    category: 'ring',
    name: 'Stone of Balance',
    imagePath: '/items/rings/stoneofbalance.png',
    saveFileSlug: 'Ring_StoneOfBalance_C',
    id: 'c20p9b',
    tags: ['All Damage'],
    description: `Increases all damage by 7%.`,
    wikiLinks: [`https://remnant.wiki/Stone_of_Balance`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Stone of Continuance',
    imagePath: '/items/rings/stoneofcontinuance.png',
    saveFileSlug: 'Ring_StoneOfContinuance_C',
    id: 'leuefm',
    tags: ['Skill Duration'],
    description: `Increases Skill Duration by 15%.`,
    wikiLinks: [`https://remnant.wiki/Stone_of_Continuance`],
    dlc: 'base',
    location: { world: `N'Erud`, dungeon: ['Tower of the Unseen'] },
  },
  {
    category: 'ring',
    name: 'Stone of Expanse',
    imagePath: '/items/rings/stoneofexpanse.png',
    saveFileSlug: 'Ring_StoneOfExpanse_C',
    id: 'efdw51',
    tags: ['Ranged Damage'],
    description: `Increases Ranged damage by 12%. Reduces all other damage dealt by 5%.`,
    wikiLinks: [`https://remnant.wiki/Stone_of_Expanse`],
    dlc: 'base',
    location: { world: `N'Erud`, dungeon: `World Drop` },
  },
  {
    category: 'ring',
    name: 'Stone of Malevolence',
    imagePath: '/items/rings/stoneofmalevolence.png',
    saveFileSlug: 'Ring_StoneOfMalevolence_C',
    id: 'kx65km',
    tags: ['Status Effect', 'Mod Power'],
    description: 'Elemental damage generates 15% additional Mod Power.',
    wikiLinks: [`https://remnant.wiki/Stone_Of_Malevolence`],
    dlc: 'base',
    location: { world: 'Losomn', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Stream Coupler',
    imagePath: '/items/rings/streamcoupler.png',
    saveFileSlug: 'Ring_StreamCoupler_C',
    id: 'jq4dje',
    tags: ['Heal'],
    description: `Using a Skill regenerates 25% of Max Health over 10s.`,
    wikiLinks: [`https://remnant.wiki/Stream_Coupler`],
    dlc: 'base',
    location: { world: 'Losomn', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Subterfuge Link',
    imagePath: '/items/rings/subterfugelink.png',
    saveFileSlug: 'Ring_SubterfugeLink_C',
    id: 'al5vs8',
    tags: ['Skill Cast Speed', 'Mod Cast Speed'],
    description: `After killing an enemy, increases the Cast Speed of the next Mod or Skill Cast by 35%. Lasts 15s or until consumed.`,
    wikiLinks: [`https://remnant.wiki/Subterfuge_Link`],
    dlc: 'base',
    location: {
      world: `N'Erud`,
      biome: `N'Erud Underworld`,
      injectable: `Sewage Facility`,
    },
  },
  {
    category: 'ring',
    name: 'Suppression Ward',
    imagePath: '/items/rings/suppressionward.png',
    saveFileSlug: 'Ring_SuppressionWard_C',
    id: '44my16',
    description: `Prevents SUPPRESSION Blight.`,
    wikiLinks: [`https://remnant.wiki/Suppression_Ward`],
    dlc: 'base',
    location: { world: `N'Erud`, dungeon: ['Ascension Spire'] },
  },
  {
    category: 'ring',
    name: 'Targeting Jewel',
    imagePath: '/items/rings/targetingjewel.png',
    saveFileSlug: 'Ring_TargetingJewel_C',
    id: 'm2uqsh',
    tags: ['Range', 'Spread'],
    description: `Increases Range on all Firearms by 4m. Reduces Spread by 15%.`,
    wikiLinks: [`https://remnant.wiki/Targeting_Jewel`],
    dlc: 'base',
    location: { world: `N'Erud`, dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Tarnished Ring',
    imagePath: '/items/rings/tarnishedring.png',
    saveFileSlug: 'Ring_TarnishedRing_C',
    id: 'w4xzfq',
    tags: ['Melee Damage'],
    description: `Increases damage of Unarmed Attacks by 30%.`,
    wikiLinks: [`https://remnant.wiki/Tarnished_Ring`],
    dlc: 'base',
    location: { world: 'Ward 13', dungeon: 'Quest' },
  },
  {
    category: 'ring',
    name: 'Tear of Kaeula',
    imagePath: '/items/rings/tearofkaeula.png',
    saveFileSlug: 'Ring_TearOfKaeula_C',
    id: 'qv7e2g',
    description: 'Increases Relic capacity by 2 while equipped.',
    wikiLinks: [`https://remnant.wiki/Tear_of_Kaeula`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: [`Kaeula's Rest`] },
  },
  {
    category: 'ring',
    name: 'Tear of Lydusa',
    imagePath: '/items/rings/tearoflydusa.png',
    saveFileSlug: 'Ring_TearOfLydusa.Ring_TearOfLydusa_C',
    id: 'k90sex',
    dlc: 'dlc2',
    tags: ['Lifesteal', 'Healing Effectiveness', 'Heal'],
    description: `Increases Healing and Lifesteal Efficacy by 20%. Reduces Healing Efficacy bonus by 1.5% for each 10% of missing Relic Capacity.`,
    wikiLinks: [`https://remnant.wiki/Tear_of_Lydusa`],
    location: { world: 'Yaesha', dungeon: ['Bloodless Throne'] },
  },
  {
    category: 'ring',
    name: 'Tempest Conduit',
    imagePath: '/items/rings/tempestconduit.png',
    saveFileSlug: 'Ring_TempestConduit_C',
    id: '4bb4gf',
    tags: ['Elemental Damage', 'All Damage'],
    description: `After receiving Elemental Damage, increases all damage dealt by 15% and Resistance to the received Element by 20 for 15s.`,
    wikiLinks: [`https://remnant.wiki/Tempest_Conduit`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: [`Endaira's End`] },
  },
  {
    category: 'ring',
    name: 'Thalos Eyelet',
    imagePath: '/items/rings/thaloseyelet.png',
    saveFileSlug: 'Ring_ThalosEyelet.Ring_ThalosEyelet_C',
    dlc: 'dlc2',
    id: '6mopod',
    tags: ['Stamina', 'Damage Reduction'],
    description: `Grants 1 stack of BULWARK and 2 Stamina Regen per second for each BULWARK stack. Increases BULWARK maximum stacks to 6.`,
    wikiLinks: [`https://remnant.wiki/Thalos_Eyelet`],
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Tightly Wound Coil',
    imagePath: '/items/rings/tightlywoundcoil.png',
    saveFileSlug: 'Ring_TightlyWoundCoil_C',
    id: '3pe83i',
    description: `When spending 75% or more of current magazine, gain a SHIELD for 15% of Max Health for 5s. Does not stack with itself.`,
    wikiLinks: [`https://remnant.wiki/Tightly_Wound_Coil`],
    dlc: 'base',
    location: { world: `N'Erud`, dungeon: ['Void Vessel Facility'] },
  },
  {
    category: 'ring',
    name: "Timekeeper's Jewel",
    imagePath: '/items/rings/timekeepersjewel.png',
    saveFileSlug: 'Ring_TimekeepersJewel_C',
    id: '3uggz9',
    tags: ['Status Effect', 'Status Duration'],
    description:
      'Increases the duration of all Status Effects applied by the wearer. Duration varies per Status.',
    wikiLinks: [`https://remnant.wiki/Timekeeper's_Jewel`],
    dlc: 'base',
    location: { world: 'Losomn', dungeon: ['Hewdas Clock'] },
  },
  {
    category: 'ring',
    name: 'Token of Favor',
    imagePath: '/items/rings/tokenoffavor.png',
    saveFileSlug: 'Ring_TokenOfFavor.Ring_TokenOfFavor_C',
    dlc: 'dlc2',
    id: 'qv7e2gx',
    description:
      'Increases All Damage by 5%. Gain 10% Critical Chance against EXPOSED targets.',
    wikiLinks: [`https://remnant.wiki/Token_of_Favor`],
    location: {
      world: 'Yaesha',
      biome: 'Floating Forests',
      injectable: 'Shrine of the Doe',
    },
  },
  {
    category: 'ring',
    name: "Tomb Dweller's Ring",
    imagePath: '/items/rings/tombdwellersring.png',
    saveFileSlug: 'Ring_TombDwellersRing_C',
    id: '6mopou',
    tags: ['Movement Speed', 'Damage Reduction'],
    description: `Increases Movement Speed by 10% for 15s after Vaulting, Climbing, Leaping, and entering Water, stacks 3x. Reduces Fall Damage by 50%.`,
    wikiLinks: [`https://remnant.wiki/Tomb_Dweller's_Ring`],
    dlc: 'base',
    location: {
      world: 'Yaesha',
      biome: 'Undead Tombs',
      injectable: 'Hidden Crypt',
    },
  },
  {
    category: 'ring',
    name: 'Vacuum Seal',
    imagePath: '/items/rings/vacuumseal.png',
    saveFileSlug: 'Ring_VacuumSeal_C',
    id: 'hnkpp0',
    description:
      'Increases Automatic Pickup Range for Scrap by 150%. Picking up Scrap, Iron, or Ammo grants a SHIELD for 15% of Max Health for 15s. Does not stack.',
    wikiLinks: [`https://remnant.wiki/Vacuum_Seal`],
    dlc: 'base',
    location: { world: `N'Erud`, dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Vestige of Power',
    imagePath: '/items/rings/vestigeofpower.png',
    saveFileSlug: 'Ring_VestigeOfPower_C',
    id: 'e6zmo5',
    tags: ['Ranged Damage', 'Melee Damage'],
    description: `After 5s of not being damaged, increases Ranged and Melee Damage by 10%.`,
    wikiLinks: [`https://remnant.wiki/Vestige_of_Power`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'Wax Sealed Ring',
    imagePath: '/items/rings/waxsealedring.png',
    saveFileSlug: 'Ring_WaxSealedRing_C',
    id: 'ekm1hx',
    tags: ['Ranged Damage', 'Melee Damage'],
    description:
      'Killing blows increase Ranged and Melee Damage by 4% for 15s. Stacks 3x',
    wikiLinks: [`https://remnant.wiki/Wax_Sealed_Ring`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: 'White Glass Bead',
    imagePath: '/items/rings/whiteglassbead.png',
    saveFileSlug: 'Ring_WhiteGlassBead_C',
    dlc: 'dlc1',
    id: 'etgc4h',
    tags: ['Perfect Dodge'],
    description:
      'Perfect Dodge applies a SHIELD for 15% of Max Health. Lasts 10s. Cannot stack with itself.',
    wikiLinks: [`https://remnant.wiki/White_Glass_Bead`],
    location: { world: 'Losomn', dungeon: 'Quest' },
  },
  {
    category: 'ring',
    name: 'White Pawn Stamp',
    imagePath: '/items/rings/whitepawnstamp.png',
    saveFileSlug: 'Ring_WhitePawnStamp_C',
    id: 'irhphl',
    tags: ['Mod Power'],
    description: `Reduces Mod Power Requirement by 10%.`,
    wikiLinks: [`https://remnant.wiki/White_Pawn_Stamp`],
    dlc: 'base',
    location: {
      world: 'Losomn',
      biome: 'Fae Palace',
      injectable: 'The Flames Event',
    },
  },
  {
    category: 'ring',
    name: 'Wind Hollow Circlet',
    imagePath: '/items/rings/windhollowcirclet.png',
    saveFileSlug: 'Ring_WindHollowCirclet_C',
    id: 'tx475e',
    tags: ['Reload Speed'],
    description: `Increases Reload Speed by 12%.`,
    wikiLinks: [`https://remnant.wiki/Wind_Hollow_Circlet`],
    dlc: 'base',
    location: {
      world: 'Yaesha',
      biome: 'Ziggurats',
      injectable: 'Wind Hollow',
    },
  },
  {
    category: 'ring',
    name: 'Wood Ring',
    imagePath: '/items/rings/woodring.png',
    saveFileSlug: 'Ring_WoodRing_C',
    dlc: 'dlc1',
    id: 'uwq264',
    tags: ['Stagger'],
    description: 'Increases Stagger Damage by 15%.',
    wikiLinks: [`https://remnant.wiki/Wood_Ring`],
    location: { world: 'Losomn', dungeon: 'World Drop' },
  },
  {
    category: 'ring',
    name: "Worn Admiral's Ring",
    saveFileSlug: 'Ring_RingOfTheAdmiral_C',
    imagePath: '/items/rings/wornadmiralsring.png',
    id: '9kcrxa',
    tags: ['All Damage'],
    description: `All damage received is increased by 200%. All damage dealt is increased by 15%.`,
    wikiLinks: [`https://remnant.wiki/Worn_Admiral's_Ring`],
    dlc: 'base',
    location: { world: 'Ward 13', dungeon: 'Vendor' },
  },
  {
    category: 'ring',
    name: "Zania's Malice",
    imagePath: '/items/rings/zaniasmalice.png',
    saveFileSlug: 'Ring_ZaniasMalice_C',
    id: 'ukufrn',
    tags: ['Weakspot Damage'],
    description:
      'Dealing Weakspot damage increases Weakspot damage by 5% for 5s. Stacks 4x',
    wikiLinks: [`https://remnant.wiki/Zania's_Malice`],
    dlc: 'base',
    location: { world: 'Root Earth', dungeon: ['Ashen Wasteland'] },
  },
  {
    category: 'ring',
    name: "Zohee's Ring",
    imagePath: '/items/rings/zoheesring.png',
    saveFileSlug: 'Ring_ZoheesRing_C',
    id: '9fe9kj',
    tags: ['Mod Duration'],
    description: `Increases Mod Duration by 20%.`,
    wikiLinks: [`https://remnant.wiki/Zohee's_Ring`],
    dlc: 'base',
    location: { world: 'Yaesha', dungeon: ['The Red Throne'] },
  },
]
