export const ITEM_TOKENS = [
  'Ammo Reserves', // Only plural one due to wording in game
  'All Damage',
  'Armor Increase',
  'Charged Melee Damage',
  'Charged Melee',
  'Charged Shot',
  'Concoction',
  'Consumable',
  'Critical Chance',
  'Critical Damage',
  'Critical Hit',
  'Damage Reduction',
  'Elemental Damage',
  'Encumbrance',
  'Firearm Swap Speed',
  'Fire Rate',
  'Grenade',
  'Grey Health',
  'Hardcore Reward',
  'Heal',
  'Healing Effectiveness',
  'Health',
  'Heat Generation',
  'Lifesteal',
  'Magazine Capacity',
  'Melee Attack Speed',
  'Melee Charge Speed',
  'Melee Critical Chance',
  'Melee Critical Damage',
  'Melee Critical Hit',
  'Melee Damage',
  'Melee Hit',
  'Melee Special Ability',
  'Melee Speed',
  'Mod Cast Speed',
  'Mod Cooldown',
  'Mod Cost',
  'Mod Damage',
  'Mod Duration',
  'Mod Power',
  'Movement Speed',
  'Neutral Backdash',
  'Neutral Dodge', // TODO Probably merge these 3 into one token
  'Perfect Dodge',
  'Perfect Neutral Evade',
  'Projectile Speed',
  'Range',
  'Ranged Damage',
  'Recoil',
  'Reduce Skill Cooldown',
  'Relic Use Speed',
  'Reload Speed',
  'Skill Cast Speed',
  'Skill Damage',
  'Skill Duration',
  'Spread',
  'Stagger',
  'Stamina',
  'Status Duration',
  'Status Effect',
  'Summon',
  'Weakspot Critical Chance',
  'Weakspot Damage',
  'Weakspot Hit',
  'Weapon Damage',
] as const satisfies string[];
